### ISSUE TITLE
Opacity of owl-item not animated when using nav or dots

### ISSUE THREAD

**Issue by leolux** [OwlCarousel2/OwlCarousel2#1013]
The opacity of the owl-item gets animated correctly only when using mouseDrag. This means that there is a smooth transition between the inactive item and the item with the CSS class "active".

The issue occurs only when I slide the items using nav or dots. Then the opacity starts at 0 and as soon as the speed-timeout finishes, the opacity switches to 1 without an animation. This is different to the mouseDrag animation and it is worse.

Here is my CSS for the items:
```
.owl-item {
    opacity: 0.3;
    &.active {
      opacity: 1;
    }
  }
```

**Comment by greg5green** [comment]
Can you please come up with a test case as described at https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md#bug-reports? Thanks

**Comment by leolux** [comment]
Yes, I made a reproducer:
http://plnkr.co/edit/jSLbQqAsNUryHJTqbluO

Attention: The issue appears only in chrome and not in firefox. But as I said when usung mouseDrag the opacity gets animated correctly.

**Comment by daviddeutsch** [comment]
No, I have it in both browsers. You forgot to set the `transition` property in your css class.

**Comment by leolux** [comment]
You are right, when adding "transition: opacity 200ms ease;" to the css class ".owl-item" the animation gets fixed in chrome. I have updated the demo:
http://plnkr.co/edit/6N18HtY3yl3jOCg2Hi8K

However this is rather a workaround than a fix. The transition properties as contained in the owl.css of OwlCarousel2 does not work the same for firefox and chrome which is still an issue.
