### ISSUE TITLE
owl carousel 2 not work with loop and 1 items

### ISSUE THREAD

**Issue by ericfavoni** [OwlCarousel2/OwlCarousel2#1019]
Problem:
when I have one content (dynamic content using PHP) `loop:true` and `items:1` not work and I see blank But if I add two content Owl worked true!!

problem : http://jsfiddle.net/Sambora/93cpX/144/

Worked: http://jsfiddle.net/Sambora/93cpX/145/

**Comment by eparisio** [comment]
add a pull request with the fix #1028
Decrised the min items to 2 (actual dimension of 1 item loop carousel) when loop to generate clones from 4.
tested on base carousel with 1 to x items : http://jsfiddle.net/93cpX/146/

**Comment by davidspiess** [comment]
As a fast workaround check the amount of images before initialising the slider.

```js
    // Header Images
    var slider= $('.owl-carousel');
    var amountHeaderImages = slider.find('img').length;

    slider.owlCarousel({
        items: 1,
        loop: !!(amountHeaderImages - 1), // if only 1 item no loop
    });
```

**Comment by alexvb** [comment]
@davidspiess This workaround unfortunately doesn't work if you use the responsive
item count option.

**Comment by keeganbrown** [comment]
This issue appears to be fixed in 2.0.0-beta.3 release. Fiddle of the broken example with owlcarosel swapped out here: http://jsfiddle.net/qb0qm5sa/1/

**Comment by leecollings** [comment]
It's still not fixed.

**Comment by Indrasis** [comment]
Fixed!!!!!!

check if more than one image is present or not. If yes then initialize owl carousel. otherwise not.

**Comment by psp-anon** [comment]
not working with 1 items.

**Comment by pascalporedda** [comment]
This should already be fixed.

**Comment by ranawhaija** [comment]
Still have the same problem on ngx-owl-carousel-2
