### ISSUE TITLE
Autoplay needs better pause handling

### ISSUE THREAD

**Issue by tdecaluwe** [OwlCarousel2/OwlCarousel2#1038]
Because the autoplay plugin uses a window.setInterval call to time the animations, pausing does not work as one might expect.

Most importantly, pausing does not really pause, but only prevents animation. Manifestations include:
- When resuming after a pause, the remaining time until the next animation seems completely random. One might expect the remaining time to be the timeout minus the time already elapsed before pausing.
- Changing the timeout is not possible without calling stop and play on the plugin.

**Comment by daviddeutsch** [comment]
See #1942
