### ISSUE TITLE
Please make this available through NPM

### ISSUE THREAD

**Issue by p-h-i-l** [OwlCarousel2/OwlCarousel2#1049]
Thanks.

**Comment by bcomnes** [comment]
It seems to be published here: https://www.npmjs.com/package/owl-carousel-2 but its not maintained by smashingboxes (although it is up to date and good as far as I can tell).

@cristianurbano Did you make any changes to the package.json to publish that?  

@maintainers, would you be willing to publish on npm officially?  Would you consider accepting a PR to help facilitate that process?   What about accepting changes described in http://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm as well?

**Comment by cristianurbano** [comment]
Hi!
I only published to use it in some projects, I don't modify any file.
It would be nice that smashingboxes to publish the official package.

**Comment by colinodell** [comment]
+1

**Comment by GarrettVD** [comment]
Agreed

**Comment by connorjburton** [comment]
Would be very useful

**Comment by JonasDoebertin** [comment]
👍

**Comment by azaharakis** [comment]
:+1:

**Comment by graingert** [comment]
@greg5green I've published this on NPM at owl.carousel. You're welcome to take it over, however.

**Comment by jorenvanhee** [comment]
:+1:

**Comment by andrewmnlv** [comment]
+1

**Comment by Traksewt** [comment]
+1

**Comment by jpmelnik** [comment]
Hi!

Is Owl Carousel 2 ready for Meteor 1.3? 
Can I import as import owlCarousel from 'owl.carousel' ?

Thanks.

**Comment by Uninen** [comment]
+1

**Comment by daviddeutsch** [comment]
@graingert I've taken over this repository and would love to take care of npm as well, so if your offer to transfer it over, please let me know!

**Comment by graingert** [comment]
@daviddeutsch what's your npm ID?

**Comment by daviddeutsch** [comment]
@graingert Right! My npm ID! Hang on… _shuffles around some papers, clicking frantically on his laptop_ "So my npm ID that I totally had for a while is…"

I just made it - it's the same as one here 😊

**Comment by graingert** [comment]
@daviddeutsch added.

**Comment by aihowes** [comment]
+1, current versions seem to need a `main : ''url/to/js/file"` in the package.json to be required/imported in using browserify/ES6

**Comment by graingert** [comment]
@aihowes that's already there https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/package.json#L6

Also OwlCarousel2 isn't in ES2015, it's in ES5 right now

**Comment by aihowes** [comment]
@graingert  Apologies, browserify/es6 is new to me, I assumed it would work as a way to import and concat files - so ignore that. The version I've downloaded from NPM didn't have a dist directory too. Might be because the current package.json you linked to is set to private?

**Comment by daviddeutsch** [comment]
thanks for the suggestion, @aihowes - didn't even notice that flag. It's removed now.
