### ISSUE TITLE
No works correctly event owl.trigger ('to.owl.carousel', [inId]);

### ISSUE THREAD

**Issue by Alezhik** [OwlCarousel2/OwlCarousel2#1059]
When you call the event owl.trigger ('to.owl.carousel', [inId]); console generates an error Uncaught TypeError: Cannot read property 'start' of undefined in owl.carousel.js:2960.

**Comment by greg5green** [comment]
Please come up with a test case as described in https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md

Thanks

**Comment by jonw100** [comment]
I had the same problem and found this page

https://github.com/smashingboxes/OwlCarousel2/issues/166

People have got it working by supplying 3 parameters - slideIndex, speed, true
Worked for me too
