### ISSUE TITLE
Circular progress bar

### ISSUE THREAD

**Issue by yusteam** [OwlCarousel2/OwlCarousel2#1061]
Can you help me to add circular progress bar on owl carousel slider?

Like this:
http://joxi.ru/v29l5xNSxvZzmG.jpg

**Comment by 269986972** [comment]
This is my solution, which uses CSS and class to control SVG progress:
html：

      <div class="custom1 owl-carousel owl-theme">
        <div class="item">
          <h4>1</h4>
        </div>
        <div class="item">
          <h4>2</h4>
        </div>
        <div class="item">
          <h4>3</h4>
        </div>
      </div>


/*css*/
		  .owl-theme.custom1  .owl-dots .owl-dot{
			  position: relative;
			  font-size: 0px;
		  }
		  .owl-theme.custom1  .owl-dots .owl-dot span{
			  position: absolute;
			  top: 50%;
			  left: 50%;
			  z-index: 2;
			  width: 5px;
			  height: 5px;
			  margin: 0px;
			  background: #ff6600;
			  transform:translate(-50%,-50%);
		  }
		  .owl-dot svg{
			  width: 30px;
		  }
		  .owl-dot svg circle{
			  stroke:#ff6600;
			  stroke-dashoffset:314;
			  stroke-dasharray:314; 
			  transition:stroke-dashoffset 0s;
			  fill:none;
		  }
		  .owl-dot.active svg circle.dotsvg1{
			   animation: circleProgress 6s infinite;
		  }
		  .owl-theme.custom1:hover .owl-dot.active svg circle.dotsvg1{
			   animation-play-state: paused;
		  }
		   
		  .owl-dot svg circle.dotsvg2{
			  stroke-dashoffset:0;
			  opacity: 0;
		  }
		  .owl-dot.active svg circle.dotsvg2{
			  stroke-dashoffset:0;
			  opacity: 0.5;
			  transition:opacity 0.4s;
		  }
		@keyframes circleProgress {
		  0%{
			stroke-dashoffset: 314;
		  }
		  100%{
			stroke-dashoffset: 0;
		  }
		}


//js
jQuery(document).ready(function($) {
              $('.custom1').owlCarousel({
                animateOut: 'fadeInDown',
                animateIn: 'fadeOut',
                items: 1,
                margin: 30,
                stagePadding: 30,
                smartSpeed: 450,
				autoplay: true,
				autoplayTimeout: 6000,  
				autoplayHoverPause:true,
				onInitialized: dot1, //When the plugin has initialized.
              });
				function dot1() {
					$(".custom1 .owl-dot").prepend('<svg style="transform: rotate(-90deg)" viewBox="0 0 100 100"><circle class="dotsvg1" cx="50" cy="50" r="49.5"></circle><circle class="dotsvg2" cx="50" cy="50" r="49.5" /></svg>');
				}
            });

**Comment by 269986972** [comment]
`jQuery(document).ready(function($) {
              $('.custom1').owlCarousel({
                animateOut: 'fadeInDown',
                animateIn: 'fadeOut',
                items: 1,
                margin: 30,
                stagePadding: 30,
                smartSpeed: 450,
				autoplay: true,
				autoplayTimeout: 6000,  
				autoplayHoverPause:true,
				onInitialized: dot1, //When the plugin has initialized.
              });
				function dot1() {
					$(".custom1 .owl-dot").prepend('<svg style="transform: rotate(-90deg)" viewBox="0 0 100 100"><circle class="dotsvg1" cx="50" cy="50" r="49.5"></circle><circle class="dotsvg2" cx="50" cy="50" r="49.5" /></svg>');
				}
            });`
