### ISSUE TITLE
Loading some parts of HTML content in slide lates in Chrome

### ISSUE THREAD

**Issue by Pcinja** [OwlCarousel2/OwlCarousel2#1062]
Guys, you've done a great job!

I'm using carousel in my new project. But I have a little problem after new slide is loaded in Chrome (Version 45.0.2454.99 m). Some parts of my custom content late when loading new slide and the other parts of HTML load just in time (please see my comments bellow in HTML). In Firefox and IE it works OK.

I've used this file "owl.carousel.2.0.0-beta.3.zip". 

My configuration is:
		$(document).ready(function() {
			var owl = $("#owl-demo");
			owl.owlCarousel({
				autoplay : true,
				autoplayTimeout: 4000,
				autoplaySpeed: 1600/true,
				loop : true,
				nav:true,
				responsive:{
					0:{items:1},
					481:{items:1},
					769:{items:1},
					1000:{items:1}
				}
			})
                        ........

and one of my custom HTML slides is:
                        ........
		<div id="slide1" class="item">
			<div id="slide_content">
			        
				<div id="icon"><img src="images/1_slide_ico.png"></div>
			        
				<div id="slide_copy"><img src="images/1_slide_title.png"></div>
			        
				<div id="slide_body">some text goes here.</div>
				<div id="btn"><a class="button" href="">click me</a></div>
			</div>
		</div>
                        ........

Please can you help me with this problem or give me some advise how to resolve?
When you expected to publish stable version?

Thank you very much. 
Good luck!

Goran,
Serbia

**Comment by Pcinja** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3808998/10097817/3507f5fc-637c-11e5-9d10-c147d71e601f.png)

**Comment by populationtwo** [comment]
I had similar issue, adding `position: relative` fixed the problem on my case.
