### ISSUE TITLE
Gap between slides and pagination until you reach last slide (IE11)

### ISSUE THREAD

**Issue by jmahony** [OwlCarousel2/OwlCarousel2#1065]
As far as I can tell this only happens when using lazy load in IE11.

Happens on this page:
http://owlcarousel.owlgraphic.com/demos/lazyLoad.html

On first loading notice the gap:
![image](https://cloud.githubusercontent.com/assets/1437913/10190112/5bcf0420-6762-11e5-8e8b-3655ad8b4f1d.png)

Scroll to last slide and the gap disappears:
![image](https://cloud.githubusercontent.com/assets/1437913/10190126/6be63b80-6762-11e5-843e-9418f8557a87.png)

Is there any easy fix?

Cheers

**Comment by pshudgins** [comment]
Hi, there... did you ever figure this one out? I'm having the same issue. Please let me know, thank you!

**Comment by jmahony** [comment]
@pshudgins No, sorry. Never had time to look into it.
