### ISSUE TITLE
<img> being lazy loaded in when set to false?

### ISSUE THREAD

**Issue by paOol** [OwlCarousel2/OwlCarousel2#1071]
here is my html structure

```
<div> (main image is set as background-img)
  <img> (the one in question)
     <div> caption stuff </div>
</div>
```
when I go through the slides, the ``` <img> ``` is appearing after a delay instead of immediately as it should.
Here is a gif showing the issue.

http://i.imgur.com/8cMSv0Z.gif

If I modify the ```<img>``` css to width 100%, the issue goes away but the image is also stretched to the entire screen width. 

I've also gone through the default owl.carousel.css file and commented out any animations. 

my settings are

```
    owl.owlCarousel({
      autoplay : true,
      autoplayTimeout: 8000,
      items : 1,
      autoplayHoverPause: true,
      loop: true
     });
```

**Comment by jeanphilippealbert** [comment]
I'm having the same problem here. .PNG icons are loading with a delay.
