### ISSUE TITLE
after upgrading to bet 2.3 slides become vertical

### ISSUE THREAD

**Issue by WPThemer** [OwlCarousel2/OwlCarousel2#1072]
I have integrated Owl slider 2.0.0 beta with my them in many areas, after weeks of development, I have come to a point where it gives error on Resize if multiple responsive sliders are on one page, so I upgraded the slider to bet 2.0.3 but now all my sliders are vertical - I have updated the .js and .css files, what am I doing wrong ? Please advise..
![owl_slider_error2](https://cloud.githubusercontent.com/assets/6549749/10256123/04787292-6960-11e5-9eae-06cda129d413.png)

**Comment by WPThemer** [comment]
ok, I got it working the .owl-carousel is mandatory in this version...

however my original problems remains the same... here is it again...

I have 4 different slider on page, each has different responsive options, but if the page is resized (mobile size) it works fine, on the way back to original resize (full desktop screen), it does not resize all sliders, it remembers the value of LAST item's responsive: {} and makes all sliders the same value.. for example if first slider had 5 items as visible and last had 2 visible (item), on resize it makes all 2 slides visible..

can someone please help here..

thanks

**Comment by eparisio** [comment]
We should see your code but some easy contro that you can do:
* use different classes for each carousel for initialize them.
* if you can try to debug owl script and see where the responsive variables are stored and when they are called
