### ISSUE TITLE
Prevent "crazy navigation"

### ISSUE THREAD

**Issue by gsmeira** [OwlCarousel2/OwlCarousel2#1073]
Hi, i was wondering if the plugin has some option (I tried with the speeds - nav, smart, dots, drag - options but no effect) to prevent multiple user clicks in the navigation at "same time". The carousel items slides like crazy. I'm using animate.css, so the animations get ugly if the user navigate to quickly between the items...

This site below have a example with the result i'm looking for:

http://globoesporte.globo.com

To test, try to click multiple times quickly in the navigation. You will see that the carousel waits the transition complete to free the navigation again..

**Comment by giacomoalonzi** [comment]
Hi man, i solved this problem like this:
`
onTranslated: function () {
				$('.owl-dot, .owl-dot > span').css({'pointer-events': 'auto'});

			},
			onTranslate: function () {
				$('.owl-dot, .owl-dot > span').css({'pointer-events': 'none'});
		
			},
`

let me know!
