### ISSUE TITLE
URL not found on owlcarousel.owlgraphic.com

### ISSUE THREAD

**Issue by marcustisater** [OwlCarousel2/OwlCarousel2#1074]
http://www.owlcarousel.owlgraphic.com/docs/classes.html

**Comment by dacur** [comment]
On which page is this link found?  This broken link was addressed in a prior issue, so I am curious where you are finding it now.  The updated one is this: http://smashingboxes.github.io/OwlCarousel2/docs/api-classes.html

Old issue: https://github.com/smashingboxes/OwlCarousel2/issues/880

Thanks

**Comment by marcustisater** [comment]
I found it at http://www.owlcarousel.owlgraphic.com/docs/api-options.html bottom of the list, Class list.

**Comment by dacur** [comment]
Thanks Marcus, I see that now.  I will look into it.

**Comment by marcustisater** [comment]
No worries 

+1 for fast rply
