### ISSUE TITLE
bug to.owl.carousel

### ISSUE THREAD

**Issue by XeL077** [OwlCarousel2/OwlCarousel2#1075]
Use: to.owl.carousel
$('.owl-carousel').trigger('to.owl.carousel', 3);
Everything is working.

Add properties
$('.owl-carousel').owlCarousel({
   dots: false
})

undefined starting value

**Comment by greg5green** [comment]
Please come up with a test case as described in https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md

Thanks

**Comment by MichielBijl** [comment]
Related to: https://github.com/smashingboxes/OwlCarousel2/issues/687
