### ISSUE TITLE
Chrome 45 and responsive images break?

### ISSUE THREAD

**Issue by ThisIsDallas** [OwlCarousel2/OwlCarousel2#1079]
This is specific to Chrome (45.0.2454.101). Actually, I haven't check on Firefox or IE but everything works on Safari.

When using Owl Carousel 2, there is a bug where it looks like the images will duplicate themselves and appear behind the actual normal images when the browser is resized. 

To see what I am talking about, here is a jsfiddle http://jsfiddle.net/qx90s8cs/9/

The slider is a very basic implementation as well:

	jQuery(document).ready(function($){
		$('.main-featured-posts').owlCarousel({
		    loop:true,
		    margin:10,
		    nav:false,
		    dots:false,
		    responsive:{
		        0:{
		            items:1
		        },
		        800:{
		            items:2
		        },
		        1000:{
		            items:3
		        }
		    }
		});

	});

All you need to do is use Chrome resize the browser and then scroll through the images. 

Is there a fix for this issue?

**Comment by talalus** [comment]
+1

**Comment by raknjak** [comment]
This issue has been existing for a while, you can destroy and reinit the carousel on window resize as a temporary workaround.

if ($('.owl-carousel-top').length > 0) {

            mainOwlCarousel(); // does the carousel loading

            $(window).resize(function() {
                $('.owl-carousel-top').trigger('destroy.owl.carousel').removeClass('owl-carousel owl-loaded');
                $('.owl-carousel-top').find('.owl-stage-outer').children().unwrap();

                mainOwlCarousel();
            });
        }

**Comment by secretdesign** [comment]
The same is and with landscape and portrait on mobile phone.

**Comment by secretdesign** [comment]
I used owl.carousel.css from OwlCarousel and this fixed bug. I didn't check which part of css from old carousel need to be implemented in v2 to fix this issue.

**Comment by Madison80** [comment]
Hi there,
I had the same issue and whith this css snippet it works fine for me:

\\\css
/* fix */
.owl-carousel  .owl-wrapper,
.owl-carousel  .owl-item{
	-webkit-backface-visibility: hidden;
	-moz-backface-visibility:    hidden;
	-ms-backface-visibility:     hidden;
  -webkit-transform: translate3d(0,0,0);
  -moz-transform: translate3d(0,0,0);
  -ms-transform: translate3d(0,0,0);
}
\\\

**Comment by secretdesign** [comment]
Yup. This is the fix.

**Comment by pedrobuelna** [comment]
Fix it Thanks!!

**Comment by SmashBrando** [comment]
This really needs to be implemented into the core CSS. I spent about an hour trying the right combo of search terms and fond a similar answer on another blog. Im my case I had several elements, not just images duplicating. I set mine to use a wild card and target any element within the owl-item.

**Comment by jrandyanderson** [comment]
I have spent a few weeks on and off trying to get this bug fixed on a client's site. The above CSS from Madison80 fixed it perfectly. I highly suggest implementing this into the main code.

**Comment by Jahangiruzzal** [comment]
Fix it Thanks!!

**Comment by eccentricpixel** [comment]
Yup, this fixes it. +1

**Comment by daviddeutsch** [comment]
@Madison80 Sweet fix! Would you like to contribute this as a Pull Request (that I would be happy to accept, of course)?

**Comment by TheFrost** [comment]
yeah! @Madison80 Fix it Thanks!!

**Comment by zzseba78** [comment]
@Madison80 Fix it !! I would be nice to have this fix in next version

**Comment by EroTiXx** [comment]
@Madison80 Thanks, it's work

**Comment by dijkermans** [comment]
This issue still exists. Yes, the CSS is updated but the carousel still needs to be reloaded in order to prevent overlapping when you resize the window.

I use this but that's not ideal either:

`if ($('.owl-carousel').length > 0) {

        mainOwlCarousel();

        $(window).on('resize',function() {

		$('.owl-carousel').owlCarousel('destroy'); 

            mainOwlCarousel();
        });
}`
