### ISSUE TITLE
Unable to select text

### ISSUE THREAD

**Issue by abhishek1234321** [OwlCarousel2/OwlCarousel2#108]
Is it possible to select text in the div of the carousel?

I tried selecting and the content just gets dragged.... is this a bug?

**Comment by sebstck** [comment]
Hey Witrin,
I dont know if it answered abishek s question, but it didnt answer mine really ...

i made a caroussel with in the same ".item" a text and an image side by side. I want the image to be draggable but not the text <p>.

I managed to cancel the drag call by adding a class "disable-owl-swipe" on the paragraph. Div that prevent the slide
		$(".disable-owl-swipe").on("touchstart mousedown", function(e) {
			// Prevent carousel swipe
			e.stopPropagation();
		})

But the text is still not selectable. I ve seen a class called ".owl-text-select-on" that seems to do exactly what i need. But it s not supported by the Owl Carrousel 2.

Did i miss something? and if not are you thinking to implement this functionality soon?
