### ISSUE TITLE
Windows 10 tablet - Edge

### ISSUE THREAD

**Issue by mathi1993** [OwlCarousel2/OwlCarousel2#1080]
Hey guys,

I just want you to know, that the touch event doesn't work good for the Edge browser on Windows 10 tablets. I just tried it and it doesn't let me swipe trough the images like it works on an android or apple device.
If I do it with the chrome browser, it works good, even on the Windows 10 tablet. But on the Edge browser it doesn't.

I hope you can do something about it.

Thanks and regards,
Mathias

**Comment by mathi1993** [comment]
Anyone?

**Comment by madmunsterdaddy** [comment]
same issue
