### ISSUE TITLE
owl-prev and owl-next button as transparent overlay on each side of the carousel maintaining dragging

### ISSUE THREAD

**Issue by wstoettinger** [OwlCarousel2/OwlCarousel2#1081]
hey there!

i just tried to implement an image gallery with owl showing one image at a time with the possibility to navigate though them. 

I would like to have transparent overlays for navigation left and right of the images without having to scale up the owl-controls to full height which would prevent the possibility of dragging the images.

anyone got an idea?

**Comment by mrsdohpaz** [comment]
I made a plugin that puts the navigation to either side. With additional css you can overlay with transparency. Would love to hear your feedback. 

https://github.com/mrsdohpaz/OwlSideNav
