### ISSUE TITLE
When using autoplay, images flash onscreen

### ISSUE THREAD

**Issue by oktalk** [OwlCarousel2/OwlCarousel2#1084]
Here is a working example of the issue: https://jsfiddle.net/ume5zy58/
Notice that the right image flashes as it slides into view.

This is caused by the Owl theme CSS adding a `transorm-style` of `preserve-3d` to the images.
The CSS property is added from the following file on line `44`:
`https://github.com/smashingboxes/OwlCarousel2/blob/develop/src/scss/owl.core.scss`
 
I also found an error within the lazy load portion of the CSS that also applies the CSS property. The error can be found in the following file on line `12`.
`https://github.com/smashingboxes/OwlCarousel2/blob/develop/src/scss/owl.lazyload.scss`
 
You can resolve this issue by setting the `transform-style` to `inherit` instead of `preserve-3d`.

Thanks.

**Comment by oktalk** [comment]
Digging into this further, I would suggest removing the `transform-style` property altogether. I don't see a need for it.

**Comment by gaziev** [comment]
@oktalk :+1:
