### ISSUE TITLE
Adjusting the dimension (height) of the items

### ISSUE THREAD

**Issue by Jzarecta** [OwlCarousel2/OwlCarousel2#1088]
Is there a way I can adjust the items so that the thumbnails are enlarge on the height to a 320px height to 290px width?

Regards.

**Comment by rafael-renan-pacheco** [comment]
Did you try to max-width, max-height them with css?

Owl will apply 100% width on img items, so maxing them should solve this.

**Comment by Jzarecta** [comment]
Thanks I was able to figure out that the size of the image depends on teh hight/width ratio and solve the issue I had.  I was looking for a set pixelage but is more of a percentage thing.
