### ISSUE TITLE
Error when theres only one slide

### ISSUE THREAD

**Issue by diegocam** [OwlCarousel2/OwlCarousel2#1091]
I normally have more than one slide dynamically created. But in the case theres only one slide, I get the following error: "Uncaught TypeError: Cannot read property 'clone' of undefined" (on Chrome console)

This is the code Im using:

 $owl.owlCarousel({
    items: 1,
    loop: true,
    margin: 0,
    center: true,
    autoplay: true,
    autoHeight: true,
    autoplayTimeout: 5000,
    smartSpeed: 800
});

I am using the latest version downloaded from the website: 
/**
 * Owl carousel
 * @version 2.0.0
 * @author Bartosz Wojciechowski
 * @license The MIT License (MIT)
 * @todo Lazy Load Icon
 * @todo prevent animationend bubling
 * @todo itemsScaleUp
 * @todo Test Zepto
 * @todo stagePadding calculate wrong active classes
 */

Is this a bug?

**Comment by onordgren** [comment]
+1

**Comment by madiedinro** [comment]
+1

**Comment by Modicrumb** [comment]
If you test it with the latest fork it works now. The latest fork isn't what you download though.

**Comment by Inggo-inHomePortal** [comment]
@Modicrumb where's the latest fork? Is it the develop branch?

**Comment by Modicrumb** [comment]
@Inggo-inHomePortal yeah, that's what i meant. I tested it this morning, it works fine with one slide.

**Comment by Inggo-inHomePortal** [comment]
I tried it out with the develop branch, I'm still getting the error.

I had to resort to something like this:

    var carousel = $(this);
    carousel.owlCarousel({
        items: 1,
        loop: carousel.children().length > 1
    });

**Comment by jarr-head** [comment]
#548 
this seems like the same issue again, it disappears when you set loop to false
