### ISSUE TITLE
Callback to onInitialize receives null parameter.

### ISSUE THREAD

**Issue by leonelag** [OwlCarousel2/OwlCarousel2#1098]
I have a carousel, with an initializing function, `myFn`. It is built as per the code below:

    function myFn(event) { ... }
    var carousel = $("#myElement").owlCarousel({
        onInitialize: myFn
    });

When my callback is called on the Carousel's initialization, the parameter `event` to the function is undefined.

I have traced this issue to function (`Owl.prototype.trigger`)[https://github.com/smashingboxes/OwlCarousel2/blob/2.0.0-beta.2.4/src/js/owl.carousel.js#L1865].

As per [the docs in Mozilla Developer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply), shouldn't apply be called with an array of arguments ?

**Comment by daviddeutsch** [comment]
Recently fixed by switching to `.call()`. Test with the next release and please do let me know if it still breaks for you. Seemed fine to me.
