### ISSUE TITLE
slideBy 'page' with autoWidth

### ISSUE THREAD

**Issue by dcb** [OwlCarousel2/OwlCarousel2#1100]
One of the features that we really needed in the carousel for one of our projects was to be able to handle variable width items and to slide by page, not by item or by a fixed number of items. I was a bit disappointed when I figured out that Owl can't actually do this, but I looked at the source and it only took me a couple of hours to implement it. It's tested with autoLoad as well, but not with merge, probably that won't work.

in owl.carousel.js in `Navigation.prototype.update`, at line 2825 insert this:
```javascript
			var me = this;
			if(options.autoWidth){
				var width = this.$element.width();
				var currentWidth = 0;
				var pageStart = lower;
				var start = 0;
				var end = 0;
				this.$element.find('.owl-item').each(function(i, e){
					if(i > lower && i <= upper){
						var itemWidth = $(e).width() + options.margin;
						if(currentWidth + itemWidth > width){		
							start = pageStart - lower;
							end = i - 1 - lower;
							me._pages.push({
								start: start,
								end: end
							});
							pageStart = i - 1;
							currentWidth = itemWidth;
						} else {
							currentWidth += itemWidth;
						}
					}
				});
				if(end < upper){
					me._pages.push({
						start: end,
						end: upper
					});
				}
			} else

**Comment by daviddeutsch** [comment]
Thanks for sharing the suggestion, I'd be happy to see a PR with a feature like this so I can try it out properly! (Will reopen then.)
