### ISSUE TITLE
please add ability to use arbitrary html-container for pages and controls

### ISSUE THREAD

**Issue by sanns** [OwlCarousel2/OwlCarousel2#1101]
for example, I want to move paging and arrow-buttons to bootstrap container>row>col-md-6 :)

**Comment by rafael-renan-pacheco** [comment]
Did you try to use your custom control to fire carousel events using JS? You are not obligated to use the owl's default controls.

**Comment by daviddeutsch** [comment]
Yeah, probably the best idea to build your own controls around the carousel.
