### ISSUE TITLE
Images getting blurry in center mode on Chrome

### ISSUE THREAD

**Issue by thomaseilander** [OwlCarousel2/OwlCarousel2#1103]
I noticed that images are getting very blurry when setting up the carousel in center mode. This only seems to happen in Google Chrome. See attached file. Above is Google Chrome, below IE/Firefox. Check the leaves on the trees for example. 

It makes no difference in setting the images as background-image or directly including them with <img> tags.

Disabling center mode immediately results in sharp images.

Anyone has an idea?

![owlblurry](https://cloud.githubusercontent.com/assets/10836087/10750978/406bf42a-7c7c-11e5-870f-5e0eb68c9a32.jpg)

**Comment by daviddeutsch** [comment]
That's just the differences in browser aliasing. If anybody has a fix for this, please open a new issue, but I'm not aware of a consistent solution.
