### ISSUE TITLE
autoplayHoverPause not working on touch devices

### ISSUE THREAD

**Issue by fabianmarinog** [OwlCarousel2/OwlCarousel2#1105]
If you set autoplayHoverPause to true then the autoplay should stop while hovering the carousel, while this works on desktop (mouse devices) on mobile devices you'll see the carousel autoplaying while you drag any item. The solution I've implemented and tested was this: 

Line 2474 version 2.0.0-beta.3

			'touchstart.owl.core': $.proxy(function() {
				if (this._core.settings.autoplayHoverPause && this._core.is('rotating')) {
					this.stop();
				}
			}, this),
			'touchend.owl.core': $.proxy(function() {
				if (this._core.settings.autoplayHoverPause) {
					this.play();
				}
			}, this)

**Comment by daviddeutsch** [comment]
Thanks for the suggestion! It's not a perfect fix (and I changed it to .pause() instead of .stop()), but since we don't have a proper hover event, there never really will be a perfect solution.
