### ISSUE TITLE
[autoplay plugin] event "autoplay.stop.owl" or "stop.owl.autoplay" ?

### ISSUE THREAD

**Issue by simmar** [OwlCarousel2/OwlCarousel2#1109]
Hello,

In the autoplay demo http://www.owlcarousel.owlgraphic.com/demos/autoplay.html it says to use 
`owl.trigger('autoplay.stop.owl')` but it would not work for me (@version 2.0.0, same as in the demo).

So I tried a few solutions and I found the event is not written the same way in https://github.com/smashingboxes/OwlCarousel2/blob/develop/src/js/owl.autoplay.js
So I tried `stop.owl.autoplay` and now it works fine :)

**Comment by daviddeutsch** [comment]
Yup, that's an error in the documentation (as noted in other issues). Soon to be fixed!
