### ISSUE TITLE
OwlCarousel2 incompatible with Bootstrap 3

### ISSUE THREAD

**Issue by allanchang** [OwlCarousel2/OwlCarousel2#1110]
Bootstrap 3 has numerous plugins that depend on $.support.transition.
Bootstrap defines it, but Owl Carousel also defines it (line:3132 in owl.carousel.js) -- overriding Bootstrap and breaking all the plugins.

**Comment by daviddeutsch** [comment]
Could not find that in Bootstrap. Reopen if there is still an issue.
