### ISSUE TITLE
OwlCarousel 2 is showing blank images!

### ISSUE THREAD

**Issue by andiruleu** [OwlCarousel2/OwlCarousel2#1123]
I'm using the more recent owl-carousel 2. My carousel is showing blank images, and if I scroll, it turns normal, but the blank space will come back when it gets back to that position
<img width="1126" alt="screen shot 2015-11-11 at 7 53 29 am" src="https://cloud.githubusercontent.com/assets/1781551/11095632/d26aed7a-884a-11e5-8f75-73816c7d2ad2.png">

my css:

```
.owl-item {
  -webkit-backface-visibility: hidden !important;
  -webkit-transform: translateZ(0) scale(1.0, 1.0) !important;  
}
.beautiful-image-oc .bi-item{
  img {
    height: 432px !important;
    width:auto;
    height:auto;
  }
}
.owl-carousel .bi-item{
  max-height:432px
}

```

This is my JS

```
$ ->
  $('.owl-carousel').owlCarousel
    margin:1
    loop:true
    autoWidth:true
    lazyLoad: true
```

**Comment by jurzyna** [comment]
+1 here

**Comment by rob-gordon** [comment]
Do the images eventually jump back into place after enough slides? If so, then +1 here too

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by crazypsycho** [comment]
You can try this:

`.owl-carousel .owl-item img {
  -webkit-transform-style: flat;
  -moz-transform-style: flat;
  -ms-transform-style: flat;
  -o-transform-style: flat;
  transform-style: flat;
}`

**Comment by TechSK0** [comment]
![image](https://user-images.githubusercontent.com/54398059/84767981-0b501c00-aff1-11ea-8bd3-4b787fbf2fee.png)
My product creates slider spaces. Please help me to solve this problem!!!

**Comment by Ajaxaj98** [comment]
I have a same problem please suggest an option

**Comment by idreesandroid** [comment]
i also face same issue 
https://giftworksstg.wpengine.com/maani-page/

![slider](https://github.com/OwlCarousel2/OwlCarousel2/assets/24524348/e36574be-c4b1-463f-804a-6b6db5fabe69)
