### ISSUE TITLE
Add style to custom nav butons on start or end

### ISSUE THREAD

**Issue by Ceyar** [OwlCarousel2/OwlCarousel2#1125]
Hello, Thank you for this great plugin.

I have a question about custom navigation. I'm trying to add ( opacity:0.5; and cursor:initial; ) to my navigation buton. But is there any event to know if we are at the first or last slide? Here is my navigation in my html:

`<img id="nav-back" class="customPrevBtn style-nav-btn" src="<?php echo get_bloginfo('template_directory')."/img/leftArrow.svg"?>" alt="leftArrow">``

`<img id="nav-next" class="customNextBtn style-nav-btn" src="<?php echo get_bloginfo('template_directory')."/img/rightArrow.svg"?>" alt="leftArrow">`

And here is my script:

             $('.owl-carousel').owlCarousel({
                loop:false,
                margin: 5,
                navContainer: '#customNav',
                slideBy: 12,
                responsive:{
                    0:{
                        items:1
                    },
                    600:{
                        items:3
                    },
                    1000:{
                        items:12
                    }
                }
            });
            var owl = $('.owl-carousel');
            owl.owlCarousel();
            // Go to the next item
            $('.customNextBtn').click(function() {
                owl.trigger('next.owl.carousel');
            })
            // Go to the previous item
            $('.customPrevBtn').click(function() {
                // With optional speed parameter
                // Parameters has to be in square bracket '[]'
                owl.trigger('prev.owl.carousel', [300]);
        })

Is there a way to get my nav like the image below?
When I can't go on the left:
![capture d ecran 2015-11-12 a 14 14 55](https://cloud.githubusercontent.com/assets/1465346/11119151/cb119dbe-8947-11e5-8917-4643adbfad8d.png)

When I can go on left or right:
![capture d ecran 2015-11-12 a 14 12 31](https://cloud.githubusercontent.com/assets/1465346/11119119/92499b94-8947-11e5-849f-62873d3f1c17.png)

When I can't go on the right:
![capture d ecran 2015-11-12 a 14 11 16](https://cloud.githubusercontent.com/assets/1465346/11119071/4a24dfcc-8947-11e5-8e5e-217b85e76dae.png)

Thank's in advance.

Best regards 
Dan

**Comment by sebstck** [comment]
```javascript

		$('.owl-carousel').on('change.owl.carousel', function(e) {
			if (e.namespace && e.property.name === 'position' 
				&& e.relatedTarget.relative(e.property.value) = 1) {

// the first slide is visible
		
			}

			if (e.namespace && e.property.name === 'position' 
				&& e.relatedTarget.relative(e.property.value) === e.relatedTarget.items().length - 1) {

// the last slide is visible
		
			}
		})
```

**Comment by Ceyar** [comment]
Hello, thank's for your quick reply. I tried the tricks above but he return me an error.
![capture d ecran 2015-11-16 a 08 46 07](https://cloud.githubusercontent.com/assets/1465346/11176577/9a9c7bbe-8c3e-11e5-85ee-5b9b2350d4c9.png)

And here is my code: 
![capture d ecran 2015-11-16 a 08 46 28](https://cloud.githubusercontent.com/assets/1465346/11176590/b7b21b00-8c3e-11e5-98ce-e143ab20aff4.png)

I tried to put ==1 instead of =1 on line 70 but the console.log doesn't appear in my console.

Do I change something to the code? 

Thank's in advance.
Best regards 

Dan

**Comment by sebstck** [comment]
hey dan,
I cant try out now, but try === 0 on line  70

**Comment by Ceyar** [comment]
Hello,

Trying with ===0 does just work when I click to move on my first element but not at very first start(refreshing page),and for the end of carousel it doesn't output a result.

Here my complete code for the js. Maybe this will help.

    // Carousel Paramaters

    $('.owl-carousel').owlCarousel({
        loop:false,
        margin: 5,
        navContainer: '#customNav',
        slideBy: 12,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:12
            }
        }
    });



    // Custom NAV
    var owl = $('.owl-carousel');
    owl.owlCarousel();
            // Go to the next item
            $('.customNextBtn').click(function() {
                owl.trigger('next.owl.carousel');
            })
            // Go to the previous item
            $('.customPrevBtn').click(function() {
                // With optional speed parameter
                // Parameters has to be in square bracket '[]'
                owl.trigger('prev.owl.carousel', [300]);
            })
    // End Custom NAV

    // Trying to add css to start and end of carousel

    $('.owl-carousel').on('change.owl.carousel', function(e) {
        if (e.namespace && e.property.name === 'position' && e.relatedTarget.relative(e.property.value)  === 0) {

            console.log('start');

        }

        if (e.namespace && e.property.name === 'position' && e.relatedTarget.relative(e.property.value) === e.relatedTarget.items().length - 1) {

            console.log('end');

        }
    });


Hope that can help.

Thank you for the time you are taking.

Dan

**Comment by Ceyar** [comment]
Ho and maybe that can help too:

Here my html code:

			<img id="nav-back" class="customPrevBtn style-nav-btn" src="<?php echo get_bloginfo('template_directory')."/img/leftArrow.svg"?>" alt="leftArrow">
			<img id="nav-next" class="customNextBtn style-nav-btn" src="<?php echo get_bloginfo('template_directory')."/img/rightArrow.svg"?>" alt="leftArrow">
			

			<div class="owl-reponsive breakpoint owl-carousel">
				
				
						<?php for ($i=1; $i < 55 ; $i++) { ?>

								<span class="edition-num-nav"><a href="#" class="edition-num-nav">N°<?php echo $i; ?></a><span class="edition-num-separator">/</span></span>
						<?php } ?>


			</div>

**Comment by sebstck** [comment]
"on('change.owl.carousel', function(e){" is a trigger to execute a function once the carousel has changed.

Try "initialize.owl.carousel" instead of change.

**Comment by Ceyar** [comment]
trying this doesn't console.log nothing:

    // Carousel Paramaters

    $('.owl-carousel').owlCarousel({
        loop:false,
        margin: 5,
        navContainer: '#customNav',
        slideBy: 12,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:12
            }
        }
    
    });





    $('.owl-carousel').on('initialize.owl.carousel', function(e) {
        if (e.namespace && e.property.name === 'position' && e.relatedTarget.relative(e.property.value)  === 0) {

            console.log('start');

        }

        if (e.namespace && e.property.name === 'position' && e.relatedTarget.relative(e.property.value) === e.relatedTarget.items().length - 1) {

            console.log('end');

        }
    })




    // Custom NAV
    var owl = $('.owl-carousel');
    owl.owlCarousel();
            // Go to the next item
            $('.customNextBtn').click(function() {
                owl.trigger('next.owl.carousel');
            })
            // Go to the previous item
            $('.customPrevBtn').click(function() {
                // With optional speed parameter
                // Parameters has to be in square bracket '[]'
                owl.trigger('prev.owl.carousel', [300]);
            })
    // End Custom NAV

And when I put that before the carousel initialisation like this:

    $('.owl-carousel').on('initialize.owl.carousel', function(e) {
        if (e.namespace && e.property.name === 'position' && e.relatedTarget.relative(e.property.value)  === 0) {

            console.log('start');

        }

        if (e.namespace && e.property.name === 'position' && e.relatedTarget.relative(e.property.value) === e.relatedTarget.items().length - 1) {

            console.log('end');

        }
    })


    // Carousel Paramaters

    $('.owl-carousel').owlCarousel({
        loop:false,
        margin: 5,
        navContainer: '#customNav',
        slideBy: 12,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:12
            }
        }
    
    });



    // Custom NAV
    var owl = $('.owl-carousel');
    owl.owlCarousel();
            // Go to the next item
            $('.customNextBtn').click(function() {
                owl.trigger('next.owl.carousel');
            })
            // Go to the previous item
            $('.customPrevBtn').click(function() {
                // With optional speed parameter
                // Parameters has to be in square bracket '[]'
                owl.trigger('prev.owl.carousel', [300]);
            })
    // End Custom NAV

An error appears:
![capture d ecran 2015-11-17 a 08 21 47](https://cloud.githubusercontent.com/assets/1465346/11204984/4d22cc50-8d04-11e5-9267-888a95674bc5.png)

Sorry I'm not a so advanced coder.

Thank's in advance

Dan

**Comment by jan-herman** [comment]
Hey.
Did you figure it out by any chance? Having the same problem right now and would be grateful for any help.

**Comment by Ceyar** [comment]
@jan-herman 
Hey, no not for the moment. I put this problem aside for the moment. If I find something I will post my solution on this forum. And if you find one, please write the solutions on this issue ;D .

**Comment by jan-herman** [comment]
Here is a code which works for me. Just change the classes according to your markup and instead of just hiding the buttons apply custom classes or whatever.

```javascript
$('.owl-carousel').on('change.owl.carousel', function(e) {
    var visibleSlides = $(this).find('.owl-item.active').length;

    var prevBtn = $('.ui-prev-button');
    var nextBtn = $('.ui-next-button');

    prevBtn.show();
    nextBtn.show();

    if (e.namespace && e.property.name === 'position' && e.relatedTarget.relative(e.property.value) === 0) {
        prevBtn.hide();
    }

    if (e.namespace && e.property.name === 'position' && e.relatedTarget.relative(e.property.value) === e.relatedTarget.items().length - visibleSlides) {
        nextBtn.hide();
    }
});
```

**Comment by tabitaaet** [comment]
OMG! Thank you jan-herman you are a life-saver!!!
