### ISSUE TITLE
3rd image not showing up?

### ISSUE THREAD

**Issue by andiruleu** [OwlCarousel2/OwlCarousel2#1127]
I'm assuming because of the default, items: 3, this is causing it to not show up? 

![screen shot 2015-11-12 at 7 47 07 pm](https://cloud.githubusercontent.com/assets/1781551/11138388/603b1306-8976-11e5-834e-0d6ac53bf8ee.png)

Is there a way to load all images that are showing in the view?

**Comment by sebstck** [comment]
post a link towards the page or a jsfiddle
