### ISSUE TITLE
Issue with loading class and container height on load

### ISSUE THREAD

**Issue by Ashkas** [OwlCarousel2/OwlCarousel2#1129]
I've searched quite widely about this but can find no definitive answer, so hoping somebody can help shed some light on this.

When an owl carousel loads, it doesn't know the height, so the boxes flicker and then pop to the size of the image as the plugin reads the size of the images.

To help get around this I originally tried adding some styles of .owl-loading, but no matter what I do none of my styles are applied there, and to be honest I can't even see it appearing on page load.

In an attempt to get around this I tried adding my own custom 'loading' class and then use the onInitialized callback like this:

    onInitialized: function() {
        $('.loading').removeClass('loading');
    }

That kind of works, but it fires too early. So I can see my loading class then, plugin initalises then remove my class, the carousel collapses in size then reappears as the images are loaded.

What I would like to do is only have that class removed AFTER the images are loaded, but there doesn't appear to be a callback for that. Any further ideas here?

**Comment by WPThemer** [comment]
Same here, still looking for a solution...

**Comment by brewern** [comment]
I am also using onInitialized, to set the height of each slide to the tallest slide. The problem is onInitialized is firing before anything in owl-stage is present.

**Comment by daviddeutsch** [comment]
Right now, the only solution, unfortunately, is a timeout.
