### ISSUE TITLE
Bug on mobile device

### ISSUE THREAD

**Issue by rorc** [OwlCarousel2/OwlCarousel2#1146]
When changing the orientation of the device carousel begins to look like this:
![screenshot_2015-12-02-09-20-59](https://cloud.githubusercontent.com/assets/9752959/11526859/6a98643e-98ee-11e5-916c-2a37269af15d.png)

**Comment by rorc** [comment]
?

**Comment by KitKat777** [comment]
I looked at your site and can't see anything wrong. So explain what you mean by "this"

**Comment by rorc** [comment]
Its strange, but now is really ok, sry =)
