### ISSUE TITLE
chrome animation bug

### ISSUE THREAD

**Issue by atrotors** [OwlCarousel2/OwlCarousel2#1149]
Here is a demonstration of this bug: http://codepen.io/anon/pen/PZwjGa
I have no idea what is actually happening. This only happens in chrome and works fine in firefox.

**Comment by Districtten** [comment]
I'm getting the same issue in chrome too! It looks as though it could be an issue with the way images are loaded as and HTML seems to be working fine.

**Comment by OfekA** [comment]
Have the same issue, any ideas?

**Comment by daviddeutsch** [comment]
You forgot the `.owl-carousel` class.
