### ISSUE TITLE
width full page

### ISSUE THREAD

**Issue by xavierartot** [OwlCarousel2/OwlCarousel2#1158]
Hi,
I'm triing to control the iterm width?
owl-item doesn't work:
```
.owl-item{
  width:100% !important;
}
```
Thank you

**Comment by lucadezena** [comment]
Hello,
you should change the container width to 100%.
For example on one of my websites I have the carousel with 100% width and the container class is .owl-wrapper-outer.
The .owl-item will stretch automatically to the container size.

owl-carousel .owl-wrapper-outer {
    overflow: hidden;
    position: relative;
    width: 100%;
}

Cheers
Luca
