### ISSUE TITLE
Internet Explorer problem

### ISSUE THREAD

**Issue by pascarel** [OwlCarousel2/OwlCarousel2#1159]
Hello, I created a screenshot carousel with your plugin, on all browser its work perfect but in IE 11 have some problems. The images from right appear and dissepear quickly, I tried an overflow hidden, and z-index , but nothing is working. Please help me.
I attach some file with print screen of problem.
P.S. sorry for my English, I hope you understud me.
![1](https://cloud.githubusercontent.com/assets/6737531/11813546/c0745078-a34a-11e5-943a-5afb99437221.png)
![2](https://cloud.githubusercontent.com/assets/6737531/11813550/c262ebec-a34a-11e5-98a4-800a6f56a8ee.png)

**Comment by WPThemer** [comment]
hi all, I am having the save issue with IE11... there is a lot of flicker, images appearing and disappearing with each slide... I am using single slide affect SlideTop and slideOutTop.. in this case the images to be next loaded is visible on rightside of the the slider and then flickers and fades in from top... 

can someone please help here...

**Comment by terryupton** [comment]
I have this issue too. Anyone managed to solve this?

**Comment by deansimcox** [comment]
For the flickering images, the "`transform-style: preserve-3d;`" style could be causing the issue.
