### ISSUE TITLE
Where is owl.transitions.css?

### ISSUE THREAD

**Issue by coffeeneed** [OwlCarousel2/OwlCarousel2#1160]
Love this plugin, but to be honest I need to get my head wrapper around all the versions out there. I installed this version via bower, but I can't see that there are any owl.transitions.css file anywhere? However, I observe there is an animate.scss, but the Owl Carousel documentation (at least here: http://owlgraphic.com/owlcarousel/demos/transitions.html) states that a owl.transitions.css file should be used. I would assume their own documentation is up to date.

In this repo there is a transitions file: https://github.com/OwlFonk/OwlCarousel

But, that's not accessible via bower. What's up? Is OwlCarousel2 an old and outdated version, but still the one and only I can get via bower?

Thanks.

**Comment by shadox** [comment]
Hello,

I was looking for a new plugin to animate my slideshow. However, I notice that there is no option on this version 2 for varied effects CSS transitions "transitionStyle", can you tell me how or if an update is planned in this meaning ?

Sincerely.

**Comment by alexiskattan** [comment]
@shadox i too am looking for transitionStyle.  Did you find anything?

**Comment by annert7** [comment]
Me too any clue?

**Comment by pascalporedda** [comment]
As stated in the docs you can use animations provided by animate.css, which you should have to include beforehand.
