### ISSUE TITLE
Transition Problem in IE9

### ISSUE THREAD

**Issue by dk1992** [OwlCarousel2/OwlCarousel2#1164]
Its working perfectly in all latest browser but in IE9 animation on slider is not working properly, you can open http://www.owlcarousel.owlgraphic.com/index.html and when you click on dot it will animate very fast. Can you suggest to resolve for this problem.

**Comment by ohepworthbell** [comment]
Unfortunately IE9 doesn't support CSS animations at all (as usual, it's IEs fault).
http://caniuse.com/#feat=css-animation

As such, the carousel calculates where the slides should be, but is unable to execute the animation between the slides. It's annoying, as it sort of ruins the aesthetic and user experience of the carousel, but it does work.

Owl Carousel does allow the ability to create your own animations, though not sure what the limitations are here, or how fiddly it'd be to revert to JavaScript animations.

Other options would be simply be to consider how much of a detriment this is, how important IE9 is, and how long a workaround will take. Functionally, the carousel still works, depending on your coding experience it may take a while to develop a hack, and IE9 usage is pretty low. If the workaround massively offsets the importance of IE9 support, maybe just give it a miss.
