### ISSUE TITLE
Synced Owls break if only one item

### ISSUE THREAD

**Issue by cptstarling** [OwlCarousel2/OwlCarousel2#1172]
I'm using synced owls to display a big image with beneath that a carousel of thumbs. These are working fine. However, when there's a page which only contains one image, the whole Owl application seems to break. The big image visually disappears (is still rendered in the code though, but the `opacity` of `.owl-carousel .owl-item .owl-lazy` is set to 0), gets the same size of the thumbnail beneath it, and the only thumb in the carousel beneath it gets out of place.

Ideally the carousel beneath the big image should disappear when there's only one image, and that big image should appear properly ofcourse.

Any idea what could be causing this behaviour, and how this can be fixed please? I'm using _Owl Carousel 2.0.0_ and _jQuery 2.1.4_. There seems to be no errors in my console either.

([link to troubled Owl carousel](http://goo.gl/u02zwk))

**Comment by daviddeutsch** [comment]
Check out this issue: [issues/1378 - Linked OwlCarousel instances](https://github.com/OwlCarousel2/OwlCarousel2/issues/1378)
