### ISSUE TITLE
Disable infinity loop with only one slide

### ISSUE THREAD

**Issue by ShinShinman** [OwlCarousel2/OwlCarousel2#1175]
Hi.
I was wondering if it's possible to disable loop feature when there's only one slide (assuming this option was switch on)? Just like dots option works...

Can't think of situation when loop + one slide is useful, actually it's misleading.

Thanks
Olaf Schindler

**Comment by fe-rod** [comment]
@ShinShinman can something like this help you?

It's a very basic and initial approach #1200

**Comment by ShinShinman** [comment]
Yeah... in my case it's just `target.owlCarousel({ loop: items >1 })`.
Thanks,
S.
