### ISSUE TITLE
loop: true + center: true + slideBy: 3 = bug :(

### ISSUE THREAD

**Issue by SidKH** [OwlCarousel2/OwlCarousel2#1181]
There is a bug when I'm trying to combine these 3 options (loop: true + center: true + slideBy: 3).
If you click on the next button sometime (when cloned items rearrange as I understand) I can see the white gap from the left of the carousel.

[jsFiddle](https://jsfiddle.net/b3un00cw/5/) (I lowered the speed to show it more obviously).
[Video of the issue](https://drive.google.com/file/d/0B2WrnDgc5ioPT0I1SnJWckdxOTg/view)

**Comment by SidKH** [comment]
@daviddeutsch Sorry, did you fixed it or couldn't reproduce?

**Comment by daviddeutsch** [comment]
I closes this because it was so old. Feel free to open a new issue :wink:

**Comment by SidKH** [comment]
Okay, I will try to reproduce it when I have time, but you've already fixed it probably.
Cool plugin btw, used it a lot, thanks.

**Comment by daviddeutsch** [comment]
:+1:
