### ISSUE TITLE
Last item not shown and problems with to.owl.carousel

### ISSUE THREAD

**Issue by dbeja** [OwlCarousel2/OwlCarousel2#1204]
Hi,

I did a small test with js bin: http://jsbin.com/lecuwe/edit?html,js,output
The last item is not shown, it seems owl carousel thinks the number of slides is total - 1.
And if I call to.owl.carousel (Go To Next link in JS Bin) when I get to the last slide but one, the slide jumps to the first one and I never get to the last slide.

Thank you!

**Comment by Mati365** [comment]
+1

**Comment by Mati365** [comment]
:+1:

**Comment by RMJuanRuiz** [comment]
Did you fix it?
