### ISSUE TITLE
Synced Owls in 2.4

### ISSUE THREAD

**Issue by mufasser** [OwlCarousel2/OwlCarousel2#1213]
I want to implement OwlCarousel beta 2.4 but i do not find 'Synced Owls'  can you please describe how can i use in beta version

Regards
Mufasser Islam

**Comment by mkstix6** [comment]
I'm very interested in this too. I'd like to start a project using owlcarousel2.

**Comment by mkstix6** [comment]
#580 has a lot more on the subject with a good example. Part way down.

**Comment by daviddeutsch** [comment]
I am currently preparing code for this, stay tuned.

**Comment by daviddeutsch** [comment]
Check out this issue: [issues/1378 - Linked OwlCarousel instances](https://github.com/OwlCarousel2/OwlCarousel2/issues/1378)
