### ISSUE TITLE
Dots and nav disabled automatically if slider have 4 or more items

### ISSUE THREAD

**Issue by jovan-ivezic** [OwlCarousel2/OwlCarousel2#1215]
I have problem on sliders which have 4 or more items - dots and nav disabled automatically and cannot be activated in slider options. I am using latest plugin version.

**Comment by lesliedoherty** [comment]
I have this same issue using latest plugin version.

**Comment by jovan-ivezic** [comment]
Problem is only with development version. I downloaded latest release from http://owlcarousel2.github.io/OwlCarousel2/, and problem is solved.
