### ISSUE TITLE
Jquery andSelf is removed in 3.0.0 beta

### ISSUE THREAD

**Issue by groie** [OwlCarousel2/OwlCarousel2#1219]
OwlCarousel is depending on andSelf method from Jquery. This method has been [deprecated in Jquery 1.8](https://api.jquery.com/andself/) and finally removed in 3.0.0 beta. That means with new JQuery OwlCarousel can no longer be used.

**Comment by constb** [comment]
according to [this jquery-migrate warning](https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnandself-replaced-by-jqueryfnaddback) the method has simply been renamed to ``addBack``, it's a simple replacement.

**Comment by groie** [comment]
Ah, shouldn't be too hard of a fix  then. I would contribute a pull request, but not sure if it would get processed.

**Comment by daviddeutsch** [comment]
@groie sure thing - just submit the PR and I'll get it in line!

**Comment by daviddeutsch** [comment]
Fixed in 2.2.0. :confetti_ball:
