### ISSUE TITLE
autoHeight not work anymore?

### ISSUE THREAD

**Issue by ghost** [OwlCarousel2/OwlCarousel2#122]
i looked in your code there still autoHight function but when i called it, it's showing an error: Uncaught TypeError: Cannot read property 'eq' of null

can you fixed that?

**Comment by sompylasar** [comment]
I've managed to update the height calculated by `autoHeight` by handling window resize myself and calling the plugin's `update` method by accessing it via the private `_plugins` property of the carousel object.

```javascript
// In a window resize handler, throttled to avoid frequent updates.
$tabsCarousel.data('owlCarousel')._plugins.autoHeight.update();
```

This is actually better than having the plugin update itself only when it wants. The content could update in any other condition, not necessarily window resize.
The only thing we need is a public API to force the update without accessing private variables.

**Comment by edanao** [comment]
is there any update on this? 
my experience is that the autoHeight does not work well with lazy loading.
