### ISSUE TITLE
Drag item to drop outside of carousel

### ISSUE THREAD

**Issue by mohamedhamad** [OwlCarousel2/OwlCarousel2#1220]
I'm working on a project using Owl Carousel and JQuery UI. I would have a carousel of items a user can scroll through. Each item in the carousel would be draggable, and droppable to a droppable space below the carousel. The issue i'm having is that the draggable object from the carousel is contained in the carousel boundaries. So that when i drag something out, the image is stuck within the boundaries but i'm able to successfully get the drop mechanism to recognize the selection.

I just need to be able to free the images in the carousel from the confines of the carousel containment

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Comment by gyx8899** [comment]
@mohamedhamad @damirkoch 
In owl.carousel.js, find "Owl.prototype.registerEventHandlers", the "dragstart" event monitor return false to prevent your "dragstart" event.

If you modify this line:
`this.$stage.on('dragstart.owl.core selectstart.owl.core', function() { return false });`
with modified:
`var that = this;
this.$stage.on('dragend.owl.core', function () {
	that.$element.removeClass(that.options.dragClass)
		.removeClass(that.options.grabClass);
});
this.$stage.on('selectstart.owl.core', function() { return false });`

It works.

**Comment by radikaledward1** [comment]
Im using Owl Carousel, but i want that each item inside the carousel would be draggable outside to be drop in a special area, i made the changes suggested by @gyx8899 but still not working, please help me with this.

**Comment by gyx8899** [comment]
@radikaledward1 
I have a demo test page. You can have a try.
[owlCarousel2-dragdrop-demo](https://gyx8899.github.io/YX-JS-ToolKit/owlCarousel2/owl-dragdrop.html)
