### ISSUE TITLE
owl slider in height 100% ?

### ISSUE THREAD

**Issue by fabienlm** [OwlCarousel2/OwlCarousel2#1221]
hello, is it possible to build a slider in height 100% of browser ? and with a fade effect (its for a one page website)
I don't found solutions ...
an example here http://www.cssvillain.com/hungry/index.html

thanks community !

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
