### ISSUE TITLE
make thumbnail more easily 

### ISSUE THREAD

**Issue by biju001** [OwlCarousel2/OwlCarousel2#1225]
this is old version exmple http://owlgraphic.com/owlcarousel/demos/sync.html but i feel this is not easy to do. bxslider did very easy way for thumbnail. so i wish owlcarousel will add that feature, i like owlcarousel much than other #

**Comment by daviddeutsch** [comment]
Check out this issue: [issues/1378 - Linked OwlCarousel instances](https://github.com/OwlCarousel2/OwlCarousel2/issues/1378)
