### ISSUE TITLE
OwlCarousel sometimes renders as 1 px high

### ISSUE THREAD

**Issue by coffeeneed** [OwlCarousel2/OwlCarousel2#1229]
![owl_carousel_height](https://cloud.githubusercontent.com/assets/11244539/13102434/bac76968-d54e-11e5-8e6f-92005d3db706.jpg)

Hi. Please have a look at this image. Most of the times when loading the page, the OwlCarousel renders like this. Any idea on why this happens? I don't have broad enough knowledge with the carousel sourcecode to diagnose this myself, but willing to paste my code if necessary.

Building a Wordpress page with Roots Sage and the carousel is installed with Bower. 2/10 reloads, the carousel loads as it should, so I guess it's a timing issue.

**Comment by mihdan** [comment]
I have the same problem

**Comment by coffeeneed** [comment]
@mihdan Did you do any further research on this and maybe know how to fix it? I can't seem to fix it, no matter what.

**Comment by mihdan** [comment]
@coffeeneed may be https://github.com/smashingboxes/OwlCarousel2/issues/760

**Comment by coffeeneed** [comment]
@mihdan This is interesting. Will test it at work tomorrow. Thanks a lot, mate.

**Comment by pascalporedda** [comment]
Duplicate of #556 
Has been fixed and will be released soon.
