### ISSUE TITLE
Multiple owl carousel in the same page

### ISSUE THREAD

**Issue by ricardoribas** [OwlCarousel2/OwlCarousel2#1234]
Hi.

I'm having problems with the owl2 slider.
In my page i have a schedule view that browse some events in days and rooms.

This is the slider definition for days:
<div id="owl-days-carousel" class="owl-carousel owl-theme">

This is the slider definition for rooms:
<div id="owl-rooms-carousel" class="owl-carousel owl-theme">

In the first case, im initializing the carousel with some configurations:
$tabs.owlDays = $('#owl-days-carousel').owlCarousel({
            loop: false,
            autoWidth: false,
            mouseDrag: false,
            touchDrag: false,
            center: true,
            items: 8
        });

Indeed for the second carousel
$tabs.owlRooms = $('#owl-rooms-carousel').owlCarousel({
            loop: false,
            autoWidth: false,
            mouseDrag: false,
            touchDrag: false,
            center: true,
            items: 4
        });

When i refresh the page the days and rooms carousel animate properly. When i start to navigate through days, the rooms carousel no longer applies animations. The days carousel is the only element that keeps animating.

Additionally, i have two lines of code that trigger the change of current tab
owlDays.trigger('to.owl.carousel', [$index, 250]);
owlRooms.trigger('to.owl.carousel', [$index, 250]);

That animates the days and rooms carousel, respectively some buttons click events.

I also notice that in the rooms carousel, all DOM items are translated outside the wrapper, leaving the item wrapper with no DOM children.

Any suggestions to solve the animations problem?

Thanks in advance.

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
