### ISSUE TITLE
browser vertical and horizontal scrollbar (mobile)

### ISSUE THREAD

**Issue by SoufianeAbid** [OwlCarousel2/OwlCarousel2#1243]
hi

I have a problem In the margin  In Browsers Mobile

The same problem here https://github.com/smashingboxes/OwlCarousel2/issues/461
The problem was resolved after the update version 2.0.0-beta.3
But in mobile browsers is still the problem 
http://i84.servimg.com/u/f84/12/29/99/55/qdgd10.png

**Comment by andersonIsaac** [comment]
In case of someone still having this issue, here is a solution I've found: 
- first, on CSS:
```
#home-banner .item img {
     width: 100vw;
}
```
- and, on JS (set autoWidth true): 
```
	$('#home-banner .owl-carousel').owlCarousel({
		autoWidth : true,
	});

```

**Comment by paradoxicals** [comment]
@andersonIsaac +1, thanks man worked for me

**Comment by zhacarias** [comment]
@andersonIsaac +1, thanks mate
