### ISSUE TITLE
Fix autoplay documentation (website)

### ISSUE THREAD

**Issue by fabiofolgori** [OwlCarousel2/OwlCarousel2#1249]
In this page http://www.owlcarousel.owlgraphic.com/demos/autoplay.html the documentation is wrong

```
$('.play').on('click',function(){
    owl.trigger('autoplay.play.owl',[1000])
})
$('.stop').on('click',function(){
    owl.trigger('autoplay.stop.owl')
})
```

this should be the correct code

```
$('.play').on('click',function(){
  owl.trigger('play.owl.autoplay', [1000])
})
$('.stop').on('click',function(){
  owl.trigger('stop.owl.autoplay')
})
```

Ciao

**Comment by edgolub** [comment]
The website owlcarousel.owlgraphic.com doesn't have the newest version of the docs. And I don't think this is the correct place to address it. 

You can find the latest docs for the autoplay demo here: http://smashingboxes.github.io/OwlCarousel2/demos/autoplay.html

**Comment by louiswalch** [comment]
Bravo, thanks for the help.
Official website not having updated docs is a huge problem.

**Comment by camtin** [comment]
Agreed, lets updated this
