### ISSUE TITLE
owlcarousel 2 throws an error and doesn't work with jquery-1.12.0

### ISSUE THREAD

**Issue by Montesk** [OwlCarousel2/OwlCarousel2#1257]
Basically it doesn't work and throw an error. Jquery-1.11.2 is ok and owl-carousel works

Browser error
Firefox: 
"TypeError: c is null" (In jquery 1.12.0)
Log: 

Ra()
 jquery-1.12.0.min.js:3
Sa()
 jquery-1.12.0.min.js:3
.css()
 jquery-1.12.0.min.js:3
W()
 jquery-1.12.0.min.js:3
cb()
 jquery-1.12.0.min.js:3
.hide()
 jquery-1.12.0.min.js:4
n.fn[b]()
 jquery-1.12.0.min.js:4
b.prototype.initialize()
 owl.carousel.min.js:2
b/this._handlers["refreshed.owl.carousel"]<()
 owl.carousel.min.js:2
.proxy/d()
 jquery-1.12.0.min.js:2
n.event.dispatch()
 jquery-1.12.0.min.js:3
n.event.add/r.handle()
 jquery-1.12.0.min.js:3
n.event.trigger()
 jquery-1.12.0.min.js:3
e.event.trigger()
 jquery-migrate-1.2.1.min.js:2
.trigger/<()
 jquery-1.12.0.min.js:3
.each()
 jquery-1.12.0.min.js:2
n.prototype.each()
 jquery-1.12.0.min.js:2
.trigger()
 jquery-1.12.0.min.js:3
e.prototype.trigger()
 owl.carousel.min.js:1
e.prototype.refresh()
 owl.carousel.min.js:1
e.prototype.initialize()
 owl.carousel.min.js:1
e()
 owl.carousel.min.js:1
a.fn.owlCarousel/<()
 owl.carousel.min.js:1
.each()
 jquery-1.12.0.min.js:2
n.prototype.each()
 jquery-1.12.0.min.js:2
a.fn.owlCarousel()
 owl.carousel.min.js:1
<анонимная>
 common.js:4
n.Callbacks/i()
 jquery-1.12.0.min.js:2
n.Callbacks/j.fireWith()
 jquery-1.12.0.min.js:2
.ready()
 jquery-1.12.0.min.js:2
K()
 jquery-1.12.0.min.js:2
 jquery-1.12.0.min.js:3:27236

Google chrome
Uncaught TypeError: Cannot read property 'opener' of null

a.getComputedStyle.Ra	@	jquery-1.12.0.min.js:3
a.getComputedStyle.Sa	@	jquery-1.12.0.min.js:3
n.extend.css	@	jquery-1.12.0.min.js:3
W	@	jquery-1.12.0.min.js:3
cb	@	jquery-1.12.0.min.js:3
n.fn.extend.hide	@	jquery-1.12.0.min.js:4
n.fn.(anonymous function)	@	jquery-1.12.0.min.js:4
b.initialize	@	owl.carousel.min.js:2
(anonymous function)	@	owl.carousel.min.js:2
n.isFunction.d	@	jquery-1.12.0.min.js:2
n.event.dispatch	@	jquery-1.12.0.min.js:3
r.handle	@	jquery-1.12.0.min.js:3
n.event.trigger	@	jquery-1.12.0.min.js:3
e.event.trigger	@	jquery-migrate-1.2.1.min.js:2
(anonymous function)	@	jquery-1.12.0.min.js:3
n.extend.each	@	jquery-1.12.0.min.js:2
n.fn.n.each	@	jquery-1.12.0.min.js:2
n.fn.extend.trigger	@	jquery-1.12.0.min.js:3
e.trigger	@	owl.carousel.min.js:1
e.refresh	@	owl.carousel.min.js:1
e.initialize	@	owl.carousel.min.js:1
e	@	owl.carousel.min.js:1
(anonymous function)	@	owl.carousel.min.js:1
n.extend.each	@	jquery-1.12.0.min.js:2
n.fn.n.each	@	jquery-1.12.0.min.js:2
a.fn.owlCarousel	@	owl.carousel.min.js:1
(anonymous function)	@	common.js:4
i	@	jquery-1.12.0.min.js:2
j.fireWith	@	jquery-1.12.0.min.js:2
n.extend.ready	@	jquery-1.12.0.min.js:2
K	@	jquery-1.12.0.min.js:2

**Comment by daviddeutsch** [comment]
Fixed in 2.2.0. :confetti_ball:

**Comment by iiimnot** [comment]
owlcarousel 2.3.4 doesn't work with jquery-1.12.4 (wordpress 5.2)
