### ISSUE TITLE
Horizontal scroll on trackpad

### ISSUE THREAD

**Issue by nodkrot** [OwlCarousel2/OwlCarousel2#126]
Horizontal swipe is very buggy, mac pro 15 inch retina, chrome, firefox and safari.
http://owlcarousel.owlgraphic.com/demos/mousewheel.html

**Comment by iceman11880** [comment]
Here is a working bugfix which just enables one mousewheel action per second.

var timestamp_mousewheel = 0;  //Define it not in a function should 
 owl.on("mousewheel", ".owl-stage", function(a) {
        var d = new Date();
        if((d.getTime() - timestamp_mousewheel) > 1000){ //minimum time difference 
            
            timestamp_mousewheel = d.getTime();
        
        console.log(timestamp_mousewheel);
        console.log(a.deltaY);
            
            
        if (a.deltaY < 0) gR.trigger("next.owl"); else gR.trigger("prev.owl");
        a.preventDefault();
            
        }
        
        
    });
