### ISSUE TITLE
Synced owls and autowidth bug

### ISSUE THREAD

**Issue by mrmoree** [OwlCarousel2/OwlCarousel2#1262]
When trying to sync two owls like seen under examples of owlcarousel 1 [http://owlgraphic.com/owlcarousel/demos/sync.html](url) the count for the second owl does not work properly. It restarts after a few owls. I guess it must have something to do with the width calculation done by autowidth. When i switch of autowidth the sync works properly.

    var sync1 = $("#sync1");
    var sync2 = $("#sync2");

    //progressbar
    var time = 7; // time in seconds

    var $progressBar,
        $bar,
        $elem,
        isPause,
        tick,
        percentTime,
        current;

    //functions
    function syncPosition(event){
        current = event.item.index;
        console.log(current);
        sync1.trigger('to.owl.carousel', current);
        sync2.trigger('to.owl.carousel', current);
        sync2.find(".owl-item")
            .removeClass("synced")
            .eq(current)
            .addClass("synced");
        if(current !== undefined){
            sync2.trigger('to.owl.carousel',current);
        }
    }

    //events
    sync2.on('initialized.owl.carousel', function(event) {
        syncPosition(event);
    });

    //owl init
    sync1.owlCarousel({
        items: 1,
        autoplay: 1,
        autoplayTimeout: 5000,
        autoplayHoverPause: 1,
        margin:0,
        URLhashListener:true,
        startPosition: 'URLHash',
        info: 1,
        lazyLoad: 0
    });

    sync2.owlCarousel({
        margin: 12,
        info: 1,
        lazyLoad: 0,
        center: 1
    });

    sync1.on('changed.owl.carousel', function(event) {
        console.log("y");
        syncPosition(event);
    });

    //loader handling
    sync1.on('load.owl.lazy', function() {
        console.log("is loading");
    });
    sync1.on('loaded.owl.lazy', function() {
        console.log("loaded");
    });

**Comment by daviddeutsch** [comment]
Check out this issue: [issues/1378 - Linked OwlCarousel instances](https://github.com/OwlCarousel2/OwlCarousel2/issues/1378)
