### ISSUE TITLE
Autoplay won't stop on 'stop.owl.autoplay'

### ISSUE THREAD

**Issue by crs1138** [OwlCarousel2/OwlCarousel2#1269]
I have a slider but the trigger('stop.owl.autoplay') seems to make no difference. See https://jsfiddle.net/planxdesign/yjy3vp22/2/

**Comment by camtin** [comment]
Set owlSlider to the element, not to the instance of OwlCarousel.  See: https://jsfiddle.net/yjy3vp22/3/

**Comment by crs1138** [comment]
Your solution does not work either. After it auto-slides to the 2nd slide, I click on the 'pause' button, then click on the first slide (using the nav dots) and the slider automatically slides to the 2nd slide again.

**Comment by daviddeutsch** [comment]
See #1942
