### ISSUE TITLE
Change content when loop:true

### ISSUE THREAD

**Issue by Olexiy665** [OwlCarousel2/OwlCarousel2#1276]
Hi, in my project user can change inner content of slider. But, when user drags the slider changes are discard.

**Comment by gibbitz** [comment]
Sorry to say it but this seems to be on you. When the user changes the content you'll need to find the duplicate slide and update it as well or just not use loop. Right now it seems like the convoluted code around rewind isn't working, so I'm not sure what benefit you're getting from loop anyway.
