### ISSUE TITLE
owlgraphic.com

### ISSUE THREAD

**Issue by Cheonio** [OwlCarousel2/OwlCarousel2#1279]
Hello, thanks for  this realy nice carousel. But letme ask.. what happened with http://owlgraphic.com/ ?? all this domine is offline.. will it be on again?
it says: "strona zablokowana"

**Comment by kkthxbb** [comment]
Yes.

http://www.owlcarousel.owlgraphic.com/

**Comment by camtin** [comment]
Will this ever be fixed?   Can't get to OwlCarousel1 information anymore.

**Comment by daviddeutsch** [comment]
You can check out the old V1 repository, the plain text files are still in there.

**Comment by tobiasherp** [comment]
@kkthxbb That server doesn't seem to exist anymore ... There is some nameserver entry for owlcarousel.com, but I was unlucky so far when trying to load it.

**Comment by manoelmarinsm** [comment]
Oh! meu domínio também está apontando para um outro servidor.
