### ISSUE TITLE
Single Item - Overlay with text and Call to Action button

### ISSUE THREAD

**Issue by stevenrosenberg** [OwlCarousel2/OwlCarousel2#1281]
Hi,

With the previous version of Owl Carousel I had created an overlay for each item... however in the new version (when I upgraded) it totally broke :(

I would like to request built in support for text overlays and buttons / links.

If running full screen width - as I was, it would be nice to move the next/prev buttons to within the image, the same with the navigation dots.

Here is the fiddle - no longer working sadly.

https://jsfiddle.net/steverosenberg/9uL8fr2q/8/

**Comment by damirkoch** [comment]
I'm sorry. You must update your code if you want to use the new version of the OwlCarousel. We can't 
guarantee downward compatibility on major releases.
