### ISSUE TITLE
Multiple carousels on same page don't slide unless the 'loop' option is set to 'true'

### ISSUE THREAD

**Issue by korynorthrop** [OwlCarousel2/OwlCarousel2#1288]
I have multiple Owl Carousels on a page, all with the same `.owl-carousel` class. I'm instantiating them like so:

```
$('.owl-carousel').each(function() {
    var owl = $(this);
    owl.owlCarousel({
        items : 1,
        margin: 12,
        autoWidth: true,
        rewind: true,
        nav: false,
        dots: false,
        onInitialized: callback
    });
});
```

All of the carousels display properly, but only the first carousel on the page slides when its navigation arrows are clicked and/or if I drag the slides manually. However, if I add `loop: true` to the options when I instantiate the carousels, all of them work properly. 

Without going into specifics, I don't want the carousels to loop, I just want them to rewind to the beginning slide when the last slide is reached.

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

**Comment by korynorthrop** [comment]
Can you explain to me why this isn't an 'issue'?
