### ISSUE TITLE
Carousel with fixed width images inside problems...

### ISSUE THREAD

**Issue by GeeWhiz** [OwlCarousel2/OwlCarousel2#1289]
Having a very difficult time trying to create what I thought would be a very simple carousel.

Goal: 
Display four 25px \* 25px icons in a carousel and slide by 1. Use the smallest amount of space possibly. The size of the container can get smaller, so with the responsive breakpoints I should be able to display 4 items, then 3, then 2. Etc.

Problem: 
I have tried various solutions to get this simple carousel working such as: setting sizes on the image icons, trying AutoWidth off and on, setting widths on the containing divs. Etc.

Owl Carousel 2 no matter what I do, behaves like this:
1. Create a 200 pixels wide container.
2. Place five 25x25 pixels images within the container
3. Set Owl Carousel to 4 items

In this scenario, Owl Carousel will create a slider that is 200 pixels wide giving 50 pixels to each item. What I need instead is a 100 pixel slider WITHIN the 200 pixel container. Each item within the slider should only be the width of the item and not the width of the container divided by the items to show.

Is there anyway to achieve this functionality or am I wasting my time trying?

**Comment by GeeWhiz** [comment]
Anyone?

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
