### ISSUE TITLE
Carousel V1

### ISSUE THREAD

**Issue by stovepot** [OwlCarousel2/OwlCarousel2#1290]
Are the V1 docs still accessible and/or is upgrading to V2 flawless?

**Comment by OwlCarousel2** [comment]
@stovepot You can find OwlCarousel 1 docs here: https://github.com/OwlFonk/OwlCarousel. The upgrade isn't completely plug and play, but many of the options are the same.

**Comment by marcusforsberg** [comment]
@OwlCarousel2 The external site for OwlCarousel 1 seems to be down. Is this intentional or has it been hacked? :( https://github.com/OwlFonk/OwlCarousel/issues/655

**Comment by rob-m-andrews** [comment]
@marcusforsberg It is likely intentional. The owner of Owl Carousel #1 is no longer actively maintaining the Owl Carousel #1 project.

**Comment by daviddeutsch** [comment]
Yup, I'm trying to contact him, will see whether I can find something out.
