### ISSUE TITLE
Video slider. Problem with Vimeo videos

### ISSUE THREAD

**Issue by JohnBabenko** [OwlCarousel2/OwlCarousel2#1291]
Why in vimeo videos image preview is not applicable? Result: black block.
http://www.owlcarousel.owlgraphic.com/demos/video.html (do now working with vimeo)
Although link image preview is in the tag(data-src).

**Comment by vorbe** [comment]
I'm also getting this issue, but it looks like only when lazy load is set to true:

Here's an example: 

http://codepen.io/okconsumer/pen/yOwQXP
Two videos within the carousel first being vimeo, second being youtube, youtube thumb seems fine.

There is a difference in output:

When lazy-load is false:
<div class="owl-video-tn" style="opacity:1;background-image:url(https://i.vimeocdn.com/video/567670267_640.jpg)"></div>

When lazy-load is true you're getting that data-src:
<div class="owl-video-tn owl-lazy" data-src="https://i.vimeocdn.com/video/567670267_640.jpg"></div>

I've not found much luck using lazy load on responsive carousels, I'd probably avoid it in this instance as well.

**Comment by JohnBabenko** [comment]
Oh, tnx, bro!
