### ISSUE TITLE
Slides do not rotate

### ISSUE THREAD

**Issue by thecenteno** [OwlCarousel2/OwlCarousel2#1292]
Hello,

I'm wondering if this bug is happening to everyone.  In IE11 and below, the slides do not rotate.  It works perfectly on other browsers. I've even downgraded the jQuery cdn.  Anything would help.  The link is below.

http://www.toolekinney.com/

Thanks!

**Comment by damirkoch** [comment]
Quick testing on ie11. I can't reproduce this problem.
