### ISSUE TITLE
Responsive list of images

### ISSUE THREAD

**Issue by KudMath** [OwlCarousel2/OwlCarousel2#1293]
Hi! I'm trying to use owl-carousel with meteor and passing it a responsive list of images, and instead of being processed properly images end up on top of one another. Any idea why?
![image](https://cloud.githubusercontent.com/assets/3056289/14060053/241a7470-f357-11e5-8855-26585856b2a6.png)

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
