### ISSUE TITLE
"THIS PROJECT IS NO LONGER MAINTAINED"

### ISSUE THREAD

**Issue by Marc-pi** [OwlCarousel2/OwlCarousel2#1294]
https://github.com/OwlCarousel2/OwlCarousel2/commit/df2e54c447bb5b0fb91647acd82193e920a52a00

uh, can we have some explanations @jfclifton @rob-m-andrews  ???
the project left the Smashing Boxes directory and went back to owlcarousel2
what's going on?

**Comment by Badspeed** [comment]
yeah whats up with this ?

**Comment by OwlCarousel2** [comment]
@Marc-pi @Badspeed We can no longer dedicate the time to maintaining this project. I am in search of a new owner, if either of you are interested, please contact me and let me know!

**Comment by progcode** [comment]
@OwlCarousel2 Hi. I'im interested in this project, can you send me the details?

**Comment by daviddeutsch** [comment]
Hey, I'm the new guy :fireworks: closing this now.
