### ISSUE TITLE
Can the lazyload preload more images

### ISSUE THREAD

**Issue by brutesque** [OwlCarousel2/OwlCarousel2#130]
It takes a while before the image on a next slide appears, which doesn't look very user-frienldy.

**Comment by addedlovely** [comment]
+1

**Comment by joepenzo** [comment]
+1

**Comment by aleroy** [comment]
+1

...except...

In [helping someone else](https://github.com/smashingboxes/OwlCarousel2/issues/820), I realized you might want to clamp `settings.items` to a whole number when setting your `page` variable (line 86)... just in case they did something strange.

**Comment by pedromvpg** [comment]
+1 !!!

**Comment by clooth** [comment]
Any update on this?

**Comment by bryns1** [comment]
+1

**Comment by longvo55** [comment]
Use [lazySizes ](https://github.com/aFarkas/lazysizes/)guys, I had much success with it

**Comment by stevenbg** [comment]
Since this seems to be main thread for this feature request, can we get "approved for development" on it?

**Comment by ccharlton** [comment]
+1

**Comment by eminos** [comment]
+1

**Comment by viniciussbs** [comment]
Any news?

Setting `items: 1.001` works until it shows the last image. Than it breaks.

**Comment by pedromagnifico** [comment]
A workable solution with a couple of variations here: https://stackoverflow.com/questions/32346288/owlcarousel-preload-image-in-background/42267289

**Comment by daniloprado** [comment]
+1

**Comment by robinlambert** [comment]
+1

**Comment by richie231186** [comment]
+1

**Comment by sayjeyhi** [comment]
+1

**Comment by damien-roche** [comment]
+1

**Comment by damien-roche** [comment]
So, to clarify - the `lazyLoad` option simply loads images when they come into view. If you have a slider with a few images, and some are not in view, it will not magically load those images in the background. As discussed above, perhaps a `prefetch` option would be good. 

Here is a really simple solution which I've found to work great. Use data attributes for each of your images, hook into `initialized.owl.carousel` and use the source(s) in your data attributes to populate your image `src` attribute. Thus, the carousel will instantly load, and then, in the background, it will run through your slider images and start loading them.

What does this look like in practice? Here is an implementation I worked on over the last few days. In addition to lazy loading slider images before they come into view, it also loads an appropriately optimised image based on the device/slider width. On top of that, if you change the resolution, it will automatically update the images for the new device/slider width. It isn't perfect, and I'm still moving away from jQuery, so feel free to modify. The below solution uses lodash for `_.each`, but I'm sure underscore could be drop-in replacement. This also wraps owl carousel, so you should be able to use it with another carousel  with a few modifications.

NOTE: you WILL have to modify selectors `yd__slider--hero` and `yd__slider__item`. This is just an example of a solution and was not built for general consumption. It has worked fantastically for me in reducing load time on a homepage. I'm also not typically a JS developer, so if someone notices some really naive stuff (looking at you `sliderImageSizes`), please do let me know.

Couple of improvements that could be made:

1. don't update src attributes if you don't have to (currently no check)
2. allow the ability to prefetch a certain number of images
3. on load, stop autoplay and only start it when the next image(s) have loaded
4. show some kind of loading background image before images are loaded
5. completely remove jquery (mainly used for `width()`)

On 3, my autoplay timeout is 7 seconds so it doesn't really affect me, but this could be an issue if you have a quick autoplay timeout.

```javascript
// html
<img src='' data-src-small='small.png', data-src-medium='medium.png' data-src-large='large.png' />

var mySlider = (function(){
  return {
    sliderImageSizes: {
      small: 400,
      medium: 640,
      large: 1200
    },

    initialize: function(selector, options) {
      this.$slider = $(selector);

      this.$slider.on('initialized.owl.carousel resized.owl.carousel',
        { self: this }, this.loadImages
      );

      return this.$slider.owlCarousel(options);
    },

    loadImages: function(event) {
      var self = event.data.self;
      var images = event.currentTarget.querySelectorAll('.yd__slider__item img');
      var imageSize = self.sliderImageSize();

      _.each(images, function(image) {
        var imagePath = image.getAttribute('data-src-' + imageSize);

        if (imagePath != null) {
          image.setAttribute('src', imagePath);
        }
      });
    },

    sliderImageSize: function() {
      var sliderWidth = this.sliderWidth();
      var imageSize = 'large';

      _.each(this.sliderImageSizes, function(width, size) {
        if (sliderWidth <= width) {
          imageSize = size;
          return false;
        }
      });

      return imageSize;
    },

    sliderWidth: function() {
      return this.$slider.find('.owl-stage-outer').width();
    }
  }
})();

// usage

var heroSlider = mySlider.initialize('.yd__slider--hero', {
  items: 1,
  loop: true,
  nav: true,
  navText : ["<i class='fa fa-chevron-left'></i>","<i class='fa fa-chevron-right'></i>"],
  center: false,
  touchDrag: true,
  autoplay: true,
  dots: false
});
```
