### ISSUE TITLE
infinity scrolling not functioning for dragging

### ISSUE THREAD

**Issue by trekkabout** [OwlCarousel2/OwlCarousel2#1300]
I am able to utilize infinity scrolling with the click events (prev and next) but this functionality is lacking when mouse dragging.  Is this purposeful?

**Comment by trekkabout** [comment]
I am using React and I believe this is causing the conflict.  Upon closer inspection I realize items in the carousel are not cloning.  When I create a "sandbox" carousel outside of React cloning of items takes place.  Any guidance would be appreciated.

Thanks

**Comment by daviddeutsch** [comment]
It would help if you could put together an example plnkr (or similar) so can check this out.

**Comment by trekkabout** [comment]
Issue resolved.  Competing versions of owl carousel.  Thanks

**Comment by daviddeutsch** [comment]
Glad to hear that!
