### ISSUE TITLE
Center thumbnails in stage

### ISSUE THREAD

**Issue by jeesus** [OwlCarousel2/OwlCarousel2#1301]
Hey

My thumbnails in Owl Carousel (.owl-stage) are aligned right using CSS property `transform: translate3d(290px, 0px, 0px);`. Where can I remove it so that on load this property won't be added?

I wouldn't want to use CSS's !important.

**Comment by bashaus** [comment]
In order to achieve this, you'd have to wrap your slides inside a container and then apply the transform to that.

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
