### ISSUE TITLE
Render Blocking Javascript

### ISSUE THREAD

**Issue by kasilioglu** [OwlCarousel2/OwlCarousel2#1305]
Hi, i like the carousel and it works fine. Google Pagespeed however gets mad on line element.owlcarousel  even this line is in document ready or in window.load.
I'm not sure this is an issue but maybe someone've some knowledge or suggest a workaround for this thing that pagespeed insist on. 

A simple link would be; 
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.owlcarousel.owlgraphic.com%2Fdemos%2FlazyLoad.html

Thanks.

**Comment by daviddeutsch** [comment]
That's actually pretty trivial to fix - the script just needs to be moved to the end of the `<body>` tag. (See: #1308)

Also: Funny to see that Google Insights doesn't like the Google Fonts CSS! 😂
