### ISSUE TITLE
Question: Usage on Flex Divs

### ISSUE THREAD

**Issue by nicutor** [OwlCarousel2/OwlCarousel2#1306]
Hi,

Can you tell me if Owl Carousel will work on divs which have display set to flex?

Thank you.

**Comment by dallanlee** [comment]
OwlCarousel2 has worked great for me with `display: flex`. I use a flex based grid for development so I often have an OwlCrarousel for mobile screens where the elements take full width (12/12 columns) and then I destroy/do not initiate the OwlCarousel on larger screens but use columns, such as 3 4-column wide elements, in a row. So go ahead and give it a shot! 👍🏻

**Comment by nicutor** [comment]
Thank you @dallanlee . I will try it.

**Comment by dioogbento** [comment]
I know it's been closed but, @dallanlee how would you destroy / do not initiate the OwlCarousel on larger screens?

Thanks in advance.

**Comment by dallanlee** [comment]
@dioogbento I create a function to contain my OwlCarousel options and settings and then call it on applicable screen size on load and after resize. 
i.e. 
```
function owl_carousel_md_down() {
    var $owl_carousel_el = jQuery( '.js--carousel' );

    $owl_carousel_el.addClass( 'owl-carousel' );

    if( $( window ).width() < 1024 ) {
        $owl_carousel_el.owlCarousel({
            // options
        });
    }

}
jQuery( document ).ready( function ($) {

    owl_carousel_md_down();

    $( window ).resize( function(){
        if( $( window ).width() < 1024 ) {
            owl_carousel_md_down();
        } else {
            $owl_carousel_el.trigger( 'destroy.owl.carousel' );
        }
    });

});
``` 
Something to that effect. And in the CSS, of course, use media queries to change display properties when needed.

**Comment by dioogbento** [comment]
@dallanlee Thank you for taking the time to reply. You've been very useful!

**Comment by dallanlee** [comment]
@dioogbento You're welcome. Glad to help.
