### ISSUE TITLE
Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by snecz** [OwlCarousel2/OwlCarousel2#1316]
Hello, I'm trying to implement OwlCarousel 2 into my WordPress theme. But I'm still have Uncaught TypeError: $ is not a function error in the console.
In the header I have css owlcarousle file and jquery 1.11.3 from WordPress.
In the footer I have js owlcarousel and after that I call the plugin.
Where can be mistake?

**Comment by daviddeutsch** [comment]
Please add a link to a page where I can verify this error. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

**Comment by snecz** [comment]
I'm working locally but I'll try with codepen. But generally is the order of scripts good?
Header: owl css and jquery
FooterL owl js and calling plugin

**Comment by daviddeutsch** [comment]
Yeah, that should be alright.

**Comment by snecz** [comment]
There was conflict with jquery that was implemented by WordPress itself. After removing it it's working fine.
