### ISSUE TITLE
Search and filter items

### ISSUE THREAD

**Issue by jayneh** [OwlCarousel2/OwlCarousel2#1319]
I was using this code to filter and also woul love a simple text box to filter items. The code on the fiddle no longer works.

Is it possible to add search and filtering to the carousel this would be a great feature.  

The search box with case insensitive text to search within the dive and show and hide items is what would help with a project I'm going. 
http://jsfiddle.net/TWtwt/301/
http://www.xcast3d.com/spotlight/bootstrap-carousel-filter/
Thank you (sorry if this not the correct place to ask)

**Comment by daviddeutsch** [comment]
Yeah, sorry, that's not really something for this issue tracker. StackOverflow should be a better fit.
