### ISSUE TITLE
Dots

### ISSUE THREAD

**Issue by snecz** [OwlCarousel2/OwlCarousel2#1325]
Hello,
I have owl.theme.default.min.css implemented in the header just after owl.carousel.min.css but still can't see the dots. Where can be the problem?

**Comment by daviddeutsch** [comment]
You probably didn't activate it in the options you passed in. 

(Sorry about the partially canned reply.)

If you still can't get it to work, please add a link to a page where I can verify this error. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

**Comment by snecz** [comment]
I have dots:true

**Comment by snecz** [comment]
I've copied css from owl.theme.default.min.css into my css, removed .owl-theme from the code and it's working fine. There's unnecessary css class before .owl-dots class

**Comment by daviddeutsch** [comment]
Alright, will check on that. Thanks!
