### ISSUE TITLE
What version should we be using?

### ISSUE THREAD

**Issue by martindefatte** [OwlCarousel2/OwlCarousel2#1328]
Honestly, what version should we be using? The website links to v2 beta 2.4 and I somehow got to v2 beta 3.

What's what?

**Comment by daviddeutsch** [comment]
I just returned the versioning to a sane semver scheme. 2.0.0 has been out for over a year and has been used in production (despite cycling through various beta versions) on many pages. That's why I have decided to release a canonical version 2.1.0.

**Comment by martindefatte** [comment]
2.0.1 or 2.1.0?

**Comment by daviddeutsch** [comment]
Definitely 2.1.0.
