### ISSUE TITLE
Custom class for items next to .center

### ISSUE THREAD

**Issue by Voorhuis** [OwlCarousel2/OwlCarousel2#133]
Is there a way to give a custom class to items next to the .center item? I tried to style them using :nth-child(2) and :last-child. But this doesn't seem to work. It would be awesome if each slide had a class the same as the number of the slide. 

The image is a example of how we  would like to style it.
![example](https://cloud.githubusercontent.com/assets/7849607/3230637/ffb871c4-f0a4-11e3-9fdd-8a3f85e4d48b.jpg)

**Comment by rajaishtiaq6** [comment]
Please check it; it may be helpful for you. It is very late, but it may be useful for others.
https://codepen.io/rajaishtiaq6/pen/qBgrYWw
