### ISSUE TITLE
Move from Grunt to Gulp

### ISSUE THREAD

**Issue by daviddeutsch** [OwlCarousel2/OwlCarousel2#1330]
I just know Gulp better, sorry.

**Comment by r3wt** [comment]
I agree. if you move to gulp i will contribute.

**Comment by daviddeutsch** [comment]
I've done a preliminary check today and it seems like all the existing plugins will be covered, so I might get to it tonight.

With Gulp, I have a better chance of fixing outstanding issues (packages missing stuff etc) quicker.
