### ISSUE TITLE
RTL and CENTER not working properly

### ISSUE THREAD

**Issue by adnanmasd** [OwlCarousel2/OwlCarousel2#1333]
I have tested in Owl Carousel v2.1.0 that when center and RTL are set to true it doesnot put the item in the center. The item is shifted left one item. Please fix the issue.

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

**Comment by adnanmasd** [comment]
Sorry I tried but I am not able to setup any fiddle or pen. Will be vary thankful if someone help.

**Comment by daviddeutsch** [comment]
@adnanmasd maybe check one of the other issues that are open for an existing fiddle that you can adapt?

**Comment by adnanmasd** [comment]
Thanks for the tip @daviddeutsch . Here you go [http://codepen.io/anon/pen/mPKKQK](url)

**Comment by adnanmasd** [comment]
@daviddeutsch . Kind Reminder

**Comment by azharijelek** [comment]
I have the same issue, any one have fixed this?

**Comment by arasdesign** [comment]
i have the same issue please help us @daviddeutsch check this pen http://codepen.io/anon/pen/mPKKQK created by @adnanmasd please fix this issue
