### ISSUE TITLE
Single item slide error on version 2.1.0

### ISSUE THREAD

**Issue by cdoshi2000** [OwlCarousel2/OwlCarousel2#1334]
It seems that single item slide does not work as expected with the new 2.1.0 version
It seems to show all the slides at the same time. It is working ok on the older version 2.0.0 beta 2.4.
Wanted to use the new version since there is a fix on the form errors.

see link example here http://plnkr.co/edit/VsKmJpDZ2JeUldzsgOlM?p=preview

Thanks

**Comment by daviddeutsch** [comment]
It seems like you've simply forgotten to set the `owl-carousel` class in your carousel wrapper.

**Comment by htmlboutique** [comment]
you forgot to add class="owl-carousel"  to  analyticsCarousel

**Comment by cdoshi2000** [comment]
Damn, now I just feel silly :)
Thanks. Strange that it worked without the class in the old version :)

**Comment by daviddeutsch** [comment]
Yeah, pretty sure that was a glitch cause I don't see any way in which that even *could* work 😉
