### ISSUE TITLE
next.owl.carousel bug in modals?

### ISSUE THREAD

**Issue by robertdwolf** [OwlCarousel2/OwlCarousel2#1336]
Hi I'm trying to add a carousel into a modal using magnific popup. When it first gets opened the nav buttons work correctly, either going back or forward by just one slide. But if I close the window and open it again the nav links go every two slides. This pattern grows by one when I reopen it and I wasn't sure if it was a bug or something not being used correctly on init?

https://jsfiddle.net/hc4Lg2ku/4/

**Comment by daviddeutsch** [comment]
Pretty simple, actually: You keep adding the prev/next triggers, but Owl only cleans up its own stuff on the `destroy.owl.carousel` event. So the Carousel gets torn down and built up again correctly, your custom triggers remain.
