### ISSUE TITLE
Carousel ignores option "items" and displaying all slides.

### ISSUE THREAD

**Issue by habotho** [OwlCarousel2/OwlCarousel2#1337]
Hello!

I'm working on drupal 7 project based on Porto template. At the product display page I have few attribute widgets which I want to be a carousel. I've implemented Owl Carousel 2 v. 2.1.0 with jQuery 1.12.3. , all owl css files from downloaded archive.

One widget has more than 30 items (models which are taxonomy terms) so I call for that widget (div) carousel plugin with following  code:

```
(function($) {
    Drupal.behaviors.myBehavior = {
      attach: function (context) {
        $('.attribute-widgets > div > div ').addClass("owl-carousel");
        $('.attribute-widgets > div > div ').addClass("owl-theme");
        var owl = $('.attribute-widgets > div > div ');
            owl.owlCarousel({
                items: 10,
                margin: 10,
                autoWidth: true,
                nav: false,
                dots: false
            });
        }
    };
})(jQuery);
```

I don't know why but carousel displaying all items instead of 10 (as option). Also as you can see at following printscreen only 3 first items get class "active". http://srv109687.hoster-test.ru/autowidth_true.jpg

But if I set autoWidth to false all necessary items get class "active" but anyway carousel displaying all items and they are rolled to each other. http://srv109687.hoster-test.ru/autowidth_false.jpg

Porto Drupal Template v. 2.1
Drupal Commerce v. 7.x-1.11

I'm trying to figure out what I do wrong and cann't handle it.

Please help. Thanks!

**Comment by daviddeutsch** [comment]
Pretty sure this is some kind of CSS conflict. I'd need you to supply a link to a page where I can verify this error, though. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

**Comment by habotho** [comment]
Hi David!

Thanks you for reply. Actually I've made it work right. I just had to set width for parent div and now carousel displays necessary items very well. But now I'm faced with another thing. All my carousel items are clickable. So when you move to the last item for example which is not visible when page loads first time and click on that item carousel switch to it start position and clicked item become not visible, but I want carousel appear after click in the same position before clicking. Tell me please how can I do that and sorry for my English.

http://srv109687.hoster-test.ru/carousel.jpg

Thank you,
Ilya

**Comment by habotho** [comment]
Here is the current version of this website: http://goo.gl/Rg9kIx

**Comment by habotho** [comment]
Well the issue is fixed by andjuting js, thanks.

**Comment by Amit241** [comment]
Hi Guy's,

how can show only three dots, when widow width is below of 600 in OWL Carousel
