### ISSUE TITLE
Please fix the v2.1.0 release, problem with bower

### ISSUE THREAD

**Issue by satrya** [OwlCarousel2/OwlCarousel2#1339]
Hi David,
I just updated owlcarousel to v2.1.0, but there is a problem in the v2.1.0 release, it missing some files in **Dist** folder.

![screenshot 2016-04-20 13 07 35](https://cloud.githubusercontent.com/assets/891643/14664851/b29d2774-06f8-11e6-9909-14dca5e2a183.png)

Thank you

**Comment by daviddeutsch** [comment]
Yeah, I'll fix that in my switching to gulp (#1330) - there are a bunch of errors like that.

**Comment by satrya** [comment]
Thank you @daviddeutsch ;)

**Comment by daviddeutsch** [comment]
Hah! I actually needed a release myself, shot myself in the foot.

`2.1.1` was just released - enjoy!
