### ISSUE TITLE
Set the size of the carousel depending of the size of the smallest image ?

### ISSUE THREAD

**Issue by Nicryc** [OwlCarousel2/OwlCarousel2#1341]
Hello,
My carousel displays 1 item by 1 item, my items are pictures and all my pictures have the same ratio (16/9), but not the same size (1920x1080, 1280x720 ...). The size of the carousel is set depending on the size of the biggest image, but can we do the opposite ? Set the size of the carousel depending of the size of the smallest image ?
Thank you and sorry for my English.

**Comment by daviddeutsch** [comment]
Hey @Nicryc - no worries about your English, I understood you just fine. There is no option for this right now. Have you tried setting an outside container to the smallest size? That should constrain all pictures to that size.

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

We have received your feature request and will evaluate the implementation of this. 

I can't give you an estimated date when or if this will be integrated into the project.
