### ISSUE TITLE
Cannot Find OwlCarousel2 In Bower Components

### ISSUE THREAD

**Issue by dallanlee** [OwlCarousel2/OwlCarousel2#1342]
I use CodeKit2. I load assets (plugins, components, etc) from [CodeKit's Bower Tool](https://incident57.com/codekit/help.html#bower). When I search for OwlCarousel2 I can never seem to find the official repository. Am I doing something wrong? I'd love to update to v2.1.1 via CodeKit. I will continue using CodeKit2 for now as it is an essential part of my workflow so I'd like a solution that works with Bower and CodeKit2. Thanks!

**Comment by daviddeutsch** [comment]
You want to search for `owl.carousel` to find it. I'm currently evaluating PR #1340 to make that clearer in the README.

**Comment by dallanlee** [comment]
Thank you for the quick reply @daviddeutsch I'm still confused though because the results I see don't have anything that makes me think they are directly tied to this repository. They have no stars and no known version or last updated date. Am I still misunderstanding?

**Comment by daviddeutsch** [comment]
Seems like a weird glitch. [Searching for the package](http://bower.io/search/?q=owl.carousel) returns no results, but when I try to (re-) register it, it tells me that the package is a duplicate.

I have my money on bower being goofy - just try it again later.

**Comment by dallanlee** [comment]
Yeah, that is strange. I will try it again later but I have tried it already a few times over the past month. So, just in case it's not "Bower being goofy" will you be tracking this?

**Comment by daviddeutsch** [comment]
Yeah, absolutely I will. The weird thing is that including it from the command line works just fine. Did you have issues with that as well, @dallanlee?

**Comment by daviddeutsch** [comment]
[Shows up just fine](http://bower.io/search/?q=owl.carousel) for me, now.

**Comment by dallanlee** [comment]
Thanks, @daviddeutsch My workflow doesn't really involve the command line so I haven't tried anything there. (It still doesn't show in CodeKit2 so it must be a CodeKit issue and I'll go from there.)
