### ISSUE TITLE
Nav and dots are not displayed properly

### ISSUE THREAD

**Issue by Nicryc** [OwlCarousel2/OwlCarousel2#1345]
Hi,
I don't understand how the nav and dots work. I have this : 
`$(document).ready(function(){
  $('.owl-carousel').owlCarousel({
    loop:true,
    items:2,
    autoplay:true,
    nav:true,
    dots:true,
    responsiveClass: true,
    responsive: {
      1280: {
        items: 1
      },
      1920: {
        items: 2
      }
    }
})
});`

I have include all the css and js : 
In the header : 
`<link rel="stylesheet" href="css/owl.carousel.css">
  <link rel="stylesheet" href="css/owl.carousel.min.css">
  <link rel="stylesheet" href="css/owl.theme.default.min.css">`

In the footer : 
`<script src="js/jquery-2.2.3.min.js"></script>
  <script src="js/owl.carousel.js"></script>
  <script src="js/zepto.min.js"></script>`

I can't see the dots and the nav displays like this : 
![capture](https://cloud.githubusercontent.com/assets/15157120/14700277/9c8fe010-079e-11e6-8e42-54d6a5f65554.JPG)

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

**Comment by Nicryc** [comment]
Could it be conflicts with bootstrap ?

**Comment by Nicryc** [comment]
http://pizzeria-paradiso.fr/carrousel.php

**Comment by yaspav** [comment]
I think, the problem is that the file owl.theme.default.min.css for version 2.1.1 in the dist folder doesn't have any content

**Comment by tonykiefer** [comment]
In the owl.carousel.js file you must goto Navigation.defaults...somewhere around line 2690.  There you must set...
        dotClass: 'owl-dot',
        dotsClass: 'owl-dots',
        dots: true,
I answered this question earlier...please refer to.

https://github.com/OwlCarousel2/OwlCarousel2/issues/1354.

when you fix your issue please leave a comment, choose the correct answer, then close the ticket

**Comment by JeffroDH** [comment]
This is a "me too" response.  The distribution zips that I'm downloading don't only have the 2 .js files and the owl.carousel.css.  None of the other files are included.

**Comment by JeffroDH** [comment]
Also, tonykiefer, this issue isn't about a preference of markings, it is a problem with the location of the nav text.  It's appearing below the carousel off to the left, rather than overlaid over the left and right edges.

**Comment by daviddeutsch** [comment]
Yeah, the minified css theme files are bonked. Need to wait until #1330 is done.

**Comment by tonykiefer** [comment]
@JeffroDH...the location of the nav; dots or text...is just a styling issue

**Comment by JeffroDH** [comment]
@tonykiefer I understand that, and have created a style that works for me, but nonetheless it's broken in the current version.

@daviddeutsch Thank you, can this be flagged as a duplicate to anything?

**Comment by showcasefloyd** [comment]
I'm having a similar issue. I've verified that the Navigation.Defaults are set correctly.

**Comment by nebo6** [comment]
I'm having a similar issue.
It turned out, I have had only one "page/owl-item" with loop, then it couldn't create nav or dots on one item only. Just add other items, then it'll be fine. Sorry for bad english, then russian there, use google translate if you need
Не отображались nav и dots, потому что у меня был только один элемент с loop:true. Один элемент - нечего перематывать. Добавьте еще парочку, мне помогло

**Comment by squalvj** [comment]
i solve it by put a class 'owl-theme' in that carousel

**Comment by RuslanBakhar** [comment]
Yeah, by default value in the documentation was only class"owl-carousel" , u should add "owl-theme" too for styling nav elements, class="owl-carousel owl-theme"!

**Comment by pascalporedda** [comment]
I will take care of this.

**Comment by jaynakrani7644** [comment]
nice

**Comment by Viktor727** [comment]
If you will comment <script src="js/zepto.min.js"></script>` it will be working. The problem in this library
