### ISSUE TITLE
UpdateVars

### ISSUE THREAD

**Issue by Uranbold** [OwlCarousel2/OwlCarousel2#1346]
Hello,

Old version has Update vars function and how do we replace this on Owl Carousel 2?

Thanks.

**Comment by daviddeutsch** [comment]
I'm not sure - what did that function do?

**Comment by hvsh** [comment]
@Uranbold I think you are looking for refresh.owl.carousel and refreshed.owl.carousel

**Comment by damirkoch** [comment]
No Answer form Uranbold. Closed.
