### ISSUE TITLE
IE8 and 2.0.0-beta.2.4 - Array or arguments object expected

### ISSUE THREAD

**Issue by ghost** [OwlCarousel2/OwlCarousel2#135]
Hi,

I just tried out the new beta version this morning and I foud out that IE8 is working but the slides aren't sliding with animation, they just shift. And mouseDrag isn't working either.
It was working properly on version 1.

IE8 is warning me with this error message on init (see screenshot)
![owl-ie8-error](https://cloud.githubusercontent.com/assets/6992746/3231820/e4268f90-f0ae-11e3-9c82-e8db440c6fc5.jpg)

Thanks a lot ! Keep up the good work :-)

UPDATE:
The js error message appears when I try to use callbacks this way:

```
function callback() {
    console.log('Initialized');
}

var owl = $('.owl-carousel');
owl.owlCarousel({
    onInitialized: callback
});
```

PS: event data is never passed (undefined) on supported events (onDrag).

But it does work fine if I do this instead:

```
var owl = $('.owl-carousel');
owl.on('initialized.owl.carousel', callback);
owl.owlCarousel();
```

Still no slide animation or mouseDrag though.

**Comment by PrasannaKannan** [comment]
Hi,

I am using carousel 2.0 , still am getting the same error Array or arguments object expected. I also tried by changes done along fix #271. Could you please help me here.

Thanks
