### ISSUE TITLE
Events Callback not working in 2.0.0

### ISSUE THREAD

**Issue by promptdev** [OwlCarousel2/OwlCarousel2#1352]
Neither this:

```
owlMain = $('#amt-carousel-main');
owlOptMain = {
    autoHeight: true,
    dots: false,
    items: 1,
    loop: false,
    nav: true,
    navText: '',
    mouseDrag: false,
    responsive: false
};
owlMain.addClass('on').owlCarousel(owlOptMain);

owlMain.on('initialized.owl.carousel', function(e) {
    console.log('initialized.owl.carousel');
});
```

nor this:

```
owlMain.owlCarousel({
    onInitialized: callback
});
function callback(event) {
    console.log('callback');
}
```

... are working for me. The carousel is still working though.

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by damirkoch** [comment]
No answere. Closed
