### ISSUE TITLE
how to add "arrow" for navigation in place of "prev/next" button!

### ISSUE THREAD

**Issue by devaloza** [OwlCarousel2/OwlCarousel2#1354]
I have created one slider with the help of owlcarousel.Here I want left and right arrow for navigation inplace of dot or prev/next button.how to do so?

**Comment by tonykiefer** [comment]
in your owl.carousel.js file...goto Navigation.Defaults...there you will set...
        navText: ["<img src='/Images/left.png'>", "<img src='/Images/right.png'>"],
        navClass: ['owl-prev', 'owl-next'],

In your html, in the $(document).ready(function){
.owlCarousel({
nav: true,
})
}

there you go!

**Comment by devaloza** [comment]
Thanks for the reply. I already set it with
NavigationText:[<img src="previous arrow.png">,<img src="next arrow.png">;]

**Comment by tonykiefer** [comment]
Please be sure to close this issue and mark the correct answer

**Comment by devaloza** [comment]
ok

**Comment by cyberformed** [comment]
I have given `navText` image as next and previous buttons. but nothing works at all.

**Comment by lxc047** [comment]
Same I tried the above code but it dosent works form me.

**Comment by ipsjolly** [comment]
**Complete tutorial** [**here**][1]

**Demo** [**link**][2]

[![enter image description here][3]][3]

**JavaScript**

	$('.owl-carousel').owlCarousel({
		margin: 10,
		nav: true,
		navText:["<div class='nav-btn prev-slide'></div>","<div class='nav-btn next-slide'></div>"],
		responsive: {
			0: {
				items: 1
			},
			600: {
				items: 3
			},
			1000: {
				items: 5
			}
		}
	});




**CSS Style for navigation**

	.owl-carousel .nav-btn{
	  height: 47px;
	  position: absolute;
	  width: 26px;
	  cursor: pointer;
	  top: 100px !important;
	}

	.owl-carousel .owl-prev.disabled,
	.owl-carousel .owl-next.disabled{
	pointer-events: none;
	opacity: 0.2;
	}

	.owl-carousel .prev-slide{
	  background: url(nav-icon.png) no-repeat scroll 0 0;
	  left: -33px;
	}
	.owl-carousel .next-slide{
	  background: url(nav-icon.png) no-repeat scroll -24px 0px;
	  right: -33px;
	}
	.owl-carousel .prev-slide:hover{
	 background-position: 0px -53px;
	}
	.owl-carousel .next-slide:hover{
	background-position: -24px -53px;
	}	


  [1]: https://www.freakyjolly.com/owl-carousel-2-customize-navigation-next-prev-arrows/
  [2]: https://freakyjolly.com/demo/jquery/OwlCarousel2/
  [3]: https://i.stack.imgur.com/t8XDX.png

**Comment by sanjayacloud** [comment]
Hi, 

I have follow above your steps. But I didn't get indicator dots. Can you help me to add that?

**Comment by murtazajafari** [comment]
You can just add this by jQuery

 ```
$( ".owl-next").html('<img src="https://d1ycj7j4cqq4r8.cloudfront.net/bbb447994b253bea1bb81b002e3413b2.svg" />');
    $( ".owl-prev").html('<img src="https://d1ycj7j4cqq4r8.cloudfront.net/20bd4ea61b53e89f4d8c6531d59f19ab.svg" />');
```

**Comment by rayappanv** [comment]
> You can just add this by jQuery
> 
> ```
> $( ".owl-next").html('<img src="https://d1ycj7j4cqq4r8.cloudfront.net/bbb447994b253bea1bb81b002e3413b2.svg" />');
>    $( ".owl-prev").html('<img src="https://d1ycj7j4cqq4r8.cloudfront.net/20bd4ea61b53e89f4d8c6531d59f19ab.svg" />');
> ```

i want html code and css tell me sir

**Comment by hemaant619** [comment]
> You can just add this by jQuery
> 
> ```
> $( ".owl-next").html('<img src="https://d1ycj7j4cqq4r8.cloudfront.net/bbb447994b253bea1bb81b002e3413b2.svg" />');
>    $( ".owl-prev").html('<img src="https://d1ycj7j4cqq4r8.cloudfront.net/20bd4ea61b53e89f4d8c6531d59f19ab.svg" />');
> ```

hello bro. i am newbie how to add this on jquery , could you give me example of code sample please....

**Comment by wwwisie** [comment]
> > You can just add this by jQuery
> > ```
> > $( ".owl-next").html('<img src="https://d1ycj7j4cqq4r8.cloudfront.net/bbb447994b253bea1bb81b002e3413b2.svg" />');
> >    $( ".owl-prev").html('<img src="https://d1ycj7j4cqq4r8.cloudfront.net/20bd4ea61b53e89f4d8c6531d59f19ab.svg" />');
> > ```
> 
> hello bro. i am newbie how to add this on jquery , could you give me example of code sample please....

Just set inside any document ready.
```
<script>
$( document ).ready(function() {
    $('.owl-carousel').owlCarousel({
	margin: 10,
	nav: true,
	navText:["<div class='nav-btn prev-slide'></div>","<div class='nav-btn next-slide'></div>"],
	responsive: {
		0: {
			items: 1
		},
		600: {
			items: 3
		},
		1000: {
			items: 5
		}
	}
    });
    console.log( "ready!" );
   $( ".owl-next").html('<img src="https://d1ycj7j4cqq4r8.cloudfront.net/bbb447994b253bea1bb81b002e3413b2.svg" />');
   $( ".owl-prev").html('<img src="https://d1ycj7j4cqq4r8.cloudfront.net/20bd4ea61b53e89f4d8c6531d59f19ab.svg" />');
});
</script>
```

**Comment by hidaytrahman** [comment]
It doesn't accept SVG

**Comment by bimalraj91** [comment]
How to add this to vue js project
