### ISSUE TITLE
Control section in the carousel (not below)

### ISSUE THREAD

**Issue by Nicryc** [OwlCarousel2/OwlCarousel2#1355]
Hi,
I try to put the owl-controls div in the owl-stage-outer div to display the control section over the pictures of my carousel, like a lot of carousel (for example : https://getbootstrap.com/examples/carousel/).
Is there a method for it ?
Thank you.

**Comment by tonykiefer** [comment]
Hi,
You are going to manage the placement of your chevrons by using styles.  You provide an example and in that example they use styling...
    width: 30px;
    height: 30px;
    margin-top: -10px;
    font-size: 30px;

Whether I use chevrons or dots I always control the placement of the control using styles.

**Comment by daviddeutsch** [comment]
Thanks @tonykiefer - Precisely, this is done via your own owl-theme.
