### ISSUE TITLE
hidden corusel if page have tag: <a href="tel:+123456789"></a>

### ISSUE THREAD

**Issue by DmitriyRF** [OwlCarousel2/OwlCarousel2#1356]
Maybe I have something error, but if put the tag into html page, the owl-carousel doesn't work.

**Comment by tonykiefer** [comment]
I tried your tag on my page and the carousel works fine.  You have an error on your page and it isn't the carousel.

**Comment by daviddeutsch** [comment]
Yup, can confirm. This should just work.
