### ISSUE TITLE
The theme css files are empty

### ISSUE THREAD

**Issue by andylobel** [OwlCarousel2/OwlCarousel2#1357]
The theme files are empty. e.g. dist/assets/owl.theme.default.css

Thanks

**Comment by waltercruz** [comment]
just came here to say this :)

**Comment by andreacasarella** [comment]
Do you plan to fix it soon?

**Comment by camaech** [comment]
Please fix asap.

**Comment by michaelwoodruff** [comment]
Just noticed this myself as well.

**Comment by lianee** [comment]
the problem is the 2 files

> src/scss/_theme.default.scss
> src/scss/_theme.green.scss

should be named:

> src/scss/owl.theme.default.scss
> src/scss/owl.theme.green.scss

for grunt to be able to properly build the themes (Gruntfile.js lines 100/101)
