### ISSUE TITLE
Bad quality images

### ISSUE THREAD

**Issue by slavame** [OwlCarousel2/OwlCarousel2#1358]
Hi!
I have list of images http://prntscr.com/axikn5 size 150x150
when I turn on responsive plugin increases sizes. for example http://prntscr.com/axilae
why?

**Comment by tonykiefer** [comment]
Your outer container should have a size restriction.  Inner container can be any % of that container.  What responsive plugin are you using?  And...Have you set any media queries?

**Comment by daviddeutsch** [comment]
Agreed, if your images are small, you need a custom style to not have them full-width.
