### ISSUE TITLE
Single img

### ISSUE THREAD

**Issue by jack-fdrv** [OwlCarousel2/OwlCarousel2#1364]
If I have an one image and try make carousel it sat error with clone function on js console.

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!
