### ISSUE TITLE
add: autoprefixer and PostCSS on project

### ISSUE THREAD

**Issue by neysimoes** [OwlCarousel2/OwlCarousel2#1365]
Hi,
I fix a problem with `backface-visibility` and `transform: translate3d`, because in carousel CSS only have -webkit- prefix version.

You accept a PR adding grunt-postcss and Autoprefixer and remove prefixes on SCSS?
https://github.com/nDmitry/grunt-postcss
https://github.com/postcss/autoprefixer

It's will fix this problem and future problems caused by prefix.

**Comment by daviddeutsch** [comment]
Yup, I have already prepared the switch, but have to finish the other features in Gulp, first. Check out the branch `feature/1330-move-to-gulp` if you're curious about the progress.
