### ISSUE TITLE
Add backface-visibility and transform: translate3d without prefix

### ISSUE THREAD

**Issue by neysimoes** [OwlCarousel2/OwlCarousel2#1366]
`backface-visibility` and `transform` have only -webkit- prefix version on `.owl-stage-outer` and `.owl-item`.

It's fix this bug https://github.com/OwlCarousel2/OwlCarousel2/issues/762 and anothers.

**Comment by neysimoes** [comment]
This issue is unnecessary if we implement autoprefixer (#1365).

**Comment by pascalporedda** [comment]
I've merged this PR until we actually changing the build process.
