### ISSUE TITLE
Add dynamic class to owl-item for filtering reasons

### ISSUE THREAD

**Issue by lgatos** [OwlCarousel2/OwlCarousel2#1372]
I'm using owl-carousel item inside a php loop and I want to combine it with mixitup filter. How to add dynamic class in owl-item. 
`<div class="owl-item mix <?php echo $plist['filter_class']; ?>">`

**Comment by daviddeutsch** [comment]
You could attach the class to the div.item that your content sits in and then transfer it to the parent div.owl-item via javascript.

**Comment by ourscreation** [comment]
Is it possible to see the result ? Thx
