### ISSUE TITLE
Swipe continious scroll & deceleration on mobile devices

### ISSUE THREAD

**Issue by mtomov** [OwlCarousel2/OwlCarousel2#1376]
Hello, 

just wondering if the carousel can be swiped and it will scroll like scrolling a page with touch gestures? 

I did not see it in the options, so I guess no, but if you could give me some direction as to where in the JS that would should go if I were to do it? 

Thank you!

**Comment by daviddeutsch** [comment]
Yes, you currently can swipe through the carousel. Just check out the demos to give it a try!
