### ISSUE TITLE
Carousel Navigation for Carousel

### ISSUE THREAD

**Issue by luizfilipe2557** [OwlCarousel2/OwlCarousel2#1377]
Owl doesn't have and "sync with carousel $x" funcionality, while others like _Slick Slider_ (go to [Slick docs](http://kenwheeler.github.io/slick/) and look for "Slider Syncing") have. 

In hash navigation we can do something realy close to this, but it's not the same thing. Sync two carousels with event listenners is not good for the code maintenance.

If I'm making a duplicate sorry, I could not find anything like this here.
<hr>
Possible duplicate for: [this question (is the same idea in the example)](https://github.com/OwlCarousel2/OwlCarousel2/issues/1350).

Demos/examples: 
- [http://vertx.com/edc-transit-sling](http://vertx.com/edc-transit-sling) **(main)**
- [http://produto.mercadolivre.com.br/MLB-683457846-pen-drive-sandisk-8gb-cruzer-blade-_JM](http://produto.mercadolivre.com.br/MLB-683457846-pen-drive-sandisk-8gb-cruzer-blade-_JM)

**Comment by luizfilipe2557** [comment]
Code for **[example one](http://vertx.com/edc-transit-sling)**:

```
$(window).load(function () {
    var $sync1 = $("#sync1"), //big photo
            $sync2 = $("#sync2"), //thumbs
            flag = false,
            duration = 300;

    $sync1.owlCarousel({
        items: 1,
        margin: 10,
        nav: true,
        dots: true,
    }).on('changed.owl.carousel', function (e) {
        if (!flag) {
            flag = true;
            $sync2.trigger('to.owl.carousel', [e.item.index, duration, true]);
            flag = false;
        }
    });

    $sync2.owlCarousel({
        margin: 20,
        items: 3,
        center: true,
        dots: true,
        autoWidth: false,
    }).on('click', '.owl-item', function () {
        $sync1.trigger('to.owl.carousel', [$(this).index(), duration, true]);
    }).on('changed.owl.carousel', function (e) {
        if (!flag) {
            flag = true;
            $sync1.trigger('to.owl.carousel', [e.item.index, duration, true]);
            flag = false;
        }
    });
});
```

**Comment by luizfilipe2557** [comment]
The plugin v1 code is here. Contribute, enjoy and don't forget to credit the source, so that more people get here and contribute even more.


    /**
     * @author Luiz Filipe Machado Barni <luizfilipe2557@gmail.com> <@luizfilipe2557>
     * 
     * Inspired by @tonykiefer's script in http://vertx.com/edc-transit-sling
     *
     * @see https://github.com/OwlCarousel2/OwlCarousel2/issues/1350
     * @see https://github.com/OwlCarousel2/OwlCarousel2/issues/1377
     *
     * @description This function was made to supply the need to synchronize two OwlCarousels. E.g.: embed product gallery.
     *
     * @usage Just follow the steps:
     *      1. Construct your exhibition carousel and your nav carousel the way you want.
     *      2. Use jQuery selector (or variable with the carousel Object) and plug the plugin on it, the plugin has an Object parameter.
     *      3. In the Object parameter, put the $(selector) of the nav carousel in the key 'target' or 'syncWith'. See example below:
     *
     *      @example $('.owl-exhibition').owlSync({
     *                   target: $('.owl-nav')
     *               });
     *
     *      4. You can still pass the duration (in milliseconds) of the slide transition and the index of first slide: 
     *
     *      @example $('.owl-exhibition').owlSync({
     *                   syncWith: $('.owl-nav'),
     *                   duration: 200, // this is an int variable that represents time in milliseconds (ms)
     *                   startIndex: 3 // will link the carousels on the fourth slide.
     *               });
     *
     * @param Object options has the $('.owl-nav') jQuery object and duration of slide transition. (example above)
     *
     * @version 1.0
     *
     */

    "use strict";

    (function ($) {
        $.fn.owlSync = function (options) {

            var src = $(this);

            var defaults = {
                target: false,
                syncWith: false,
                duration: 300,
                startIndex: 0,
                debug: false
            };

            // DEEP COPY:
            var settings = $.extend(true, {}, defaults, options);

            if (settings.debug) {
                console.log(src);
                console.log(settings);
            }

            return src.each(function () {
                var $thisSrc = $(this);
                var $thisNav = settings.target || settings.syncWith;

                if (!$thisNav) {
                    console.error('Error 001: não achei seu carousel de navegação.');
                    return false;
                }

                $thisSrc.on('changed.owl.carousel', function (e) {
                    runOwlSync({
                        owlSrc: $thisSrc,
                        owlTarget: $thisNav,
                        index: e.item.index
                    });
                });

                $thisNav.on('changed.owl.carousel', function (e) {
                    runOwlSync({
                        owlSrc: $thisNav,
                        owlTarget: $thisSrc,
                        index: e.item.index
                    });
                }).find('.owl-item').on('click', function () {
                    runOwlSync({
                        owlSrc: $thisNav,
                        owlTarget: $thisSrc,
                        index: $(this).index()
                    });
                });

                runOwlSync({
                    owlSrc: $thisNav,
                    owlTarget: $thisSrc,
                    index: settings.startIndex
                });

                $thisSrc.trigger('sync.owl.carousel');
            });
        };

        var flag = false;

        function runOwlSync(settings) {
            if (!flag) {
                //console.info('Linking slides.');
                flag = true;
                settings.owlTarget.trigger('to.owl.carousel', [settings.index, settings.duration, true]);
                // Remove actual link between and links the slides who have the same index.
                settings.owlTarget.find('.owl-item').removeClass('linked').eq(settings.index).addClass('linked');
                settings.owlSrc.find('.owl-item').removeClass('linked').eq(settings.index).addClass('linked');
                flag = false;
            } else {
                //console.warn('Blocking link overflow.');
            }
        }
    })(jQuery);

**Comment by daviddeutsch** [comment]
Hi @luizfilipe2557 - Thanks for sharing your solution!

I'm currently working on another solution, though - one that lets you link unlimited owl instances and that is implemented in a native plugin.

**Comment by luizfilipe2557** [comment]
Oh, hello @daviddeutsch, thanks to @eparisio we could get this in [version two](https://github.com/luizfilipe2557/owlcarousel-sync-plugin/tree/version-2) (https://github.com/luizfilipe2557/owlcarousel-sync-plugin/tree/version-2), we made the plugin as a "native plugin", I would be very happy if you could join us to make it better. :smile: 
<hr>
- [V2.2 Plugin example 1 (jsFiddle)](https://fiddle.jshell.net/odahcam/310d470p/)
- [V2.2 Plugin example 2 (jsFiddle)](https://fiddle.jshell.net/odahcam/kdc874zm/)

**Comment by daviddeutsch** [comment]
@luizfilipe2557 There are two things that I object to in this implementation - keeping an internal index (I prefer explicitly handling bubbling to prevent endless recursion) and mixing in the indicator stuff. I understand there is a need to keep a consistent "focus" element, but in my approach, that's a separate plugin that I want to put in. Also - I'm not sure what you use the extra options for, really. Why an extra css class?

I've uploaded my [solution as a gist](https://gist.github.com/daviddeutsch/07b8e5201652456e428c9e7e65729433), perhaps you'd be interested in checking that out? Would be nice to hear if you can make it work for you. It's not completely cleaned up yet, though.

**Comment by luizfilipe2557** [comment]
@daviddeutsch As you can see [**here**](https://fiddle.jshell.net/odahcam/g0svqczz/), the only way of showing the user what is the "in focus" slide is to add a class on it and style in a different way from the other slides, close to what happens with the dots navigation.

I forgot that this class would be added even when the Sync is not set, so we have a Issue here.

**Comment by eparisio** [comment]
@daviddeutsch hi, there is some question about your gist, it's an interest solution but i think the it's only the starting part.
I made a new [gist](https://gist.github.com/eparisio/6ed9d6fd37f964796314719e57763dac) to show the clean solution that i develop. if you have question about some part ask without problems.
The additional class i think is optional but in some case can be necessary to add it.

I think that my actual solution cover the main aspect of this functionality, there are some other case where it will not work and i should focus on this cases.

[gist](https://gist.github.com/eparisio/6ed9d6fd37f964796314719e57763dac)

**Comment by luizfilipe2557** [comment]
@eparisio your solution fails when one carousel have more items on screen than the other. E.g.: if you have a main carousel with 1 item per slide positioned in slide 5 and a nav carousel with 3 items per slide, the nav carousel will have the `.owl-linked` in the slide 3. This is an error that we don't have here: https://fiddle.jshell.net/odahcam/q7jsLk93/

**Comment by daviddeutsch** [comment]
Sorry, but I think I still favor my solution. The main reason is that it's not working with other options (try setting loop to true).

I've opened a [new issue for this](https://github.com/OwlCarousel2/OwlCarousel2/issues/1378), feel free to chime in there once I push the code.

**Comment by odahcam** [comment]
@daviddeutsch Try setting center to false, it's awesome that your carousel works with loop, but I found two problems:

1. `center: false` disables the linking
2. When you have a `loop: true` carousel and a `loop: false` carousel, when the `loop: true` carousel achieves the end, both go back to the start, but when in the first slide you drag left the `loop: true` carousel (last slide in loop), it slides to the **next** slide instead of **previous**. [**Demo here**](https://jsfiddle.net/odahcam/09prv7ap/). (try setting `rtl: true`, the linking will work fine :confused:)

If you let me, I could try to contribute to your code. Besides that I think the user needs to be able to navigate by clicking in the `.owl-item`s that are in the navigation carousel ([click navigation demo here](https://jsfiddle.net/odahcam/ejs47fry/)).

**Comment by daviddeutsch** [comment]
@odahcam 
1. You're using the old version of the code where I didn't have a bug cleared up. It was actually the `items: 1` that disabled the linking.
2. I think what you have there is the expected behavior - a non-looped carousel *should* jump back. Perhaps I'm not really understanding your issue correctly, though.

I'd love for you to help out find and perhaps even resolve any outstanding issues - if you could contribute to the one I opened up, that'd be great!

**Comment by odahcam** [comment]
@daviddeutsch If you saw my example, with [this explanation](https://jsfiddle.net/odahcam/09prv7ap/) you will understand. I know it's outdated, but I'll use it for illustration purpouses.

1. Load the page, run the code in jsFiddle if necessary.
2. Using the nav carousel (on bottom), try to navigate to slide nº5 right on the left side of the slide nº1.
2.1 The carousels will slide to slide nº2. **(unexpected behavior)**
2.2 This only happens when you wait a few seconds before using the carousel, if you be quick enough when the page loads, you will see the expected behavior.
3. After 2.1, navigate right until you get the first nº1 slide on right.
4. Navigate to slide nº5 right on the left side of the present slide nº1.
4.1 You will get the expected behavior.

Sorry if I'm making you waste your time for nothing, I just want to clearify what I said before.
