### ISSUE TITLE
Pull Request:   typeof(stagePadding) === 'function'

### ISSUE THREAD

**Issue by ensemblebd** [OwlCarousel2/OwlCarousel2#1379]
Am wanting to submit a pull request, with your pre-authorization to do so. This is to convert the stagePadding read operations to check if it's a function, and if so - call it. 

This allows one to create a fully responsive staged owl carousel, that can have any width desired, with appropriate stagePadding given the resolution.

Example change for read ops:
`((typeof(this.settings.stagePadding)==='function')?this.settings.stagePadding():this.settings.stagePadding)`
Lines (325,326,327,358,554);

Example usage result: 
```
var target=('.my_responsive_class_container');

var owl=$('#gallery .carousel');

owl.owlCarousel({
      loop:true,
      stagePadding: function() {
            var self=owl;
            var root=self.parents('.row'); // get current width of container of carousel.
            var desired_w=target.css('width').replace(/\D/g,''); // now obtain desired width using a responsive element in the dom.
            desired_w-=target.css('padding-left').replace(/\D/g,'');
            desired_w-=target.css('padding-right').replace(/\D/g,'');
            var diff=root.width()-desired_w; // grab the difference, now we have the size for our stage.
            setTimeout(function() {
                  owl.find('.owl-nav > div').width(diff/2); // one on left, and one on the right. This sets the click-region for navigation to correct size. For this example, it's an overlay.
            },20);// let function return first, so it's resized before we adjust
            return diff/2;
      },
```

So this example allows for a full-width (on page) carousel, that has stage padding which maintains the responsive breakpoints for the content. Basically, if 83% is the size of the inner content region, this forces the carousel to maintain that same sizing for the stage. So the site appears symmetrical on all resolutions.

This is a request to allow such code to be performed, by means of checking if stagePadding is a function or not.
![example_impl](https://cloud.githubusercontent.com/assets/13471536/15081309/0220b3ec-1388-11e6-82cc-0fd1115a1224.png)

Thank you for your consideration!

**Comment by daviddeutsch** [comment]
Would you mind putting together a jsfiddle (or similar) with a custom owl plugin with your changes (preferably with a comment to mark what you changed)? Would love to check this one out!

**Comment by ensemblebd** [comment]
https://jsfiddle.net/5bu9f7h5/53/

Did my best to document it and keep it clean. :)

**Comment by CracyCrazz** [comment]
The same functionality was added a hotfix ago.
