### ISSUE TITLE
AutoHeight Carousel Not Showing In IE 11

### ISSUE THREAD

**Issue by dallanlee** [OwlCarousel2/OwlCarousel2#1381]
[On this site](https://biomane.com/), on that home page, the OwlCarousel doesn't even show up in IE 11. The reason is because the autoHeight is not calculating with the images so it's only 1px in height. The carousel shows up and works great in the other browsers I have tested. Instead of loading the carousel on `document ready`, I am using this `window load` (`jQuery(window).load(function ($)`). Help would be greatly appreciated!

**Comment by ensemblebd** [comment]
probably better to let the pro's answer this, but I did find that if I added css, i could get it to at least show. So I think the problem is css related.

```
.owl-drag.owl-carousel .owl-item {
   min-width: 200px;
}
```

**Comment by dallanlee** [comment]
@daviddeutsch I'm still looking for some help with this..
