### ISSUE TITLE
google chrom bags

### ISSUE THREAD

**Issue by andron81** [OwlCarousel2/OwlCarousel2#1383]
Your plugin very much. however, have a problem in Google Chrome.
When we begin to change the width of the browser montaut here are the bugs :
![1](https://cloud.githubusercontent.com/assets/5709002/15108731/38736e3a-15e0-11e6-8ffd-2af1c82d259b.jpg)
![2](https://cloud.githubusercontent.com/assets/5709002/15108730/3872f9a0-15e0-11e6-8a14-bc62a5358c6c.jpg)

**Comment by andron81** [comment]
P.S.
You can see in this :
[link](http://lead100gram.ru/4.html)

**Comment by daviddeutsch** [comment]
Please try to recreate the error in a dedicated jsfiddle (or similar). I cannot even make out the error in my own chrome, so recreating this would simply take too much time on my end, sorry.

**Comment by andron81** [comment]
you see bugs in http://lead100gram.ru/4.html

**Comment by daviddeutsch** [comment]
yeah, a jsfiddle would definitely help.

**Comment by andron81** [comment]
[jsfiddle](https://jsfiddle.net/andron81_81/s8c973dn/1/#&togetherjs=P53kKhwAJU)

try to resize the width of the result - screen (google chrome)

![image](https://cloud.githubusercontent.com/assets/5709002/15156226/b634a866-16ee-11e6-975d-785f67217522.png)

**Comment by andron81** [comment]
sorry . see this - [example](https://jsfiddle.net/andron81_81/xaqd24j7/)

**Comment by andron81** [comment]
you saw my last post ?

**Comment by daviddeutsch** [comment]
I couldn't open the jsfiddle (it asked me for a collaborate mode, which I denied). You closed this in the meantime. Would be nice if you had mentioned whether (and how!) you resolved your issue. Thanks!
