### ISSUE TITLE
Feature Request: Add !default flag to theme SCSS variables

### ISSUE THREAD

**Issue by joeyquarters** [OwlCarousel2/OwlCarousel2#1385]
When including the SCSS files into a project, it would be nice to just override the colors with a simple variable declaration instead of overriding the resulting CSS. We can do this by adding the `!default` flag for all SCSS variables in the default theme file. E.g. :

_Default owl carousel theme_
```scss
$color-base:			#869791 !default;
$color-white:			#FFF !default;
$color-gray:			#D6D6D6 !default;
```

_Project SCSS file_
```scss
$color-base:			#C18C82;
$color-gray:			#EEEEEE;

@import "owl.carousel.scss";
@import "_theme.default.scss";
```

I would be more than happy to submit a pull request if you would like to approve this feature for development.

**Comment by daviddeutsch** [comment]
Dang, missed that last sentence of yours! Anyhow - great suggestion, thanks! Implemented!
