### ISSUE TITLE
autoplayHoverPause not working properly

### ISSUE THREAD

**Issue by Baranov74** [OwlCarousel2/OwlCarousel2#1394]
Function works incorrectly in version 2.1.0
If to establish autoplayHoverPause:true
Version 2.0.0-beta.2.4
http://www.owlcarousel.owlgraphic.com/demos/autoplay.html - works correctly
Version 2.1.0
http://owlcarousel2.github.io/OwlCarousel2/demos/autoplay.html - Autoplay doesn't renew

**Comment by rahulbshinde** [comment]
Same issue found and trying to resolve.

**Comment by despecial** [comment]
Here is a temporary fix:

```
  $('.owl-carousel .owl-item').on('mouseenter',function(e){
  	$(this).closest('.owl-carousel').trigger('stop.owl.autoplay');
  })
  $('.owl-carousel .owl-item').on('mouseleave',function(e){
  	$(this).closest('.owl-carousel').trigger('play.owl.autoplay',[500]);
  })

```

**Comment by rahulbshinde** [comment]
@despecial: Thank you. This work for me.

**Comment by JayHoltslander** [comment]
@despecial Hmm that didn't work for me.

**Comment by despecial** [comment]
Depends on your version of the script and code implementation.

**Comment by daviddeutsch** [comment]
See #1942

**Comment by suatsuphi** [comment]
<pre>
<code>
$(document).ready(function () {
    var owl = $('.owl-carousel');
    owl.on('mouseleave', function (e) {
        var data = $(e.currentTarget).data('owl.carousel');
        //console.log('autoplay:' + data.settings.autoplay + ' autoplayTimeout' + data.settings.autoplayTimeout);
        if (data.settings.autoplay) {
            $(e.currentTarget).trigger('stop.owl.autoplay');
            $(e.currentTarget).trigger('play.owl.autoplay', data.settings.autoplayTimeout);
            //console.log('It is working autoplay:' + data.settings.autoplay + ' autoplayTimeout' + data.settings.autoplayTimeout);
        }
    });
});
</code>
</pre>
