### ISSUE TITLE
Prefix fo scss variables

### ISSUE THREAD

**Issue by soulcreate** [OwlCarousel2/OwlCarousel2#1395]
Please add prefix for scss default variables, for example:
```
$owl-color-base:			#869791 !default;
$owl-color-white:			#FFF !default;
$owl-color-gray:			#D6D6D6 !default;
```

**Comment by daviddeutsch** [comment]
Already done, check #1385

**Comment by soulcreate** [comment]
But if I use variable $color-base in my scss environment it go to config owl scss!
please rename varibles $color-base and etc to add prefix, for example: 
```
$color-base -> $owl-color-base
```
