### ISSUE TITLE
LazyLoad don't work, when count of items less, than in option

### ISSUE THREAD

**Issue by 66zonta99** [OwlCarousel2/OwlCarousel2#1413]
When I have count items in HTML (2) and set option in javascript (4), than load only one item

$(document).ready(function(){
            $("#owl-carousel").owlCarousel({
    items:4,
    lazyLoad:true,
    loop:true
              });
});

**Comment by Teranode** [comment]
I get this too. Lets say I set the amount of items to 5, and i currently only have 1-4 items.
It will lazyload the first item fine (1) but anything below 5 and above 1 item will not be loaded.

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
