### ISSUE TITLE
Mouse drag up & down prevents auto-play from resuming. Bug?

### ISSUE THREAD

**Issue by isteven** [OwlCarousel2/OwlCarousel2#1414]
Thanks for creating this plugin; it's a life saver. 

I recently found a bug where; if you click & drag your mouse on the auto-play carousel, it will stop the carousel and it will never resume. The only way to make it work again is by dragging left or right. 

This can be reproduced even in the autoplay demo page; http://www.owlcarousel.owlgraphic.com/demos/autoplay.html. Even clicking the Play button doesn't resume it. I tried on latest Chrome & Firefox on Windows platform.

It would be great if someone can find a solution for this. Cheers :)

**Comment by isteven** [comment]
Tagging @daviddeutsch, hopefully someone can shed a light on this. Thanks :)

**Comment by damirkoch** [comment]
Make sure you're using the latest Owl Version!

https://owlcarousel2.github.io/OwlCarousel2/demos/autoplay.html
