### ISSUE TITLE
How can i use loop:true, and items:1, when there are only one slider item

### ISSUE THREAD

**Issue by Nur-jaman** [OwlCarousel2/OwlCarousel2#1415]
I wanna use loop:true with when slider only one here is my code 

`
      $("#owl").owlCarousel({
        items : 1,
        loop:true,
        autoplay: true,
      });`

but it's giving me an error that clone not define 
How can i do that 

Please help 

Thanks in  advance

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [plnkr](https://plnkr.co/), [jsfiddle](http://jsfiddle.net/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by Nur-jaman** [comment]
Thank you so much. 
yes i am using Owl 2.0.0 
i wanna keep loop illusion though there only one slider item. 
here how i am init it `  $("#owl").owlCarousel({ items : 1, loop:true, autoplay: true, });`

the error i getting is 'undefined property .clone is undefined '
i used it in my WordPress site. let me extract it and send you in a zip file 

Thanks Again

**Comment by arodger3** [comment]
Hi
I have same problem
If I use 2.0.0 version, it says "clone not define"
If I use 2.1.0, there is no errors, but slider doesn't create

**Comment by ilicmarko** [comment]
Can you please share your page link or post your code on codepen or jsfiddle because I can't reproduce that problem.

Here is a test:

**Owl Carousel v2.0.0 beta 2.4** *working*
https://jsfiddle.net/wxza0fLw/

**Owl Carousel v2.1.0** *working*
https://jsfiddle.net/0fk258ns/

**Owl Carousel v2.1.4** *working*
Currently using it o na project in development!

Please reply with all needed information so someone can assist you.

**Comment by damirkoch** [comment]
No link to a page where I can verify this error, closed.

**Comment by develpo** [comment]
I guess there is an error of comma at the last property in your code.
It should be like: $("#owl").owlCarousel({ items : 1, loop:true, autoplay: true });
also make sure to add the code in: $(document).ready(function({-----owl carousel code here-------})
