### ISSUE TITLE
When stagepadding and rtl applied active classes calculated incorrectly

### ISSUE THREAD

**Issue by davebat** [OwlCarousel2/OwlCarousel2#1416]
If a carousel has stagePadding and rtl applied, then the wrong number of owl items have the active class applied.

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!
