### ISSUE TITLE
Class init 

### ISSUE THREAD

**Issue by microdesign** [OwlCarousel2/OwlCarousel2#1425]
I lost almost half day to understand when I change the default class '.owl-carousel' 
it broke almost everything. 

How I can have different classes ?

Not only
`<div class="owl-carousel owl-theme">`

but also 

`<div class="owl-carousel-something-else ">`

**Comment by microdesign** [comment]
Also from this code 

`
<script   src="https://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="   crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="assets/owl.carousel.css">	

<div class="owl-carousel owl-theme" style="color:black">
    <div class="item"><h4>1</h4></div>
    <div class="item"><h4>2</h4></div>
    <div class="item"><h4>3</h4></div>
    <div class="item"><h4>4</h4></div>
    <div class="item"><h4>5</h4></div>
    <div class="item"><h4>6</h4></div>
    <div class="item"><h4>7</h4></div>
    <div class="item"><h4>8</h4></div>
    <div class="item"><h4>9</h4></div>
    <div class="item"><h4>10</h4></div>
    <div class="item"><h4>12</h4></div>
</div>


<script type="text/javascript" src="owl.carousel.js"></script>
<script type="text/javascript">
	
	$('.owl-carousel').owlCarousel({
    	autoPlay: 3000, //Set AutoPlay to 3 seconds
        dots: true,
        nav:true,
        items: 2,
})
</script>`


In navigations are only

`<div class="owl-nav"><div class="owl-prev disabled">prev</div><div class="owl-next">next</div></div>`

where are the dots

**Comment by microdesign** [comment]
So with two words version 2 suck - I lost me whole day to find that when I add the old version and it run like a rocket .

**Comment by CracyCrazz** [comment]
I'm sorry but I don't see the problem here yet. If you experience any further issues, feel free to submit a JSFiddle for example.

**Comment by microdesign** [comment]
I show you the code - this code result in BLANK page on my website - there is the problem.

I just switch to the old version without changing any code - and it`s work like a rocket.
That is the problem
