### ISSUE TITLE
Autoplay stops automatically when changing tabs 

### ISSUE THREAD

**Issue by nishantdeveloper** [OwlCarousel2/OwlCarousel2#1426]
I have used to sliders on my home page with different autoplay speeds. However, when i switch tabs and work on some other tabs for a min or two and come back to the main tab having the home page, i find that the autoplay has stopped. Can you please help me with this issue. Thank you in advance.

**Comment by Tranxuanvu** [comment]
The same problem with me, :disappointed:

**Comment by rtud** [comment]
Same here

**Comment by tourdefran** [comment]
Same here...
@nishantdeveloper any workaround?

**Comment by nishantdeveloper** [comment]
No i did not get any workaround. Still waiting for the solution.

**Comment by tourdefran** [comment]
Thanks for your answer. I don't like what they did with Owl Carousel. It used to work fine, but now is very unstable and buggy :/

**Comment by AlexGidarakos** [comment]
After some testing, reverting etc, it seems that the last release without this bug is:
https://github.com/OwlCarousel2/OwlCarousel2/releases/tag/2.0.0-beta.3

**Comment by nishantdeveloper** [comment]
Ok. Thanks for the support and taking out time.

**Comment by AlexGidarakos** [comment]
Happy to help. I hope the project developers manage to fix this bug with a normal release (IDK if it's already fixed on master).

**Comment by tourdefran** [comment]
thanks for the support! @AlexGidarakos this version is working like a charm

**Comment by AlexGidarakos** [comment]
Surely there must be some bug fixes we are missing by reverting to such an old release. Everyone should thoroughly test it before reverting for good.

**Comment by efoula** [comment]
```
$(window).on("blur focus", function(e) {
		var prevType = $(this).data("prevType");
	
		if (prevType != e.type) {   //  reduce double fire issues
			switch (e.type) {
				case "blur":
					// do work
					owl.trigger('stop.owl.autoplay');
					break;
				case "focus":
					// do work
					owl.trigger('play.owl.autoplay', [1000]);
					break;
			}
		}
	
		$(this).data("prevType", e.type);
	});
```

**Comment by ExillustX** [comment]
is there any fix to this?

**Comment by daviddeutsch** [comment]
See #1942
