### ISSUE TITLE
Navigation doesn't work.

### ISSUE THREAD

**Issue by Infonautica** [OwlCarousel2/OwlCarousel2#1428]
Simple feature as custom navigation by some reasons doesn't work for me. No any errors or console logs. Event is actually firing, but carousel simply doesn't move. Navigation buttons is outside of #carousel

Here is my js:
`
    $(document).ready(function(){
        var owl = $("#carousel");
        owl.owlCarousel({
            items: 1,
            loop: true,
            dots: false
        });

```
    $(".carousel__navigation--prev").click(function() {
        console.log('111');
        owl.prev();
    });

    $(".carousel__navigation--next").click(function() {
        console.log('111');
        owl.next();
    });
});
```

`

**Comment by Infonautica** [comment]
Additional:
If i'll add navigation button as slide, mean inside carousel, all buttons will be fine, even those outside carousel.

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by Infonautica** [comment]
Here is the pen:
http://codepen.io/Infonautica/pen/LZEazV

Carousel code in the end of js

**Comment by harryfinn** [comment]
@Infonautica your code seems to work correctly if you add another slide in. Would appear that when there is only one item with `loop: true`, cloned slides are not treated correctly when attempting to trigger a `next` or `prev` action

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
