### ISSUE TITLE
Adding a function to the `reponsive` option breaks carousel

### ISSUE THREAD

**Issue by gtaranti** [OwlCarousel2/OwlCarousel2#1432]
Trying to parameterize the `stagePadding` option (version 2.1.4) depending on the window width by adding a function to the `responsive` option, at initialization stage.
Like that : 
`responsive: {
    0: {
      stagePadding: function() {
        return Math.round(.15 * $(window).width())
      }
    }, ....(other breakpoints)....`

The problem is that even that `stagePadding` gets the **correct value**, the carousel breaks (all items are shown vertically).

If I set a fixed value to `stagePadding` (e.g 320) the carousel works.

If it takes the `stagePadding` option from the function it breaks.

codepen >>>> http://codepen.io/gtaranti/pen/yJNKBP

**Comment by CracyCrazz** [comment]
I have fixed this issue locally. I will push this fix in a few days, once I got a few more hot fixes ready.

**Comment by CracyCrazz** [comment]
Fix is now available in version 2.1.6
