### ISSUE TITLE
Update to latest version broke Carousel

### ISSUE THREAD

**Issue by florianmatthias** [OwlCarousel2/OwlCarousel2#1433]
I updated from a previous Carousel 2.- version to the latest version and my carousel broke. I updated the js file and the css file, but now the carousel items won't float anymore and are listet underneath each other. 

```
    $(".featured-products .group").owlCarousel({
        //items : 1,
        loop : false,
        nav: false,
        dots: true,
        lazyLoad: true,
        baseClass : "owl-carousel",
        margin:10,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
            },
            767:{
                items:2,
            },
            1199:{
                items:4,
                dots: false,
            }
        }
    });
```

Also the dots don't appear, and nav is shown. Exactly the opposite to what I'm declaring above.

http://i.imgur.com/XUODJkn.png

**Comment by leecollings** [comment]
This is the exact same issue as I'm having, how did you resolve it @florianmatthias ?
