### ISSUE TITLE
Delay between slide transitions

### ISSUE THREAD

**Issue by Macuzzin** [OwlCarousel2/OwlCarousel2#1435]
Is there a way to set the delay between slide transitions?

Thanks

**Comment by CracyCrazz** [comment]
I might be wrong, but I did not found a yet implemented way to add a delay between slide transitions.

Although, you could add an animation-delay property to the animation class to have an delay between transitions.

**Comment by CracyCrazz** [comment]
I close this one. If you need further help feel free to ask.
