### ISSUE TITLE
npm -> remove .andSelf and substitute with addBack

### ISSUE THREAD

**Issue by matteo-bombelli** [OwlCarousel2/OwlCarousel2#1452]
i've taken it from *npm* and i found a bug:

> .andSelf is not a function ...

I think is due to the npm installing last versions of jquery.

please remove .andSelf (deprecated) and substitute it with addBack 

on line 1298 (example) will be
```javascript  
this._mergers.push(item.find('[data-merge]').addBack('[data-merge]').attr('data-merge') * 1 || 1);
```

also on line 1327 and 1331 

i've done it and i found no errors.

Thank You!

**Comment by nebrot** [comment]
See PR #1442 for jQuery 3.0

**Comment by CracyCrazz** [comment]
I've committed your changes in the current hotfix branch. This will be released soon.

**Comment by CracyCrazz** [comment]
New version is now available.

**Comment by matteo-bombelli** [comment]
:+1:

**Comment by benjamincombes** [comment]
Thanks a lot for the fix! However, it looks like last version is still 2.1.4 and not 2.1.6 on npm :
https://www.npmjs.com/package/owl.carousel
