### ISSUE TITLE
Width Issue in  Safari

### ISSUE THREAD

**Issue by Raghuch2415** [OwlCarousel2/OwlCarousel2#1458]
owl-item have width 0 automatically only at safari.. other browser have the width according to the screen!!.. When i'm try to resize window width issue resolved automatically,  
![owl_width_issue](https://cloud.githubusercontent.com/assets/20072656/16240795/6c3bd938-3808-11e6-8d45-690bca3429c9.png)

**Comment by Raghuch2415** [comment]
Any one can help me....???

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by damirkoch** [comment]
No answer, closed.
