### ISSUE TITLE
Navigation buttons / dots not working on Chrome?

### ISSUE THREAD

**Issue by khromov** [OwlCarousel2/OwlCarousel2#146]
Just set up the basic demo (2.0.0-beta.2.4) and the buttons (prev / next) and dots do not work on Chrome 35. 

Firefox works OK. Any ideas?

**Comment by b-d-k** [comment]
It seems this issue is supposed to be solved, but we're having the exact same problem with beta 2.4.
Not sure what to do and I don't even know how to test as I don't have a touch enabled laptop. Maybe Modernizr is required? Any input welcome. Thank you.
