### ISSUE TITLE
LazyLoad not updating/loading images responsively

### ISSUE THREAD

**Issue by bobdepalmo** [OwlCarousel2/OwlCarousel2#1460]
Images are not being loaded if say a browser window is resized and goes from displaying 1 item in the slider to 4. The images only load if the slider is advanced. The lazyLoad plugin should be called if the window is resized. Example attached (start at 1 item and resize to show more)

http://codepen.io/bdepalmo/pen/XKNYxQ

**Comment by bobdepalmo** [comment]
Resolved this by adding the "refreshed.owl.carousel" event to line 1845 and 1843.

1845: 'initialized.owl.carousel change.owl.carousel refreshed.owl.carousel': $.proxy(function(e) {

1843: if ((e.property && e.property.name == 'position') || e.type == 'initialized' || e.type == 'refreshed') {

**Comment by dijkermans** [comment]
Hi, I still have this problem with version 2.2.1 :/
