### ISSUE TITLE
Calling initializer function

### ISSUE THREAD

**Issue by wutzelmutz** [OwlCarousel2/OwlCarousel2#1469]
Hey there,

In the Docs it says after setting up the HTML markup, I need to call the initializer function. I'm trying to implement this plugin into a wordpress site and I'm quite unsure where to put this function. Any help would be much appreciated :)

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
