### ISSUE TITLE
Optimizing `refresh` and remove usage of jQuery's `data`

### ISSUE THREAD

**Issue by witrin** [OwlCarousel2/OwlCarousel2#147]
I would like to optimize the refresh method and remove most of jQuery's data calls within the core to improve the performance this week. As far as I can tell, jQuery's `data` method is very bad for the performance at all (http://jsperf.com/jquery-data-vs-object-property/2), so my plan would be to replace those calls with vanilla js arrays and objects except for the plugin call itself. Also the refresh method always re-creates the cloned items too often.

Would you be interested? And if so, do you have still unpublished hotfixes in your local repository?

**Comment by edwin-command-line-inter** [comment]
> Sorry, I have to postpone my pull request for a day. Unfortunately I've forgot to rebase onto the HEAD of the `develop` branch :). [@OwlFonk](https://github.com/OwlFonk) If you'll find the time maybe you could give me a hint about `watchVisibility()`. Greetings!





https://kellyfriction.github.io/MOQfJNkYRJ00gIHkXtVs4wm0Y3XkUheR/
