### ISSUE TITLE
Mouse Navigation

### ISSUE THREAD

**Issue by odahcam** [OwlCarousel2/OwlCarousel2#1473]
With `owl.linked` #1378 Owl users are trying to use the linked feature to make galeries with thumbnail click navigation, using two carousels.

This feature will allow you to Link both the carousels and set the mouse navigation on the thumbnails carousel to create a galllery with thumbnail navigation.

The code is here: https://github.com/odahcam/OwlCarousel2/blob/develop/src/js/owl.mousenav.js

**Comment by eminos** [comment]
I can not get this to work.

`$('.slider-configurator').owlCarousel({
            items: 1,
            //dotsData: true,
            linked: '.slider-nav-configurator',
            onRefreshed: function() {
                setTimeout(function(){
                    $('.slider-configurator').css('min-height', $('.slider-configurator').outerHeight());
                }, 2000);
            }
        });

        $('.slider-nav-configurator').owlCarousel({
            items: 5,
            margin: 20,
            linked: '.slider-configurator',
            mouseNav: true,
            onRefreshed: function() {
                setTimeout(function(){
                    $('.slider-nav-configurator').css('min-height', $('.slider-nav-configurator').outerHeight());
                }, 2000);
            }
        });`

Live example here:
https://www.lintex.se/configurator-dev.html

**Comment by Asday** [comment]
The OP is now a 404, and I'm having trouble getting this to work.  My problem is on line 154.  When you slide the top carousel, I want the bottom carousel to keep the current slide in view, but triggering `to.owl.carousel` with reasonable indices does something completely nonsensical.

https://jsfiddle.net/yjvtntxf/

**Comment by odahcam** [comment]
@Asday you need to include the `owl.mousenav.js` to use a mouse navigation. Your issue is:
 1. You are using the owl.linked plugin incorrectly.
 2. You are not even using the plugin provided in this issue.

As long as I can see, you created your own code for **mouseNav**:

    thumbs.on('initialized.owl.carousel linked.to.owl.carousel', function(e, to) {
                        thumbs.find('.owl-item.current').removeClass('current');

                        var current = thumbs.find('.owl-item:not(.cloned)').eq(to);
                        current.addClass('current');

                        thumbs.trigger('to.owl.carousel', to);
                    });

                    thumbs.on('click', '.owl-item', function() {
                        var el = $(this);
                        el.parent().find('.current').removeClass('current');
                        el.addClass('current');

                        var clones = carousel.find('.cloned').length / 2;
                        carousel.trigger('to.owl.carousel', el.index() - clones);
                    });

First remove this code, correct your Linked functionality and then include owl.mousenav to create a cool mouse navigation.

**Comment by Asday** [comment]
My bad, I got here from a link about linked functionality and incorrectly assumed it was to do with `owl.linked`, which I can't get to work properly, and can't find out why.

You say "correct your Linked functionality", would you be able to tell me how?

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

**Comment by odahcam** [comment]
@damirkoch  I'm not asking for help, I'm asking for an implementation of a plugin I made.

**Comment by damirkoch** [comment]
@odahcam 

Thank you Odahcam. You can create a pull request for this. If we have to received your pull request, we will evaluate the implementation of it.

I can't give you an estimated date when or if this will be integrated into the project.

**Comment by odahcam** [comment]
I've already created ;) https://github.com/OwlCarousel2/OwlCarousel2/pull/1548
