### ISSUE TITLE
Autoplay issues

### ISSUE THREAD

**Issue by ross-reid** [OwlCarousel2/OwlCarousel2#1480]
Hi i think i may have found a bug on the autoplay section i am trying to use this as a sort of gallery page and am adding a slideshow feature using auto play and can get this to stop and start however if i use a next/previous button to move one image then it will begin the slide show/ auto play feature 
thanks

**Comment by Naphier** [comment]
My autoplay just seems to restart on its own even after multiple triggers of stop.owl.autoplay. Looks like I'll have to write my own...

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by szaqal83** [comment]
[https://jsfiddle.net/zhed8o5u/8/](https://jsfiddle.net/zhed8o5u/8/), important note, if you move mouse over for a short time < autoplayTimeout, autoplay starts again on mouse leave, but if you hold mouse over for a while, autoplay won't start on mouse leave.

**Comment by daviddeutsch** [comment]
See #1942
