### ISSUE TITLE
Support for social-feed

### ISSUE THREAD

**Issue by MaluNoPeleke** [OwlCarousel2/OwlCarousel2#1481]
I would like to use it together with https://github.com/pavelk2/social-feed but I cannot make it to work because the page stays empty: http://peleke.diphda.uberspace.de/bower_components/social-feed/owl.html

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by MaluNoPeleke** [comment]
Thanks for the reply and sorry for the missing link. 
In the meantime I got it working: http://peleke.diphda.uberspace.de/bower_components/social-feed/index.html
The "last" challenge is that I need to find out how to make the boxes swipe horizontally instead of the current solution where you still scroll down and swiping doesn't do anything except looking fancy.
