### ISSUE TITLE
Carousel within carousel dots not working properly.

### ISSUE THREAD

**Issue by ImranBug** [OwlCarousel2/OwlCarousel2#1483]
Hi,

I am using an owl carousel within another carousel.
Everything works fine except the navigation dots are acting weird i.e 2nd dot doesn't trigger 2nd slide.

Here is my code:

     $owl1.owlCarousel({
          items: 1,
          dots: true,
          autoplay: true,
          loop: true,
          nav: false,
          touchDrag: false,
          mouseDrag: false,
     });
     $owl2.owlCarousel({
          items: 1,
          dots: false,
          autoplay: false,
          loop: false,
          nav: true,
     });

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by ImranBug** [comment]
I tried replicating the bug but it works fine in fiddle (https://jsfiddle.net/ezrm30av/) :)
I guess the problem was caused by something else at that time & I didn't even end up using carousel within carousel ....
Thanks for you time any ways.
