### ISSUE TITLE
Owl Carousel download does not have files mentioned on the site docs

### ISSUE THREAD

**Issue by kasturichavan** [OwlCarousel2/OwlCarousel2#1487]
Hi,

 I downloaded latest owl Carousel beta2.0.0.0-beta2.4 from http://www.owlcarousel.owlgraphic.com/download/owl.carousel.zip  

As mentioned on site: following files should exist in the folder assets 
![owlcarouselsitefilesincluded](https://cloud.githubusercontent.com/assets/9099244/16843073/ca0f9160-49ad-11e6-95f8-251bebbc26cd.PNG)

But My downloaded zip only contains 
![actualowlcarouseldownloadfiles](https://cloud.githubusercontent.com/assets/9099244/16843095/d95888a2-49ad-11e6-9dfe-9bc297497854.PNG)

I need that files. Can you tell me where I can download those?

Thanks,
Kasturi Chavan

**Comment by CracyCrazz** [comment]
The version you downloaded is outdated. Please use the latest version from this site: 

https://github.com/OwlCarousel2/OwlCarousel2/releases

Or install it via bower.
