### ISSUE TITLE
Display number of total

### ISSUE THREAD

**Issue by SpenMillard** [OwlCarousel2/OwlCarousel2#1496]
Hi,

How can I display the current and total number of slides i.e. 1 of 5?

Thanks,

Spencer

**Comment by codeninja93** [comment]
May be this can help you

<p data-height="265" data-theme-id="0" data-slug-hash="AXadWQ" data-default-tab="js,result" data-user="codeninja93" data-embed-version="2" class="codepen">See the Pen <a href="http://codepen.io/codeninja93/pen/AXadWQ/">Owl Carousel with slide index</a> by Deep Patel (<a href="http://codepen.io/codeninja93">@codeninja93</a>) on <a href="http://codepen.io">CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

**Comment by SpenMillard** [comment]
Hi Deep, 

Thanks a million.

I have loaded the script in a .js file, but am getting the following errors. Any idea?

`owl.owlCarousel is not a function. (In 'owl.owlCarousel', 'owl.owlCarousel' is undefined)`

Thanks again,

Sven

**Comment by SpenMillard** [comment]
Hi again Deep,

This is the carousel I am trying to add it to: [http://tobarchitect.ie/completed/sundays-well/](url)

And the js file: [http://tobarchitect.ie/wp-content/themes/tobarchitect/js/plugins.js](url)

It all seems to be loading ok, only the number is not populating the counter.

Sven

**Comment by SpenMillard** [comment]
Oddly, the autoplay seems to be disabled when this script is loaded as well.

Any idea about this? Sorry for all the questions :-)

**Comment by codeninja93** [comment]
@SpenMillard  

sorry for not replying, was busy ..

did you load jQuery before this script ?

can you post code because link you provided is 404

**Comment by codeninja93** [comment]
@SpenMillard 

script loading must be in this order
``` javascript
<script src="jQuery.js"></script>
<script src="owl.carousel.js"></script>
<script src="yourScriptFile.js"></script>
```

and `autoplay: 5000` is to enable auto-play feature replace your time-span with 5000 (miliseconds)

**Comment by adrien-raciocinative** [comment]
Hi,

Is there any much more modern way to accomplish this directly in the owl carousel plugin?

Thanks,

Adrien
