### ISSUE TITLE
not working with jquery 2.2.4

### ISSUE THREAD

**Issue by hariskhan10** [OwlCarousel2/OwlCarousel2#1498]
hello concerns,

this carousel not working with jquery 2.2.4

**Comment by mcauser** [comment]
Broke bootstrap 3 modals with jQuery 2.2.4

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!
