### ISSUE TITLE
to.owl.carousel move only to right/left

### ISSUE THREAD

**Issue by CyanoFresh** [OwlCarousel2/OwlCarousel2#1499]
Hello. I'm making roulette experiment site and I use your plugin for spinning animation. So can you please add feature to move carousel only right instead of left even it is closer. Because I have a bug with blank space when I move left by event calling

**Comment by CracyCrazz** [comment]
If I understood correctly you want to disable the navigation to the left? 

Could you provide me a JSFiddle or sth. similar where I can verify this issue?

**Comment by CyanoFresh** [comment]
Could not repeat issue with blank space on codepen, maybe it depends on layout.
Also, I found some bug: sometimes when I slide left (by mouse) it jumps a lot (3+ items) on fixed carousel width: http://codepen.io/CyanoFresh/pen/OXvGXA
Sliding on right works perfectly.

**Comment by CyanoFresh** [comment]
`If I understood correctly you want to disable the navigation to the left?`
Yep, as a parameter for `to.owl.carousel` event, like slideIndex and speed

**Comment by pascalporedda** [comment]
I don't think that this is something we will implement. There are other ways to disable this behavior.

**Comment by elgreatly** [comment]
i have the same problem, any one have a solution
