### ISSUE TITLE
Broken in jQuery 3.x

### ISSUE THREAD

**Issue by dschu-lab** [OwlCarousel2/OwlCarousel2#1501]
Hey, since .andSelf() is deprecated in jQuery 3, this plugin will stop working with the latest version of jQuery.  https://api.jquery.com/andself/

But there's a simple solution: 

Just replace .andSelf() with .addBack() and everything goes back to normal.

I would provide you with a pull request, but I'm in a hurry.

**Comment by nebrot** [comment]
It's already fixed, see #1442 
https://github.com/OwlCarousel2/OwlCarousel2/releases/tag/2.1.6

**Comment by dschu-lab** [comment]
Thanks @nebrot !
