### ISSUE TITLE
2 Carousels on same page do not work: (1) Single-slide carousel + (1) Multi-slide carousel

### ISSUE THREAD

**Issue by mokanfar** [OwlCarousel2/OwlCarousel2#1505]
If I have different sections on my website and want to do in owl carousel2:

2 carousels: 1 single sliding carousel + 1 multi item sliding carousel one of the carousels always ends up broken.

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by codeninja93** [comment]
it should work fine.
Make sure you are initializing both carousels with different id or class name. 

```
$(document).ready(function(){
 $("#carouselID1").owlCarousel({
                items: 1
});
 $("#carouselID2").owlCarousel({
                items: 5
});
});
```

**Comment by stephaniefrankdesignltd** [comment]
I have 2 carousels on the same page.
The old version of owl carousel (unknown version) but does not loop for the seocd carousel which you can view 3 slides at once.
So Downloaded 2.3.4 this does not work with my js 

var owl = $('#owl-carousel-banner');
    owl.owlCarousel({
        navigation: false,
        singleItem: true,
        pagination: true,
        autoPlay: 6000,
        dots: true,
        loop: true,
        transitionStyle: "fade"
    });

var owlPagelist = $('#owl-carousel-page-list');
    	owlPagelist.owlCarousel({
        nav: true,
	    navText: [
			// "<img src='/application/themes/custom/images/back-button.png'>",
			// "<img src='/application/themes/custom/images/next-button.png'>"
                "<img src=\"\\application\\themes\\custom\\images\\owl-left.png\">",
                "<img src=\"\\application\\themes\\custom\\images\\owl-right.png\">",
	    ],
        autoPlay: true,
        slideSpeed : 2000,
        dots:false,
        loop: true,
        items: items
	});
It puts the first carousel as the setting for the second and does not do the second.

I have put my code onto demo site for you to look at.

Thank you Stephanie
