### ISSUE TITLE
Can't get videos to display - SOLVED

### ISSUE THREAD

**Issue by gregknudsen** [OwlCarousel2/OwlCarousel2#1512]
#### My apologies. I am using a theme that is not using the latest version of Owl. Please close this issue.

---

I hit a wall tonight. I just cannot get videos to play or even display.

See this [link](http://stackoverflow.com/questions/26194001/owl-carousel-not-displaying-videos) from StackOverflow. My question would be identical to the OP in that I have copied and pasted the code with no results. I added the CSS suggested to give the .item-video a height of 300px with no results. It just makes the blank space taller. It works for neither YouTube nor Vimeo videos. I followed the advice further down the thread with no results. I would like to know if others are having the same issue or if anyone might have a solution.

**Comment by damirkoch** [comment]
SOLVED
