### ISSUE TITLE
Disable Slider mobile

### ISSUE THREAD

**Issue by jolution** [OwlCarousel2/OwlCarousel2#1514]
good morning, thanks for this nice slider :)
Its looks great on my desktop.
May there is a possibiliy to disable the slider mobile ?
I want to show the Items among themselves. That the user can scroll instead of sliding.
Thanks a lot

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
