### ISSUE TITLE
OWL center item

### ISSUE THREAD

**Issue by sufiiiyan** [OwlCarousel2/OwlCarousel2#1515]
not able to apply dynamic css on run time.
css not working on left side of center item but working correctly on right side ! any idea?
i had seen 'owl-item active center' css class for center item
'owl-item active' css class for right side item
and 'owl-item cloned' css class for left side items
is cloned css class affecting there any idea?

**Comment by odahcam** [comment]
Can you post an example?

**Comment by ianhobbs** [comment]
too many of these incomplete issues.... conversations dropped. Think they should auto expire..
