### ISSUE TITLE
Owl Controls Missing

### ISSUE THREAD

**Issue by johnrlytle** [OwlCarousel2/OwlCarousel2#1516]
I'm using owl.carousel.2.0.0-beta.2.4.

Owl Controls output is nowhere in my rendered source:

	$('#owl-slider').owlCarousel({
		items:1,
		autoplay:true,
		autoplayHoverPause:true,
		smartSpeed:10,
		dots:true,
		responsiveClass:true,
		responsiveRefreshRate:0,
		animateIn: 'fadeIn',
		**nav: true,**
		navText: ['<i class="fa fa-chevron-left"></i>','<i class="fa fa-chevron-right"></i>'],
	});

**Comment by mformanu** [comment]
The HTML changed with the last update (even on the demo-pages!) and a wrapping div is gone, which breaks the basic theme. Try my work-around:

```
/* Basic Theme */

.owl-nav, .owl-dots {
  margin: 10px;
  text-align: center;
  -webkit-tap-highlight-color: transparent
}
.owl-nav [class*=owl-] {
  color: #fff;
  font-size: 14px;
  margin: 5px;
  padding: 4px 7px;
  background: #d6d6d6;
  display: inline-block;
  cursor: pointer;
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px
}
.owl-nav [class*=owl-]:hover {
  background: #869791;
  color: #fff;
  text-decoration: none
}
.owl-nav .disabled {
  opacity: .5;
  cursor: default
}
.owl-dots .owl-dot {
  display: inline-block;
  zoom: 1;
  /* display: inline */
}
.owl-dots .owl-dot span {
  cursor: pointer;
  width: 10px;
  height: 10px;
  margin: 5px 7px;
  background: #d6d6d6;
  display: block;
  -webkit-backface-visibility: visible;
  -webkit-transition: opacity 200ms ease;
  -moz-transition: opacity 200ms ease;
  /* -ms-transition: opacity 200ms ease; */
  -o-transition: opacity 200ms ease;
  transition: opacity 200ms ease;
  -webkit-border-radius: 30px;
  -moz-border-radius: 30px;
  border-radius: 30px
}
.owl-dots .owl-dot.active span,  .owl-dots .owl-dot:hover span {
  background: #869791
}
```

**Comment by andview** [comment]
Hi! It's working. Thanks. But I look one problem. I use responsive (five) items, and if visible one of five item displayed all five dots; if visible more than one items dots not all. I'm not programmer, build own portfolio. Please, check here [a-che.net](url)

**Comment by mformanu** [comment]
It doesn't work like that. You can see all images in **two** _phases_, so If you would have 8 images and 4 beeing displayed at the same time, you would also see only **2** dots. Look here: http://www.auszeit-weltweit.de/blog/ (8 images, 4 beeing displayed).

**Comment by andview** [comment]
I understand it, but in my case, very necessary that number of dots matches the number of items, if it's possible.

**Comment by despecial** [comment]
The dots have the following function: navigate the pages you see.
It's not about items. Even if you change the number of dots to the total number of items, there is no logic behind because navigating won't work if you see 5 items on the same page.

The only way to use it in responsive mode is to set show only 1 item per page.

**Comment by andview** [comment]
Thank you

**Comment by johnrlytle** [comment]
Thanks all. I had actually figured that out right after and added it.
