### ISSUE TITLE
autoplayHoverPause:true confusing

### ISSUE THREAD

**Issue by guykatz** [OwlCarousel2/OwlCarousel2#1517]
Hi;
the common person thinks that if you set autoplayHoverPause:true, then when you hover out the carousel resumes its autoplay feature.
thanks

**Comment by odahcam** [comment]
`autoplayHoverPause`:
- if **true**: the autoplay will pause when mouse is over the carousel.
- if **false**: the carousel will do nothing about the autoplay when mouse is over the carousel.
