### ISSUE TITLE
item:1 + animation + autoloop + loop time <1 does not work

### ISSUE THREAD

**Issue by guykatz** [OwlCarousel2/OwlCarousel2#1518]
Hi;
the following specific option combination does not work:

```
items:1,
animateOut: 'fadeOut',
animateIn: 'fadeIn',
autoplay:true,
autoplayTimeout:1000,
```

changing some of the values, for example setting autoplayTimeout to a value greater than 1000 works, changing items to 2 works etc. this specific combination together does not work - the animation will animate ONLY the first item and then will not continue (there is html modifications still going on in the background but visually its not shown)
see: http://jsbin.com/coxucah/5/edit?html,js,output

**Comment by daviddeutsch** [comment]
See #1942
