### ISSUE TITLE
remove navigation when only one item

### ISSUE THREAD

**Issue by matthewcarleton** [OwlCarousel2/OwlCarousel2#1519]
Not sure if this is possible but I'd like to remove the owl-controls if there is only one item.

**Comment by asipple1** [comment]
So I was able to solve this by using the onInitialize event.

 You will first need to determine how many slides are in a carousel.

` var item_count = parseInt($(this).find('.slide').length `);

Second in the owlCarousel
```
onInitialize: function(event) {
    // Check if only one slide in carousel
    if (item_count <= 1) {
        this.settings.loop = false;
        this.settings.nav = false;
        this.settings.dots = false;
    }
    // I have more than one slide?! Great what are my options?!
    else {
        this.settings.loop = true;
        this.settings.nav = true;
        this.settings.dots = true;
    }
},
```

**Comment by matthewcarleton** [comment]
Any idea why I get the error "Function statements must have a name."

**Comment by asipple1** [comment]
post your code

**Comment by matthewcarleton** [comment]
Fixed, I didn't place inside OwlCarousel. Thanks!

**Comment by despecial** [comment]
Thanks for the code @asipple1 

Any idea why it's still draggable?

`  	onInitialize: function(event) {
    // Check if only one slide in carousel
    if (item_count <= 1) {
        this.settings.loop = false;
        this.settings.dots = false;
        this.settings.mouseDrag = false;
        this.settings.touchDrag = false;
        this.settings.pullDrag = false;
        this.settings.freeDrag = false;
    }
    // I have more than one slide?! Great what are my options?!
    else {
        this.settings.loop = true;
        this.settings.dots = true;
    	}
	},
`

**Comment by asipple1** [comment]
Do you know what version of owl you are using? I just did this.settings.mouseDrag = false; and it worked for me.

**Comment by despecial** [comment]
The latest: 2.16

**Comment by asipple1** [comment]
you should try  a console.log(this.settings). See if you are actually setting mouseDrag = false

**Comment by Alit4inov** [comment]
another solution

$('.main-slider').owlCarousel({
            items: 1,
            loop: true,
            onInitialized: callback,
        });

function callback(event) {
            var items = event.item.count;
            console.log(items);
            if (items <= 1) {
                $('.owl-carousel .owl-stage').addClass("single");
            }
        } 

and in css
.owl-carousel .single{ transform: translate3d(0px,0px, 0px) !important; }
