### ISSUE TITLE
OwlCarousel 2.1.6 not available on npmjs.com

### ISSUE THREAD

**Issue by martijngastkemper** [OwlCarousel2/OwlCarousel2#1520]
2.1.4 is the latest version on npmjs.com. I would like to use 2.1.6 because of the jQuery 3 compatibility fixes.

**Comment by CracyCrazz** [comment]
@daviddeutsch I don't have yet the access to publish a new version in the npm registry.

**Comment by eli-mar** [comment]
+1

**Comment by eli-mar** [comment]
Is there an ETA for this? Just to know if I have to include the plugin in my project in another way :-)

**Comment by daviddeutsch** [comment]
@eli-mar done!

**Comment by eli-mar** [comment]
@daviddeutsch, thank you so much!
