### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by stephan-v** [OwlCarousel2/OwlCarousel2#1521]
Is this still in development or what? I am keen to implement this in a huge project but I am unsure since the project development looks stale with the "new owner" stuff and the last update being 2 months ago.

Hopefully somebody can tell me a bit more.

**Comment by CracyCrazz** [comment]
Hey Stephan,

I can speak for David, the answer is yes. It is still maintained, but we are currently working on a plan / milestones for this project, quite big things that need to be planned. 

That's all I can tell you at the moment.
