### ISSUE TITLE
Can you center an item on click

### ISSUE THREAD

**Issue by PyroSteveJr** [OwlCarousel2/OwlCarousel2#1522]
Say you show 5 items and either has 20 in there or infinite loop. If I click on the 5th item (showing 1-5), the 5th item would now be center, showing 3-4-5-6-7?

**Comment by asipple1** [comment]
have you tried the to-owl-carousel event? http://owlcarousel2.github.io/OwlCarousel2/docs/api-events.html#to-owl-carousel
