### ISSUE TITLE
move the slide as soon as the video ends

### ISSUE THREAD

**Issue by maynam26** [OwlCarousel2/OwlCarousel2#1523]
I have the video in the first slide. i want to move the slide as soon as the video ends. I am not able to do so.  As my video is in the first slide,can we autoplay the video as soon as the page loads.
My owl carousel function
$('.owl-carousel').owlCarousel({
                            items:1,
                            merge:true,
                            loop:true,
                            margin:10,
                            nav:true,
                            autoplay:true,
                            autoplayTimeout:140000,
                            video:true,
                            videoHeight: 520, 
                            videoWidth: 1000,
                            lazyLoad:false,
                            center:true,
                            autoHeight:true
                        });

**HTML Code**

<div class="owl-carousel">
<div class="item-video" >
<a class="owl-video"  href="https://www.youtube.com/embed/F0vg4HUEIyk"></a>
</div>

<div class="item"><img src="1.jpg"/></div>

<div class="item"><img src="2jpg"/></div>

<div class="item"><img src="3.jpg"/></div>

</div>

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

We have received your feature request and will evaluate the implementation of this. 

I can't give you an estimated date when or if this will be integrated into the project. This might happen when the main refactoring will take place.
