### ISSUE TITLE
How to achieve this event idea?

### ISSUE THREAD

**Issue by MoradHamdy** [OwlCarousel2/OwlCarousel2#1524]
Hello there,

I want to fire some code when a slide will '_sure_' go to another slide. I mean actually when the slider goes from item 1 to item 2, or from item 1 to any item index.

The **changed** event is fired when the slider ends sliding to another item.
The **translate** event is fired any moment you try to move slider items.
The **translated** event is fired when the slider end translation whatever it moved to another slide or it back to its same current position.

What i'm searching for is "if the slider will '_sure_' go to the next item, do something"

The idea that i'm searching for is to fire some function after item changed which will be with the available event "changed". But when the slider know that it will '_sure_' go to a different slide, do some function. This is the missed event for me.

Here is a preview link provided by OwlCarousel2 for how events work http://www.owlcarousel.owlgraphic.com/demos/events.html

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

We have received your feature request and will evaluate the implementation of this. 

I can't give you an estimated date when or if this will be integrated into the project. This might happen when the main refactoring will take place.
