### ISSUE TITLE
responsive is not work on mobile device

### ISSUE THREAD

**Issue by andview** [OwlCarousel2/OwlCarousel2#1526]
Everything is fine when I changing browser width on PC. But on mobile device (android 2.2 chrome & opera; iphone 4s) it's not working. 
`<script>
$('.owl-carousel').owlCarousel({
    autoplay:true,
    autoplayTimeout:4000,
    autoplayHoverPause:true,
	loop:true,
    margin:0,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true,
        },
        480:{
            items:2,
            nav:true,
        },
        960:{
            items:3,
            nav:true,
            loop:true
        }
    }
})

</script>`
I need help or hint or clue.
TNX

**Comment by andview** [comment]
am sorry
<meta name="viewport" content="width=device-width, initial-scale=1"> 
problem solved.

**Comment by skostadinovcom** [comment]
Hey how to fix? I have the same problem :)

**Comment by infseeker** [comment]
I had the same problem and solved it as follows:
`responsiveBaseElement: 'body'`

**Comment by nikiul** [comment]
> I had the same problem and solved it as follows:
> `responsiveBaseElement: 'body'`

Dude, u saved my time

**Comment by PouriaDiesel** [comment]
> I had the same problem and solved it as follows:
> `responsiveBaseElement: 'body'`

Tnx Bro:)

**Comment by Coennie** [comment]
> I had the same problem and solved it as follows: `responsiveBaseElement: 'body'`

Hero of the day!

**Comment by Araman99** [comment]
> I had the same problem and solved it as follows: `responsiveBaseElement: 'body'`

Thanks bro 👍🏼

**Comment by royzhicheng** [comment]
thanks.
