### ISSUE TITLE
owl version 2.1.6 has problem with jquery 3.1.0

### ISSUE THREAD

**Issue by Tahere-NJ** [OwlCarousel2/OwlCarousel2#1528]
Hello everyone
The owl container does not show anything.
This is the error: " TypeError: invalid 'in' operand obj"
and these lines are what I see in the debugger:

isArrayLike()                                     jquery-3.1.0.js:534
.each()                                              jquery-3.1.0.js:365
Owl.prototype.setup()                      owl.carousel.js:506
Owl()                                                owl.carousel.js:173
$.fn.owlCarousel/<()                         owl.carousel.js:1661
.each()                                               jquery-3.1.0.js:368
jQuery.prototype.each()                     jquery-3.1.0.js:157
$.fn.owlCarousel()                              owl.carousel.js:1656
<anonymous>   
please help if you know any solution.
Tanx

**Comment by CracyCrazz** [comment]
We'll look into this with #1538.

**Comment by rathahin** [comment]
For someone else who have similar problem in version 2.2.1 with jQuery version 3.2.0:
![image](https://cloud.githubusercontent.com/assets/4031452/24642796/a17701f4-1912-11e7-9c5a-f80e972ecaa7.png)

In my case, the type of variable 'responsive' is boolean not obj nor array. I guess the new version may no longer need to set responsive when set up the carousel. So I have a try to remove the responsive from option and the error is go away.
![image](https://cloud.githubusercontent.com/assets/4031452/24642955/6d8d9c26-1913-11e7-87b7-77076b7245bb.png)
