### ISSUE TITLE
The Double Row Bug (And it's solution!)

### ISSUE THREAD

**Issue by lautaromss** [OwlCarousel2/OwlCarousel2#1529]
Hi guys, I'm using Owl for a new project and I kept having this bug where the carousel would create two rows of items instead of 1. I was using the autoWidth option, setting my images with a height:200px and a width:auto.

But you see, when putting width:auto in this way the width will almost always end up with decimals, and that's where the problem begins. If the decimal was less that .5, Owl Carousel (jQuery width() method to be more precise) will round down the width, and then, use that rounded down width to calculate the width of the stage area. But items now don't fit in this rounded down area, so the last item will be placed in a new row.

**Clear example:** https://jsfiddle.net/2nahh3x6/2/ (The bug exists in google chrome, haven't checked other browsers)

(the second row in that example is blank because the last item is one of those cloned items and it's out of sight, but you can drag the carousel from that blank row and stuff)

The **easy solution** is to add 1 pixel to the calculated width of each element. For this we would search the following code:

`widths[iterator] = !grid ? this._items[iterator].width() : width * merge;`

And replace it with

`widths[iterator] = !grid ? this._items[iterator].width() + 1 : width * merge + 1;`

I tested it and it fixes the double row issue but now our coordinates are wrong by 1 pixel, so some of our margins will have an error of 1 pixel, which, if you are putting a margin of 0, shows an unwanted white line 1 pixel thick. The horror.

I also tried to force the divs to be the new calculated size (so we strip them of their decimals), but then the image inside the div, which still has the decimals, sometimes overflows from the div fucking up our margin by 1 pixel. You could put an overflow:hidden rule in css but that's not ideal either cause some people might want something to overflow from their divs.

All in all I prefer a 1 pixel error in my margin than a broken second row. I'm sure some of the main contributors can find a better solution.

Hope this helps. If I'm saying nonsense be kind with me lol, I'm fairly new to JavaScript but I think I got it right.

**Comment by CracyCrazz** [comment]
We'll probably address this with #1538

**Comment by anamdev16** [comment]
![bug](https://user-images.githubusercontent.com/16870110/51366233-7753eb00-1ab2-11e9-8f1b-0b82db8b6d34.png)

Please help!

**Comment by dimadroog** [comment]
Hi!
This solved for me.
I decided to give each carousel time to load.
`  
  var settings = {
    margin:10,
    nav:true,
    autoWidth:true,
    lazyLoad: true,
  }

setTimeout(function(){ 
    jQuery('.owl-carousel-one').owlCarousel(settings);
  }, 1000)

  setTimeout(function(){ 
    jQuery('.owl-carousel-two').owlCarousel(settings);
  }, 2000)

  setTimeout(function(){ 
    jQuery('.owl-carousel-three').owlCarousel(settings);
  }, 3000)

  setTimeout(function(){ 
    jQuery('.owl-carousel-four').owlCarousel(settings);
  }, 4000)`

But I had to show / hide the preloading block.
Hope it help someone.

**Comment by mariovalney** [comment]
Still happens.

Had to apply this patch.
