### ISSUE TITLE
Responsive mode in Chrome Android / Webapp manifest (BUG)!?

### ISSUE THREAD

**Issue by Zaanmedia** [OwlCarousel2/OwlCarousel2#1533]
Hallo all,

I'm not sure if this occurs only with my code / phone but it seems that the responsive mode doesn't seem to work on mobile devices if they save the page/website on their phone. So the people are saving the website/page to their phone and the page will be loaded as webapp icm the manifest file.

If you browse with the chrome browser to the website it is working! Not sure how it's possible it is not working when it's get loaded as webapp...  

Hope someone can confirm this issues and will there be a possible fix for this?

Kind regards,
Patrick

**Comment by ianhobbs** [comment]
Can you give some techincal details....

**Comment by Zaanmedia** [comment]
Hallo ianhobbs,

I have it working right now! Don't know what the problem was i have changed the displaymode a few times and then set it back to fullscreen / portrait. maybe caching problem or i had 2 installs on my phone don't know.

Thanks.
