### ISSUE TITLE
Owl carousel autoplay direction (going to the wrong direction)

### ISSUE THREAD

**Issue by alysonsm** [OwlCarousel2/OwlCarousel2#1534]
I am using owl carousel and I believe there are some bugs in "autoplay" parameter. According to the sample below, you will see that the animation is going to the opposite side. But when we resize the window it goes to the right direction. And the dots are working oddly because of that as well. 

Anyone can help me to fix that?

Here is the sample working:
https://jsfiddle.net/alysonsm/17xf4Lvw/1/

**Comment by alysonsm** [comment]
The way that I fix was working with events like 
'translated.owl.carousel', 'next.owl.carousel' and 'prev.owl.carousel'. So I implemented the workaround bellow:

https://jsfiddle.net/alysonsm/17xf4Lvw/3/

**Comment by CracyCrazz** [comment]
Your fiddle isn't working at all for me. Seems like you forgot to add jQuery?

**Comment by alysonsm** [comment]
It doesn't work in chrome but it does in Firefox. Sorry about that.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a **working** live example. Please provide an example that works in Chrome as well as in Firefox.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
