### ISSUE TITLE
Autoplay Not Working

### ISSUE THREAD

**Issue by TheInkblot** [OwlCarousel2/OwlCarousel2#1535]
Hi!

For some reason autoplay is not working for me. The slider is loading up and all the other options are working just fine, but the autoplay doesn't seem to trigger:

$footer_testimonials_slider = $('#footer-testimonials');

	$footer_testimonials_slider.owlCarousel({
	    loop:true,
	    margin:10,
	    nav:true,
	    items:1,
	    autoplay:true
	});

**Comment by alysonsm** [comment]
Take a look at this working sample:
https://jsfiddle.net/alysonsm/t1Lmoveq/1/

Probably is not working because of ` symbol after owlCarousel function.

**Comment by TheInkblot** [comment]
Hi Alysonsm,

Thanks for the reply and for taking a looking at this!

Two things:
1. Can't get your Fiddle example to work
2. There is no ' symbol after the owlCarousel function in my actual code. I think that got added accidentally when I posted in Github.

**Comment by alysonsm** [comment]
I think that might be a jsfiddle issue. Can you try it in firefox?

Thank you,

**Comment by TheInkblot** [comment]
Hi Alysonsm,

Thanks for the reply! The jsFiddle is working in Firefox.

I have tried your code on my site and it does not resolve the issue. Same problem unfortunately.

Thanks,
- Marcus

**Comment by alysonsm** [comment]
Hi Marcus,

I am experiencing weird issues with autoplay properly as well.  The way that I fix was working with events like 
'translated.owl.carousel', 'next.owl.carousel' and 'prev.owl.carousel'. So I implemented a workaround like bellow:
Take a look at his example:
https://jsfiddle.net/alysonsm/17xf4Lvw/3/

**Comment by TheInkblot** [comment]
Hi Alysonsm,

Thanks! This looks great. Thanks for looking into this for me and putting together this fix. It's actually not working on my end, so I have to assume I have something setup wrong or conflicting with Owl Carousel. I think I am going to just tinker around for awhile and see if I can figure out the issue.

Best,
- Marcus

**Comment by lautaromss** [comment]
The first jsfiddle that TheInkblot presented works well for me after loading the jQuery resource (because the fiddle is missing the jQuery library?)

**Comment by iftikharyk** [comment]
jsfiddle is empty
