### ISSUE TITLE
How to reload OwlCarousel

### ISSUE THREAD

**Issue by hungchunlin** [OwlCarousel2/OwlCarousel2#1536]
When I dynamic change element under .owl-carousel
How to refresh the OwlCarousel ??

**Comment by despecial** [comment]
`$('your-selector').trigger('refresh.owl.carousel');`

**Comment by sandip1699** [comment]
not working in bootsrap tab

**Comment by muayadjamal** [comment]
if `.trigger('refresh.owl.carousel');` didn't work with you, you can use 

> window.dispatchEvent(new Event('resize'));

 which will make the carousel refresh automatically.
