### ISSUE TITLE
Bug progress bar after a reboot of the slider

### ISSUE THREAD

**Issue by webgefest** [OwlCarousel2/OwlCarousel2#1541]
I do autoplay slider on by click button ( Slideshow ) with the progress bar, which must be disappear off after display of all sliders . 
Here is a link that did
[http://jsfiddle.net/webgefest/g3f4qqku/9/](http://jsfiddle.net/webgefest/g3f4qqku/9/)

I have two problems
1) After restarting the slider by pressing the button , slides start to switch faster than the press slider bar. 
How can I reset the progress bar ?
2) It does not go to synchronize the time between slides and closing the slider . Can you close the slider after the last slider ?

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a **working** live example. The link you provided does not seem to work at all. The Carousel is not displayed correctly anyhow.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
