### ISSUE TITLE
To many items?

### ISSUE THREAD

**Issue by xApep** [OwlCarousel2/OwlCarousel2#1543]
Hi,
I don't know if there is to many items or there is something else.

I have this property set:

> ```
>         loop:               false,
>         margin:             10,
>         responsive:{
>             0:{
>                 items:      8
>             }
>         }
> ```

What happens that on when you resize browser on some resolution the last items gets into a new row, than you have 7 items in 1 row and 1 item in new row.

If I set items to 7 than everything works fine.
Also when I have items 8 and if I set margin to 11 the issue is the same, even on the full width (not resized).

Thanks.

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by EDsolution** [comment]
Hello. Can I send you the link of dev project on your e-mail? It's not for public jet :)

Thanks.

**Comment by odahcam** [comment]
You should recreate your scenario (removing private data) in one of the services listed by @CracyCrazz . Once you do it, more people can help ya.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
