### ISSUE TITLE
Items squished on refresh

### ISSUE THREAD

**Issue by apur** [OwlCarousel2/OwlCarousel2#1544]
I am having issue when on viewport size 1024x768
If I inspect the item element, I see style="width: 5px".

The items are squished on refresh, could you please suggest something to fix?
![squished](https://cloud.githubusercontent.com/assets/8587307/17956329/a35a36dc-6aa6-11e6-8655-55485f44a79d.png)

Following is the html

<div class="owl-carousel completed-project">

                <div class="item">
                    <article class="project">
                        <div class="pro-img-wrap">
                        <div class="overlay"></div>

```
                        <img src="images/img1.png" alt="" class="scale" data-scale="best-fill" data-align="center">
                    </div>

                    <div class="pro-content">
                        <div class="pro-body">
                            <ul class="pillars text-center">
                                <li>
                                    <img src="someimg" alt="">
                                </li>
                            </ul>
                            <div class="heading-wrap">
                                <h2 class="heading">projects</h2>
                                <div class="flag">
                                <span class="sub-heading">
                                <img src="someimg" alt="">
                                </span>
                                </div>
                            </div>
                            <div class="beneficiaries">
                                <span class="num">projects</span>
                                <span>Beneficiaries</span>
                                <i class="fa fa-users"></i>
                            </div>
                            <div class="pro-footer">
                            <h4 class="updated">Updated 1 min ago</h4>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        </div>
```

Following are the options

  'someProject': {
            center: true,
            loop: true,
            margin: 20,
            lazyLoad: true,
            // addClassActive: true,
            responsiveClass: true,
            dots: false,
            responsive: {
                320: {
                    items: 1,
                    stagePadding: 10
                },
                480: {
                    items: 1,
                    stagePadding: 50
                },
                767: {
                    items: 2
                },
                1000: {
                    items: 3
                },
                1280: {
                    items: 3
                },
                1366: {
                    items: 4
                }
            }
        }

Following are the styles

.some-project .item{
  background: #4DC7A0;
  position: relative;
  max-width: 100%;
}

.some-project .item .project{
  padding: 0px;
  position: relative;
}
.some-project .item .project .pro-img-wrap .overlay{
  background: rgb(27,69,131);
  position: absolute;
  width: 100%;
  height: 100%;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  opacity: 0.75;
  z-index: 9;
}
.some-project .item .project .pro-img-wrap{
     /_width: 337px;_/
    height: 275px;
    /_width: 100%;_/
    max-width: 100%;
    overflow: hidden;
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
}
.some-project .item .project .pro-img-wrap img{
  /_width: 100%;
  height: auto;_/
  max-width: 100%;
}

.some-project .item .project .pro-content{
  display: -webkit-flex;
  display: flex;
  align-items: center;
  justify-content: flex-end;
  flex-direction: column;
  position: absolute;
  top: 0px;
  left: 0px;
  width: 100%;
  height: 100%;
  padding: 20px 0;
  z-index: 9;
  /_color:#FFFFFF;_/
}
.some-project .item .project .pro-content .pro-head .duration{
  color:#bababa;
}
.some-project .item .project .pro-content .pro-head .duration span{
  color:#FFFFFF;
}
.some-project .item .project .pro-content .pro-body{}
.some-project .item .project .pro-content .pro-body ul.pillars{
  padding: 0px;
}
.some-project .item .project .pro-content .pro-body ul.pillars li{
  display: inline-block;
  list-style: none;
  padding: 10px;
}
.some-project .item .project .pro-content .pro-body ul.pillars li img{
  width: 34px;
}

.some-project .item .project .pro-content .pro-body .beneficiaries{
  text-align: center;
  display: -webkit-flex;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #bababa;
  font-size: 14px;
}
.some-project .item .project .pro-content .pro-body .beneficiaries i{
  font-size: 18px;
  margin: 10px 5px;
}
.some-project .item .project .pro-content .pro-body .beneficiaries span{
  text-transform:uppercase;
}
.some-project .item .project .pro-content .pro-body .beneficiaries .num{
  font-size: 18px;
  color: #FFFFFF;
  margin: 10px 5px;
}
.some-project .item .project .pro-content .pro-body .pro-footer {
    display: -webkit-flex;
    display: flex;
    align-items: center;
    justify-content: center;
    color: #bababa;
    font-size: 14px;
}

.some-project .item .project .pro-content .pro-body .heading-wrap{
  position: relative;
  border-top: 1px solid #9c9c9c;
  border-bottom: 1px solid #9c9c9c;
  padding: 10px;
  margin: 0 10px;
  text-align: center;
  color: #FFFFFF;
  letter-spacing: 1px;
}
.some-project .item .project .pro-content .pro-body .heading-wrap .flag{
    display: flex;
    align-items: center;
    justify-content: center;
}
.some-project .item .project .pro-content .pro-body .heading-wrap .flag img{
      width: auto;
      margin: 0 5px;
}

.some-project .item .project .pro-content .pro-body .heading-wrap .heading{
  /_font-family:'BebasNeue', Arial, Helvetica, sans-serif ;_/
  font-size: 24px;
  line-height: 24px;
  font-weight: 400;
}
.some-project .item .project .pro-content .pro-body .heading-wrap .sub-heading{
  /_font-family:'Lato', Arial, Helvetica, sans-serif !important;_/
  font-size: 16px;
  line-height: 24px;
  text-transform:uppercase;
}
.some-project .item .project .pro-content .pro-footer .updated{
  color:#bababa;
}
.some-project .item .project .pro-content .pro-footer .updated span{
  color:#FFFFFF;
}

**Comment by irajMrPerfect** [comment]
did you get the solution of it?

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
