### ISSUE TITLE
Youtube Embed on HTTPS site not working

### ISSUE THREAD

**Issue by bharling** [OwlCarousel2/OwlCarousel2#1545]
I'm getting a 'generic playback error' when trying to use an embedded video in a gallery served on an https site.

the markup I output for the item concerned is simply:

```
        <div class="video-item">
            <a class="owl-video" href="https://www.youtube.com/watch?v={{instance.youtube_id}}"></a>
        </div>
```

Owl renders this as:

`<iframe class="owl-item active center" data-video="https://www.youtube.com/watch?v=iw0O9Gg_NBc" style="width: 483px;" frameborder="0" allowfullscreen="1" title="YouTube video player" width="640" height="390" src="https://www.youtube.com/embed/https://www.youtube.com/watch?v=iw0O9Gg_NBc?enablejsapi=1&amp;origin=https%3A%2F%2Fwww.exeterlivingawards.co.uk&amp;widgetid=1" id="widget2"></iframe>`

This looks to be correct as far as I can tell from the youtube docs and I can see the player but it refuses to play the video. Should the content of the src attribute be escaped like it appears above ?

Has anyone else hit this ?

**Comment by eparisio** [comment]
i think you must change `https://www.youtube.com/watch?v={{instance.youtube_id}}` with `https://www.youtube.com/embed/{{instance.youtube_id}}`, because youtube iframe works only with embed version of the url

**Comment by bharling** [comment]
ah, thanks I'll give this a try. I think the docs say that the watch url should work though...

**Comment by eparisio** [comment]
i've see the code and yes, teorically it should works with watch url also.
probably there is a bug with them, i've used always the embeded and it works fine.

**Comment by bharling** [comment]
Using embed also seems to fail for me - I now get 

`src="https://www.youtube.com/embed/https://www.youtube.com/embed/iw0O9Gg_NBc?enablejsapi=1&amp;origin=https%3A%2F%2Fwww.exeterlivingawards.co.uk&amp;widgetid=1"`

when the widget is rendered. I've switched to directly outputting the iframe instead of an <a> tag which seems to work for me, but does not integrate very well with owl.

**Comment by KitKat777** [comment]
Youtube discontinued object/embed with the last release 8/11. Only iframe now.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
