### ISSUE TITLE
On Chrome, calling "update" method, Flash Video into owl-item stop reproducing 

### ISSUE THREAD

**Issue by ale-grosselle** [OwlCarousel2/OwlCarousel2#1546]
If you add a flash object into an owl-item, for example an swf video player, this css rule
owl-refresh .owl-item {
		display:none;
}

breaks video reproducing; flash stop playing.

See the attach for more details about problem
[UpdateFlashProblem.zip](https://github.com/OwlCarousel2/OwlCarousel2/files/437113/UpdateFlashProblem.zip)

**Comment by ale-grosselle** [comment]
PR #1547

**Comment by daviddeutsch** [comment]
Closed by accepting PR. Thanks!
