### ISSUE TITLE
Owl-carousel stop working when applying dragend()

### ISSUE THREAD

**Issue by namgivu** [OwlCarousel2/OwlCarousel2#1549]
When using [dragend()](https://github.com/Stereobit/dragend) to get multiple owl-carousel blocks aligned horizontally and swipe-able, owl-carousel functionality not working for me and dragend()

Have you guys get this issue before and how we would work around for it?

p.s.

I also [asked](https://github.com/Stereobit/dragend/issues/88) dragend() author on this.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
