### ISSUE TITLE
Last Dot Does Not Get Active Class

### ISSUE THREAD

**Issue by DJMIMi** [OwlCarousel2/OwlCarousel2#1550]
Hi guys

When dots are used and let's say we have 10 items out of which 8 are visible 2 dots will be displayed as it should, but once you click on dot 2 slider is scrolled to display items 9 and 10 but the second dot does not have active class applied to it.

Regards.

**Comment by TalD** [comment]
+1

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
