### ISSUE TITLE
Custom duration per slide

### ISSUE THREAD

**Issue by brian1037** [OwlCarousel2/OwlCarousel2#1552]
There doesn't seem to be a supported option in the docs so I'm hoping there's a workaround or something. Is it possible to set a custom slide duration per slide (the amount of time a slide is shown before it slides, not the animation duration)? 

Something with data-\* attributes would be great. If not, even an .updateSlideDuration() method I could call programatically after a slide change would be enough. If none of that is possible then this is a suggestion :p

Thanks

**Comment by winnienyc123** [comment]
try autoplayTimeout in options
