### ISSUE TITLE
owl.carousel npm + Meteor.js Error: TypeError: item.find('[data-merge]').andSelf is not a function.

### ISSUE THREAD

**Issue by grundmanise** [OwlCarousel2/OwlCarousel2#1553]
I receive this message when trying to run owl carousel  v.2.1.4 ([installed from npm](https://www.npmjs.com/package/owl.carousel)) in my `Meteor.js` v.1.4.0.1 project:

> Exception from Tracker afterFlush function:
> TypeError: item.find('[data-merge]').andSelf is not a function. (In 'item.find('[data-merge]').andSelf('[data-merge]')', 'item.find('[data-merge]').andSelf' is undefined)`

My code:

```
// .js
import owlCarousel from 'owl.carousel';

...

Template.name.onRendered(function() {

  const owl = $('#owl-tabs');

  owl.owlCarousel({
      items: 1,
      dots: false
  });

});

//.html
<template name="name">
<ul class="owl-carousel" id="owl-tabs">
    <li class="owl-tab owl-tab__rewards" id="owl-tabs__rewards">Rewards</li>
    <li class="owl-tab owl-tab__activity" id="owl-tabs__activity">Activity</li>
    <li class="owl-tab owl-tab__rating" id="owl-tabs__rating">Rating</li>
</ul>
</template>
```

**Comment by matteo-bombelli** [comment]
If it is possible llok at this issue:
https://github.com/OwlCarousel2/OwlCarousel2/issues/1452

Substitute addSelf with addBack

**Comment by pascalporedda** [comment]
Should be already fixed.
