### ISSUE TITLE
Carousel initializes, but doesn't do anything in Sage

### ISSUE THREAD

**Issue by scferg** [OwlCarousel2/OwlCarousel2#1554]
I'm using Sage and trying to get Owl Carousel working, but have been unsuccessful. I'm fairly new to Sage, so perhaps I'm missing something. I installed Owl Carousel via `bower install --save owl.carousel` and that also installed jQuery as a dependency.

The first issue was that the css and js weren't being included, so I added an override into `bower.json`
```json
"owl.carousel": {
    "main": [
        "dist/owl.carousel.js",
        "src/scss/owl.carousel.scss"
    ]
}
```
(It feels wrong to include a file from the `src` directory, but I can't import the css file from the `dist` directory)

Finally, both the css and js are being included into the correct files. Owl Carousel correctly sets up the DOM, but nothing happens after that. Below is what Owl Carousel sets up:
![xtant_medical_ _just_another_wordpress_site](https://cloud.githubusercontent.com/assets/1112334/18136377/2654d990-6f73-11e6-9105-b69195075349.png)

Here's my Owl Carousel code:
```javascript
$('.hero-bg').owlCarousel({
    items: 1,
    loop: true,
    mouseDrag: false,
    touchDrag: false,
    pullDrag: false,
    dots: false,
    autoplay: true,
    autoplayTimeout: 6000,
    animateOut: 'fadeOut'
});
```
I'm very confused as to how the carousel is initialized, but doesn't do anything, while the exact same code (OC & jQuery versions, and OC init code) works correctly outside of Sage. Nothing is being reported in the console, either.

What am I missing?

**Comment by CracyCrazz** [comment]
Seems like you are missing the .owl-carousel class on your parent div. 

`<div class="hero-bg owl-loaded **owl-carousel**">`
