### ISSUE TITLE
CSS transform translate3d blur issue 

### ISSUE THREAD

**Issue by andym193** [OwlCarousel2/OwlCarousel2#1556]
There is a blur problem with the translate 3d, mainly noticeable in the Google Chrome browser. The issue is that some item elements blur if the transform:translate3d values has decimal number instead of a whole number.

For example:
transform: translate3d(-450px, 0px, 0px) - this is okay.
transform: translate3d(-450.5px, 0px, 0px) - this will cause some elements in the owl carousel items to blur because the value is not a whole number.

This jsfiddle explains it all if you open it in a Chrome browser:
https://jsfiddle.net/xk4g29du/2/

I haven't found any CSS fixes that I can add to stop this blur.

In the carousel js file, when calculations are being made ready for the transform:translate3d values, is it possible for you to fix this by ensuring that the values will always be whole numbers? So if the value is in a decimal form, either round it up to the nearest whole number or completely remove the numbers after the decimal point.

**Comment by andym193** [comment]
I've just downloaded the v2.1.6 master version and it has fixed the problem. I was going to mention there was another problem when scaling up from a small screen to a large screen, but the the 2.1.6 has fixed this too. Great job on this! I've tried a variety of tests on this and it is all working good. When is this going to be released as stable?

**Comment by daviddeutsch** [comment]
:+1:

**Comment by pcarballeda** [comment]
I think that this bug is caused by decimals, maybe you can try with integers in your translate3d or applying toFixed() if you manage your transition paramenters with JS.

**Comment by andym193** [comment]
@pcarballeda The fix to this is here (read the comments):
https://stackoverflow.com/questions/45588937/icon-font-blur-in-chrome-when-using-transform-translate3d?rq=1

In the owl.carousel.js file, I have to change `transform: transform: 'translate3d(' + coordinate + 'px,0px,0px)'`, to `transform: 'translate(' + coordinate + 'px,0px)'`. It would be great if the author made this change, but not sure if the translate3d is there for a reason.

**Comment by manishasawlani129** [comment]
In the owl.carousel.js file
**REPLACE** 
transform: 'translate3d(' + coordinate + 'px,0px,0px)'
**WITH**  
transform: 'translate3d(' + (coordinate-1) + 'px,0px,0px)'

And, in case of the owl.carousel.min.js file
**REPLACE** 
transform: 'translate3d("+b+"px,0px,0px)'
**WITH**  
transform: 'translate3d("+(b-1)+"px,0px,0px)'

Hope this helps!
