### ISSUE TITLE
NPM 2.1.4 > 2.1.6 please =)

### ISSUE THREAD

**Issue by bakeruk** [OwlCarousel2/OwlCarousel2#1557]
Hi,

Is it possible that you can update the NPM package to 2.1.6 please?

I've noticed a ticket has already been submitted requesting this but it got closed.

Can we leave this ticket open (as a reminder) until it gets done please?

Many thanks,

Luke

P.s. Awesome work keep it up =D

**Comment by adriaanzon** [comment]
Until it's updated on NPM you can run `npm install OwlCarousel2/OwlCarousel2` and it will install directly from github.

**Comment by daviddeutsch** [comment]
Did you one better - just released 2.2.0! :wink:
