### ISSUE TITLE
Single Item issue, with latest dev version

### ISSUE THREAD

**Issue by cinghaman** [OwlCarousel2/OwlCarousel2#1560]
Hi, I tried version from 2.0.0 to 2.1.6 and none solves the issue of single item + autoplay 
I tried doing this, if i use 2.0.0 version with initialize.owl it atleast runs the code and does't break page, but shows console error at testi.settings.loop  TypeError: Cannot set property 'loop' of undefined
 may be i am initialising it wrong? but when i use 2.1.6 it totally breaks shows a huge width on the div and duplicates same item 4-5 times (screenshot: showing what it is doing - note there is only 1 slider item: http://prntscr.com/ceipnj)
codepen: http://codepen.io/cinghaman/pen/WGbdjo/

var testi = $('.testimonial-container');
        /_testi.on('initialize.owl.carousel initialized.owl.carousel ', function(event) {
            if ($('.testimonial-container > div').length <= 1) {
                        testi.settings.loop = false;
                        testi.settings.nav = false;
                }
        });_/
        testi.owlCarousel({
            loop: true,
            autoplay: true,
            autoplayHoverPause: false,
            margin: 0,
            items: 1,
            center:true,
            stopOnHover: false,
            dots: false,
            nav: true,
            //singleItem:true,
             navText: [
              "<span class='fa fa-chevron-left'></span>",
              "<span class='fa fa-chevron-right'></span>"
          ],
           pagination: false, 
           responsiveClass: true,
           responsive:{
                0:{
                    items:1
                },
                600:{
                    items:1

```
            },
            1000:{
                items:1
            }
        }
    });
```

**Comment by ccharlton** [comment]
I wonder if it's similar issue to https://github.com/OwlCarousel2/OwlCarousel2/issues/1572

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!
