### ISSUE TITLE
critical bug in every version of owl.carousel.min.js

### ISSUE THREAD

**Issue by dmagician** [OwlCarousel2/OwlCarousel2#1564]
I hope this is not a false alarm but I have tested heavily before I found out that non minified version works correctly. 

**Every distribution of Owl Carousel 2 has bug in minified version causing "destroy.owl.carousel" not to work properly which causes TypeError: this.e is null error.** 

This glitch caused 4 hours of my life go away in desperate search for solution through github isssue reports ans stackoverflow debates, and I had even to restore my forgotten password to github to report this, so I hope this will be now solved for everyone in future ;-)

And if I'm wrong, and there is some otherworldly explanation of that, feel free to enlighten me. 

Anyway now when I work with **owl.carousel.js** , my faith for Owl Carousel 2 has been restored. ;-) Have a nice whatever part of the day you have.

**Comment by ccharlton** [comment]
Ouch.

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
