### ISSUE TITLE
When using data-hash the slide where is being navigated to will be blank.

### ISSUE THREAD

**Issue by mvaneijgen** [OwlCarousel2/OwlCarousel2#1565]
When using the slider with the normal navigate buttons everything is fine, but when using the 'data-hash' function navigating to the slide using for example `<a href="#slide8">my slide</a>` the slide will be completely blank (resizing the browser will make it appear again). 

What version is the best to use when wanting to use the `data-hash` feature or what is the best way to get it to work like expected?

I have tried the following owl version
- [from the website](http://www.owlcarousel.owlgraphic.com/download/owl.carousel.zip)
- If you want to use the [latest development](https://github.com/owlcarousel2/OwlCarousel2/archive/develop.zip)
- and the latest release version [2.1.6](https://github.com/OwlCarousel2/OwlCarousel2/archive/2.1.6.zip) (which breaks the slider completely)

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
