### ISSUE TITLE
Can't add 5 items at one time correctly

### ISSUE THREAD

**Issue by Skorogovorochka** [OwlCarousel2/OwlCarousel2#1568]
I add items to my carousel by ajax in this code:

`jQuery(document).ready(function() {

```
        jQuery(this).owlCarousel(
            {
                dots:false,
                nav:true,
                margin:10,
                lazyLoad : true,
                navText:['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>'],
                responsive : {
                  // breakpoint from 0 up
                  0 : {
                      items : 1,
                  },
                  // breakpoint from 480 up
                  480 : {
                      items : ipad_item,
                  },
                  // breakpoint from 768 up
                  768 : {
                      items : ipad_item,
                  },
                  1000 : {
                      items : desktop_item,
                  },
                  1025 : {
                      items : desktop_item,
                  }
              }
            }
        );
     });
    jQuery("#frames-carousel .owl-next, #frames-carousel .owl-dot").click(function() {
    var data2 = {
        'action': 'zhan_load_frames',
        'page' : current_page,
    };      
    jQuery.ajax({
        url:ajaxurl,
        data:data2,
        type:'POST',
        success:function(content){
            var owl = jQuery("#frames-carousel .owl-carousel");
            owl.owlCarousel().trigger('add.owl.carousel', [jQuery(content)]).trigger('refresh.owl.carousel');
        }
    });
```

  });  
});`
So I retrive 1 product from BD by zhan_load_frames function and add it as 1 item to the carousel by one right arrow click. It is added and slided correctly.
But I need to add and slide 5 items by 1 click.
So I add the code:

`slideBy:5;`

and change the WP_Query arguments in zhan_load_frames function to get 5 products from DB.

The products are retrieved. But they are added to carousel incorrectly. I can see in debugger that the owl-stage width grows only by one item width. Not by 5 items width. So only one item is added to the same carousel string. The other 4 are added to the next one ([see the screenshot](http://joxi.ru/Vm6zeO1i8bpPmZ) )
Be so kind to help me what do I do wrong?
Thank you.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
