### ISSUE TITLE
Animation for multiple item slide

### ISSUE THREAD

**Issue by caseydev** [OwlCarousel2/OwlCarousel2#1569]
Is there any feature about animation on multiple slide item? I have tried its fine on single slide but not working on multiple item slide.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

**Comment by ysushah** [comment]
It is not bug but  Animation feature is not working on multiple slide owl carouse
