### ISSUE TITLE
Owl Carousel Width Is Calculated Wrong In 1920×1080 Resolution

### ISSUE THREAD

**Issue by beymat** [OwlCarousel2/OwlCarousel2#1570]
Hi. I use this plugin : https://wordpress.org/plugins/product-carousel-slider-for-woocommerce/ for my woocommer in wordpress. That plugin is based on owl carousel.

Please take a look here : http://www.musclegears.net/2016991/
 
This plugin had a conflict with my theme. In 1366×768 resolution, the slider fit perfectly. But in larger resolution, it’s broken.

So, what code to fix this ?
 
You can test in 1920×1080 resolution or zoom in your browser to see the error.

**Comment by daviddeutsch** [comment]
Probably an issue with the image size, but the example is gone now.
