### ISSUE TITLE
Owl carousel crashes with 1 image

### ISSUE THREAD

**Issue by TheMysticMan** [OwlCarousel2/OwlCarousel2#1572]
Great work, Thanks.

I found 1 issue. 
When you only have one image it crashes and doesn't show anything.

**Comment by JoeyiBrows** [comment]
I have that issue when I have the loop option enabled with only one item.

**Comment by TheMysticMan** [comment]
@JoeyiBrows I also have the loop enabled. 
My config is:
`var owl = this.$('.owl-carousel');
owl.owlCarousel({
    items:1,
    dots: true,
    loop:true,
    autoplay:true,
    autoplayTimeout:4000,
    autoplayHoverPause:true,
    responsiveClass: true,
    smartSpeed: 1000
});`

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
