### ISSUE TITLE
when items is 1 and loop is true ,will occur an  error

### ISSUE THREAD

**Issue by snayan** [OwlCarousel2/OwlCarousel2#1573]
when items is 1 and loop is true ,will occur an  error
![error1](https://cloud.githubusercontent.com/assets/18651872/18940697/1ff03a14-863d-11e6-8c03-81955aa8ebad.png)

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
