### ISSUE TITLE
window still listen to url hash changes ignore URLhashListener

### ISSUE THREAD

**Issue by snayan** [OwlCarousel2/OwlCarousel2#1574]
when set URLhashListener=false,window still listen to url hash changes ,have not a judgement.
![error2](https://cloud.githubusercontent.com/assets/18651872/18941489/2cc0d7ce-8644-11e6-9474-20381b12a30e.png)

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
