### ISSUE TITLE
Once upon a time

### ISSUE THREAD

**Issue by stratboy** [OwlCarousel2/OwlCarousel2#1578]
I read somewhere: "Owl Carousel has been choosen as number one jQuery plugin by hundreds of developers. Now its time for a new version that comes with lots of new features and even more user friendly API. Watch this space- we'll be launching soon :)"

So when a final version?

**Comment by faridv** [comment]
5 months passed and counting since new owner said he is sorting stuff!
I've used Owl in many projects and am very disappointed that a great plugin is left alone without updates and bug-fixes.

**Comment by ccharlton** [comment]
+1

**Comment by daviddeutsch** [comment]
Patience, folks, we're getting there. In the meantime, there is always #1538 where I'm still super ready for people to chime in.
