### ISSUE TITLE
owl carousal to setup items:1.5 in the viewport and disable next button and prev button 

### ISSUE THREAD

**Issue by anuragjainsagar** [OwlCarousel2/OwlCarousel2#1579]
owl carousal to setup items:1.5 in the viewport and disable next button in last slide and prev button when first slide occurs. so in this prev and next button is not working properly.

if owl carousal items will setup to float number then at last slide it will not appear and if we slide by mouse then its prev button will not work.
please see the above code and solve the issue

Can anyone help me for solve the issue of prev. and next button of slider in 1.5 slides.

```
owl.owlCarousel({
        itemsCustom : [
          [0, 1.5],
          [1200, 2]
        ],
        navigation : true,
        nav: true,
        pagination : false,
        rewindNav : false

      });
```

Thanks in advance

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
