### ISSUE TITLE
Numbered pagination

### ISSUE THREAD

**Issue by oozrafa** [OwlCarousel2/OwlCarousel2#158]
For larger carousels I'd like to be able to use numbered pagination instead of dots so it would display something like 3/20

**Comment by jovan-ivezic** [comment]
Here you can see pure css solution for numbered pagination http://codepen.io/jovanivezic/pen/JXWOex

**Comment by janzenz** [comment]
Thanks @wpexplorer but looks like the dots are created per item. I got 12 items and it shows a dot for each item

<img width="426" alt="screen shot 2016-07-08 at 1 51 49 am 1" src="https://cloud.githubusercontent.com/assets/1410147/16663416/95fa950e-44ae-11e6-810b-6e19d19ded51.png">

I also tried putting `dotsEach: false` but it doesn't do anything, the dots still show all the indices.

**Comment by x404** [comment]
css code:
```
.owl-dots {
    counter-reset: dots;
}
.owl-dot:before {
    counter-increment: dots;
    content: counter(dots);
}
```

**Comment by SamiShelah** [comment]
Here's a method without using dots, useful if you want to keep the navigation and dots separate. 

```
window.owl = jQuery('#slider .slides');
window.owl.owlCarousel({
	nav: true,
	navText: ['<i class="fa fa-arrow-left" aria-hidden="true"></i>','<i class="fa fa-arrow-right" aria-hidden="true"></i>'],
	onInitialized: function(){
		var t = this,
			currSlide = t._current + 1,
			length = t._items.length;
		jQuery('<div class="slide-num">' + currSlide + '/' + length + '</div>').insertAfter('#slider > .slides.owl-carousel .owl-nav > .owl-prev');
	},
	onTranslate: function(){
		var t = this,
			currSlide = t._current + 1,
			length = t._items.length;
		jQuery('#slider > .slides.owl-carousel .owl-nav > div.slide-num').html(currSlide + '/' + length);
	}
}

```

**Comment by abiani** [comment]
.owlCarousel({
    paginationNumbers: true
});

I have test and work well

**Comment by tuanbtre** [comment]
using jquery add number of page to span
$('.owl-dot').each(function(){
		$(this).children('span').text($(this).index()+1);
	});
