### ISSUE TITLE
Two websites: confused - which one is the right one?

### ISSUE THREAD

**Issue by luciash** [OwlCarousel2/OwlCarousel2#1580]
http://owlcarousel2.github.io/OwlCarousel2/ (shows 2.1.0 - is missing the pagination dots and some CSS for the prev/next buttons it seems) vs the http://www.owlcarousel.owlgraphic.com/index.html (shows 2.0.0-beta.2.4 - the pagination dots and prev/next buttons in demos seem all right)

Which one is the right one? Should one of the sites be redirected to the other?

**Comment by leecollings** [comment]
The Github links on both pages actually go to the same thing (this project)

**Comment by luciash** [comment]
@leecollings And? Sorry, confused... I am not talking about the Github links.

**Comment by KitKat777** [comment]
But the download link gives you some other version.

I think these are the links you should use.
OwlCarousel V1
http://owlgraphic.com/owlcarousel/

OwlCarousel V2
http://owlcarousel2.github.io/OwlCarousel2/

**Comment by muhamed87** [comment]
As @luciash said there are 2 links. I'm working with that one:
http://www.owlcarousel.owlgraphic.com/index.html
and I'm facing an issue on it, you can view it here:
https://github.com/OwlCarousel2/OwlCarousel2/issues/1600

I opened the second version and I found that it works perfectly for me, but when I replaced the files on my project I didn't get the plugin to work.

**Comment by ccharlton** [comment]
The issue is one website shows Owl version 2.0.0-beta.2.4 while the other shows (and downloads) version 2.1.0. That is a problem, not to mention confusing, but spoof sites or old sites can hurt. One person above downloaded the old version, not knowing.

**Comment by daviddeutsch** [comment]
Yeah, it's super confusing. I've tried to contact the owner (original author of owl carousel), but to no avail. As described in #1538, this may force us to name fork the project in the future :confused:
