### ISSUE TITLE
hello owl

### ISSUE THREAD

**Issue by aldegad** [OwlCarousel2/OwlCarousel2#1582]
hi, my name is soohong kim in korea.

owl.carousel is too good.

I want to make some open source libraray.

Can I fix and include your owl.carousel library in my library?

I will link and make sure your license in my code and api page.

**Comment by ccharlton** [comment]
Follow the terms of the license.

**Comment by daviddeutsch** [comment]
What @ccharlton said.

**Comment by aldegad** [comment]
thx~
