### ISSUE TITLE
Custom nav buttons not fading

### ISSUE THREAD

**Issue by lukeinstant** [OwlCarousel2/OwlCarousel2#1583]
Hey.
I am using fade effect for Owl Carousel 2, with the animateOut: 'fadeOut',
When I use built-in navigation buttons, they work normally (they fade)
When I use custom navigation buttons with this trigger

`jQuery('.custom-prev').click(function(e) {
    owl.trigger('prev.owl.carousel');
    e.preventDefault();
})`

They slide! I think its a bug

**Comment by chinhexp** [comment]
i had same issue,
anybody can help ?

**Comment by chinhexp** [comment]
i solved it myself by just remove mouseDrag  

mouseDrag = false

**Comment by lukeinstant** [comment]
Did you add this on slider options call ?

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
