### ISSUE TITLE
Safari not remove active state

### ISSUE THREAD

**Issue by giacomoalonzi** [OwlCarousel2/OwlCarousel2#1584]
Hello, on safari I have this issue:
https://infinit.io/_/SAkYTKX

the plugin not remove the active state and classes to non active elements. 
All works perfect on Chrome/Firefox.

Any hint?

this is my code:

`owl.owlCarousel({
            margin: 0,
            items: 1,
            autoplay: true,
            autoplayTimeout: 4000,
            touchDrag: false,
            mouseDrag: false,
            loop: true,
            autoWidth: false,
            dots: true,
            animateIn: 'fadeIn'
            animateOut: 'fadeOut'
});`

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
