### ISSUE TITLE
After Init other elements become invisible

### ISSUE THREAD

**Issue by gomezmark** [OwlCarousel2/OwlCarousel2#1587]
After initializing owl
the other items below become invisible

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!
