### ISSUE TITLE
Different js from main site..

### ISSUE THREAD

**Issue by swaranan** [OwlCarousel2/OwlCarousel2#1590]
The js on main site("http://www.owlcarousel.owlgraphic.com/" ) and the js on github is different.I am trying to implement this ("http://jsfiddle.net/BBoyJuss/thbLB/embedded/result/") on my website but its not working with github js("owl.carousel.min.js") but working with the main site js("owl.carousel.min.js") which i downloaded direct from http://www.owlcarousel.owlgraphic.com/..

**Comment by ccharlton** [comment]
Similar issue to #1580: https://github.com/OwlCarousel2/OwlCarousel2/issues/1580

**Comment by swaranan** [comment]
ok..
