### ISSUE TITLE
image not showing

### ISSUE THREAD

**Issue by transferplus** [OwlCarousel2/OwlCarousel2#1593]
if the amount of items is less than the limit set on js, only one img is beeing shown
example:

```
<div class="item">
<img class="owl-lazy" data-src="image/<?php echo $product['thumb']; ?>">
<img class="owl-lazy" data-src="image/<?php echo $product['thumb']; ?>">
<img class="owl-lazy" data-src="image/<?php echo $product['thumb']; ?>">
<img class="owl-lazy" data-src="image/<?php echo $product['thumb']; ?>">
</div>
<script>
$('#carousel').owlCarousel({items:7});
</script>
```

if limit is set to 4 ou less, i works perfect

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
