### ISSUE TITLE
How to set the "wait" time between transitions?

### ISSUE THREAD

**Issue by renekreijveld** [OwlCarousel2/OwlCarousel2#1598]
I have OwnCarousel2 successfully running at http://www.anacverzekeringen.nl/ (see bottom of page). What I am struggling with is the wait time between the transitions.
The slider is setup to display 3 news items, wait a while and then slide to the next 3 items.
How do I set the wait time between the next slide?

**Comment by JoeyiBrows** [comment]
Add the option `autoplayTimeout: 10000,` for a ~10 second wait time,  play with the number, in milliseconds until you get your desired effect.

**Comment by renekreijveld** [comment]
Excellent, works like a charm!
