### ISSUE TITLE
How can i add pagination & paginationNumbers for owl-carousel 2.1.0 ?

### ISSUE THREAD

**Issue by dvkCharan** [OwlCarousel2/OwlCarousel2#1599]
Hi,

I need to show paginationNumbers instead of prev,next.
I'm using owl-carousel 2.1.0 version.
Could you guys help me out ASAP.

Thanks,
Charan.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
