### ISSUE TITLE
Stopping carousel autoplay and resize the window

### ISSUE THREAD

**Issue by muhamed87** [OwlCarousel2/OwlCarousel2#1600]
Hi guys,

I'm facing an issue on that you can check on the demo link of the plugin here:
http://owlcarousel.owlgraphic.com/demos/autoplay.html

Just click on the stop button to fire the stop autoplay event, you will see the carousel stopped, now resize the window and you will see that the play autoplay event fired without clicking play button.

I want to get a solution to stop it even if I resized the window because I'm working on something that showing a div element when clicking a link on the carousel item.

Regards

**Comment by muhamed87** [comment]
I'm using the beta version 2.0.4 from:
http://www.owlcarousel.owlgraphic.com/index.html
and facing a problem that was solved on the 2.1.0 version, but when I replace the owl carousel files with the new version I'm getting that error:

Kindly check the following demo (version 2.0.0):
http://www.owlcarousel.owlgraphic.com/demos/autoplay.html
Click the stop button, you will see the carousel stopped; resize the window and you will see the carousel started to work alone without clicking the play button.

Now check that demo (version 2.1.0):
https://owlcarousel2.github.io/OwlCarousel2/demos/autoplay.html
Do the same steps and you will see that it has no issue and when you resize the window the carousel will not play automatically until you click the play button.

When I tried to update to the new version I got that error in the console:
TypeError: this.$element.attr(...) is undefined and the error is from the carousel.min.js

Any help?!

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Comment by muhamed87** [comment]
Check the owl demo here:
https://owlcarousel2.github.io/OwlCarousel2/demos/autoplay.html

Steps to check the issue:
- Click the "Stop" button.
- Resize the screen, and don't mouse over the carousel and you will see that the owl will start playing without clicking the "Play" button.

Waiting...

**Comment by muhamed87** [comment]
Another issue at the same demo, you will see the carousel is auto-played and just mouse over the carousel for one second, and then mouse out it, you will see the carousel not playing even if you clicked the "Play" button.

**Comment by br-designer** [comment]
I'm having the same issue. 
https://jsfiddle.net/khbaker7/4ttxbgpx/2/

When resize.owl.carousel is initialized by resizing the browser (i.e.: desktop view to mobile), the _default_ setting of autoplay reinitializes. I've added a console log to look for when this trigger is called.

The preferred response is once `owl.trigger('stop.owl.autoplay')` has been triggered the carousel won't restart autoplay until `owl.trigger('play.owl.autoplay')` has been triggered.

**Comment by daviddeutsch** [comment]
See #1942

**Comment by niyasmnassar** [comment]
hello anyone help me for solving on resize owl 2 behave various height on my various block slides
