### ISSUE TITLE
Lazy load not working on Safari v10.0 

### ISSUE THREAD

**Issue by rensramos** [OwlCarousel2/OwlCarousel2#1603]
Got this problem that the image doesn't load unless you remove the owl-lazy class.

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Comment by Semne** [comment]
example: https://loftbd.com/gallerys/
