### ISSUE TITLE
Is there ANYONE supporting this at all?

### ISSUE THREAD

**Issue by leecollings** [OwlCarousel2/OwlCarousel2#1604]
I'm beginning to feel pretty frustrated that there seems to be no active support for this product, despite many people seeming to be having recent issues.

I've created an issue, which has received no response, and also managed to email the author directly, which again has received no response.

There doesn't seem to be any activeness by the plugin author on these issues list, and seems that there is no support.

Please  someone tell me if this is the case, then I can stop wasting my time, and go in search of another product that is in active development.

#1591

**Comment by despecial** [comment]
Maybe you should add your reply here: [#1538](https://github.com/OwlCarousel2/OwlCarousel2/issues/1538)

**Comment by leecollings** [comment]
Still no answer... I need to hear from the developers!

**Comment by daviddeutsch** [comment]
Huh, please chill. This is FOSS and not commercial support. We're here to collaborate, not to do everybodies jobs.
