### ISSUE TITLE
Small problem with lightbox, please help

### ISSUE THREAD

**Issue by oceanwp** [OwlCarousel2/OwlCarousel2#1606]
Hello,

Before I explain my problem, I want to thank you for creating a plugin so awesome, is really great and usefull :)

Everything works perfectly except for a small problem, I created a free theme, I used owl carousel for  gallery post format, when I click on an image of the carousel, it opens in ligtbox with magnific popup, the problem is with cloned images, instead of opening in lightbox, it opens in a window, I think the problem is because the lightbox script runs before the images are cloned.

Here is my code for the carousel:
```
$carousel.imagesLoaded( function() {
	$carousel.owlCarousel( {
    	items: 1,
	    loop: true,
	    nav: true,
        navText: ['<span class="fa fa-angle-left"></span>','<span class="fa fa-angle-right"></span>'],
        smartSpeed: 300,
        autoPlay: autoplay,
        autoplayHoverPause: true,
	} );
} );
```

And my code to lightbox:
```
j('.gallery-lightbox').magnificPopup( {
    type:'image',
    gallery: {
        enabled: true,
        tPrev: 'Previous',
        tNext: 'Next',
    },
    closeBtnInside: true,
    preloader: false,
    midClick: true,
    removalDelay: 300,
    callbacks: {
        beforeOpen: function() {
            this.st.mainClass = 'my-mfp-slide-bottom effect-rotate';
        }
    }
} );
```

Can you help me solve this problem?

Thank you a lot :)

**Comment by daviddeutsch** [comment]
You probably want to attach the popup to the clones after they have been instantiated.

**Comment by oceanwp** [comment]
Hello, thank you for your answer.
Any idea how I can do this?
Thank you.

**Comment by jeffconklin** [comment]
I am also looking for a solution for this.
