### ISSUE TITLE
Lazyload for 2 rows with 3 columns, please help me!!

### ISSUE THREAD

**Issue by axeusonline** [OwlCarousel2/OwlCarousel2#1607]
Is there anyway to create such the requirement?

If I use version 1 , the images show only first rows.
But when I move to version 2 the images are shown just only 1 column.

My requirement would like to show 3 slides (items=3) which includes 2 images of each. and show images 7 , 8 when next to forward slide.
1 3 5 > 7 9 ...
2 4 6 > 8 10 ...

**Comment by daviddeutsch** [comment]
Sure, set your rows/columns up as separate slides.
