### ISSUE TITLE
Supporting other video urls?

### ISSUE THREAD

**Issue by purushothamgk** [OwlCarousel2/OwlCarousel2#1608]
Does it support other than youtube, vimeo or vzaar URLs? Correct me if i am wrong, i see it in the code only this has been handled to fetch id and thumbnails. Suppose i have video uploaded in S3 which i would like to autoplay in the carousel. Let me know your inputs if any.

**Comment by daviddeutsch** [comment]
Sure, you could write a plugin for that.
