### ISSUE TITLE
insertContent method: Uncaught TypeError: Cannot read property 'indexAbs' of undefined

### ISSUE THREAD

**Issue by ghost** [OwlCarousel2/OwlCarousel2#161]
Hi,

I've been trying for 2 hours to make the insertContent method work without any luck.
I keep getting this error message in Chrome console:
`Uncaught TypeError: Cannot read property 'indexAbs' of undefined`

This is thrown by owl.carousel.js on line 1453:

```
Owl.prototype.minimum = function() {
    return this.dom.$oItems.eq(0).data('owl-item').indexAbs;
};
```

The "minimum" method (wich is called on `change.owl.carousel` event) is supposed to "Get the absolute minimum position for an item".  But it seems to be triggered to soon, at a time when no item is present in the slider yet.

**Comment by richgcook** [comment]
@photoart-mtlwebdev @witrin I still get the Uncaught TypeError: Cannot read property 'indexAbs' of undefined error when removing the first slide on mobile? Any thoughts?

**Comment by AndrewEastwood** [comment]
I have the same problem? does somebody know how to get it fixed?
