### ISSUE TITLE
Mobile images distorted

### ISSUE THREAD

**Issue by livetameion** [OwlCarousel2/OwlCarousel2#1611]
I am trying to use a media query to change the size of the images on mobile devices.

When I load the site up on my mobile phone (iPhone 6S and Galaxy S5), the images are being stretched. I am using centered, auto width, single item, and loop.

Carousel 2 beta.

The problem does not occur when I'm using my laptop or desktop with the screen sized down.

any suggestions?

**Comment by daviddeutsch** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by KitKat777** [comment]
Try updating to V2.1.6 or latest release from github. There are some old links from V1 -> V2 beta most likely you don't want to use it.
https://github.com/OwlCarousel2/OwlCarousel2/releases

Owl V1,32 final
https://github.com/OwlFonk/OwlCarousel/releases
