### ISSUE TITLE
Custom animation doesn't work.

### ISSUE THREAD

**Issue by alexilin83** [OwlCarousel2/OwlCarousel2#1612]
Hi.
"animateIn" and "animateOut" doesn't work in last version (2.1.6). Animation demo https://owlcarousel2.github.io/OwlCarousel2/demos/animate.html also doesn't work. Tested in ff49 and chrome54 on win10.

**Comment by daviddeutsch** [comment]
Works just fine now with 2.2.0. Probably worked before, too, though - it only works for the dot transition, not the drag (which makes sense to always use the same animation).
