### ISSUE TITLE
Can we fix the center mode on a certain class?

### ISSUE THREAD

**Issue by leecollings** [OwlCarousel2/OwlCarousel2#1615]
I'm highlighting a carousel item that shows the current page I'm viewing, and would like this item to always be centred when loaded. Currently, it appears off the page - UPDATE: It can also be shown on the page, and is inconsistent as the slider is loaded randomly.

Is there a way to centre the item that contains a certain class? If it would help to see this visually, this is what I'd like to achieve: 
![patientstorystrip-center](https://cloud.githubusercontent.com/assets/6681733/19886905/76cee0ca-a01d-11e6-8db5-d3698aa553bb.jpg)

So the goal here is to find the item that has the class `thisPatient` added to it, and to set that item to be in the center.

```
<div class="patient-story-strip">
    <?php
    $pages = get_pages(array('child_of' => 117, 'sort_column' => 'post_date', 'sort_order' => 'desc' ));
    foreach ($pages as $story) { ?>
    <a href="<?php echo get_permalink($story->ID); ?>" class="patient <?php if( $story->ID === $post->ID ) { echo 'thisPatient'; } ?>">
        <?php echo wp_get_attachment_image(get_post_thumbnail_id( $story->ID ), 'thumbnail', true, array('class' => 'img-responsive')); ?>
    </a>
    <?php } ?>
</div>
```

```
$(".patient-story-strip").owlCarousel({
        nav:false,
        dots:false,
        loop:true,
        center:true,
        margin:10,
        responsive:{
            0:{items:5},
            768:{items:9},
            1200:{items:13}
        }
    });
```

**Comment by odahcam** [comment]
1. Can you load the carousel in a certain order on every page?
2. I know that there's some methods to get an item's owlCarousel index and slide to it, but I don't remember how to do it without a plugin scope. So if the first option is viable, you won't need to do this, else I think that this is the only way.

**Comment by leecollings** [comment]
I don't think the first option is viable, because
1. The carousel is looped, and has no start or finish essentially.
2. The number of items won't always be the same. New items are added on a regular weekly basis.

My only thinking is literally to try and 'find' the item that contains the class, and then set to be centered (in my head)

**Comment by odahcam** [comment]
1. owlCarousel has an internal index for each item, so even if one item is cloned, it's internal owl index will be always the same.
2. Can you keep the same items order?

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

**Comment by leecollings** [comment]
That's not really helpful though, as I believe the solution to getting this to work, will lie within the way that the carousel is outputting. For example, how would you suggest I have the current item centred when the page is loaded?
