### ISSUE TITLE
Request - option to duplicate nav and dots

### ISSUE THREAD

**Issue by morrow95** [OwlCarousel2/OwlCarousel2#1617]
I'm doing a little bit of customization with my use of owl on a responsive site (bootstrap).  One of the things I am looking to do is have 'arrows' on the side when on large screen and the regular prev/next buttons of the default theme on smaller screens.  I can do this in css of course with a little bit of work and some media queries, but I was thinking it would be a lot easier if I could do something like : 

```
owl.owlCarousel({
    items:1,
    nav:true,
    dots:false,
    responsive:{
        0:{
            nav:true
        },
        992:{
            nav:false,
                **navDupe:'owl-nav-arrows'**
        }
    }
})

```

In other words the regular nav theme buttons would show on the 0-991 and then 992 on it would duplicate that nav-buttons yet with my class name of 'owl-nav-arrows'.  Something like this would allow you to create different variations of navs and dots and the ability to turn them on/off with the responsive settings.  You could even have more than one navigation such as the regular buttons plus the side arrows at the same time.

Two reasons I bring this up : 

1 - Why not just make custom buttons and use the api? Yeah, I could do that, but in the case of the side arrows I mentioned it would require me to append html into the .owl-carousel class so my custom buttons are 'inside'.  This is a problem I faced today as I want the side arrows to be vertically aligned and span the entire height of the carousel... to do that properly while having a variable height the buttons need to be 'inside' and not outside of the carousel - that is why duplication would make it easier.

2 - It would be really nice to turn on/off custom navs/dots with the responsive options rather than using media queries in css.  For instance, I might want side arrows on all viewing sizes on one page and only on mobile sizes on another - that would require separate css/media queries for each.  If duplication like above was possible you could just use the responsive option when initializing to decide when it is shown for certain screen sizes like any of the other options in 'responsive'.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
