### ISSUE TITLE
autoHeight only working for one instance of carousel on page

### ISSUE THREAD

**Issue by leecollings** [OwlCarousel2/OwlCarousel2#1621]
I have three carousel elements on the page at one time, and need to use the autoHeight feature.

At this point, all three instances are using the same initiation JS script, and I've wrapped that within a window.load function, and set `autoHeight:true`.

However, only the first instance of the carousel works, the other two, only show a portion of it (certain divs inside the slide).

Also, if I remove the autoHeight feature, all the instances seem to work absolutely fine (apart from the space is left on the other slides which is taken up by the yellow box on the first slide)

```
    $(window).load(function() {
    $(".owl-carousel-main").owlCarousel({
        items:1,
        margin:10,
        mouseDrag:false,
        touchDrag:false,
        nav:true,
        navText:['<span class="fa fa-fw fa-chevron-left"></span>','<span class="fa fa-fw fa-chevron-right"></span>'],
        dots:false,
        autoplay:true,
        autoplayHoverPause:true,
        loop:true,
        autoHeight:true
    });
    });
```

![owl_carousel-autoheight_bug](https://cloud.githubusercontent.com/assets/6681733/19862192/3f9fcdee-9f87-11e6-8c38-389f482f9383.jpg)

Working example is found here: http://development.bellavou.co.uk/patient-stories/sally/

**Comment by pascalporedda** [comment]
We already noticed that issue. Will be fixed in one of the upcoming releases.
