### ISSUE TITLE
event data not correct?

### ISSUE THREAD

**Issue by morrow95** [OwlCarousel2/OwlCarousel2#1622]
I need to use the event data for use with some custom buttons so I know when the first and last slides are shown.  I figured this would be a piece of cake, but I am getting really strange values from the event data.

onChanged: changed

outputting these to the console : 

console.log(event.item.count +' count');
console.log(event.item.index +' index');
console.log(event.page.count +' page count');
console.log(event.page.index +' page index');
console.log(event.page.size +' page size');

I am not seeing any way to determine if I am showing the last slide with the values being returned.  For example, I have 6 slides and using the following responsive settings : 

```
responsive:{
    0:{
        items:1
    },
    768:{
        items:2
    },
    992:{
        items:3,
        nav:false
    }
},
```
above 992px I get the following results for the 'end'  of the carousel : 

6 count
3 index
0 page count
-1 page index
3 page size

It seems the only way the above values are of any use at all is if you only display ONE slide at a time.  Then you can use the following logic : 

```
if (event.item.index == 0) {
	//first slide is being shown
}
else if (event.item.index == event.item.count - 1) {
	//last slide is being shown
}

Am I missing something here or was the event data not coded to handle responsiveness and/or multiple items?

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Comment by jowan** [comment]
I'm seeing the same thing. Version 2.3.4, latest downloaded through npm.

Issue is : in the data object as accessed from the event callbacks, event.page is incorrect.

```
$owl.owlCarousel({
          smartSpeed: 450,
          items: 4,
          nav: false,
          dots: false,
          center: false,
          autoHeight:true,
          fallbackEasing: 'swing',
          responsive : items_default
        });

$owl.on('changed.owl.carousel', function(event) {
          var pages = event.page.count;     // Number of pages
          var page = event.page.index;     // Position of the current page
          console.log(pages);
          console.log(page);
});
```
yields the same result on every changed event, 0 and -1.

event.item is correct and shows the index and the total, but when using more than one item per page, you may want to identity which page you are on.
