### ISSUE TITLE
Next navigation issue with less than one page of items in the carousel.

### ISSUE THREAD

**Issue by budjoe** [OwlCarousel2/OwlCarousel2#1624]
Working on a solution with a thumbnail carousel and a large image carousel linked.
Using version 2.2.0
The thumbnail carousel should have navigation true to go to the next image, but have turned it off since next does not advance thru the images if they fit on the page, or if the last page has more than 1 image on it.
It will navigate through the images if there is more than one page, until the first one on the last page.
Behavior is the same even with autoWidth: false.

Would think that next should always advance through the images one by one, even if they are paged as a result of autoWidth: true. 
Next only works as expected for a single image in the carousel stage.

If there is more than 1 image in the carousel, nav is visible, but it is only useable if more than one page of images, and then only through the first image of the last page.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
