### ISSUE TITLE
Width calculation or item placement on start and resize are different

### ISSUE THREAD

**Issue by atilkan** [OwlCarousel2/OwlCarousel2#1626]
Page load and window resize calculations are different. After resizing window, it looks fine. 
Two screenshot are almost same width. 
**Focus to end, right part of the images.**

on **start**
![capture](https://cloud.githubusercontent.com/assets/1254613/20084635/6fdbf646-a56c-11e6-9192-3647d67404a4.PNG)

on **resize**
![capture2](https://cloud.githubusercontent.com/assets/1254613/20084638/73ec9376-a56c-11e6-91d2-8455f5b8197e.PNG)

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Comment by atilkan** [comment]
This is persistent. I am working hole new project and the same bug bugs me.
I made a codepen demo but it doesn't repeat the same thing there.
https://codepen.io/atilkan/pen/GmLOXW

I suspect the resized value and the initial value of stage with calculated differently. Because after resizing the window back and forth it works as expected.

**Comment by atilkan** [comment]
This is the value after resizing the window (this is what i expect, close at least)
**`style="transform: translate3d(0px, 0px, 0px); transition: 0s; width: 1300px;"`**

From here: I just click refresh and the value here:
**`style="transform: translate3d(0px, 0px, 0px); transition: 0s; width: 1220px;"`**


As i suspected. Initial value and the resized value calculated different. And one of them is not correct.
Can you direct me the core code please?
