### ISSUE TITLE
owl carousel without jquery?

### ISSUE THREAD

**Issue by guykatz** [OwlCarousel2/OwlCarousel2#1629]
is it possible to use this great component without jquery? for example, vanila js
thanks

**Comment by CracyCrazz** [comment]
No, it was built to use with jQuery.

**Comment by Spider149** [comment]
If you want to use a library similar to owl carousel written in vanillaJS, try this: https://spider149.github.io/own-carousel/

**Comment by takuhii** [comment]
I've found I can tweak some of the code to work as Vanilla JS rather than initialising stuff with jQuery

**Comment by txufiknr** [comment]
> I've found I can tweak some of the code to work as Vanilla JS rather than initialising stuff with jQuery

would you fork?

**Comment by abmah** [comment]
> If you want to use a library similar to owl carousel written in vanillaJS, try this: https://spider149.github.io/own-carousel/

very usefull!

**Comment by zakirhasan736** [comment]
yes but how can i pass in hee active clad for curren ,prev and next item?
