### ISSUE TITLE
animation issues

### ISSUE THREAD

**Issue by guykatz** [OwlCarousel2/OwlCarousel2#1630]
Hi; I have the most simple carousel in code pen: https://codepen.io/guykatz/pen/aBdvJy
please open the codepen in chrome and you will see that from the second image onwards the images are not displayed correctly and things get messy.
this behavior does not exist in IE.
is this a browser issue? a codepen issue? a library issue?
thanks!
BWT, remove the in out animation config from the owl options and things work fine...

UPDATE: adding animation.css solves this as it probably reverts to animation.css instead of the owl home brew animation

**Comment by pascalporedda** [comment]
You are using other animations than those that are included with the carousel itself. As soon as you add animate.css you get all of the other animations.
