### ISSUE TITLE
center mode doesn't work with odd items numbers

### ISSUE THREAD

**Issue by mustafasalah** [OwlCarousel2/OwlCarousel2#1632]
Hello,

i read that center mode works with odd & even items numbers, but i tried to make carousel with odd items number and it didn't work.

i use these options with center mode and it didn't work :

loop, dots, autoplay, autoplayTimeout, autoplayHoverPause, autoplaySpeed, navSpeed ,stagePadding, margin: margin, nav: , rtl, navText, responsiveBaseElement, responsive.

and please improve "stagePadding" option to support relative unit as well.

and Thank You Very Much!

**Comment by JordanSayner** [comment]
I have noticed this as well, a bit of a shame, but i can work around it.

But ideally it would be better if this feature worked.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Comment by neoman666** [comment]
+1

Here is a codepen with the issue...

[https://codepen.io/anon/pen/vQBWNY](https://codepen.io/anon/pen/vQBWNY)

With even items it works, with odd items it does not work.
