### ISSUE TITLE
Single page application and multi owl carousel

### ISSUE THREAD

**Issue by onyxnl** [OwlCarousel2/OwlCarousel2#1634]
Hi all,

I am using single page application with multiple owl carousel slider. My issue is slider is working properly on first time, when i go to second page slider width is narrow. How to fix for that.

Hopefully..

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by onyxnl** [comment]
Hi Pascal,

I already solved this issue.
I used to load() for carousel.

Thanks,
Nilar

**Comment by omermindivanli** [comment]
Could you please share a snipplet how to solve that problem? I have used react and client-side rendering I have not solved that problem. When I surf from component to component, the carousel does not start automatically owing to the windowLoad(); func. I guess...
https://github.com/omermindivanli/visioncenter.se is the link of project. You can see the code inside client folder. 
http://165.227.162.187/ is the real website.
