### ISSUE TITLE
Empty items.

### ISSUE THREAD

**Issue by al3xandrei** [OwlCarousel2/OwlCarousel2#1635]
I just got a issue that a empty item is created and cloned if the content is not fully loaded so I get 1 empty item as first and last item.
I set the function call to owlCarousel in a setTimeout and it works correctly.
The function call is already in a jQuery ready statement.

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
