### ISSUE TITLE
When the stable and fully functioned version will release including syncing two carousel and infinite loop ?

### ISSUE THREAD

**Issue by dekavadia** [OwlCarousel2/OwlCarousel2#1636]
I require syncing and infinite loop on swipe in one of my project. I have tried code of OwlCarousel 2 and also referred #1378 for the same, but somehow it is not working properly and also it has issues in real device and Mac. Would you please announce date for full functioned and stable version for the same or provide solution by providing code which works in all device and browsers ?

**Comment by pascalporedda** [comment]
This is up to @daviddeutsch. But maybe I can take care of this in one of the upcoming releases.
