### ISSUE TITLE
Background video image not loading

### ISSUE THREAD

**Issue by BB-000** [OwlCarousel2/OwlCarousel2#1638]
Hi,  I have a simple owl carousel with images and videos. When navigating through the carousel left to right , ie. sliding right, things work as normal. However if you scroll left, the video background / placeholder display nothing until are on that slide.  After it has been loaded like this it is visible as normal. This behaviour is replicable every time. I've tried with and without lazyload. Any ideas?

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
