### ISSUE TITLE
Call Back to Create Animate Caption

### ISSUE THREAD

**Issue by Chudz** [OwlCarousel2/OwlCarousel2#1639]
Hello,

I am trying to use use call backs to add a class to my caption div after the side has animated. Please seen my jQuery below, it does not seem to be working no classes are being added.

	$(".home-carousel").owlCarousel({
		items: 1,
		smartSpeed: 600,
		loop: true,
		autoplay: true,
		nav: true,
		navText: ["<img src='img/prev-icon-white@2x.png' alt='prev icon'>","<img src='img/next-icon-white@2x.png' alt='next icon'>"],
		dots: false,
		callbacks: true
	});

	$('.home-carousel').on('onAnimationEnd', function(){
		$(".home-carousel .owl-item.active div").addClass('animated fadeIn');
	});

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
