### ISSUE TITLE
Set scroll speed

### ISSUE THREAD

**Issue by illuzii** [OwlCarousel2/OwlCarousel2#1643]
Hello, i've used your demo
https://owlcarousel2.github.io/OwlCarousel2/demos/mousewheel.html
only changed 
    if (e.deltaY>0) {
        owl.trigger('prev.owl');
    } else {
        owl.trigger('next.owl');
    }
because it make reverse scroll in your sample.

But it scrolls it with a very big speed.
if you use 6 items per stage - it's ok, but if you use like me 2 or 1 items per stage - it scroll me through to numbers 10-11, not to item numbers 3 or 4.

How i can make scroll speed slow? To scroll 2-3 items at one scroll?

I use Safari, Mac OSX Sierra
//Sorry for my english

**full JS code:**

var owl = jQuery('.owl-carousel');
owl.owlCarousel({
    loop:false,
//    stagePadding: 100,
	slideBy:1,
    nav:true,
    margin:0,
    responsiveClass:true,
    responsive:{
        0:{items:1},
        600:{items:2,slideBy:2},            
        1024:{items:2,slideBy:2},
        1600:{items:3,slideBy:3},
        1920:{items:4,slideBy:4}
    }
});

jQuery(".owl-prev").html('<i class="fa fa-chevron-left"></i>');
jQuery(".owl-next").html('<i class="fa fa-chevron-right"></i>');

owl.on('mousewheel', '.owl-stage', function (e) {
    if (e.deltaY>0) {
        owl.trigger('prev.owl.carousel', [1000]);
    } else {
        owl.trigger('next.owl.carousel', [1000]);
    }
    e.preventDefault();
});

**Comment by illuzii** [comment]
no ideas?

**Comment by CracyCrazz** [comment]
This is rather an Stackoverflow question. Please just report issues here.

**Comment by illuzii** [comment]
ok, thanks. Posted it here http://stackoverflow.com/questions/40847532/set-scroll-speed-of-owlcarousel2
