### ISSUE TITLE
3D effect

### ISSUE THREAD

**Issue by paloties** [OwlCarousel2/OwlCarousel2#1646]
H,
I would like to know if it’s possible to add a 3D effect to the slider (something [like this](https://www.google.co.uk/search?q=slider+3d&espv=2&biw=1329&bih=1221&source=lnms&tbm=isch&sa=X&ved=0ahUKEwipq7Chi87QAhUlDsAKHVI2A6wQ_AUIBygC#tbm=isch&q=slider+3d+products&imgrc=Q6OeK-VKzkH3gM%3A)), having the slide of the centre closer than the others…

Thanks

**Comment by pascalporedda** [comment]
Currently this is not planned, there are other things on the Roadmap before we get into such things.
