### ISSUE TITLE
Prevent vertical scroll of page when drag an slide

### ISSUE THREAD

**Issue by fabiojunior** [OwlCarousel2/OwlCarousel2#1648]
Hi!

Im try to solve this question but i have no success.

Is there any way to prevent vertical scroll of page when drag an slide? This issue is only active in mobile access.

Thanks in advance!

**Comment by thomaseilander** [comment]
Would be interested to know this as well. Anyone?

**Comment by ewape** [comment]
I'm having the same issue.

**Comment by dankiv** [comment]
Look like this issue is reproducing only on ios version > 8. On 7.1.2 works fine

**Comment by ewape** [comment]
I was able to solve the issue by setting pullDrag option to false.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
