### ISSUE TITLE
Bug with Dots

### ISSUE THREAD

**Issue by Dippy83** [OwlCarousel2/OwlCarousel2#1651]
If you have loop:false and enable Dots, the last dot will not be highlighted when you reach the end of the slide. This can be seen in 1 of the demo http://www.owlcarousel.owlgraphic.com/demos/responsive.html
If you click on the last dot, it will slide but the dot will not change class to show it is at the end

**Comment by ufitch** [comment]
It's not Bug. 
This is because You have total 12 items and 5 items per slide in more than 1000px resolution. So You have 12/5=2,4 slides. Add 3 items or turn _loop_ on, or change items quantity in one slide for more than 1000px resolution from 5 to 4 and everything will be ok.

**Comment by guidobakkes** [comment]
Problem is I don't have control over how many items are going to be uploaded into the carousel. Loop doesn't fix this either. If I have 4 items in total, showing 3 per slide, the dot will stay on the first page until my first item is returned to the first position (which is after 2 loops).

**Comment by SjoerdRijsdijk** [comment]
Hey, I created a fix that highlights the dots when the last item on the carousel is reached.
In the code $(this) refers to that element on which you initialize the owlCarousel. I don't know that the way I check for dragging is the right way to do it, but it seems to work at the moment. 
```javascript
$(this).owlCarousel({
  items: 1,
  margin: 40,
  mouseDrag: false,
  loop: false,
  responsive: {
    700: {
      items: 2,
      dotsEach: 2,
      slideBy: 2
    },
    1064: {
      items: 3,
      dotsEach: 3,
      slideBy: 3
    }
  }
});

//The dot fix does some weird stuff on resize. This prevents those things from happening by going to the first carousel page | WIP
$(this).on("resized.owl.carousel", function(e) {
  $(this).trigger("to.owl.carousel", [0, 0]);
});

var lastPage = false;
var prevStartTime = 0;

//Fix for the dot bug | Yay
$(this).on('changed.owl.carousel', function(e) {
  //Not necessary when the loop property is set to true, since it doesn't work with that
  if (!e.relatedTarget.options.loop) {
    prevStartTime = e.relatedTarget.drag.startTime;
    if (lastPage) {
      //Check if the change was not done by dragging
      if (e.relatedTarget.drag.startTime == prevStartTime) {
        //Go to the previous page 
        $(this).trigger('to.owl.carousel', [e.page.count - 2]);
      }
      prevStartTime = e.relatedTarget.drag.startTime;
      lastPage = false;
    }
    //Check if the last dot needs to be highlighted or not
    else if (e.page.count > 1 && e.item.index % e.page.size && e.item.index > (e.item.count - 1) - e.page.size) {
      $(e.target).find('.owl-dots div:last').addClass('active').siblings().removeClass('active');
      $(this).trigger('to.owl.carousel', [e.page.count - 1]);
      lastPage = true;
    }
  }
});
```

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Comment by shaddam** [comment]
If you use "  loop:true " then your problem will be solve.
