### ISSUE TITLE
Understandable part of code for me, please understand me, i have magic problem

### ISSUE THREAD

**Issue by yunusga** [OwlCarousel2/OwlCarousel2#1654]
What is doing this code and what for? [2.2.0/dist/owl.carousel.js#L820](https://github.com/OwlCarousel2/OwlCarousel2/blob/2.2.0/dist/owl.carousel.js#L820 )

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
