### ISSUE TITLE
BUG autoplay

### ISSUE THREAD

**Issue by andreamk** [OwlCarousel2/OwlCarousel2#1655]
Hello 
if Owl Carousel start with **autoplay false** and I use the event **play.owl.autoplay** it work only one time.
you can see the bug at http://codepen.io/andreamk/pen/eBMNBW

**Comment by pascalporedda** [comment]
I can approve this behavior. Will be fixed in one of the upcoming releases.

**Comment by pascalporedda** [comment]
Ups.. Didn't wanted to close that.

**Comment by daviddeutsch** [comment]
See #1942
