### ISSUE TITLE
iPhone Issue: Carousel width not calculated correctly 

### ISSUE THREAD

**Issue by obeyda** [OwlCarousel2/OwlCarousel2#1657]
Everything is working fine in desktop browsers. But in iPad/iPhone safari, the width of the carousel become wider.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
