### ISSUE TITLE
to.owl.carousel - Navigation plugin bug

### ISSUE THREAD

**Issue by AaronLayton** [OwlCarousel2/OwlCarousel2#166]
It seems that the navigator plugin is throwing an error

``` javascript
$($0).trigger("to.owl.carousel", 1)
```

`TypeError: Cannot read property 'start' of undefined`

**Comment by ThomWilhelm** [comment]
Just came across this same issue, still seems the docs are outdated:

http://www.owlcarousel.owlgraphic.com/docs/api-events.html

Please update as this is going to catch a lot of users out.

**Comment by brunomuler** [comment]
@ThomWilhelm I was having the same problem after updating to beta 3, but found out the website is still pointing to beta 2.4, so the documentation is updated to this version, not to beta 3.

**Comment by arashtavoosi** [comment]
use
dots: true
and it works

**Comment by jack-fdrv** [comment]
without dots it doesnt work?

**Comment by shtalinberg** [comment]
dots: false 
TypeError: Cannot read property 'start' of undefined,

**Comment by thegreengrass** [comment]
Seeing this too.

**Comment by BB-000** [comment]
Didn't have an error message but didn't work properly until I put the 'true' parameter in

**Comment by jafarchoupan** [comment]
Cannot read property 'start' of undefined ?
