### ISSUE TITLE
In version 2.2.0, default themeClass = owl-theme, controlsClass = owl-controls not available in html

### ISSUE THREAD

**Issue by shashankitsoft** [OwlCarousel2/OwlCarousel2#1661]
In version 2.2.0, 
The default themeClass = **owl-theme** and controlsClass = **owl-controls** not available in generated html by default in owl carousel.

Even setting these classes via class options in javascript while initializing carousel options not rendering these classes in html.

It was there by default in 2.0.0 beta 2.4. After upgrading to 2.2.2 above mentioned classes not available in html, so  carousel displays wrong.

**Comment by NekoStudio** [comment]
Same problem. Also, not working `nav:false`

```
$('.carousel').owlCarousel({
        items : 5,
        margin: 10,
        responsiveClass:false,
        responsive:{
          0:{
            items:1,
            slideBy:1,
          },
          480:{
            items:1,
            slideBy:1,
          },
          768:{
            items:2,
            slideBy:1,
          },
          1000:{
            items:3,
            slideBy:1,
          }
        },
        autoplay:true,
        smartSpeed:1400,
        autoplayTimeout:5000,
        autoplayHoverPause:true,
        loop:false,
        dots:false,
        nav:false
    });
```
But 

![screenshot_54](https://cloud.githubusercontent.com/assets/15041120/21126265/3ede8cf6-c0fc-11e6-9d86-af1a71415386.jpg)

**Comment by chappydboz** [comment]
same problem.

**Comment by KitKat777** [comment]
I think the name changed .default added. So make sure you are including that one.
owl.theme.default.min.css

**Comment by rusticblonde** [comment]
Ive copied the default CSS as above. These are still not rendering in the new version of Owl 2.2. Any news of a resolution?!?!

Thanks

**Comment by shashankitsoft** [comment]
I posted this issue about a month ago, many other developers are also facing the same problem. Have any  OwlCarousel2 team looked into it to fix it? OwlCarousel 2.2.0 is completely broken, non-working, urgent fix needed.

**Comment by pascalporedda** [comment]
This is not a bug, you have to add the owl-carousel and owl-theme class before initializing the carousel.

This is also stated in the readme..

**Comment by vonund** [comment]
Hi there,
adding the **owl-theme** (optional) class to carousel before initializing does not solve the problem with missed **owl-controls** container for nav and dots. This container is't rendering in html.

**owl-controls** container exists on the [example structure here](https://owlcarousel2.github.io/OwlCarousel2/docs/api-classes.html) but in all of the demos this wrapper is missed and html structure looks like attached one.

Is the is any way to render **owl-controls** container in the html?

![sample](https://cloud.githubusercontent.com/assets/13350294/23309029/d2a15b06-fab5-11e6-8502-83400f05d27c.png)

**Comment by bigegodesign** [comment]
For missing use of `themeClass: your-classes,` I have used the following to add my classes to the Owl gallery:
````
$('.owl-carousel').on('initialized.owl.carousel', function(e) {
    $(e.target).addClass('you-class1 your-class2 class3');
}).owlCarousel({
items:1,
    ..etc
````
