### ISSUE TITLE
Autoplay Interval in seconds?

### ISSUE THREAD

**Issue by mathetos** [OwlCarousel2/OwlCarousel2#1664]
It seems an important feature of Autoplay isn't supported currently: Interval. Many people want to be able to set how many seconds pass between the transition of each slide in the carousel. As far as I can see, these are the only existing options:

```
autoplay:true // Enable Autoplay
autoplayTimeout:5000 // time delay until Autoplay automatically stops
autoplayHoverPause:false // Set whether Autoplay should pause or not on mouse hover
```

I'd love to see the following supported:

`autoplayInterval: 5000`

Thanks!

**Comment by pascalporedda** [comment]
https://owlcarousel2.github.io/OwlCarousel2/docs/api-options.html#autoplaytimeout
