### ISSUE TITLE
Multiple Owl Carousel not loading fully all of the time.

### ISSUE THREAD

**Issue by Chudz** [OwlCarousel2/OwlCarousel2#1667]
Please see example here: http://www.silentdisco.fr/nos-casques/

I am using Google Chrome, when I load the page sometimes (most of the time) it does not load all of the images inside the carousels. However if you refresh a few times it will eventually load them all.

Any idea what could be causing this issues?

Thanks

**Comment by Chupz0r** [comment]
I can also confirm this problem. It appears on Opera too. Then I reset browser cache (CTRL+F5) I get 1px height Owl Carousel, but when I refresh page a few times Owl Carousel starts working normally.
NOTE: It only happpens when option autoWidth is true.
![2017-01-19_16-06-04](https://cloud.githubusercontent.com/assets/5112441/22107888/78b9d6f6-de61-11e6-9d1e-7a68b5d02c68.png)
![2017-01-19_16-07-06](https://cloud.githubusercontent.com/assets/5112441/22107889/78baa590-de61-11e6-9f9a-3202f90a8572.png)

**Comment by CracyCrazz** [comment]
You are probably using the "autoheight: true" setting - this can break the carousel once the images aren't fully loaded.

This is a known issue and will be targeted in one of the upcoming releases. Until this is fixed I could recommend you to use a jQuery Libarary like https://github.com/desandro/imagesloaded 

And wrap the initializer in a imagesLoaded(function(){});

**Comment by mathmul** [comment]
According to first heading of Owl Carousel's [first GitHub page](https://github.com/OwlCarousel2/OwlCarousel2) I suppose there won't be any new releases where this is fixed, am I right?
