### ISSUE TITLE
Specify different stagePadding for right and left

### ISSUE THREAD

**Issue by eggxman** [OwlCarousel2/OwlCarousel2#1669]
Hi,

I've been using owl-carousel 2, and for a project I had to specify 2 different values for padding-right and padding-left using stagePadding. I may be wrong but basically Owl Carousel doesn't allow you to do that.

I made a quick fix in owl.carousel.js to fit my needs and I managed to add stagePaddingLeft and stagePaddingRight as options to pass to any owl instance.

It could be useful to be able to pass either an integer or an array to stagePadding in case we want to apply different values for padding-left and padding-right.

Thanks,

**Comment by victorlabigar** [comment]
Hi eggsman, 

I'm looking for the exact same feature. Would you mind to share your solution here for me/us?

Thanks in advance,

Victor

**Comment by eggxman** [comment]
Hi Victor,

First sorry for the later answer, was off the whole week-end and didn't
have the modified owl carousel file.

So I've updated owl.carousel.js so you can specify both stagePaddingRight
and stagePaddingLeft independantly in your instance options. I've attached
it to this mail ;)

Feel free to contact me back if you have any issue with my solution !

Regards



2017-01-13 13:24 GMT+01:00 Victor Labigar <notifications@github.com>:

**Comment by victorlabigar** [comment]
Hi Clement,

Thanks for the reply and no worries, I’m glad you’ve answered!
Also many thanks that you’re willing to share it with me… but unfortunately I think you’ve forgot to attach your file?


Regards,

Victor Labigar

M: 0641986566 
E: victorlabigar@gmail.com
W: www.studioviq.nl

LinkedIn: https://www.linkedin.com/in/victorlabigar

**Comment by eggxman** [comment]
I'm sure I've attached the modified file, in case you can't see it, I've
also created a snippet on my bitbucket account :
https://bitbucket.org/snippets/eggxm4n/AqrMd

Feel free to use it ;)




2017-01-16 11:43 GMT+01:00 Victor Labigar <notifications@github.com>:

**Comment by victorlabigar** [comment]
Perfect man!
Thanks, I’ll let you when I’ve implemented it… can’t wait! ^^


Regards,

Victor Labigar

**Comment by victorlabigar** [comment]
Hi Clement,

Totally forgot to tell you that your code modification works perfectly. 
Many thanks for sharing it!

Regards,
Victor

**Comment by eggxman** [comment]
Hi Victor,

No problem, I'm glad it worked for you !
I hope this feature will be approved for developement so someone could add
this in a future release soon! ;)

Regards

Clément




2017-01-26 11:31 GMT+01:00 Victor Labigar <notifications@github.com>:

> Hi Clement,
>
> Totally forgot to tell you that your code modification works perfectly.
> Many thanks for sharing it!
>
> Regards,
> Victor
>
>
> > On 16 Jan 2017, at 11:56, Victor Labigar <victorlabigar@gmail.com>
> wrote:
> >
> > Perfect man!
> > Thanks, I’ll let you when I’ve implemented it… can’t wait! ^^
> >
> >
> > Regards,
> >
> > Victor Labigar
> >
> >> On 16 Jan 2017, at 11:47, Clément Parent <notifications@github.com

**Comment by aastudio** [comment]
Has the functionality been merged ?

**Comment by eggxman** [comment]
Seems like it hasn't 

I can provide you my modified file which supports it though.
