### ISSUE TITLE
owl-carousel-2 and owl-carousel-1- can they live together?

### ISSUE THREAD

**Issue by halukkaramete** [OwlCarousel2/OwlCarousel2#1671]
Just a quick question, I got the owl-carousel 1 code. I have this running

 * 	Core Owl Carousel CSS File
 *	v1.3.2

if I just replace the source files to owl-carousel 2, would the existing carousels continue to work or break?

Or do I need to change their HTML/CLASS names to make it work with owl 2?

Thank you for your time in advance!

**Comment by CracyCrazz** [comment]
I can't give you an answer for this. But I think that this would break.
