### ISSUE TITLE
Synced 2 Owl Carousel

### ISSUE THREAD

**Issue by silicondigit** [OwlCarousel2/OwlCarousel2#1672]
For peoples who need to sync 2 Owl Carousel this is my solution :

var owl = $('.owl-destination');
var owl2 = $('.owl-navigation');

/*
 * Destination carousel
 */
owl.owlCarousel({
  nav:false,
  dots:false,
  items:1
}).on('changed.owl.carousel', function(event) {
    owl2.trigger('to.owl.carousel', [event.item.index, 300, true]);
    // (Optional) Remove .current class from all items
    owl2.find('.current').removeClass('current');
    // (Optional) Add .current class to current active item
    owl2.find('.owl-item .item').eq(event.item.index).addClass('current');
});

/*
 * Navigation carousel
 */
owl2.owlCarousel({
  nav: true,
  dots:true,
  margin:10,
  items: 3
})
.on('click', '.owl-item', function(event) {
    owl.trigger('to.owl.carousel', [$(event.target).parents('.owl-item').index(), 0, true]);
});

Demo : http://silicon.ma/owlcarousel2/demos/sync.html

**Comment by muhamed87** [comment]
It is available here:
https://github.com/OwlCarousel2/OwlCarousel2/issues/1378

Just include this file:
https://github.com/OwlCarousel2/OwlCarousel2/blob/feature/1378-linked-owls/src/js/owl.linked.js

and simply add the following to the options of the carousel:
`linked: "#other-carousel,.maybe-another-one"`
