### ISSUE TITLE
autoplay stop if change tab browser

### ISSUE THREAD

**Issue by filipenco92** [OwlCarousel2/OwlCarousel2#1674]
Hello, owl stop autoplay if i change browser tab (chrome, firefox...), it start if i click to next slide or drag image! And other problems: if autoplayHoverPause: true, not starting autoplay after hover! thank you

**Comment by muhamed87** [comment]
I have the same issues, I think these issues weren't available in a previous version (v2.0.0)

Any help??

**Comment by nirajrajgor** [comment]
@filipenco92 I am also facing the same issue. trying to integrate in my project. When i change tab and comeback the carousel does not start. you need to reload the page. Any help ? Has someone found the solution?

**Comment by filipenco92** [comment]
i used 2.0.0-beta.3 and work fine  from here https://github.com/OwlCarousel2/OwlCarousel2/releases

**Comment by nirajrajgor** [comment]
@filipenco92 is it consider good to use beta versions in production website? as i will be using it for live projects.

**Comment by CristyTarantino** [comment]
I use version 2.2.0.

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Comment by aristidesfl** [comment]
I do have the same problem with 2.2.0

**Comment by pascalporedda** [comment]
Still no live example. @aristidesfl

**Comment by aristidesfl** [comment]
@filipenco92

**Comment by dynostatic** [comment]
I have a live example:

1. Go to https://owlcarousel2.github.io/OwlCarousel2/demos/autoplay.html
2. Open a new browser tab, or switch to an existing one
3. Switch back to original tab with carousel
4. Autoplay is halted

Tested in Firefox, Chrome, Safari

**Comment by nirajrajgor** [comment]
Working example is provided, so i think issue should be reopen now. @pascalporedda

**Comment by vineetkumar1511** [comment]
Any update on this issue ?

**Comment by Creational** [comment]
Any news? It's still not working properly ... 
Or does anybody found a workaround in the meanwhile?
