### ISSUE TITLE
Strange font rendering issue

### ISSUE THREAD

**Issue by andrejarh** [OwlCarousel2/OwlCarousel2#1675]
I have a very strange text rendering issue in Chrome. 
Please check:
https://jumpshare.com/v/vGb1z0idcL0jIndlPw2M

It is not an .active CSS issue (although it might appear so on the first glance). This appears at random: One slide works and the other one doesn't: https://jumpshare.com/v/IF5s4cnK1LHPFia54Uew

As soon i change any CSS value on the element in web inspector, the issue disappears.

Relevant info: 
HTML validates (w3c check passed without warnings or errors),
Fonts I'm using are Google fonts, "Source Sans Pro", 
OWL version 2.2.

Spend already day and a half trying to debug this, ran out of ideas on what to try next. Any ideas are welcome.

**Comment by CracyCrazz** [comment]
This could be caused by the CSS animation rendering in the chrome browser.

Not much I can do at this point. Maybe post it on https://stackoverflow.com
