### ISSUE TITLE
navRewind doesnt seem to work

### ISSUE THREAD

**Issue by aunruh** [OwlCarousel2/OwlCarousel2#168]
Check it out here: http://trailingwhitespace.com/owl2/

When I'm on the last slide and click my 'next' button, the slides don't rewind. This is my js:

``` javascript
jQuery(document).ready(function(){
    $(".slideshow").owlCarousel({
        items : 1,
        mouseDrag : false,
        nav : true,
        loop : false,
        navRewind : true,
        dots : false
    });
});
```

**Comment by judewang** [comment]
Hi, it seems the navRewind bug have not been solve, could you check it with beta2.4?
Thanks.

**Comment by minhluan259** [comment]
+1 navRewind don't work on owl 2.0.0-beta.3

**Comment by greg5green** [comment]
If it still doesn't work with beta 3, please create a new issue with info on how to reproduce the problem and a codepen/jsfiddle/jsbin example. Thank you.

**Comment by greg5green** [comment]
Btw, the option is just known as `rewind` now (http://smashingboxes.github.io/OwlCarousel2/docs/api-options.html#rewind) as of https://github.com/smashingboxes/OwlCarousel2/commit/8dff4400160573e08fc0d7beca5266a47a0d305b

**Comment by minhluan259** [comment]
:+1:  with rewind,  it's working

**Comment by greg5green** [comment]
:+1:

**Comment by jonw100** [comment]
I'm using OwlCarousel2 with loop set to false.  Unfortunately neither navRewind or rewind seem to be working for me.

**Comment by notxactly** [comment]
Not working for me either, using 2.0.0 beta 3 from http://smashingboxes.github.io/OwlCarousel2/ - have tried both rewind and navRewind set to true and loop to false.

**Comment by danielepennati** [comment]
Not working for me either, using 2.0.0 beta 3 but I have the opposite bug... 
I don't want the rewind but I always get it. I've set both rewind to false (even if it is its default value) but I still get the rewind when a get the end of the carousel.

**Comment by sentisoft** [comment]
for me rewind not work.. how this can be? for someone work for another people not work??? do we need to add something more not just owl.carousel.min.js

**Comment by TalD** [comment]
+1. Neither work ("rewind" or "navRewind").

**Comment by TalD** [comment]
Appears to work with "loop" set to true.

**Comment by AjithPG** [comment]
> Delete the "loop" and set "rewind: true" to the top or individually, after that, it's working for me fine.

This work for me
