### ISSUE TITLE
New version breaks when classe name on selector is diferente from owl-carousel

### ISSUE THREAD

**Issue by guibattoni** [OwlCarousel2/OwlCarousel2#1680]
Hello there!
In the previous versions, I was able to change freely the main class selectors. The follow example will illustrate it:

`    $('.whereaver-i-want').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        dots:false,
        autoplay:true,
        autoplayTimeout:1500,
        autoplayHoverPause:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:5
            }
        }
    });`

Last week I downloaded the new version and this feature seem to be impossible now. It only works when I keep the selector as in documentacion, ergo: **$('.owl-carousel')**.  I already tryed:

- Other jQuery version
- Multiple browsers

At this moment, I made a fallback to the previous version where this feature still works great. Any hint about this issue?

**Comment by sanPuerquitoProgramador** [comment]
I'm using the version 2.0.0 and the selector works well. Maybe you are not using the container class owl-carousel and owl-theme

```
/* Firs Slider JS Code*/
if ($(".featured-slider").length) {
        $(".featured-slider").owlCarousel({
            autoplay: true,
            autoplayTimeout:3000,
            loop:true,
            items: 1,
            animateOut:'fadeOut'
        });
    }

/* Second Slider JS Code*/
if ($(".text-slider").length) {
        $(".text-slider").owlCarousel({
            autoplay: true,
            autoplayTimeout:5100,
            smartSpeed:5000,
            loop:true,
            items:1,
            dots:false
        });
    }
```

The class owl-carousel and owl-theme is required in the slider container

```
<-- For the firs slider -->
<div class="col-md-10">
	<ul class="featured-slider owl-carousel owl-theme">
		<li class="item">Item 1</li>
		<li class="item">Item 2</li>
		<li class="item">Item 3</li>
	</ul>
</div>

<-- For the second slider -->
<div class="col-md-10">
	<ul class="text-slider owl-carousel owl-theme">
		<li class="item">Item 1</li>
		<li class="item">Item 2</li>
		<li class="item">Item 3</li>
	</ul>
</div>
```

**Comment by CracyCrazz** [comment]
You are probably missing the .owl-carousel class on the DOM element.

This class is required as it is stated in the documentation.

You can still initialize the Carousel with any other selector.
