### ISSUE TITLE
How to add animated text caption

### ISSUE THREAD

**Issue by ivent** [OwlCarousel2/OwlCarousel2#1681]
Hello, I would like to know how to add an animated text caption feature in the style of https://revolution.themepunch.com/ just missing this for this perfect script.

**Comment by ohepworthbell** [comment]
```
owl.owlCarousel({
  items: 1,
  loop: true,
  onChanged: function(e) {
    // Add in any JavaScript here to run when a slide has changed
  }
});
```
You can then add in any functions there to animate text captions

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

**Comment by ivent** [comment]
Hello thanks @ohepworthbell  this worked for me with the junction of some css transitions
