### ISSUE TITLE
if tab-content-container become {display:block} from {display:none},the owlcarousel's img just 26px width

### ISSUE THREAD

**Issue by admin00001** [OwlCarousel2/OwlCarousel2#1685]
i have a tab with two tab-content-container: one tab-content-container is display:block,and the other one is display:none; and each tab-content-container has a owlcarousel with many img; but the bug is:  while the first tab-content-container is {display:block } from {display:none},the first tab-content-container's owlcarousel is not responsive even though i have set the responsive options ,the img in the owlcarousel just has 26px width! if there are any bug effect the  owlcarousel's img  auto responsive while the owlcarousel-container transform between display:none and display:block?
`
 $('.sm-img-owl').owlCarousel({...});
 $('.sm-img-owl2').owlCarousel({...});
$('#myTab').find('a').click(function () {
            var attr = $(this).attr('href');
            if (attr === '#tab1') {
                $('sm-img-owl').trigger('refresh.owl.carousel');//here has refresh ,but it doesn't work
                console.log(1);
            } else if (attr === '#tab2') {
                $('sm-img-owl2').trigger('refresh.owl.carousel');//here has refresh ,but it doesn't work
                console.log(2);
            }
        });`

**Comment by yunusga** [comment]
just refresh carousel after show

**Comment by muhamed87** [comment]
@admin00001 Firstly, Are both the carousels have the same options?
If yes, you can try the following:

---------------------------

Try to make your owl carousel in a function as follows:

`function yourFunction(e) {
    e.owlCarousel({...});
};`

Then when you display your tab just call the function as follow:
`$('#myTab').find('a').click(function () {
     var attr = $(this).attr('href');
     if (attr === '#tab1') {
          yourFunction($('.sm-img-owl'));
     } else if (attr === '#tab2') {
          yourFunction($('.sm-img-owl2'));
     }
});`

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
