### ISSUE TITLE
Active prev/next on item 

### ISSUE THREAD

**Issue by romain0801** [OwlCarousel2/OwlCarousel2#1690]
Hi,

i'm using owl-carousel2 to set a playlist of sound (with loop:true and center:true), all is working fine, but i cant find doc about my problem :

i'm trying to add prev/next navigation on each item on click. I want user can click on item of his choice and so it slide center to this item. It works with mouse slide, but not on item click.

Is there a way to do this ?

there is my carousel init :

```
owl.owlCarousel({
            loop:true,
            center: true,
            margin:3,
            dot: false,
            nav: false,
            items:5,
            responsive:{
                0:{
                    items:2
                },
                768:{
                    items:4
                },
                1200:{
                    items:5
                },
                1500:{
                    items:4
                }
            }
      });
```
I tried this :

```
owl.on('click', '.item', function (property) {
          console.log(property);
          owl.trigger('next.owl.carousel');
      });
```
It works, but only for next item, i dont find how to know if it's a prev click

Thanks for help

**Comment by romain0801** [comment]
Hi, 

there is no solution ? 

thanks

**Comment by ohepworthbell** [comment]
You pretty much change 'next' to 'prev'
```
// Go previous
owl.on('click', '.prev', function() {
  owl.trigger('prev.owl.carousel', [300]);
});

// Go next
owl.on('click', '.next', function() {
  owl.trigger('next.owl.carousel', [300]);
});
```
And obviously need to add in 2 elements within each slide with the classes `.prev` and `.next`.

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
