### ISSUE TITLE
Nav is not working and custom nav with disturbing behaviour

### ISSUE THREAD

**Issue by hassanbinsafdar** [OwlCarousel2/OwlCarousel2#1694]
everything seems working fine but nav is not showing even its true and on custom navigation when i click on next it moves 2 slide on loop true when loop is false it moves 1 what is this . its problem when i use owl.carousel.js file then it giving me issue no nav show no items number work . when i use owl.carousel.js nav still not working but items number start work and custom navigation work is upset. anybody can help me .
actually i am using multiple carousel in single page and its work well but these issues i am facing right now or anyone have valid file for carousel 2 let me know thanks

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
