### ISSUE TITLE
I want to change default options after setup

### ISSUE THREAD

**Issue by kibaek-kimm** [OwlCarousel2/OwlCarousel2#1696]
I have that source code for init **owlCarousel**

```
visualSlider.owlCarousel({
	items : 1,
	merge: true,
	loop : true,
	autoplay : true,
	autoplayTimeout : 4000,
	smartSpeed : 5000
});
```

And i want to change _**smartSpeed**_  property when i dragging element.
How can i change it?

This is my _OwlCarousel2_ version.

> @version 2.0.0

Thank you.

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community. By the way, you should update your Owl version.
