### ISSUE TITLE
owlCarousel stage not getting width in safari

### ISSUE THREAD

**Issue by jengz** [OwlCarousel2/OwlCarousel2#1697]
Hi I am using OwlCarousel 2 for my project 
but when i checked in safari there is some issue about width.

Owlcarousel 2 not getting width in safari.

**Code**

> $(window).load(function(){
> var owl = $('.owllist');
> 					owl.owlCarousel({
> 						loop:false,
> 						margin:0,
> 						nav:false,	
> 						responsive:{
> 								0:{  
> 									items:1	
> 								},
> 								600:{ 
> 									items:2
> 								},
> 								1024:{ 
> 									items:4
> 								}
> 						  }					
> 					})
> 
> })

**in Chrome**
`<div class="owl-stage" style="transform: translate3d(-3166px, 0px, 0px); transition: 0s; width: 11081px;">`

**in Safari**
`<div class="owl-stage" style="-webkit-transform: translate3d(0px, 0px, 0px); transition: 0s; -webkit-transition: 0s; width: 0px;">`

But when i resize the browser it will proper..

**Comment by daniel-fgmnt** [comment]
@jengz were you able to fix this issue?

**Comment by jengz** [comment]
Yes @daniel-fgmnt , i got the solution..

All this issue comes because of transition for that i add some css

`.owl-carousel,.owl-stage-outer,.owl-stage,.owl-item,.owl-item .item,.owl-wrapper{transition: none;}
.owl-carousel:after,.owl-carousel:before,.owl-stage-outer:after,.owl-stage-outer:after,.owl-stage:after,.owl-stage:before,.owl-item:after,.owl-item:before,.owl-item .item:after,.owl-item .item:before{transition: none;}`

and my problem solved..

I hope this will helps you...

Thanks.

**Comment by johnchidiac** [comment]
I'm having the exact same problem, same browsers, same thing that it rights itself when browser is resized. Unfortunately, the CSS solution above did not work. 

In my case, owl-stage has width set inline to 4.998px...

`<div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: 0s; width: 4.998px;">`

I can't find where this width is being set.

**Comment by EvvC** [comment]
@jengz thanks, it works
