### ISSUE TITLE
Issue with Owl2 - Controls

### ISSUE THREAD

**Issue by deepads90** [OwlCarousel2/OwlCarousel2#1699]
Hi Team,
I am facing issue in owl carousel 2 .
I have added the autoplay- controls and i have owl-dots active in my silder. The issue is when my slider is paused and when i click on any of the slider dots even though the slider is paused the carousel is auto-played.

Could you please help me with that?

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
