### ISSUE TITLE
Error with jQuery 3.1.1

### ISSUE THREAD

**Issue by vdecree** [OwlCarousel2/OwlCarousel2#1700]
I am getting the error `TypeError: t(...).find(...).andSelf is not a function` with jquery version 3.1.1 using the latest version of Owl slider from github. 

Has the plugin been dropped by the new owner? I notice the website isn't working anymore and there are no recent updates. I did notice other threads reporting issues with the newer jQuery - apparently fixed in 2.2.0, but doesn't seem to work from what I can see.

**Comment by Disorrder** [comment]
https://codepen.io/anon/pen/pRaPMX

At least, it works... Not good, but works

**Comment by CracyCrazz** [comment]
The issue you are referencing should be fixed already in the latest version. 

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
