### ISSUE TITLE
Multiple URL Hash Navigations on one page

### ISSUE THREAD

**Issue by jjang1449** [OwlCarousel2/OwlCarousel2#1702]
Hi,

I set up two url hash navigation sliders on one page and both have <div class="owl-carousel">.

If I have one url hash navigation slider, I can type on hash value in the url to load a page and have that specific slide show up like this https://owlcarousel2.github.io/OwlCarousel2/demos/urlhashnav.html#ten (this shows 10th slide on page load)

However, when I have 2 url hash navigation sliders, this doesn't work. If I pass hash value into the url on page load, that slide does NOT get selected.

How do I resolve this issue?

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
