### ISSUE TITLE
autoplayTimeout on multiple carousel

### ISSUE THREAD

**Issue by Ladylain** [OwlCarousel2/OwlCarousel2#1703]
Hi, 

I have many OwlCarousel on my site, and i want to autoplay them with a different autoplay to show them like a metro style tiles. 

So my question is : " Is there a way to add multiple autoplayTimeout ? or a value like "random" on this option ? 

Thx, and btw it's a very cool carousel ! nice work !

**Comment by sanPuerquitoProgramador** [comment]
You can set each carousel with their own settings:

```
/* Slider numer one */

if ($(".slider-featured-images").length) {
        $(".slider-featured-images").owlCarousel({
            autoplay: true,
            autoplayTimeout:3000,
            loop:true,
            items: 1,
            animateOut:'fadeOut'
        });
    }

/*Here is another slider */

if ($(".text-slider").length) {
        $(".text-slider").owlCarousel({
            autoplay: true,
            autoplayTimeout:2500,
            loop:true,
            items:1,
            dots:false
        });
    }
```

**Comment by Ladylain** [comment]
Hum... it's a solution i didn't think ! thanks to you !
