### ISSUE TITLE
Uncaught Can not detect viewport width

### ISSUE THREAD

**Issue by franklinjavier** [OwlCarousel2/OwlCarousel2#1704]
Hi... I'm receiving a lot of error event in Sentry about `Uncaught Can not detect viewport width.`.

I would suggest to not throw an error since users can't do anything about this. Also, It will use up my error reporting quota. 

How about print a console warning or error though?

cc @daviddeutsch

**Comment by franklinjavier** [comment]
cc @daviddeutsch

**Comment by damirkoch** [comment]
(Sorry about the canned reply.)

We have received your feature request and will evaluate the implementation of this. 

I can't give you an estimated date when or if this will be integrated into the project. This might happen when the main refactoring will take place.

**Comment by pascalporedda** [comment]
Fixed in latest release.

**Comment by franklinjavier** [comment]
:beers:
