### ISSUE TITLE
How to Disable Carousel Autoplay while Video is Playing

### ISSUE THREAD

**Issue by Key7i** [OwlCarousel2/OwlCarousel2#1709]
I have 3 items in carousel, two images and a video. Autoplay is true with 8 sec timeout.. but the problem is that when i play the video, slide move out while video is still loading. Is there a way to stop autoplay while video is playing. And resume autoplay function when video is not playing or paused?

**Comment by odahcam** [comment]
You can detect when the video loads and ends and manually move the carousel via API.

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
