### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by hcossio** [OwlCarousel2/OwlCarousel2#1710]
Hi.

OwlCarousel came with my Salient Theme installation.

The problem is I want the carousel to keep looping as you have in your demo page.

There is no visible setting for this other than Autoplay.

Please help.

Thank you!

**Comment by mycarrysun** [comment]
The API option "loop" gives this functionality:

```
$('.owl-carousel').owlCarousel({
  loop: true
});
```
