### ISSUE TITLE
2.2.0: "rewind" set to false is currently not working

### ISSUE THREAD

**Issue by tsteuwer** [OwlCarousel2/OwlCarousel2#1713]
No matter how many .owl-item elements I have, setting "rewind" to ``false`` does not stop it from going back to the beginning when it reaches the last item. This happens on all devices. The funny thing, though, is it adds the "disabled" class to the "next" and "prev" buttons, but still allows them to continue.

Installed through bower if that matters. But I doubt it.

**Comment by nullvariable** [comment]
I'm also encountering this bug. I'm advancing by 4 items, if I have 8 items it rewinds no matter what, if I have 9 it stalls but does not rewind.

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
