### ISSUE TITLE
On page load carousel calculates wrong width

### ISSUE THREAD

**Issue by charmcat** [OwlCarousel2/OwlCarousel2#1715]
Example of issue: https://charmcat.net/shop/stationery/fair-day-invitation/

When using a window that is 768px or more, on initial page load the carousel ignores the column on the right and imposes a width that spans the entire page. Any resize of the browser window fixes the sizing issue. Not an issue on smaller viewports because the columns rearrange to take up 100% width anyway.

Columns created using bootstrap responsive classes.

Options:
`
    $('#gallery').owlCarousel({
        items: 1,
        center: true,
      	autoHeight: true,
        margin: 10,
        stagePadding: 10,
        nav: true,
        navText: [
      "<i class='fa fa-angle-left'></i>",
      "<i class='fa fa-angle-right'></i>"
      ],
        dots: false,
        loop: false,
        autoplay: false,
    });
`

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

The provided live example is unclear to me, I don't know which carousel you mean. I have clicked through all of them and have not seen your described issue.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Comment by shivbhan** [comment]
Hey Guys,
I am facing the similar issue.
![owlcarousel](https://user-images.githubusercontent.com/2980198/31390834-96fc308a-adf2-11e7-99c2-7ddd95ee7515.png)
