### ISSUE TITLE
Have 'last' slide as a link to show the rest of the slides?

### ISSUE THREAD

**Issue by leecollings** [OwlCarousel2/OwlCarousel2#1716]
Let's say I have 50 slides. I would like all of these slides to be visible, or accessible to the user.

However, I want to really reduce loading time as much as possible for the page, so I would like to load the first 10 slides. At the end of these 10 slides, I would like one more slide to provide a link or action saying 'Load more slides'.

On clicking this, the remaining 40 slides are loaded and inserted in place of the 'Load more slides' slide, which is then removed.

This is on a Wordpress site, and the slides are loaded via `$wpdb->get_results`. So I guess I should load all slides that will appear here. Then I'm thinking if I hard code the 'Load more slides', I can then create events to remove that, but how do I initially hide the remaining 40 slides, and then show them again?

My current format of slides is as follows:
```
<div class="owl-carousel owl-theme owl-carousel-main">
    <div class="twentytwenty">
        <img src="#" />
        <img src="#" />
    </div>
    // Rest of slides
</div>
```

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
