### ISSUE TITLE
Security risk Client DOM XSS

### ISSUE THREAD

**Issue by gregoryo** [OwlCarousel2/OwlCarousel2#1722]
As part of a security audit on a site using version 2.2.0, we ran a proprietary static code security analyzer on the source code.  It reports several Client DOM XSS risks.  Can this data be filtered or sanitized to eliminate the risk of cross-site scripting? Below are some of the output from the security scanning system.

> Method function at line 557 of /ge_ir/assets/js/bin/owl/dist/owl.carousel.js gets user input for the data element. This element’s value then flows through client-side code without being properly sanitized or validated and is eventually displayed to the user in }).each at line 1303 of /ge_ir/assets/js/bin/owl/dist/owl.carousel.js.This may enable a DOM XSS attack. 

>owl/dist/owl.carouse l.js
> Source Method Owl.prototype.prepare = function(item) {
> ... line 567
```
return event.data;
```

> Destination Method }).each($.proxy(function(index, item) {

> ...  line 1305.  
```
this.$stage.append(item);
```
The same message for Destinations
> ... line 1334. 
```
 this._items.length !== 0 && this._items[position - 1].after(content);
```
> ... line  1338. 
```
 this._items[position].before(content);
```

**Comment by CracyCrazz** [comment]
Hey @gregoryo,

as far as I understand Client DOM XSS this has to do with user input and I don't see any user input given into the carousel.

I will discuss this with @daviddeutsch the following days.

**Comment by daviddeutsch** [comment]
Yeah, we looked at this for a bit and while there is a XSS risk, it's handed into the carousel from the outside. It's not up to plugins like OwlCarousel to make sure only sanitized content enters them. That's your responsibility.
