### ISSUE TITLE
glitch in autoplay stop and play - potential workaround

### ISSUE THREAD

**Issue by akhatri** [OwlCarousel2/OwlCarousel2#1723]
There seems to be an issue with the carousel with the autoplay trigger. 
I have added a custom click event to stop the autoplay when any of the navigation items and dots are clicked. It works fine but as soon as the user clicks the navigation items again, the autoplay starts.

There seems to be some issue with the trigger for the autoplay stop/play but somehow I have managed to get a workaround. It would be good if this could be added as a new option to "stop autoplay on user interaction"

The fix 

```
// initialise carousel
 var $carousel= $('.owl-carousel');

// click event
            $('.owl-next, .owl-prev, .owl-dot').on('click', function() {
                setTimeout(function() {
                    $carousel.trigger('play.owl.autoplay', [1000])
                    $carousel.trigger('stop.owl.autoplay');
                }, 500);
            });
```

**Comment by damirkoch** [comment]
Please make a pull request. We evaluate the implementation of this. 
I can't give you an estimated date when or if this will be integrated into the project.
