### ISSUE TITLE
to.owl.carousel not using animation effects

### ISSUE THREAD

**Issue by leecollings** [OwlCarousel2/OwlCarousel2#1724]
I'm using two carousels, one for main and one for thumbnail navigation.

EVerything works fine, apart from there is a noticeable difference between using the main carousel navigation and using the thumbnail carousel. The main carousel navigation next/prev includes the animation effect (either slide or fade). The thumbnail navigation, which is using `to.owl.carousel` just seems to jump directly to the slides.

I'm triggering the navigation like this:
```
// Thumbnail Carousel
    owl2.owlCarousel({
        margin:10,
        responsiveClass:true,
        responsive:{
            0:{
                items:3,
                dots:false
            },
            768:{
                items:6,
                dots:true
            },
            992:{
                items:8,
                dots:true
            }
        }
    })
    .on('click', '.owl-item', function(event) {
        owl.trigger('to.owl.carousel', [$(event.target).parents('.owl-item').index(), 0, true]);
    });
```

Live example can be seen at: <a ref="nofollow" src="http://development.bellavou.co.uk/face/facelift/">development.bellavou.co.uk/face/facelift/</a>

**Comment by CracyCrazz** [comment]
Hey, I'am sorry but i have clicked through your live example and can't find the issue you have described.

Could you maybe provide a working live example. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Comment by leecollings** [comment]
Hi, yes sorry I managed to get this working, realised one of the parameters of `owl.trigger` is the speed, which is currently set to `0` in the example.

After changing this, the transition effect is working fine.

**Comment by badharinder** [comment]
http://tmtplus.co.in/
i have banner carousel issue in this website
my animation is not working properly when i click left or right arrow

**Comment by ghost** [comment]
@badharinder Your issue doesn't seem to be related to mine, and is very generic. It's probably down to the slides not being implemented right. 

Have you been able to replicate the issue in a separate file, or something online we can see like jsfiddle?

You seem to have a slideInUp class applied somewhere, that's probably related. HAve you tried removing this and seeing if this makes it any different?
