### ISSUE TITLE
Videowidth & Video Height

### ISSUE THREAD

**Issue by weilinzung** [OwlCarousel2/OwlCarousel2#1725]
When I set the video width & video height and has items:2 option on that cause issue.

screenshot: https://s27.postimg.org/ehcxqhgeb/Screen_Shot_2017_02_04_at_8_02_21_AM.png
here is the option I turn on, on desktop if has items: 2 that everything overlap and no margin.
```
 margin: 10,
  // lazyLoad: true,
  nav: true,
  dots: false,
  responsiveClass:true,
  smartSpeed: 1000,
  center:true,
  // loop:true,
  video: true,
  items: 1,
  videoWidth: false,
  videoHeight: false,
  responsive:{
    991: {
      items: 2,
    },
    // 1201:{
    //   items: 1,
    //   videoWidth: 960,
    //   videoHeight: 540,
    // },
  }

```
thanks!

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
