### ISSUE TITLE
Correct width only after resize window!

### ISSUE THREAD

**Issue by flipmode85** [OwlCarousel2/OwlCarousel2#1729]
Hi,

the plugin works very well, but i got an issue if using the plugin within an "popup".
It looks like this...
<img width="2320" alt="bildschirmfoto 2017-02-06 um 15 31 14" src="https://cloud.githubusercontent.com/assets/25587585/22651021/c22a605c-ec81-11e6-8d19-c9be27a28964.png">

when resized the window..
<img width="2295" alt="bildschirmfoto 2017-02-06 um 15 35 04" src="https://cloud.githubusercontent.com/assets/25587585/22651035/da6534e4-ec81-11e6-8939-0c2065804910.png">

Tried some callbacks, to refresh the plugin before the modal are shown, but doesn't work!

**Comment by flipmode85** [comment]
Problem solved!

The Plugin can't handle "opacity". 
Changed the css and now it is working nicely.

**Comment by krisstoof** [comment]
How did you do this?
