### ISSUE TITLE
owl.carousel.js to .min version problem

### ISSUE THREAD

**Issue by kriit24** [OwlCarousel2/OwlCarousel2#1732]
end line with ";" in
on line: 715
code: $.support.transform ? this.animate(stage.x) : this.$stage.stop()
recommend: $.support.transform ? this.animate(stage.x) : this.$stage.stop();

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
