### ISSUE TITLE
nav is not showing

### ISSUE THREAD

**Issue by soxepo** [OwlCarousel2/OwlCarousel2#1733]
everything seems working fine but nav is not showing even its true

**Comment by stevewinni-cc** [comment]
Just found out why the Docs are wrong it should be navigation not nav;

Try this..

$('.owl-carousel').owlCarousel({
    	singleItem:true,
        items:1,
        loop:true,
        margin:10,
        responsiveClass:false,
        autoWidth:false,
        navigation:true,
        autoplay: true,
        autoplayTimeout: 100
        
    })

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
