### ISSUE TITLE
rewind behaviour not correct

### ISSUE THREAD

**Issue by jmiquel** [OwlCarousel2/OwlCarousel2#1734]
> owl.owlCarousel({
                            margin:10,
                            nav:true,
                            rewind: true,
                            loop: false,
                            responsive:{
                                0:{
                                    stagePadding: 20,
                                    items:1,
                                    slideBy: 1,
                                    nav: false,
                                    dots: false
                                },
                                600:{
                                    items:3,
                                    slideBy: 3
                                },
                                1000:{
                                    items:4,
                                    slideBy: 4
                                }
                            }
                        });

Having this carousel set up, the rewind seems to break when it reaches a position out of the maximum. Let's say we have 10 elements and slideBy is 3, we'll get 4 different indexes:
0-->3-->6-->9
On the next one, which is the one that needs to be rewinded we get 12 and according to this bit of code 
`position = (position % maximum + maximum) % maximum;`
position = 2 so instead of going to the first element of the carousel (index 0) we get to the third (index 2). I've created a workaround that fixes it, so I could create a pull  request if needed.

Thank you guys,
Really good carousel

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
