### ISSUE TITLE
Multiple carousels on One page with different transitions

### ISSUE THREAD

**Issue by rahx** [OwlCarousel2/OwlCarousel2#1737]
hey there, i am using your carousels in One page, but i dont want them to have the same number for autoplay, i wanna add delay to them or i want them to start with different transition times, the thing is the page is creating them dynamaticly and i may have 3 carousels or i may have 7 carousels  in page, so im creating them with 

$owl = $(".owl-carousel").owlCarousel({
			
	  	pagination : false,
		paginationSpeed : 1300,
		autoPlay: 4000,
		singleItem:true,
		navigation : false,
		lazyLoad : true,

  });
is there any option right now ?
or can i send them to a function and reinit them to have different transitions times?
something like this:
$owl = $(".owl-carousel").owlCarousel({
			
	  	pagination : false,
		paginationSpeed : 1300,
		autoPlay: 4000,
		callbacks:true,
                afterMove: reinit,
		singleItem:true,
		navigation : false,
		lazyLoad : true,

  });

function reinit(){
              //reinit and change transition time
}

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
