### ISSUE TITLE
Content doesn't seem to render after completing one cycle of carousel.

### ISSUE THREAD

**Issue by designcraveyard** [OwlCarousel2/OwlCarousel2#1738]
Hi, 
**Kindly Help its a bit Urgent**
I've enabled single item, loop and autoplay for 6 items, also on I've used callback function of  'onChanged' to animate the captions of images in every item. Everything works fine for the first cycle of transitions till carousel reaches the 6th (last item), but after that, it doesn't render content of carousel properly, though carousel is still visible and functional, some 4th or 5th slide will render and then it will stop to render again. `$(document).ready(function(){
  $(".owl-carousel").owlCarousel({
	  items:1,
	  loop:true,
	  autoplay: true,
	  autoplayHoverPause:false,
	  autoplay:1,
	  
  });
});
	
	var owl = $('.owl-carousel');
	var animationName = "animated slideInRight";
	
		owl.owlCarousel({
		items: 1,
			loop: true,
			animateOut: 'fadeOut',
			
		 items:1,
	  loop:true,
	  autoplay: true,
	  autoplayHoverPause:false,
	  autoplay:1,
			onChange:remove,
			
		
			
	});
	
$('.customNextBtn').click(function() {
    owl.trigger('next.owl.carousel');
})
// Go to the previous item
$('.customPrevBtn').click(function() {
    // With optional speed parameter
    // Parameters has to be in square bracket '[]'
    owl.trigger('prev.owl.carousel', [300]);
})
	function remove(event){
	$(".animationeffect").addClass("animated slideInUp").one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',
															   function(){
		$(this).removeClass("animated slideInUp");
	});
	}
![screenshot 302](https://cloud.githubusercontent.com/assets/25705858/22853888/5619bc8c-f087-11e6-9f45-5387c6e90e86.png)
![screenshot 303](https://cloud.githubusercontent.com/assets/25705858/22853889/56209142-f087-11e6-85c5-e884ed1c635b.png)

`

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
