### ISSUE TITLE
Dots not showing 

### ISSUE THREAD

**Issue by ittisafur** [OwlCarousel2/OwlCarousel2#1739]
Everythiing on my project went fine but stuck with this the nav dots are not showing. I used " **dot:true,** " and " **dots:true**  " none seems to work.
$('.portfolios-carousel').owlCarousel({
	    items:3,
            nav:true,
	    loop:true,
	    margin:10,
	    autoplay:true,
	    autoplayTimeout:2500
});

**Comment by CracyCrazz** [comment]
(Sorry about the canned reply.)

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!
