### ISSUE TITLE
Turbolinks

### ISSUE THREAD

**Issue by breiko83** [OwlCarousel2/OwlCarousel2#1740]
Opening this cause of a compatibility issue with Rails 4.2.7.1 and Turbolinks 5.0.1.

The plugin is rendering just fine on first page load and refresh but it breaks on browser back button.

This is my code:

applications.js

```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require owl.carousel
//= require custom
```

custom.js

```
$(function () {
  $('.owl-carousel').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        items: 4
  });
});
```

index.html

```
<div class="owl-carousel">
    <div class="item"><h4>1</h4></div>
    <div class="item"><h4>2</h4></div>
    <div class="item"><h4>3</h4></div>
    <div class="item"><h4>4</h4></div>
    <div class="item"><h4>5</h4></div>
    <div class="item"><h4>6</h4></div>
    <div class="item"><h4>7</h4></div>
    <div class="item"><h4>8</h4></div>
    <div class="item"><h4>9</h4></div>
    <div class="item"><h4>10</h4></div>
    <div class="item"><h4>11</h4></div>
    <div class="item"><h4>12</h4></div>
</div>
```

application.css
```
 /*
 *= require_tree .
 *= require_self
 */
```

custom.css
```
.item {
  height: 100px;
  background-color: red;
  color: black;
  margin: 3px;
}

.item img{
  display: block;
  width: 100%;
  height: auto;
}
```

With this code on navigation back from a second page the plugin in unresponsive but the layout is ok.
[Screenshot](http://imgur.com/a/77Hu9)

After reading around about Turbolinks I have changed the code to this:
```
document.addEventListener("turbolinks:load", function() {
  $('.owl-carousel').owlCarousel({
      loop:true,
      margin:10,
      nav:true,
      items: 4
  });
});
```

The plugin is responsive now but the layout is broken.
[Screenshot](http://imgur.com/a/hHwVv)

**Comment by CracyCrazz** [comment]
Hey, I'am sorry but I don't know Turbolinks and not really familiar with rails at all.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by breiko83** [comment]
Hi @CracyCrazz, you are right sorry about that. 

This is a link to a working example: [https://owlcarousel.herokuapp.com/](https://owlcarousel.herokuapp.com/)

**Comment by breiko83** [comment]
Hi @CracyCrazz, you are right sorry about that.

This is a link to a working example: [https://owlcarousel.herokuapp.com/](https://owlcarousel.herokuapp.com/)

**Comment by FugiOnline** [comment]
@breiko83 I am having this exact same issue and cannot get it to work properly. 

Did you ever find a working solution?

**Comment by breiko83** [comment]
Hi @FugiOnline,
the workaround I found was to destroy the carousel at turbolinks:before-cache and re-initialize it at turbolinks:load.

Try the following:

    document.addEventListener("turbolinks:load", function() {
      $('.owl-carousel').owlCarousel({
          loop:true,
          nav:true,
          items: 4
      });
    });

    document.addEventListener("turbolinks:before-cache", function() {
      $('.owl-carousel').owlCarousel('destroy');
    });

I have also updated the example here: [https://owlcarousel.herokuapp.com/](https://owlcarousel.herokuapp.com/)

**Comment by FugiOnline** [comment]
Yes! @breiko83 this is awesome, you just fixed my problem! Confirmed working. Triggers me to learn more about Turbolinks!

**Comment by mtomov** [comment]
Thank you so much for the solution @breiko83!

**Comment by zoggxxx** [comment]
Yessssssssssssss

**Comment by bettingweekly** [comment]
Legend, works for me.

**Comment by mining016** [comment]
> turbolinks:before-cach

Thank you , it works
