### ISSUE TITLE
Icon gets duplicated

### ISSUE THREAD

**Issue by Louis-MarieMatthews** [OwlCarousel2/OwlCarousel2#1745]
Hello all,

Apparently, the use of an infinity-loop combined with boostrap causes one icon of owl-carousel to get duplicated.
I reproduced the bug with the least possible amount of code possible [there](http://shift-two.alwaysdata.net/wordpress/owlcarousel/).
If you press the right slider once you should see the cloned owl item.
This is because the javascript sets the size of the carousel (`.owl-stage`) to `width: 3047px;` (in my case), which is not large enough to accommodate the last icon. As a result, it falls on the second line.
It looks like the bug is directly caused by the `.row` class from bootstrap. When I remove the `div` with that class, it works fine.

**Comment by daviddeutsch** [comment]
That page has no carousel.

Please reopen this with a new example using a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!
