### ISSUE TITLE
auto play stops working when changing browser's tab

### ISSUE THREAD

**Issue by sanderserwin** [OwlCarousel2/OwlCarousel2#1748]
Hi, i'd like to report an issue where the autoPlay stops working when you're changing tabs. Here's how to reproduce the issue:

1. Open Owl Demo: https://owlcarousel2.github.io/OwlCarousel2/demos/autoplay.html
2. See the carousel moves automatically
3. Open new tab and move to that tab about 1-2 sec
4. When you're back to the owl demo, the auto play won't work unless you use mouse drag

i'd like to know if there's any workaround for this issue?
note: this issue is replicable using google chrome v56.0.2924.87

thanks

**Comment by ojorma** [comment]
in my case autoplay doesn't work at all.
in the older version it works fine, in this new release now doesnt work but when you click on the owl-pagination . sample here. http://www.stephensellaengineering.com/

**Comment by khaliljan** [comment]
The same problem with mine. I use v2.2.0 Owl Carousel (http://codepen.io/gjk/pen/BpyYoj).
I tried to find solution, and it seems it's a BIG issue. still wonder why it has not solution yet!

**Comment by ocvninfo** [comment]
it's really a BIG issue. Hope it will be fixed asap.

**Comment by sanderserwin** [comment]
found a workaround for the moment. u can use this:
$(window).onfocus(function(){
owl.trigger('play.owl.autoplay',[1000]);
});

not the best workaround as it will be triggered everytime you're changing tabs, but works for the meantime

**Comment by ocvninfo** [comment]
@sanderserwin i tried. But it's not working :(

**Comment by pascalporedda** [comment]
There is already an issue for this. See #1727
