### ISSUE TITLE
Scroll pages with nav arrows

### ISSUE THREAD

**Issue by matzexcom** [OwlCarousel2/OwlCarousel2#1749]
I hope it is not a duplicate or already implemented but it would be helpful to have an option to scroll pages instead of single items with the nav arrows (from nav:true) like it is with dots.

**Comment by ohepworthbell** [comment]
Does the [slideBy](http://owlcarousel2.github.io/OwlCarousel2/docs/api-options.html#slideby) option not help with this?

**Comment by matzexcom** [comment]
That's completely true, I somehow missed that option thank you very much.
