### ISSUE TITLE
Passive event listeners, chrome and touch events

### ISSUE THREAD

**Issue by ohepworthbell** [OwlCarousel2/OwlCarousel2#1750]
Recent releases of Chrome default touch events to `{passive: true}`, which overrides and disables `preventDefault()` calls. OwlCarousel may need to implement a test to check for browser support for passive events and disable it when necessary (i.e. `el.addEventListener('touchmove', functionName), {passive: false}}`)

To replicate:
* Use any version of OwlCarousel (e.g. [fiddle](https://jsfiddle.net/Lpvd6vef/) )
* Open in Chrome and open dev console.
* Use either a touch-device or emulate a touch device in the device manager
* Swipe left/right on the carousel
* Check the console log - you will see a warning "_Unable to preventDefault inside passive event listener due to target being treated as passive._" and preventDefault will similarly be ignored.

**Comment by AzureusSme** [comment]
Any PR?

**Comment by pascalporedda** [comment]
Feel free to submit a PR for this.

**Comment by mamarmite** [comment]
Thanks @vs7 your fix work in my project for chrome.
Tested it as an scss addon, though, not as part of the _core.scss.
