### ISSUE TITLE
Disable dots navigation, but not hide them

### ISSUE THREAD

**Issue by hikasho** [OwlCarousel2/OwlCarousel2#1751]
Hello everyone,

I was wondering if its possible to, by NOT hiding the dots, to disable the navigation from it. Right now, users can go to item 3, when they click on dot #3.  I would like it that the user can't click on the dot (and navigate with only the buttons), while not hiding the dots. I would still like the user to see how many items/dots there total are.

**Comment by daviddeutsch** [comment]
That's not an Issue. Please use StackOverflow for questions like this.
