### ISSUE TITLE
Slide by 'page' not working when touch/mouse dragging

### ISSUE THREAD

**Issue by thomasdom** [OwlCarousel2/OwlCarousel2#1755]
I've setup my carousel so that my carousel slides by "page" when clicking on navigation arrows, by setting this option: slideBy: 'page'. I expected the carousel to also slide by page when touch/mouse dragging, but it only slide my items 1 by 1.

What is the right configuration to make it slide by page on touch/mouse dragging ?

Here is a jsfiddle to demonstrate this : https://jsfiddle.net/kqfLxpw0/2/

**Comment by Boooober** [comment]
@thomasdom, hello.
If you are still interested in the solution, take a look at this jsfiddle:
https://jsfiddle.net/2ay4chvb/

**Comment by thomasdom** [comment]
Nice work ! Wéve changed the layout of our slider components short after I opened this issue, but this could be useful to the community ! Thank you :)
