### ISSUE TITLE
a lot of owl-items produced

### ISSUE THREAD

**Issue by shalakhin** [OwlCarousel2/OwlCarousel2#1757]
I have only 5 items in my owl carousel but I see so many of them being generated.

Example is here: http://megadiscounts.club/

![screenshot 2017-02-25 15 55 29](https://cloud.githubusercontent.com/assets/433637/23331672/04ae1a4a-fb73-11e6-87ca-7c8afc8f0622.png)

**Comment by daviddeutsch** [comment]
Thoase are the item clones OwlCarousel generates for smooth sliding.
