### ISSUE TITLE
How to make the central image is larger than the other in Owl Carousel?

### ISSUE THREAD

**Issue by NekoStudio** [OwlCarousel2/OwlCarousel2#1763]
please can you tell me how to get Owl Carousel so that it looks like this:
https://i.stack.imgur.com/j43ea.jpg
I tried but it does not work.

Thank you very much in advance.

Here is the working file will be very grateful for the help.

https://jsfiddle.net/BakuTorid/pqbrtk5p/

**Comment by daviddeutsch** [comment]
That's not an Issue. Please use StackOverflow for questions like this.
