### ISSUE TITLE
Align center for the elements with lower dimension

### ISSUE THREAD

**Issue by abdfahim** [OwlCarousel2/OwlCarousel2#1765]
If I have 10 elements with different height, the carousel takes the largest height, which makes perfect sense.

However, is it possible that the smaller images appear in the center (both horizontally and vertically)?

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
