### ISSUE TITLE
Allow package file to expose CSS

### ISSUE THREAD

**Issue by keefyhub** [OwlCarousel2/OwlCarousel2#1767]
Suggest adding `"style": "./dist/assets/owl.carousel.css",` to `package.json`

By adding this field, npm modules like [sass-module-importer](https://www.npmjs.com/package/sass-module-importer) or [npm-css](https://www.npmjs.com/package/npm-css) can import the CSS from the Owl Carousel `npm_modules` folder.

EG.
`@import 'owl-carousel';`

NOTE - this is not standardised, but is becoming more widely used in node modules.

**Comment by pascalporedda** [comment]
Feel free to submit a pull request for this.
