### ISSUE TITLE
navContainer no longer working AND destroy() leaves behind owl stage div.

### ISSUE THREAD

**Issue by r3wt** [OwlCarousel2/OwlCarousel2#1768]
since the upgrade a few days ago:

1. navContainer no longer works; worked previously.
2. when calling the destroy method of owl, an `.owl-stage` div is left behind. 

Environment is angular but i don't think it really matters.

**Comment by r3wt** [comment]
# RE: navContainer 

Relevant File: https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/src/js/owl.navigation.js

alright, so in plugin's init function(**Line 155**), the navContainer is stored as a control, called `this._controls.$relative()`:

**Plugin.init():**
```js 
this._controls.$relative = (settings.navContainer ? $(settings.navContainer)
: $('<div>').addClass(settings.navContainerClass).appendTo(this.$element)).addClass('disabled');
```

then it is removed in the plugin's destroy method (**Line 209-211**) as shown:

**Plugin.destroy()**

```js
for (control in this._controls) {
	this._controls[control].remove();
}
```

Obviously this was lazy programming. If the user is supplying their own elements, we should not destroy them. we should instead just remove the inserted controls into the custom element. 

@pascalporedda If i make this PR, how soon can you land it? It's currently making me look very bad.

**Comment by r3wt** [comment]
# Re: destroy() method leaving behind `.owl-stage` div.

Relevant file: https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/src/js/owl.carousel.js#L1391

As you can see here, stage is never removed. it obviously should be, right? another super easy PR. please let me know as soon as you can, i am very anxious to see this land. I need it bad.

**Comment by r3wt** [comment]
@daviddeutsch @pascalporedda please respond asap, thank you ( not to be rude, i just need to resolve this so i can mark the internal tracker for our project that this is upstream)

**Comment by pascalporedda** [comment]
Do you got any example that shows this broken state? I would be willing to merge your PR as soon as I can approve this.

**Comment by r3wt** [comment]
Read the code of each patch, sode effects withoit these two changes should be quite obvious.

**Comment by pascalporedda** [comment]
Merged.
