### ISSUE TITLE
when items=1 then div width=100%  Right seam problem

### ISSUE THREAD

**Issue by mbdmt** [OwlCarousel2/OwlCarousel2#1774]
If the page no scrollbar then the first time into the page, the right will see the next picture about 17px
Is equal to a scroll wide.
if BODY tag use overflow: hidden ,It is normal.
In addition, the page have scrollbar it is also normal.
Will be automatically corrected when resize.
problem image demo
http://imgur.com/8TJxMGV

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example we can reopen this issue.
