### ISSUE TITLE
Multiple Carousel in same page

### ISSUE THREAD

**Issue by MahenAbeyrathna** [OwlCarousel2/OwlCarousel2#1776]
I need to create multiple carousel in same page,
but one carousel works fine and other shows all images 
i have seen options such as add id instead of class, and more.
i applied most of them but couldn't solve the problem
this is my code,plz help me guys
https://jsfiddle.net/MahenAbeyrathna/4mdvoafn/7/

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
