### ISSUE TITLE
mouse scroll trigger delay

### ISSUE THREAD

**Issue by MyPC8MyBrain** [OwlCarousel2/OwlCarousel2#1780]
this is a preference issue not a bug,
maybe few others out there share the same issue im experiencing,
the only issue i have with Owl2 is hijacking mouse,
is there a way to delay this trigger?

i have Owl in the middle of my page with infinity mouse scroll,
it is impossible t scroll up or down the page now without Owl catching my mouse and breaks the scroll,
is there a way to delay this behavior to allow a mouse to scroll up or down the page? 

TIA
Chris

**Comment by pascalporedda** [comment]
This is not an implemented feature. I see the use for this, but there are other things we gotta do beforehand. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
