### ISSUE TITLE
bootstrap popover

### ISSUE THREAD

**Issue by Showcase-Joz** [OwlCarousel2/OwlCarousel2#1782]
i've added owl as a client logo slider on [http://sabsafeguarding.uk/#clients](http://sabsafeguarding.uk/#clients) which works as well as expected. Though, as i've used bootstraps popover element on these logo's to give the user a little more info.

hovering over a logo should activate the popover js on bootstrap.
i can only get this to work if i **change** the following owl css

`.owl-carousel .owl-stage-outer {
    overflow: visible;
}`

from hidden to **visible**

i've looked at a callback, but can't seem to find a solution that doesn't butcher the owl css

**Comment by pascalporedda** [comment]
You can feel free to override this on your site in your custom css. But this is not relevent for the main project.

**Comment by Showcase-Joz** [comment]
Yes, I am aware that it can be overridden through css but this creates further issues pertaining to the overflow of the child elements. 

Therefore I was trying to suggest owl carousel 2 won't work effectively in a Bootstrap scenario that includes popover elements.

**Comment by Psytanium** [comment]
This is a serious problem with Owl Carousel. I tried all day long to work around this issue without success

**Comment by coler-j** [comment]
@Psytanium and @Showcase-Joz did you find a solution to this?

**Comment by Psytanium** [comment]
@coler-j no i didnt find a solution. I ended using a small tooltip slidi g to the left. Still inside the owl container

**Comment by Snakespeare** [comment]
this should do the job, stick this in your popover <code>data-container="body"</code>

Yes - i am that good! 

It's Voodoo Magic. 

Have fun, thank me later!

**Comment by Psytanium** [comment]
@Snakespeare where should i stick this nice short solution ? I tried to put it many places around the code. thanks :)

**Comment by coler-j** [comment]
No sorry it didn't work. Turn's out my dev used Owl Carousel 1 though so I think I am SOL for now. Too much work to migrate now...
