### ISSUE TITLE
Owl not initializing when including jQuery in HTML Head

### ISSUE THREAD

**Issue by qbert1984** [OwlCarousel2/OwlCarousel2#1788]
Hi!

It seems that owl carousel is not initializing if jQuery is included in the HTML header (including in body is working fine). However, I need jQuery in the header for building some angular directives which use jQuery UI components. Is there a way to initialize owl anyway?

Thanks a lot,
q

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
