### ISSUE TITLE
Slides are stacked on each other

### ISSUE THREAD

**Issue by vstrelianyi** [OwlCarousel2/OwlCarousel2#1789]
Hi!

When creating a simple owl carousel module (using owl carousel2-2.2.1) I have faced the following problem - carousel items are not in one row, but are rendered under each other. 
Meanwhile on version owl.carousel.2.0.0-beta.2.4 everything works fine for me.

Regards, Viktor.

**Comment by keefyhub** [comment]
Looks like older versions on Owl Carousel added the class `.owl-carousel` to the element automatically, not sure why it was removed but in the [README](https://github.com/OwlCarousel2/OwlCarousel2#usage) it states:

> Wrap your items (`div`, `a`, `img`, `span`, `li` etc.) with a container element (`div`, `ul` etc.). Only the class `owl-carousel` is mandatory to apply proper styles:
> ```html
> <div class="owl-carousel owl-theme">
>   <div> Your Content </div>
>   <div> Your Content </div>
>   <div> Your Content </div>
>   <div> Your Content </div>
>   <div> Your Content </div>
>   <div> Your Content </div>
>   <div> Your Content </div>
> </div>
> ```
> **NOTE:** The `owl-theme` class is optional, but without it, you will need to style navigation features on your own.

**Comment by vstrelianyi** [comment]
Thx for explanation.
