### ISSUE TITLE
Console warning when using touch events

### ISSUE THREAD

**Issue by keefyhub** [OwlCarousel2/OwlCarousel2#1790]
Example: [link](https://owlcarousel2.github.io/OwlCarousel2/demos/basic.html)
Open dev tools and toggle device toolbar, activate a touch event by dragging the carousel item. Observe the following console warning:
`Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080`

Looks like a change in touch event listeners in Chrome - https://developers.google.com/web/updates/2017/01/scrolling-intervention

Possible solution at the bottom of the article:
`Developers should apply the touch-action CSS property on elements where scrolling and zooming should be disabled to notify the browser before any touch events occur.`

Adding:
```
.owl-carousel {
  touch-action: none;
}
```
to the CSS seems to solve the warning, but I am not sure what effect this property has.

[link to CSS property summary](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action)

**Comment by AzureusSme** [comment]
+1

**Comment by keefyhub** [comment]
I have just found out that adding`touch-action: none;` stops any scrolling in Chrome, so I tried each property one by one and `touch-action: manipulation;` is the only one that allowed gestures, without causing the error.

> manipulation
> Enable panning and pinch zoom gestures, but disable additional non-standard gestures such as double-tap to zoom. Disabling double-tap to zoom removes the need for browsers to delay the generation of click events when the user taps the screen. This is an alias for "pan-x pan-y pinch-zoom" (which, for compatibility, is itself still valid).

**Comment by panteleywhat** [comment]
+

**Comment by keefyhub** [comment]
Still an issue, waiting for an "approved for development" tag on the issue to raise the PR

**Comment by daviddeutsch** [comment]
@keefyhub I went ahead and put in the change myself, didn't want to bother you further. Thank you for your contribution!

**Comment by mckenzieja** [comment]
Can confirm. adding `touch-action: manipulation;` to `.owl-carousel` resolved the console warning.

**Comment by 1naveengiri** [comment]
Working fine, Thanks @keefyhub

**Comment by samdawit** [comment]
`.owl-carousel .owl-item {
  position: relative;
  min-height: 1px;
  float: left;
  -webkit-backface-visibility: hidden;
  -webkit-tap-highlight-color: transparent;
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}`
