### ISSUE TITLE
How to get responsive?

### ISSUE THREAD

**Issue by aritabacan** [OwlCarousel2/OwlCarousel2#1791]
How to activate the plugin is responsive carousel. ONLY WHEN size less than 1024px width. But if more than 1024px then inactive. Example i use

            
```
$(window).bind("load resize", function() {
    var width = $(window).width();
    if (width <= 1024) {
        $(".product-item").addClass("owl-carousel");
    } else {
        $(".product-item").removeClass("owl-carousel");
    }
});
```

https://jsfiddle.net/zgnkn3hw/

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
