### ISSUE TITLE
How to get number of visible items (slides)

### ISSUE THREAD

**Issue by demogorgorn** [OwlCarousel2/OwlCarousel2#1816]
How to get number of visible items (slides) when they are set for different resolutions?

Thanks!

**Comment by keefyhub** [comment]
Owl Carousel adds a `.active` class to all active items, so you could do something like

`console.log($('.owl-item.active').length);`

Only issue I can see is if you are using `center` as it might show more than the expected amount on screen, even though they are not considered "active"

**Comment by demogorgorn** [comment]
Thank you! Works fine!
