### ISSUE TITLE
startPosition option does not change startPosition

### ISSUE THREAD

**Issue by Errortype520** [OwlCarousel2/OwlCarousel2#182]
Trying to change the start position for my slides, and no matter what I use the slides always start at 0:

owl.owlCarousel({
            loop: true,
            nav: false,
            dots: false,
            startPosition: -2,
            responsive: {
                0: {
                    startPosition: 0,
                    items: 1
                },
                400: {
                    startPosition: 0,
                    items: 2
                },
                520: {
                    startPosition: -1,
                    items: 3
                },
                768: {
                    startPosition: -1,
                    items: 4
                },
                992: {
                    startPosition: -2,
                    items: 5
                }
            }
        });

**Comment by camilonova** [comment]
@joeyjoejoejr can you?
