### ISSUE TITLE
Carousel appearing after toggling inspect element

### ISSUE THREAD

**Issue by iShubhamRaj** [OwlCarousel2/OwlCarousel2#1849]
Hi,

URL: http://exploreyourcities.com/location/pen/

In Google Chrome, when I visit this page, I can't see the carousel loaded at first, only the nav buttons and the wrapper box. When I open inspect element, carousel shows up and works fine.
If I reload the page while inspect element is open, same thing happens. Carousel isn't loaded. When I close inspect element, it appears. I tried looking for problem, and it comes down to the widths of _owl-stage_ and _owl-item_

Also, if I put the same code of carousel above the 4 boxes above it, carousel loads fine. Those 4 boxes are calling out to Bootstrap.min.js from CDN. I suppose that is causing the problem here?
Please someone try it out once.

Thanks in advance!

**Comment by iShubhamRaj** [comment]
Solved it.
This was very very weird issue.
The boxes above carousel on the above-mentioned page has a class of **.post-new-masonry** which had a **float:none** to it. After trying out many different things, I discovered this issue and I had the **float:none** removed and viola!
I don't know how that CSS was affecting the carousel, if anyone had similar issue, please spread the knowledge! Just curious. :)

**Comment by Junaidshaikh34** [comment]
I am having a similar issue, owl carousel is visible only after toggling F12 and then some weird thing is happening that it gets zoomed  every time I toggle F12.
I am using noble UI theme with Angular 11

**Comment by Junaidshaikh34** [comment]
> I am having a similar issue, owl carousel is visible only after toggling F12 and then some weird thing is happening that it gets zoomed every time I toggle F12. I am using noble UI theme with Angular 11

problem solved, it was affected by the flex properties of its parent's container

**Comment by Marwannmahmoudd** [comment]
How you solve it ?
