### ISSUE TITLE
AutoplayHoverPause BUG

### ISSUE THREAD

**Issue by pxwee5** [OwlCarousel2/OwlCarousel2#1860]
To replicate:
1. Setup
```
$('.owl-carousel').owlCarousel({
      items: 1,
      loop: true,
      autoplay: true,
      autoplayTimeout: 1000,
      autoplayHoverPause: true,
      nav: true,
      navText: '',
    });
```

2. Hover when carousel is autoplaying.

3. Hover away from carousel

4. You will see that the carousel stopped autoplaying completely. It should resume autoplaying after mouse out.

**Comment by sophiekovalevsky** [comment]
The same is happening for me. I am using the latest version of the library.

**Comment by daviddeutsch** [comment]
See #1942
