### ISSUE TITLE
autoplay will be force start even in the pause state

### ISSUE THREAD

**Issue by billyyip** [OwlCarousel2/OwlCarousel2#1862]
after press pause button to pause autoplay state, but when I resize the page or press previous, next or nav dots button, the carousel will force to start autoplay immediately, please help to fix it thanks.

**Comment by daviddeutsch** [comment]
See #1942

**Comment by sagemike** [comment]
This is still an issue

**Comment by pascalporedda** [comment]
@sagemike Got any live example for this?
