### ISSUE TITLE
Autowidth 0 on fisrt page load

### ISSUE THREAD

**Issue by Soph87** [OwlCarousel2/OwlCarousel2#1863]
Hi!

So here's my issue : I have two sliders in the same page, one has autowidth. On the fisrt load of the page, the width doesn't seem to be calculated but if I refresh it, it works. 
You can check the page out here : http://92.222.93.153
Does anyone know what I could do ?

Thanks!

**Comment by keefyhub** [comment]
you could try wrapping it in a `$(document).on('ready' function(){ ... });`

It might be to do with the images not fully loading before the carousel initialises. Then on the second load, the images are cached so the width is calculated correctly.

**Comment by Soph87** [comment]
Thanks for your reply!
What exactly should I wrap in the function? 
Do you think that my images may be too heavy?

**Comment by keefyhub** [comment]
so wrap your owl carousel stuff inside like this

```
$(document).on('ready' function(){
  $('.your-carousel').owlCarousel({
    ...
  });
});
```
You could try compressing the images, but I think the issue is that the carousel is activating before the images are ready, and the images are setting the size.

You could also set the width on the `.lien-owl` but Im not sure how that would work responsively

**Comment by Soph87** [comment]
I tried wrapping the owl carousel stuff like you said, but I must have done it the wrong way, because the sliders are not loading at all. I have SyntaxError: missing ) after argument list
Here's my code : 

`$(document).on('ready' function(){
	$('#carousel_dossiers').owlCarousel({
			items:1,
			dots: true,
			nav:false
	});

	$('#carousel_critiques').owlCarousel({
		nav:true,
		dots:false,
		autoWidth:true,
		loop:true,
		center:true,
		navText:["&#10096;" , "&#x2771;"]
	});
});`

**Comment by Soph87** [comment]
I tried what you suggested but it still didn't work, so I replaced it with `$( document ).ready(function(){})`
and it worked but I still have the same issue with the width. 
I also tried giving a fixed width to the `.lien-owl`, didn't work either.
I'm getting a bit desperate here! ><'
Do you have another suggestion?

**Comment by keefyhub** [comment]
you could try `$(window).on('load', function() {...});` as the ready event fires when the DOM is loaded, whereas load is after the page has finished loading.

You might get some issues where is flashes un-styled, then corrects itself after Owl Carousel loads. But you could use some CSS to stop that happening.

**Comment by Soph87** [comment]
It seems to be working! Thank you so much!! :)
