### ISSUE TITLE
Slider breaking on first load

### ISSUE THREAD

**Issue by Pantone337C** [OwlCarousel2/OwlCarousel2#1880]
Hi there !

My slider doesn't seem to work on first load and refreshing the page breaks it completely. It does work if you back to previous page and back to it again. I'm using autoplay, center & auto width.
You should see the problem on [this page](http://www.juliettelatil.design/projects_pages/packaging_limite.html) of my portfolio (but it also happens on every other project page of my site). 
I'm fairly new to html, css and jquery so it could very well be my mistake. Any help would be appreciated :)
Thanks in advance !

**Comment by keefyhub** [comment]
Its possible that the images aren't loaded before the carousel is initialised.  You could try `$(window).on('load', function() {...});` instead of document ready.

Also looks like you are loading 2 versions of jQuery. If its not needed, remove your local version

**Comment by Pantone337C** [comment]
It seems to work ! Thank you so much for your help & advice !
