### ISSUE TITLE
when i switch the page, aotuplay is not working....

### ISSUE THREAD

**Issue by adevin** [OwlCarousel2/OwlCarousel2#1885]
my config:
`    $(function() {
        $('.owl-carousel').owlCarousel({
            items: 1,
            loop: true,
            rewind: true,
            autoplay: true,
            autoplayTimeout: 3000
        });
    });`

when i switch the page in the blower , aotuplay is stop.. and i found the demo in official website is same..

**Comment by zdarovka** [comment]
Same problem

**Comment by daviddeutsch** [comment]
See #1942
