### ISSUE TITLE
Paging Issue on Active dot

### ISSUE THREAD

**Issue by NunoBentes** [OwlCarousel2/OwlCarousel2#189]
Hi 

I found a small bug on paging dots. For example let´s say that you have five items, but on the carousel you want to show 4 by default. The paging shows 2 dots. Then if you click on the second dot, this scrolls to the last "group" but the dot don´t stay active.

Amazing plugin, by the way. :)

**Comment by sanya-arora** [comment]
Is this issue resolved or not yet?
