### ISSUE TITLE
Slide specific CSS animations/transitions

### ISSUE THREAD

**Issue by ne0nlight** [OwlCarousel2/OwlCarousel2#1907]
Hey guys!

How are the owl slides revealed individually? 

I ask this because I am trying to implement moving sections via css animations on specific slides (be it buttons or graphics or anything), and I was going to initiate these by using something like:

```
if ($(element).is(":visible")) {  //element being the particular slide
    //do animation when slide is visible, have it reset when slide goes away
};
```
Or
```
if ($(element).css('display')==='block') { //element being the particular slide
    //do animation when slide is visible, have it reset when slide goes away
}
```

However I am not seeing these really being affected while all the changing is going on. Any ideas or better ways to implement what I'm thinking??

Thanks!

**Comment by keefyhub** [comment]
Do you mean when a slide is active the internal elements animate in? You could add a class to the element, then target it like this

```
.your-element {
  opacity: 0;
  transition: opacity .3s;
}

.owl-item.active .your-element {
  opacity: 1;
}
```

**Comment by ne0nlight** [comment]
Thanks for the assistance @keefyhub

That is exactly what I am looking for, however I notice that it isn't adding the active class to the active slides. The only variance when slides are changing is a quick add of `.owl-fadeUp-out` and `.owl-fadeUp-in` for the respective slides, which lasts a second and then all slides are identical in terms of just being labeled `owl-item` and nothing more during the length of each slide. Any ideas??

**Comment by keefyhub** [comment]
Ive found some old documentation for v1 - http://www.landmarkmlp.com/js-plugin/owl.carousel/#customizing

You'd need to add `addClassActive: true,` as an option.

If you can, Id recommend upgrading to v2.

**Comment by ne0nlight** [comment]
That was plenty enough, now that I have the active class, I can get to work. Thanks so much! 

I wasn't aware how out of date the slideshow was either, I will definitely be looking into v2 asap. Thanks again!
