### ISSUE TITLE
autoplayHoverPause won't resume on mouseleave

### ISSUE THREAD

**Issue by esamo** [OwlCarousel2/OwlCarousel2#1911]
Hey.

In the 2.2.1. version this bug is still present.
Steps to reproduce:
1. Wait for carousel to autoplay.
2. Hover mouse over carousel to stop it.
3. Move the mouse cursor away from the carousel.
4. Autoplay does NOT resume.

Workaround
```
"mouseover.owl.autoplay": a.proxy(function () {
    this._core.settings.autoplayHoverPause && this._core.is('rotating') && this.stop()
}, this),
"mouseleave.owl.autoplay": a.proxy(function () {
    this._core.settings.autoplayHoverPause && !this._core.is('rotating') && this._core.settings.autoplay && this.play()
}, this)
```

My carousel
```
$('.featured .owl-carousel').owlCarousel({
    items: 4,
    margin: 20,
    loop: true,
    nav: true,
    dots: false,
    autoplay: true,
    autoplayTimeout: 3500,
    autoplaySpeed: 800,
    autoplayHoverPause: true,
    navText: ['<i class="fa fa-angle-left"></i>', '<i class="fa fa-angle-right"></i>']
});
```

Regards & respect

**Comment by daviddeutsch** [comment]
See #1942

**Comment by suatsuphi** [comment]
<pre><code>
$(document).ready(function () {
    var owl = $('.owl-carousel');
    owl.on('mouseleave', function (e) {
        var data = $(e.currentTarget).data('owl.carousel');
        //console.log('autoplay:' + data.settings.autoplay + ' autoplayTimeout' + data.settings.autoplayTimeout);
        if (data.settings.autoplay) {
            $(e.currentTarget).trigger('stop.owl.autoplay');
            $(e.currentTarget).trigger('play.owl.autoplay', data.settings.autoplayTimeout);
            //console.log('It is working autoplay:' + data.settings.autoplay + ' autoplayTimeout' + data.settings.autoplayTimeout);
        }
    });
});
</code></pre>
