### ISSUE TITLE
Github Pages: Page build failure

### ISSUE THREAD

**Issue by dpmango** [OwlCarousel2/OwlCarousel2#1913]
Im facing the issue on my projects because of fetching owl from bower into /src/components folder
For a long time a have no idea why this happens and only complete removal of package helped

But now github is showing exact thing why build is failing.

The message goes below

> The page build failed for the `master` branch with the following error:
> 
> The variable `{{!-- ## owl.lazyload.js LazyLoad require `class="owl-lazy"` and link to image inside data: data-src="url_to_img" or/and data-src-retina="url_to_highres_img". There is also option to load images into background but this needs to be tested. [See demo](/demos/demo.html) Usage: ``` $('.owl-carousel').owlCarousel({ lazyLoad:true }` on line 35 in `src/components/owl.carousel/docs_src/templates/pages/docs/dev-buildin-plugins.hbs` was not properly closed with `}}`. For more information, see https://help.github.com/articles/page-build-failed-tag-not-properly-terminated/.

**Comment by sebalaini** [comment]
same here, the carousel work perfect but failed to create a github pages

**Comment by RuslanBakhar** [comment]
the same problem,  how solve it?

**Comment by pascalporedda** [comment]
I can't actually prove this, build is working fine for me.

**Comment by owlran** [comment]
Facing the same issue. any update about this ?

**Comment by Manimall** [comment]
any news about it? Can we ignore the file with this problem somehow?

**Comment by abdulrahmanmokhlef** [comment]
I've the same proplem!

**Comment by kidqn** [comment]
Try to delete all unnecessary test files in your owlcarousel library, just remain all included files

**Comment by AcmeStandUp** [comment]
Same problem with me too. What are the unnecessary test files here?

**Comment by AcmeStandUp** [comment]
> I can't actually prove this, build is working fine for me. If you encounter any issues, then please provide me a step by step guide to reproduce this error.

Just try to import a bootstrap webpage and publish it using github-pages. It throws an error as mentioned by OP.

**Comment by raulpetruta** [comment]
@kidqn 
Thank you!!!
It's working!!
30 minute I tried to figure it out. Keep just what are you using in your projects.

**Comment by JohnLing73** [comment]
@kidqn @petrutaraul 
Excuse me, what's "unnecessary test files in your owlcarousel library" means and where can I find and delete it?

**Comment by MahnoorSaeed** [comment]
Any step by Step update?

**Comment by pedrohenriquebl** [comment]
@MahnoorSaeed 
I was able to fix this issue by deleting the entire  **/OwlCarousel2-2.3.4/test** folder and the **/OwlCarousel2-2.3.4/docs_src/templates/pages/docs/dev-buildin-plugins.hbs** file

**Comment by kethellynWend** [comment]
> @MahnoorSaeed Consegui corrigir esse problema excluindo toda a pasta **/OwlCarousel2-2.3.4/test** e o arquivo **/OwlCarousel2-2.3.4/docs_src/templates/pages/docs/dev-buildin-plugins.hbs**

Realmente funciona

**Comment by aybarsumur** [comment]
deleting 2 files solved my problem too. Thanks.
