### ISSUE TITLE
2 owl sliders which depends of each other

### ISSUE THREAD

**Issue by Natteke** [OwlCarousel2/OwlCarousel2#1930]
Hello guys!

Could someone suggest me some idea how to make 2 sliders at one page
which will work together?

So for example if i slide "slider 1", "slider 2" also should be moved with same speed as "slider 1" etc.

**Comment by keefyhub** [comment]
Ive done it before by using `to.owl.carousel` event and `URLhashListener` option
 https://owlcarousel2.github.io/OwlCarousel2/demos/urlhashnav.html

```
$('.js-carousel').on('click', '.owl-prev, .owl-next', function() {
    var current = $('.js-carousel').find('.active img').attr('data-hash');
    $('.js-navigation-carousel').trigger('to.owl.carousel', current);
  });
```

So this would listen for a change on the main carousel, then trigger the 2nd carousel to change to the slide with the same data-hash value.

I guess you could use the same logic to do the reverse, but I did it by adding the `URLhashListener` to the first carousel so if you clicked an item in the second carousel, it would move the first carousel to that item.

If you want to see it working let me know and Ill send you the link

**Comment by andrea-86** [comment]
in my opinion it's all much simpler. Just stop autoplay on the second carousel, and trigger next/prev event when click on the next/prev button of first carousel and/or bind it on next/prev event of first carousel if it has autoplay
