### ISSUE TITLE
Autoplay stop and play trigger not working

### ISSUE THREAD

**Issue by docdrue** [OwlCarousel2/OwlCarousel2#1935]
USing new version from site 
            var owl = $('.owl-carousel.slider-main');

            owl.owlCarousel({
                loop: true,
                mouseDrag: false,
                margin: 0,
                //animateOut: 'slideOutDown',
                //animateIn: 'zoomIn',
                nav: true,
                navText: [],
                autoHeight:true,
                smartSpeed: 550,
                autoplay: true,
                autoplayTimeout: 500,
                autoplayHoverPause: false,
});
            setTimeout(function() {
                owl.trigger('stop.owl.autoplay');
                console.log("stop");

                setTimeout(function() {
                    owl.trigger('play.owl.autoplay');
                    console.log('play');
                }, 6000);
            }, 6000);
i see in console that events are going, but autoplay don't stop or play
trying to use but see thet stop.autoplay don't worck(((

**Comment by daviddeutsch** [comment]
See #1942
