### ISSUE TITLE
Autoplay reactivates after interaction with slider but then stop button no longer works

### ISSUE THREAD

**Issue by laura-richer** [OwlCarousel2/OwlCarousel2#1948]
I am trying to get play/stop buttons working on my carousel but the issue I am having is the stop button only works once. The same issue is happening on the OWL carousel demo page too... https://owlcarousel2.github.io/OwlCarousel2/demos/autoplay.html

To recreate the issue...
Go to https://owlcarousel2.github.io/OwlCarousel2/demos/autoplay.html
1 ) Press stop
2 ) Interact with the slider... swipe/use dots to navigate (observe autoplay gets reactivated)
3) Try to stop slider again, observe stop button not stopping the slider second time round.

Anyone got any ideas??

**Comment by tdecaluwe** [comment]
I opened a pull request to solve I bunch of issues with the autoplay plugin. I verified it resolves this one as well. If you need a hotfix you can just include the file `src/js/owl.autoplay.js` from my branch in a `<script>` after including the OwlCarousel code.

**Comment by laura-richer** [comment]
Looks to be working perfectly now. Thank you :)
