### ISSUE TITLE
Not an issue but what will happen to OwlCarusel2?

### ISSUE THREAD

**Issue by black-byte** [OwlCarousel2/OwlCarousel2#1955]
Hello,
How OwlCarusel2 will be updated ? There will be total new version of it OwlCarusel3?
Are we going to be able to move from current version to new one without trouble ?
Is there any timeline when it will be avalible ? And are there any plans what will exactly change ?

**Comment by liquidvisual** [comment]
+1 Would like to know this too

**Comment by Quinter** [comment]
See here for roadmap: https://github.com/OwlCarousel2/OwlCarousel2/issues/1756

**Comment by pascalporedda** [comment]
^
