### ISSUE TITLE
option dotsEach not responsive

### ISSUE THREAD

**Issue by arkoe** [OwlCarousel2/OwlCarousel2#1960]
Using the following code still gives me 10 dots when having 10 images in my slider. Expected result is 2 dots (since 5 per dot).

	$("#slider-wrapper").owlCarousel({
		items: 5,
		margin: 10,
		loop: true,
		center: true,
		autoplay: true,
		nav: false,
		dotsEach: 5,
		dots: true
	});

Slider itself is fully functioning and there are no JavaScript errors present.

**Comment by keefyhub** [comment]
Seems to be any issue with `center: true`, if you remove that it works. Do you need center if you are showing 5 items?

**Comment by arkoe** [comment]
Yes, that solves the issue.
