### ISSUE TITLE
Doesn't show images, dots and nav correctly

### ISSUE THREAD

**Issue by ygoe** [OwlCarousel2/OwlCarousel2#1992]
I've added this code following the (thin) documentation and it does show some items and I can scroll through them. But the images, set up for lazy loading, do not show up. Also, I see no dots and the prev/next buttons are just plain text below the carousel.

Owl carousel v2.2.1

Sample code:

```
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<link rel="stylesheet" href="css/owl.carousel.min.css">
	<link rel="stylesheet" href="css/owl.theme.default.min.css">
</head>
</body>
    <section class="container-fluid">
        <div class="owl-carousel">
		<div class="item">
			<img class="lazyOwl" data-src="images/demo.jpg"><br>
			Text
		</div>
	</div>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="js/classie.js"></script>
    <script src="js/cbpAnimatedHeader.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
	<script>
	$(document).ready(function() {
		$(".owl-carousel").owlCarousel({
			items: 4,
			lazyLoad: true,
			nav: true
		});
	});
	</script>
</body>
</html>
```

I'm remaking an old website from somebody else and found that it uses owl carousel so I chose to keep it. This is my first contact with this libarary.

**Comment by acutedeveloper** [comment]
Hiya. I would change `data-src` to `src`

Then add a class of `owl-theme` Alongside the owl-carousel class.

Also keep in mind that until you have more items than you have defined in the options, will you see the navigation.

**Comment by acutedeveloper** [comment]
Apologies I had mis read your comment if you saw the notification.

Change the class `lazyOwl` to `owl-lazy`.

For the nav to render correctly you need to add the class `owl-theme` alongside `owl-carousel`.

**Comment by ygoe** [comment]
Thank you, that works fine! Except your link is broken (404).

**Comment by acutedeveloper** [comment]
Aha! Might of helped if I added the url correctly. Link amended.

**Comment by ygoe** [comment]
Better now. :-)
