### ISSUE TITLE
The coordinate problem with the value 0

### ISSUE THREAD

**Issue by aekarimov** [OwlCarousel2/OwlCarousel2#2001]
The carousel doesn't slide when one of the coordinates value is 0, because there is an error at condition for check:
`this.op(coordinate, '>', coordinates[index + 1] || value - width)`.

For my [example](https://jsfiddle.net/Lxt92pce/3/) coordinates array value is `[331, -0, -330, -661, -992, -1322, -1653, -1984, -2314, -2645, -2976, -3306]`.

When I try to slide to next slide, in method Owl.prototype.closest in $.each method.
With first coordinate (index is 0), this condition became as:
`this.op(coordinate, '>', coordinates[0 + 1] || value - width)`
the same as:
`this.op(coordinate, '>', -0 || value - width)`
the same as:
`this.op(coordinate, '>', value - width)` (checking if there is the end of carousel)

And that is why it returns current position index. 
So my carousel stand still.

There is an [image](https://gyazo.com/405e5bc5cf56676e0ae644bb34625d5b) with this behavior.

**Comment by aekarimov** [comment]
The solution is to replace condition on:
`this.op(coordinate, '>', coordinates[index + 1] !== undefined ? coordinates[index + 1] : value - width)`

**Comment by dennis40** [comment]
I think you can make one more edit. It will also help on this topic https://github.com/OwlCarousel2/OwlCarousel2/issues/2239
`(this.op(coordinate, '<=', value)
					&& this.op(coordinate, '>', coordinates[index + 1] !== undefined ? coordinates[index + 1] : value - width))`
It is in the first condition `<=`
