### ISSUE TITLE
Feature Request: Changing active slide without showing slides between currrent and new active ones.

### ISSUE THREAD

**Issue by CyberDildonix** [OwlCarousel2/OwlCarousel2#2020]
Is it possible to add an option for this type of workflow:
1. User opens second slide.
2. User switches to the fourth slide.
3. Third slide isn't visible when slides are switching.

I thought about possible implementation as for looping of the slider, when before playing animation the new active slide should be appended after current one. (Prepend for other direction, of course)

**Comment by keefyhub** [comment]
If you use animations, it should work the way you are describing.

https://codepen.io/altro-nvp2/full/MmQBVd/ - this pen has lots of animation examples.

**Comment by CyberDildonix** [comment]
Thank you for the help. This is what i've search for.
