### ISSUE TITLE
How to configure Continues transaction/ Ticker mode

### ISSUE THREAD

**Issue by nasirkhan** [OwlCarousel2/OwlCarousel2#2022]
Is is possible to implement a continues transaction of the carousel? I did not find any doc but there are options like smartSpeed, fluidSpeed, autoplaySpeed. 

A similar feature is available at an another plugins, http://bxslider.com/examples/ticker

**Comment by leotinoco** [comment]
I need the same but I have not been able to make it work. I use jquery 3.2.1 and bootstrap. If anyone finds a solution I will be waiting.

**Comment by pascalporedda** [comment]
There is no such feature for the owl carousel.
