### ISSUE TITLE
Jquery 3.2.1 problems

### ISSUE THREAD

**Issue by Webdinge** [OwlCarousel2/OwlCarousel2#2024]
Hi,

When using jquery CDN from https://code.jquery.com/ and then use any version above 1.11.0 will give this error -> 

TypeError: invalid 'in' operand a

I've tried  owl version 2.2.1 and 2.2.0

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! As this one is already an older issue, I assume that you've found a solution for your problem. If that is not the case feel free to reply me and I will reopen this issue.
