### ISSUE TITLE
slideBy supported with dots?

### ISSUE THREAD

**Issue by MarkNewcomb1** [OwlCarousel2/OwlCarousel2#2032]
Hello,

I had a request recently from a client to see if the dots that appear underneath a slider with multiple slides could be configured to navigate to three at a time instead of the dot advancing you one at a time (that is, if you click on each dot in order from left to right). 

I tried doing it with the slideBy option, but apparently that only works with the navigation buttons, but not the dots. Perhaps a dotBy?

**Comment by keefyhub** [comment]
Close, `dotsEach` - https://owlcarousel2.github.io/OwlCarousel2/docs/api-options.html#dotseach

So you could have a dot for each `X` amount of slides

**Comment by MarkNewcomb1** [comment]
Ok, thanks for that. I'm having trouble integrating it, but then again I'm dealing with a Wordpress loop as well, but that's another ball of wax.

**Comment by keefyhub** [comment]
It should work out of the box - https://codepen.io/keefyboooo/pen/GvXRKQ

If not, post the code and I might be able to help

**Comment by MarkNewcomb1** [comment]
I found it! Thanks to your help with the codepen. What was making dotsEach not work was I had the "center: true" option. I took your working codepen code and, one-by-one, I changed it to what I had until it broke. 

Thanks again!
