### ISSUE TITLE
1 px height image

### ISSUE THREAD

**Issue by laminr** [OwlCarousel2/OwlCarousel2#2039]
Goodday,

On the homepage of my website, where I have put the carrousel, the carousel start almost every time with the first picture with a **height** of **1px**, then while sliding to the second, it takes the normal size.

check on: www.vytashop.com

please help

**Comment by saturdaynight** [comment]
I have the same problem. Did you find a solution?

**Comment by laminr** [comment]
unfortunately not :'-(

**Comment by saturdaynight** [comment]
Try this, might need to adjust the value. It worked for me.

.owl-height {min-height: 500px;    height:auto !important;    height: 500px; }

**Comment by laminr** [comment]
Will have another try with that, thanks
I think my issue with it was that the carousel is not more responsive in height then....

**Comment by saturdaynight** [comment]
my issue only happen when i press CTRL+F5 or first time image loads.

**Comment by laminr** [comment]
me too, the first load of the page...

**Comment by piotrorlowski-idego** [comment]
The same issue here ... setting min-height however will remove rwd concept

**Comment by robertrhu** [comment]
Anyone able to find a good fix for this? I'm completely stuck.

Started this thread here...
https://github.com/OwlCarousel2/OwlCarousel2/issues/2185

**Comment by pascalporedda** [comment]
Duplicate of #556 

Has been fixed with the latest commit and will be released soon.
