### ISSUE TITLE
video loading slowly from youtube in my webpage in owlcarousel

### ISSUE THREAD

**Issue by SakthiSelvaraj** [OwlCarousel2/OwlCarousel2#2055]
i want the video to be loaded immediately or wanna decrease the time consumed to load...so please suggest me a solution..it takes much time for my webpage to load the video from the you-tube..is there any way to solve this issue..or just to hide loading from the customers

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
