### ISSUE TITLE
OWL Carousel doesn't work

### ISSUE THREAD

**Issue by FC-Aachen** [OwlCarousel2/OwlCarousel2#2061]
Hello everybody, 

my name is Chris from Aachen, i have a problem with the carousel slider on my webside.

www.bonkidz.de - can someone help me ? 

Thanks! 

Chris

**Comment by keefyhub** [comment]
You have some javascript console errors, it might be down to the version of jQuery you are using. Have you tried a different version or using a CDN?

**Comment by FC-Aachen** [comment]
Thanks a lot keefyhub ! That's the problem .....
