### ISSUE TITLE
Rewinding a few elements

### ISSUE THREAD

**Issue by alosev** [OwlCarousel2/OwlCarousel2#2067]
Tell me, please, is it possible to configure scrolling by two elements?

**Comment by keefyhub** [comment]
Use [slideBy](https://owlcarousel2.github.io/OwlCarousel2/docs/api-options.html#slideby)

You would need to use this in combination with `items`
```
$(".owl-carousel").owlCarousel({
  items: 3,
  loop: true,
  slideBy: 3
});
```
