### ISSUE TITLE
Carousel broke when initialized on hidden container

### ISSUE THREAD

**Issue by eparisio** [OwlCarousel2/OwlCarousel2#207]
I try the last dev update, my older version is the master version, and when i load carousel on hidden content the carousel broke. Before with the master ver. it works perfectly on hidden content too.
In this example the content is messed up.
On my website the carousel don't trigger anything, don't give any error and is visible only one image + navs (the carousel is initialize correctly, all elements are created but it stop working), it is inside a boostrap tab.

I have used the script from the site in this fiddle, not exactly the last dev, because the link on the jsfiddle example didn't work.

http://jsfiddle.net/93cpX/3/

**Comment by efflux** [comment]
Thanks for the patch witrin.. confirmed it's working with bootstrap 3 tabs

**Comment by chandra10207** [comment]
Same issue here.
I have added owl-carousal inside li tag
initially carousal is hidden i.e display:none; from css and after li:hover I have make it display:block.

Problem is:
Owl carousal calculate item width on hover only so it breaks the design intially on hover.

Can I make owl carousal to calculate with initially on hidden div.

**Comment by arturhaddad** [comment]
I had this problem when i placed owl carousel inside a fancybox.
I patched it changing the `display: none` container to `height: 0, opacity: 0`.

**Comment by prabhjeevnijjar** [comment]
I am facing similar problem with bootstrap modal,
I am adding a 50 ms delay in opening the modal after click
