### ISSUE TITLE
Lazyload with stage padding does not load visible images

### ISSUE THREAD

**Issue by Wufe** [OwlCarousel2/OwlCarousel2#2082]
Referring to issue #1210.
The problem is the same.

When using stage padding + lazy load, the visible images shown by stage padding don't get loaded.

Here is the link to [JSFiddle](https://jsfiddle.net/crgf8mzz/).

![image](https://user-images.githubusercontent.com/7671694/31283362-a9eac084-aab5-11e7-8903-95409c8769be.png)

Black images are not loaded yet.

I'm about to propose a PR implementing the patch proposed by @clooth

**Comment by pascalporedda** [comment]
I've took your changes and added them to the project had to fix a few things but now they are working.
