### ISSUE TITLE
Owl Carousel 2 Need customize ability to adjust time per slide.

### ISSUE THREAD

**Issue by rvpatel** [OwlCarousel2/OwlCarousel2#2090]
@keefyhub 
Please help me. Issue arrived when i have drag previous slides.

Now i have using Owl Carousel 2 for single slide scroll with 5 second time each slide. 
Now Need customize ability to adjust time per slide. 

something like nevo slider. 
https://stackoverflow.com/questions/13315904/jquery-nivo-slider-set-delay-time-for-each-slide
 
example: 
Slide1 : 5 second  
Slide2 : 10 second  
Slide3 : 2 second

```
           var owl = $(".home-banner .owl-slider").owlCarousel({
                autoplayTimeout:60000,
                autoplay: true,
                items: 1,            
                loop: true,
                dots: false,			
                nav: true,
                onDragged: setDelay,
            });

```
            owl.on('initialized.owl.carousel translated.owl.carousel', function () {
                setDelay();
            });

            function setDelay(){
                owl.trigger('stop.owl.autoplay'); 

                var defaultTiming = 5000;
                var carouselTiming = $('.home-banner .owl-item.active .item').data('timing') ? $('.home-banner .owl-item.active .item').data('timing') : defaultTiming;

                setTimeout(function () {
                    owl.trigger('next.owl.carousel',[carouselTiming]); 
                },carouselTiming);
            }    
 `

-- | --

**Comment by keefyhub** [comment]
Like I said in the other issue, you'd need to either disable users being able to change slides with either a swipe/drag or prev/next or add in some kind of cancelling of the setTimeout function when a user does one of those actions.

You also do not need autoplay if you are using the `initialized.owl.carousel` event as it will run when the carousel is loaded.

**Comment by rvpatel** [comment]
@keefyhub
Please suggest some conditional code for slider event.

`owl.on('dragged.owl.carousel', function () {
                alert('1');
            });
            
            owl.on('initialized.owl.carousel translated.owl.carousel', function () {
                alert('2');
            });`

**Comment by rvpatel** [comment]
@keefyhub @barneycarroll 

I have need help to fixout for else condition.
i have managed default auto slide time based now need help for when user use swap no of slides then next slide scroll auto with it's time based.

**Comment by keefyhub** [comment]
Instead of `owl.trigger('play.owl.autoplay');` could you do

```
slidercode = '1';
setDelay();
```

So the function calls itself? Im still not sure using autoplay and `setTimeout()` together is the best idea

**Comment by rvpatel** [comment]
This one issue generated but i have fixed code using "clearTimeout()"  function.
Thanks @keefyhub .

**Comment by binishmp** [comment]
@rvpatel how to achieve the same in vuejs. Thanks in advance!

**Comment by rediasa** [comment]
> This one issue generated but i have fixed code using "clearTimeout()" function.
> Thanks @keefyhub .

@rvpatel 
Hello,
I have the same problem when using data-timing to set the time of the item.
When the user clicks on NEXT, PREV or Drag Item, the time defined in the data-timing no longer works and if you click next several times the slides skip.
How did you manage to solve this?
