### ISSUE TITLE
My carousel stop work correctly before some Chrome update

### ISSUE THREAD

**Issue by lucasvieira** [OwlCarousel2/OwlCarousel2#2092]
My carousel does't work correctly after some Chrome update. 
If the site is in desktop mode, it works ok. But if it is in mobile version, the carousel didn't work correctly.
It looks like the width calc doesn't work.

I have a local (127.0.0.1) version that I haved removed all the jQuerys and called only one. But it still doesn't work

Can you help me?

The site: http://modelo.bringcommerce.com.br/

**Comment by hassanbinsafdar** [comment]
Hello @lucasvieira I had same problem how i fix it i am going to tell you solution.
you have to paste your owl carousel code inside set interval option and carousel will be working fine. Actually its issue on loading js properly so this hack works for me.
setInterval(function(){
  // Here paste your whole carousel
 },1500);

Thanks :)

**Comment by pascalporedda** [comment]
I wasn't able to recreate this problem. Probably wasn't related to OwlCarousel directly.
