### ISSUE TITLE
CSS Transitions

### ISSUE THREAD

**Issue by Anydog** [OwlCarousel2/OwlCarousel2#21]
Hi,
 great, great work.

Question:
are you going to abandon the css transitions with "transitionStyle" ...?

**Comment by eagle-design** [comment]
Hi,
I load owl.carousel.min.js (2) 
but 

$('.bloginfo-descs').owlCarousel({
    loop:true,
    items:1,
    nav:true,
    mouseDrag:false,
    autoplay:true,
    autoplayTimeout:3000,
    transitionStyle : "fade"
})


there is not any fade effect !

i need to fade slides whene  slides auto changed  : )

thanks :+1:

**Comment by coffeeneed** [comment]
So, how can I achieve this fade effect? :)
