### ISSUE TITLE
Is possible to have two owl versions on the same page?

### ISSUE THREAD

**Issue by cararroy** [OwlCarousel2/OwlCarousel2#2108]
Hi there, 

I need to have two owl-carousel versions on the same page. I need the new version 2 funcionality but i cant update the old version (corporative issues). So i need to have one carousel with an old version and other carousel with the new version in the same page. 

I am trying to rename clases and js methods in the new version but it doesn't works 100%. Could someone help me about it? Thanks a lot!

**Comment by donohoe** [comment]
The short answer is Yes, but as you can see it would take a lot more effort on your part to resolve conflicts.

From a practical perspective I wouldn't do this if it is at all possible to avoid it.

**Comment by cararroy** [comment]
Thanks for your answer, i have updated the old version and fix all issues. Have a good day!
