### ISSUE TITLE
Adding an item resets the carousel to the beginning

### ISSUE THREAD

**Issue by raulfelix** [OwlCarousel2/OwlCarousel2#211]
It would be desirable to be able to add 1 or more elements to the end of the carousel without losing the current position you are viewing. At the moment you are taken back to the beginning meaning you cannot lazy load content you are displaying.

**Comment by Wtower** [comment]
I understand that this is an old close one, but just in case somebody else lands here facing the same issue with owl 1.3.3, you can simply call `jumpTo` immediately after having called `addItem` to reset the position to wherever necessary.

**Comment by greg5green** [comment]
1.3.3 is a different project that you can find [here](https://github.com/OwlFonk/OwlCarousel)
