### ISSUE TITLE
Freeze scroll while swiping

### ISSUE THREAD

**Issue by johnylaravel** [OwlCarousel2/OwlCarousel2#2111]
Hi, is there any option to **freeze "scroll up/down"** while user is swiping slides?

Problem is when I swipe thru slides, my **page is going up and down** because scroll is triggered in the same time. It feels really bad. I would like that user can't swipe and scroll at the same time, is that possible?

For example, you can see **instagram slider when someone pick more photos** in one Post. I would like to have same effect.

**Thanks!**

**Comment by Hlsgs** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

**Comment by johnylaravel** [comment]
Thanks for the anwser. Do you have something that is **supported in every browser**?

I found **example gallery** just to be sure what I'm talking about: "https://www.net-a-porter.com/rs/en/product/993434/rosetta_getty/one-shoulder-stretch-ponte-midi-dress" - **see on mobile**

**Comment by Hlsgs** [comment]
A far as i know opwl does not support this in js. So either go with a custom JS solution like [here](https://stackoverflow.com/questions/16348031/disable-scrolling-when-touch-moving-certain-element) or switch to [Slick](https://github.com/kenwheeler/slick).
Personally, i would just use the native CSS, as Safari will get its'a act together.

**Comment by pascalporedda** [comment]
Hlsgs proposed the right answer. This is now also included in v2.3.1
