### ISSUE TITLE
Images wrong height on initial load

### ISSUE THREAD

**Issue by kevmon** [OwlCarousel2/OwlCarousel2#2113]
After I save my CSS file, the first load calculates the width of .owl-item incorrectly.  It's much too large and only shows half the image (cut off due to overflow: hidden).  Upon refresh and every refresh after that, it's the correct size.  If I make no changes to my CSS file but save it again, the problem repeats.  

Very simple code:

```
$(".owl-carousel").owlCarousel({
    items: 1
});
```

I'm running it in document ready and they're just standard images.

I'm not sure what other info I can give you to help, so please let me know.

Thanks

**Comment by icepoint0** [comment]
how to trigger calculation item's height hook?

**Comment by pascalporedda** [comment]
Duplicate of #556 

This issue will be solved with the next release.
