### ISSUE TITLE
one image

### ISSUE THREAD

**Issue by jumpping** [OwlCarousel2/OwlCarousel2#2114]
when have one image it will show this
![image](https://user-images.githubusercontent.com/22951415/32212131-8381432e-be50-11e7-823e-7ebf6f0655f5.png)
this is my code
$('#index-banner').owlCarousel({
        items: 1,
        loop: true,
        margin: 0,
        autoplay: true,
        autoplayTimeout: 3000,
        autoplayHoverPause: true
    });

**Comment by Agonn** [comment]
Have you tried  singleItem: true ?

**Comment by jumpping** [comment]
'singleItem: true' is the same as above

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.
