### ISSUE TITLE
Black border around images

### ISSUE THREAD

**Issue by bene25** [OwlCarousel2/OwlCarousel2#2119]
Hello. I am having this awfull black border around all carousel images. I could fix it through CSS, but is it normal to have them?
 
![image](https://user-images.githubusercontent.com/11219968/32301007-b7d9c28a-bf64-11e7-929d-04115c071e23.png)

WP version 4.8.3
FooGallery Owl Carousel Template Version 1.4.2
FooGallery Version 1.3.8

In CSS it;s called

.foogallery-owl-carousel.hover-effect-zoom a  {
    background: #000 url('img/zoom.png') no-repeat center center;
 }

**Comment by donohoe** [comment]
Without more information my guess is that this is CSS on your side that is adding the border and you should be able to remove it.

This does not appear to me to be related to OwlCarousel itself, rather your usage of it.

Hope that helps.

**Comment by bene25** [comment]
Try this 
WP version 4.8.3
FooGallery Owl Carousel Template Version 1.4.2
FooGallery Version 1.3.8. 

Create foo gallery with owl carousel and foobox as lightbox.

**Comment by bene25** [comment]
Any news for this issue?

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project, rather to the plugin you are using. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
