### ISSUE TITLE
can change the position of prev button and next button

### ISSUE THREAD

**Issue by andrewAIS** [OwlCarousel2/OwlCarousel2#2120]
![image](https://user-images.githubusercontent.com/32729797/32367937-f330c404-c0be-11e7-9809-5bc0984d416f.png)
now the prev button and next button below the carousel. can any setting change the position of buttons?

for example, 
likes below image
![image](https://user-images.githubusercontent.com/32729797/32368002-3fd333a0-c0bf-11e7-8394-1af6248abf20.png)

**Comment by keefyhub** [comment]
You could do this using CSS,

```
.owl-prev,
.owl-next {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
}

.owl-prev {
  left: -2rem;
}

.owl-next {
  right: -2rem;
}
```

You might have to adjust the `-2rem` as needed. If you are using dots, you might also need to make them absolutely positioned so it doesn't affect the height of the whole carousel and make the prev/next elements not be vertically centred.

**Comment by leothorp** [comment]
Another option is leaving `nav: false`, creating your desired buttons anywhere you like with html/css, and then setting them up to trigger the previous and next events on the carousel element, like so:

```
    var carouselEl = $('.owl-carousel');

    carouselEl.owlCarousel({
        items: 6
    });

    $(".my-next-button").click(function() {
        carouselEl.trigger('next.owl.carousel');
    });

    $(".my-previous-button").click(function() {
        carouselEl.trigger('prev.owl.carousel');
    });

```

**Comment by pascalporedda** [comment]
Seems like this is one is solved.

**Comment by devbikram** [comment]
> Another option is leaving `nav: false`, creating your desired buttons anywhere you like with html/css, and then setting them up to trigger the previous and next events on the carousel element, like so:
> 
> ```
>     var carouselEl = $('.owl-carousel');
> 
>     carouselEl.owlCarousel({
>         items: 6
>     });
> 
>     $(".my-next-button").click(function() {
>         carouselEl.trigger('next.owl.carousel');
>     });
> 
>     $(".my-previous-button").click(function() {
>         carouselEl.trigger('prev.owl.carousel');
>     });
> ```

This works fine for a single carousel, but for multiple carousels, it moves all the carousels.

**Comment by deepakmewada** [comment]
hi team ,
when i click on next button i skip some slide directly go another slide,
i want track my slide when i click next same on previous option but  always go last slide not my flow of previous step of slider.

**Comment by DianeTereshko** [comment]
var owl = $('.owl-carousel');
    owl.owlCarousel(); // with this working normal
    // Go to the next item
    $('.customNextBtn').click(function () {
        owl.trigger('next.owl.carousel');
    })
    // Go to the previous item
    $('.customPrevBtn').click(function () {
        owl.trigger('prev.owl.carousel');
    })

**Comment by Hamza0101-bug** [comment]
how we can get next and previous functionality in TS
