### ISSUE TITLE
add.owl.carousel event add item on wrong index

### ISSUE THREAD

**Issue by padaliyajay** [OwlCarousel2/OwlCarousel2#2121]
Hello author,

I am using add.owl.carousel event to append new items in owl carousel using index. but it is always add new item at first index. here is my code. please suggest me.

```
var items = $(data['products']).filter('.owl-item'); // Products markup gotted by ajax
var owl = product_container.data('owl.carousel');
var current_items_length = owl._items.length; // get total number of current available items
for(var i = 0; i < items.length; i++){
    product_container.trigger('add.owl.carousel', [items[i], i + current_items_length]);
}
product_container.trigger('refresh.owl.carousel');
```

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
