### ISSUE TITLE
Mouse Drag issue

### ISSUE THREAD

**Issue by karthickms** [OwlCarousel2/OwlCarousel2#2122]
If 4 items occurs in carousel, when mouse drag the image, blank space occurs while using stagepadding attribute

Example : http://prntscr.com/h6uslj

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! As this one is already an older issue, I assume that you've found a solution for your problem. If that is not the case feel free to reply me and I will reopen this issue.
