### ISSUE TITLE
slide to item with deeplink (URLhashListener)

### ISSUE THREAD

**Issue by 7L3HN** [OwlCarousel2/OwlCarousel2#2123]
i have a carsousel with twelce item (january, february, ..., november, december) and the actual month should be active...

my code:

jQuery(document).ready(function(){
	
    // MONTH NOW
    var date = new Date().getMonth();
    
    // MONTH SLIDER
    var owl = jQuery('#main .packages-owl-slider');
    owl.owlCarousel({
	mouseDrag: false,
	touchDrag: false,
	items: 1,
	dots: false,
	URLhashListener: true,
        startPosition: 'URLHash'
    });
    owl.on('changed.owl.carousel', function(event){
        var currentItem = event.item.index;
	jQuery('.owl-carousel-nav ul li').removeClass('active');
	jQuery('.owl-carousel-nav ul li:nth-child(' + (currentItem+1) + ')').addClass('active');
    });
    owl.trigger('to.owl.carousel', date);
    
});

with this code, the carousel slides automatically to item#10. But if i want to use a deeplink ... for example the carousel should slide to item#5 ... it doesn't slide to slide#5 ... always to slide#10

i know that this code is responsible for this behavior. But how can i fix this - is this possible?

thanks for your help

**Comment by keefyhub** [comment]
You shouldnt need to use `owl.trigger` if you are using the URL Hash Listener.

https://owlcarousel2.github.io/OwlCarousel2/demos/urlhashnav.html

If your owl navigation has a hash of `a href="#june"` and there is an owl item which has a data attribute of `data-hash="june"` it should work automatically.

If that doesnt work, you could look at something like this
```
$(DOT OR BUTTON CLASS).on('click', function () {
    owl.trigger('to.owl.carousel', [$(this).index(), 300]);
});
```

**Comment by 7L3HN** [comment]
but i think i need the `owl.trigger` function, because i want to slide to the actual month, while the page is loading...

**Comment by keefyhub** [comment]
You could add a hash to the end of the URL and use `startPosition: 'URLHash'`?

Or if you want to use `to.owl.carousel` you would need to get the position of the current month.

```
var date = new Date().getMonth();
var targetPosition = $(".item[data-month='" + date + "']").attr('data-month');

$(window).on('load', function() {
  owl.trigger('to.owl.carousel', [targetPosition, 300]);
});
```

I created a codepen example - https://codepen.io/keefyboooo/pen/POjyYo

**Comment by 7L3HN** [comment]
this works almost

the url changes to "https://www.domain.tld/slider/#11" on page load because it's november now - this is korrekt, this is what i want.

but if i set a deeplink to e.g. "https://www.domain.tld/slider/#4" the slider doesn't scroll to "https://www.domain.tld/slider/#4" - always to the actual month

i can maybe also create a codepen example if this helps?

**Comment by keefyhub** [comment]
ah OK, I see. Rather than get the current month, you could get the hash from the URL?

```
var date = window.location.hash;
```

Might do it. You might need to have a fallback if there is no hash.

**Comment by 7L3HN** [comment]
i think the problem is always the same...

maybe i have to check if there ist a hash before initialization of the slider - for the deeplink? if not scroll to actual month?

**Comment by keefyhub** [comment]
Yeah you could write the variable as a ternary, like

```
var date = window.location.hash ? window.location.hash : new Date().getMonth();
```

Which will either return the hash or the current month.

Bare in mind that `window.location.hash` will return it as `#{THE NUMBER}`, you will need to remove the `#`

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! As this one is already an older issue, I assume that you've found a solution for your problem. If that is not the case feel free to reply me and I will reopen this issue.
