### ISSUE TITLE
Npm owl.carousel unable to load while *ngFor loop with Angularjs 4

### ISSUE THREAD

**Issue by jvkiran** [OwlCarousel2/OwlCarousel2#2125]
`<div class="owl-carousel owl-theme">
      <div class="scrolling-object-latest" *ngFor="let item of latest_designs">
        <a href="{{ 'invitation/' + item.slug + '/' + item.id + '/preview'}}" class="">
           <img [src]="item.image" alt="{{ item.title }}"> 
        </a>
      </div>
    </div>`

Also AutoPlay and loop:true  is not working, if i use demo HTML instead of *ngFor loop it's working fine.
I think it's a issue with looping

**Comment by vishal-pandey** [comment]
<div class="owl-carousel owl-theme">
    <div class="item" *ngFor="let pr of product;"><h4>1</h4></div>
    <div class="item"><h4>2</h4></div>
    <div class="item"><h4>3</h4></div>
    <div class="item"><h4>4</h4></div>
    <div class="item"><h4>5</h4></div>
    <div class="item"><h4>6</h4></div>
    <div class="item"><h4>7</h4></div>
    <div class="item"><h4>8</h4></div>
    <div class="item"><h4>9</h4></div>
    <div class="item"><h4>10</h4></div>
    <div class="item"><h4>11</h4></div>
    <div class="item"><h4>12</h4></div>
</div>


Same Problem 
div.item without *ngFor is working fine
but with *ngFor it get displayed static and not sliding

**Comment by vishal-pandey** [comment]
`<div class="owl-carousel owl-theme"> <div class="item" *ngFor="let pr of product;"></div><div class="item"><h4>2</h4></div>    <div class="item"><h4>3</h4></div>    <div class="item"><h4>4</h4></div>    <div class="item"><h4>5</h4></div>    <div class="item"><h4>6</h4></div>    <div class="item"><h4>7</h4></div>    <div class="item"><h4>8</h4></div>    <div class="item"><h4>9</h4></div>    <div class="item"><h4>10</h4></div>    <div class="item"><h4>11</h4></div>    <div class="item"><h4>12</h4></div></div>`

Same Problem 
div.item without *ngFor is working fine 
but with *ngFor it get displayed static and not sliding

**Comment by lafama** [comment]
Anyone managed to fix this

**Comment by lafama** [comment]
Solution is to make sure the list in *ngFor is not undefined :-)

**Comment by pascalporedda** [comment]
Seems like this one is solved.

**Comment by hgurung** [comment]
Its not working in angular version when i try to loop in item div. Here is my code below.

> <div class="item" *ngFor="let movie of newMoviesData">
> 						<div class="w3l-movie-gride-agile w3l-movie-gride-agile1">
> 							<a [routerLink]="['/movies', movie.slug]" class="hvr-shutter-out-horizontal">
> 								<img src="{{ movie.image }}" title="album-name" class="img-responsive" alt=" " *ngIf="movie.image !== ''"/>
> 								<div class="w3l-action-icon">
> 									<i class="fa fa-play-circle" aria-hidden="true"></i>
> 								</div>
> 							</a>
> 							<div class="mid-1 agileits_w3layouts_mid_1_home">
> 								<div class="w3l-movie-text">
> 									<h6>
> 										<a [routerLink]="['/movies', movie.slug]">{{movie.title}}</a>
> 									</h6>
> 								</div>
> 								<div class="mid-2 agile_mid_2_home">
> 									<p>{{movie.movie_date | amDateFormat: 'YYYY'}}</p>
> 									<div class="block-stars">
> 										<ul class="w3l-ratings">
> 											<li *ngFor="let star of starsMovie;let i = index;">
> 												<a href="#">
> 												  <i class="fa fa-star" [ngClass]="(movie.ratingCount >= (i + 1)) ? 'fa-star' : 'fa-star-o'" aria-hidden="true"></i>
> 												</a>
> 											  </li>
> 										</ul>
> 									</div>
> 									<div class="clearfix"></div>
> 								</div>
> 							</div>
> 							<div class="ribben">
> 								<p>NEW</p>
> 							</div>
> 						</div>
> 					</div>
