### ISSUE TITLE
mouseDrag causing scroll problems on mobile devices

### ISSUE THREAD

**Issue by TheZoker** [OwlCarousel2/OwlCarousel2#2126]
When `mouseDrag: true` is set, scrolling vertically on the carousel images on mobile devices does not work. 

So when I try to "swipe" up on the image, the page does not scroll.
`touchDrag` does not cause this issue btw, but the `mouseDrag` setting

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by pascalporedda** [comment]
Since you didn't replied I will assume that you found a fix for your issue and will therefore close this.
