### ISSUE TITLE
Incorrect version number

### ISSUE THREAD

**Issue by bjarnef** [OwlCarousel2/OwlCarousel2#2127]
I noticed that the `@version` number is `owl.carousel.js` doesn't match the version in the comment.

![image](https://user-images.githubusercontent.com/2919859/32768542-83e0de2e-c918-11e7-878f-3f8819764b0c.png)

https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/dist/owl.carousel.js#L8

**Comment by pascalporedda** [comment]
Will be fixed  with the upcoming release.

**Comment by pascalporedda** [comment]
Adjusted in the latest dev branch.
