### ISSUE TITLE
set of images on forward or back link....

### ISSUE THREAD

**Issue by martin334a** [OwlCarousel2/OwlCarousel2#2128]
Hi,
I would need to change forward/backward behavior.
**Rather then "just"  1** new image in carousel on clicking the forward/backward arrow, I would like to **change the set of images.** 
Like a carousel with 4 Images.... on clicking those 4 images should change for the next set with 4 images....rather then just one new in the set.

I could not get that function to work. 
Any Idea??

**Comment by keefyhub** [comment]
https://owlcarousel2.github.io/OwlCarousel2/docs/api-options.html#slideby

You might need to nest this inside the responsive option

**Comment by martin334a** [comment]
Thank you for your reply:
... simply by  adding:
`$("#latest-property").owlCarousel({
    navigation: true,
    pagination: true,
    slideSpeed: 300,
    stopOnHover: true,
    autoPlay: true,
    items: 4,
    **slideBy: 2,**
    owl2row: true,
    rowsCount: 2,
    itemsDesktopSmall: [1024, 3],
    itemsTablet: [600, 3],
    itemsMobile: [479, 2]
});`
did not work.
What did you mean by:
_You might need to nest this inside the responsive option_??
I "kind of" did not specialy take care of a responsive option, should I?

**Comment by keefyhub** [comment]
If you use `slideBy: 'page'` it should work

**Comment by pascalporedda** [comment]
Seems like this one is solved.

**Comment by pascalporedda** [comment]
Is this an error related to any OwlCarousel functionality?
