### ISSUE TITLE
Owl carousel in Osclass

### ISSUE THREAD

**Issue by pilarf** [OwlCarousel2/OwlCarousel2#2135]
Hello.
Should I inquire about installing Carousel on Osclass?
Nowhere to write about the use of Osclass, I do not write about Carousel.
I'm not a professional, but I can do little, so I would ask for more detailed instructions.
I divide in advance.
Pilař

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
