### ISSUE TITLE
Owl Carousel 2.2.1 - sliding without delay

### ISSUE THREAD

**Issue by eyemiru** [OwlCarousel2/OwlCarousel2#2136]
My issue is my the slider works perfectly but I can't find an option to let it slide continuously without a delay.

My option:
function miniSlider () {
    var owl = $(".mini-slider");
    owl.owlCarousel({
        loop: true,
        nav: false,
        navText: false,
        dots: false,
        autoplay: true,
        responsiveClass:true,
        lazyLoad:true,
        autoplayTimeout:3000,
        //autoplayHoverPause:true,
        responsive:{
            0:{
                items:1
            },
            651:{
                items:2
            },
            992:{
                items:4
            }
        }
    });
}

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
