### ISSUE TITLE
Premium offers in Carousel-Please

### ISSUE THREAD

**Issue by pilarf** [OwlCarousel2/OwlCarousel2#2139]
Can I ask someone for advice?
I would need Carousel to display premium ads in endless feed and autoplay.
How do I change or edit my code?
Now I have this:

<?php if (osc_count_latest_items() > 0) { ?>
    <div class="owl-carousel  owl-theme">
        <?php while (osc_has_latest_items()) { ?>
            <div class="item">
                <?php if (osc_images_enabled_at_items()) { ?>
                    <div class="photo">
                        <?php if (osc_count_item_resources()) { ?>
                            <a href="<?php echo osc_item_url(); ?>">
                                <img src="<?php echo osc_resource_thumbnail_url(); ?>" width="auto" height="135" title="<?php echo osc_item_title(); ?>" alt="<?php echo osc_item_title(); ?>" />
                            </a>
                        <?php } else { ?>
                            <img src="<?php echo osc_current_web_theme_url('images/no_photo.gif'); ?>" alt="" title="" />
                        <?php } ?>
                    </div>
                <?php } ?>
                <div class="text">
                    <h3><a href="<?php echo osc_item_url(); ?>"><?php echo osc_item_title(); ?></a></h3>
					<?php echo osc_item_category() ;?>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>
<script type="text/javascript">
    $(document).ready(function () {
        $(".owl-carousel").owlCarousel();
    });
</script>

**Comment by pilarf** [comment]
<?php if (osc_count_latest_items() > 0) { ?>
    <div class="owl-carousel  owl-theme">
        <?php while (osc_has_latest_items()) { ?>
            <div class="item">
                <?php if (osc_images_enabled_at_items()) { ?>
                    <div class="photo">
                        <?php if (osc_count_item_resources()) { ?>
                            <a href="<?php echo osc_item_url(); ?>">
                                <img src="<?php echo osc_resource_thumbnail_url(); ?>" width="auto" height="135" title="<?php echo osc_item_title(); ?>" alt="<?php echo osc_item_title(); ?>" />
                            </a>
                        <?php } else { ?>
                            <img src="<?php echo osc_current_web_theme_url('images/no_photo.gif'); ?>" alt="" title="" />
                        <?php } ?>
                    </div>
                <?php } ?>
                <div class="text">
                    <h3><a href="<?php echo osc_item_url(); ?>"><?php echo osc_item_title(); ?></a></h3>
					<?php echo osc_item_category() ;?>
                </div>
            </div>
        <?php } ?>
    </div>
<?php } ?>
<script type="text/javascript">
    $(document).ready(function () {
        $(".owl-carousel").owlCarousel();
    });
</script>

**Comment by pilarf** [comment]
Tot is the beginning-he did not appear

!---- owl ---->
<?php if (osc_count_latest_items() > 0) { ?>

**Comment by pilarf** [comment]
"  !---- owl ---->
   <?php if (osc_count_latest_items() > 0) { ?>  "
Tot is the beginning-he did not appear

**Comment by pilarf** [comment]
I can not insert the first line

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
