### ISSUE TITLE
Owl carousel inside bootstrap modal footer

### ISSUE THREAD

**Issue by Pappakapa** [OwlCarousel2/OwlCarousel2#2141]
Hi everyone,

I'm having a problem about the owl carousel inside my modal bootstrap. BTW I'm new in programming so maybe some of my codes are not good as yours. I just want to remove the delay of the pictures and flash it more neatly.

Thanks

<button type="button" class="btn btn-success"  data-toggle="modal" data-target="#myModal">More Info<i class="fa fa-info-circle" aria-hidden="true"></i></button> 

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
		<div class="modal-content">
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4>Carpet Stain Remover</h4>
		    </div>
		    <div class="modal-body">
		    	<div class="row">
		    		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				    	<img src="{{URL::to('themes/default/assets/img/prodtry2.png')}}" />
			    	</div>
			    	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
			    		<h4>Features:</h4>
				    	<h5>Degreaser Anti-bacteria</h5>
				    	<h4>Scents:</h4>
				    	<h5>Kalamansi Citrus Lemon</h5>
			    	</div>
		    	</div>
		    </div>
		    <div class="modal-footer qwe">
		    	<h5>You might also like this:</h5>
		    	<div class="container">
		    		<div id="owl-demo" class="owl-carousel owl-theme">
						<div class="item">
							<img src="{{URL::to('themes/default/assets/img/prodtry1.png')}}" alt="AGGIE MAY ESPIRITU" />
							<div class="bgtext">
								<h5>prod name</h5>
							</div>
						</div>
						<div class="item">
							<img src="{{URL::to('themes/default/assets/img/prodtry1.png')}}" alt="QUEENDY NULLAN" />
							<div class="bgtext">
								<h5>prod name</h5>
							</div>
						</div>
						<div class="item">
							<img src="{{URL::to('themes/default/assets/img/prodtry1.png')}}" alt="Sheryl Geromiano" />
							<div class="bgtext">
								<h5>prod name</h5>
							</div>
						</div>
					</div>
		    	</div>
		    </div>
		</div>
	</div>
</div>
var owlCarousel = $('#owl-demo');
    $('#myModal').on('shown.bs.modal', function (event) {
        owlCarousel.owlCarousel({
            margin: 10,
    	responsiveClass: true,
            responsive: {
                0: {
                    items: 1,
                    nav: false,
                    autoplay:true
                },
                600: {
                    items: 2,
                    nav: false,
                    autoplay:true
                },
                1000: {
                    items: 3,
                    nav: false,
                    loop: false,
                    autoplay:true
                }
            }
        });
    });

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
