### ISSUE TITLE
How to disable the lazy load fade-in effect

### ISSUE THREAD

**Issue by jetibbetts** [OwlCarousel2/OwlCarousel2#2142]
I've created a lazy-load carousel, and when the next image is loaded for the first time, there is a fade-in effect. Is it possible to disable the fade-in?

This is my current owl carousel:

```javascript
var owl = $('.owl-carousel').owlCarousel({
	items: 1,
	lazyLoad: true,
	loop: false
});
```

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! As this one is already an older issue, I assume that you've found a solution for your problem. If that is not the case feel free to reply me and I will reopen this issue.
