### ISSUE TITLE
Responsive not working in iOS with latest version of Safari browser

### ISSUE THREAD

**Issue by vijaydogra** [OwlCarousel2/OwlCarousel2#2146]
Check my website over iOS device, the website spans due to width of items inside the owl carousel. It has been working perfectly fine on other browser, however, if its on iOS device, this gets a scroller at bottom which at present stage is not what seems to be responsive.

Website - http://dogratech.com

**Comment by keefyhub** [comment]
you've added `overflow: visible;` to `.owl-carousel-main .owl-stage-outer` & `.owl-carousel-center .owl-stage-outer` in your CSS somewhere, if you remove that the responsive styles should work

**Comment by vijaydogra** [comment]
Ok, got that, you can close this as I have resolved the issue with overflow parameter.
