### ISSUE TITLE
Making a slide appear next instead of scrolling the whole carousel? 

### ISSUE THREAD

**Issue by kevinnnz** [OwlCarousel2/OwlCarousel2#2148]
Is there currently a way to make a slide come second if the dots (or a link) are clicked instead of scrolling the whole carousel?

**Comment by PerfectByte** [comment]
Do you have an example of what you mean? I need some more clarity

**Comment by kevinnnz** [comment]
I am trying to do something like this: https://deals.bestbuy.com/?category=tv+amp+home+theater

When you click on any of navigation dots it pulls the slide up to the second position as opposed with Owl where it will slide every item past until you get to the desired slide.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
