### ISSUE TITLE
may i make vue component?

### ISSUE THREAD

**Issue by hagi4u** [OwlCarousel2/OwlCarousel2#2150]
hi, I usually use to owl carousel.
first of all, thank you to make great carousel plugin

nowadays i have interested to use vue component. but i didn't find to great carousel vue component. so i wanna use owl carousel on vue.js, if you accept, i'm gonna make vue carousel component your OwlCarousel2 !!

please check my issue.
thank you

**Comment by PerfectByte** [comment]
This isn't an issue. This is open source software so you are free to do as you please with it.

**Comment by hagi4u** [comment]
@PerfectByte Okay. i understand.
but i didn't know how to contact repo owner.

thank you
