### ISSUE TITLE
Align image to the bottom

### ISSUE THREAD

**Issue by JWestarp** [OwlCarousel2/OwlCarousel2#2152]
Is is possible to align the slider images to the bottom of the slider?

(In a website with a full with slider, the bottom of an image is cropped on big monitors. But the bottom is the intrance of an hotel, so the image should be sticky to the bottom and the top could scale out of view.)

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
