### ISSUE TITLE
load owl carousel before other page content?

### ISSUE THREAD

**Issue by pshudgins** [OwlCarousel2/OwlCarousel2#2153]
Hello... it seems my owl carousel is loading AFTER some of the other content on my home page, so getting a flash of content before the slides load.  

http://www.fitzgeraldpetersen.com/

Quick thoughts on how to avoid this issue?  Thank you!

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! As this one is already an older issue, I assume that you've found a solution for your problem. If that is not the case feel free to reply me and I will reopen this issue.
