### ISSUE TITLE
Content top bottom portion crop or hide

### ISSUE THREAD

**Issue by hhasan16** [OwlCarousel2/OwlCarousel2#2154]
I want to make a testimonial section using owl carousel but when activating it, it's work fine but content crop top and bottom. 

Jsfiddle link https://jsfiddle.net/wpdevhouse/sLfj2uyw

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
