### ISSUE TITLE
Owl Carousel Auto Height Not Working

### ISSUE THREAD

**Issue by robertrhu** [OwlCarousel2/OwlCarousel2#2155]
I'm working with an Owl carousel that has both video and images. It is set to auto height. The thumbnail image is adjusting the height as I scroll through the slider. But once I press the play button for the video, the video that appears is cut off at the bottom and has a black gap at the top, making the player controls not visible.

I'd LOVE to have the video fit the width and height of the slide so there is no black space top, bottom, right or left. And of course the player control buttons need to appear. What am I missing?

I've been banging my head against a wall on this one. Any help would be greatly appreciated. Thanks in advance!

Here are the settings for the owl carousel:

`<script>
    $(document).ready(function(){
        //Initialize Owl Carousel Javascript
        $(".owl-carousel").owlCarousel({
        items: 1,
        loop: true,
        nav: true,
        center: true,
        navText: [
            "<img src='<?php echo get_template_directory_uri(); ?>/assets/images/desrosiers-architects-image-slider-arrow.png' />",
            "<img src='<?php echo get_template_directory_uri(); ?>/assets/images/desrosiers-architects-image-slider-arrow.png' />"
        ],
        margin: 0,
        dots: false,
        autoplay: false,
        animateOut: 'fadeOut',
        video: true,
        responsive: true,
        autoHeight:true,
    });

    });
</script>`

Here's the HTML/PHP for the slider:

```
<div id="property-slider">
    <ul class="owl-carousel">
        <?php if( have_rows('project_photos') ): ?>
            <?php while( have_rows('project_photos') ): the_row();
                //Variables
                $photo = get_sub_field('project_photo');
                $photofull = get_sub_field('project_photo_full');
                $alt = get_sub_field('project_photo_alt');
               $Vedio = get_sub_field('project_video');
            ?>
            <li class="slide test">
        <?php     if($Vedio){ ?> <a class="owl-video" href="<?php echo $Vedio; ?>"></a> <?php } else { ?>
                <img class="slide-image slide-image-cropped"
                     src="<?php echo $photo; ?>"
                     alt="<?php echo $alt; ?>" />
                <img class="slide-image slide-image-full"
                     src="<?php echo $photofull; ?>"
                     alt="<?php echo $alt; ?>" />
                    <?php } ?>
            </li>
            <?php endwhile; ?>
        <?php endif; ?>
    </ul>
</div>
```

Here's a link to the page where the slider is:

[http://desrosiers.robertrhu.com/residential/bathroom-briar-cliff/?cid=5](url)

**Comment by pascalporedda** [comment]
As already mentioned in another issue, there are a few bugs in the auto height plugin that will be addressed soon. I will close issue as a duplicate for #556.
