### ISSUE TITLE
Featured slide over the others?

### ISSUE THREAD

**Issue by ZhuJo** [OwlCarousel2/OwlCarousel2#2158]
Is it possible to create featured slide which sits above the others like in this old carousel?

https://bkosborne.com/jquery-feature-carousel

**Comment by keefyhub** [comment]
if you use the `center` option, it will add a class to the middle item (when showing 3 items), you could then do

```
.owl-item:not(.center) {
  YOUR STYLES
}
```
to target the other slides

https://owlcarousel2.github.io/OwlCarousel2/docs/api-options.html#center

**Comment by pascalporedda** [comment]
Seems like this one has been solved.
