### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by Fcodapaz** [OwlCarousel2/OwlCarousel2#2160]
When the user clicks the carousel, does it zoom in and zoom in on the image? it's possible

**Comment by burhanahmed92** [comment]
Any one know this?

**Comment by keefyhub** [comment]
you could use it with a combination of a lightbox plugin. Ive used Owl Carousel and Magnific Popup together before which worked quite well

This is not my example, but it does use both Owl Carousel and Magnific Popup - https://codepen.io/milairagny/pen/oxqZWz

**Comment by ohepworthbell** [comment]
That feature doesn't exist within the carousel, and it's not really a function typical of a carousel anyway. You will need to use a separate plugin to do that, of which there are many available.

**Comment by soanvig** [comment]
Since after initiating carousel `.owl-item` size is unaffected by content size, You can freely change the content size by using external plugins. If you experience any problems, they should be CSS matter, therefore You should be able to fix them by yourself.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
