### ISSUE TITLE
Is there anyway to detect active states from 2 different carousels items.

### ISSUE THREAD

**Issue by grafxflow** [OwlCarousel2/OwlCarousel2#2163]
I have 2 carousels. One goes from right to left and the other from left to right. Each slide item has a data-attribute number for both. The same item data number appears in both carousels.

1 > 2 > 3 > 4 > 5

5 < 4 < 3 < 2 < 1

I want it so that every time a 'active center ' item for both above and below have the same number then have the same class added.

I am using the 'changed.owl.carousel' but the problem I have is syncing the 2 carousels data-attribute. I am guessing this is because the other is still moving.

`on('change.owl.carousel', function (e) {`
`var activeCarousel1 = Carousel1.find('.owl-item.active.center>div').data('id');`
`var activeCarousel2 = Carousel2.find('.owl-item.active.center>div').data('id');`
`....`

`<div class="owl-item active center" style="width: 194px; margin-left: 40px;">`
`<div data-id="4057" class="item">`
`<h4>Header</h4>`
`</div>`
`</div>`
`....`

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
