### ISSUE TITLE
Creating new button container breaks navigation 

### ISSUE THREAD

**Issue by idrisdopico** [OwlCarousel2/OwlCarousel2#2164]
Using OwlCarousel2 as a gallery, I linked the buttons to a custom container.

`
        dots: true,
        dotsContainer: '.unit-teaser__dots',
    `

When pressing the buttons in the container, it sometimes jumps back to button number 1, when pressing on another button. Any idea if this is a bug or there is something wrong with my code?

Regards,

Idris

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
