### ISSUE TITLE
jquery 2.1.1 has known vulnerabilities

### ISSUE THREAD

**Issue by santoshgiridhar** [OwlCarousel2/OwlCarousel2#2165]
Using RetireJS I was able to find that the dependency used in this package has multiple known jquery security vulnerabilities for docs_src.
1) /owl.carousel/docs_src/assets/vendors/jquery.min.js
2) /owl.carousel/docs/assets/vendors/jquery.min.js

Is it possible to update the jquery version to 1.12.0 ?
-- http://research.insecurelabs.org/jquery/test/
-- https://github.com/jquery/jquery/issues/2432
-- https://bugs.jquery.com/ticket/11974

**Comment by pascalporedda** [comment]
Hey @santoshgiridhar 

I will take a further look into this and come back to you when I've got news for you.

**Comment by pascalporedda** [comment]
I've been taking care of this, but this was not a dangerous problem though. As this was only used in the documentation, but it's fixed now.
