### ISSUE TITLE
Is there an option for a constant autoplay speed?

### ISSUE THREAD

**Issue by delahoc** [OwlCarousel2/OwlCarousel2#2169]
I've been trying to create a slider/ticker that either continually slides (ie, no pausing at each slide) or where I can minimise the pause. The documentation is sadly lacking, so I was left to experiment with the various speed options, but all to no avail. I found that some combinations actually broke the slider (eg, using both autoplaySpeed and autoplayTimeout just stopped the slider after one slide). Is it possible to do what I want? Are you able to update the documentation to provide some meaningful explanation of each option?

(Also, on the front page of your website, "Owl Carousel has been choosen as number one jQuery plugin ..." should read "Owl Carousel has been chosen as the number one jQuery plugin ...")

**Comment by delahoc** [comment]
PS - My client is now also asking if it's possible to have an AutoPlay option that slides from left to right ... ?

**Comment by keefyhub** [comment]
There is no option to turn the carousel into a continuous "ticker", Id recommend using something else if that us what you require. I believe it is in the pipeline https://github.com/OwlCarousel2/OwlCarousel2/issues/296

I did try it once, see this thread - https://github.com/OwlCarousel2/OwlCarousel2/issues/2030

There is a "right to left" class in the docs, although Im not sure if it is working - https://owlcarousel2.github.io/OwlCarousel2/docs/api-classes.html#rtlclass

Another option could be to start at the last slide

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

**Comment by delahoc** [comment]
I see this is still not implemented, which is a bummer. I've checked out all the threads that suggest that the slideTransition: 'linear' option is now working and will allow a constantly scrolling slider, but trying out all of the examples under the latest version of Owl (2.3.4) still doesn't do it. Bummer.
