### ISSUE TITLE
Customize html children order of owl-carousel

### ISSUE THREAD

**Issue by svanskivar** [OwlCarousel2/OwlCarousel2#2170]
Hi,

Owl Carousel wrapper looks now so:
```
<div class="owl-carousel"> <!-- START WRAPPER -->

      1. <div class="owl-stage-outer"></div>
      2. <div class="owl-nav"></div>
      3. <div class="owl-dots"></div> <!-- 3. Child -->

</div> <!-- END WRAPPER -->
```

but I need to customize child elements order of Owl-Carousel like so:

```
<div class="owl-carousel"> <!-- START WRAPPER -->

      1. <div class="owl-dots"></div> <!-- 1. Child -->
      2. <div class="owl-stage-outer"></div>
      3. <div class="owl-nav"></div>

</div> <!-- END WRAPPER -->
```

Have owl-carousel some function like this, that I can customize order? If not, how can I do this?
best regards

**Comment by pascalporedda** [comment]
Hello @svanskivar,

why would you need to customize the order? If you just need it for any visual changes you can simply do this by using css.

**Comment by svanskivar** [comment]
Hello @pascalporedda ,

I want, that **.owl-dots** are above **.owl-stage-outer**. Because it is in HTML after **.owl-stage-outer**, I cannot position **.owl-dots** relative above it. I did it with absolute positioning, but I need also custom JS to work everything well. How I checked, owl-carousel.js adds all wrappers with JS code. Because of this, I think, that order option for wrappers **.owl-dots**, .**owl-stage-outer**, **.owl-nav** will be helpful. 

best regards
