### ISSUE TITLE
Adguard Filter Problem..!

### ISSUE THREAD

**Issue by Kalbaliev** [OwlCarousel2/OwlCarousel2#2171]
I use Adguard 6 version. İts filter block owl-carousel. When disable the filter then show carousel. I use owl carousel for contributors' logos but this cause block my work. How to help me ?

**Comment by Kalbaliev** [comment]
![image](https://user-images.githubusercontent.com/30353187/34436398-04245584-ecaf-11e7-977f-8002e83f1145.png)

**Comment by pascalporedda** [comment]
Hello there,

I'am sorry but I don't know Adguard and I can't tell you why it is blocking your logos. Please refer to a site like stackoverflow to get help by the community.
