### ISSUE TITLE
Owl / Bootstrap / Parent width not cascading down

### ISSUE THREAD

**Issue by novak84** [OwlCarousel2/OwlCarousel2#2172]
I have an issue with owl. I leave the width at 100%, owl sits within a bootstrap grid and yet it ignores the width of the parent div making the owl carousel huge.

If i have 5 elements to show on the slider (one at a time) then it makes the owl-carousel 5 times the width of the window breaking the page and it has horizontal scroll because the carousel has gone to something crazy like 8000 pixels. I have tried the ResponsiveBase and it ignores that. If i specify the width in pixels then it's fine, but i want it as percent as i am using responsive framework.

For example:

```
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="owl-carousel" id="owl-example">
                <!-- owl content goes in here (its dynamically loaded) -->
            </div>
        </div>
        <div class="col-md-6">
            <div class="owl-carousel-3" id="owl-example-2">
                <!-- owl content goes in here (its dynamically loaded) -->
            </div>
        </div> 
    </div>
</div>
```

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
