### ISSUE TITLE
Possible to add a depth effect?

### ISSUE THREAD

**Issue by seanhak** [OwlCarousel2/OwlCarousel2#2173]
If we have a carousel with 3 items, its easy to give "depth" to active center item. like this: oOo
Is there a way to do this with 5 items? 
.oOo.
Would I do this best with JS or CSS?

JS I would imagine I would have to find the center one, and add sibling css classes with distance from center.

And with CSS maybe something like this: ?
.item{ transition: transform; scale(0) }
.item.active{ transform: scale(.0.5); }
.item.active:nth-child(even){ transform: scale(0.8) }
.item.active.center{ transform: scale:(1) }

Edit: fixed syntax.

**Comment by keefyhub** [comment]
I did something similar with 3 items - https://codepen.io/keefyboooo/pen/LWRjoj

I used the `center: true` option which added a class on the middle item (when using 3 items). Not sure how it would work with 5 and it is a bit buggy when skipping more than 1 slide at a time

**Comment by seanhak** [comment]
Cool! Actually my nth child solution almost worked, except nth-child reports odd items as even. Maybe the browser caches the odd/even state or something.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
