### ISSUE TITLE
Load carousel with dinamyc elements

### ISSUE THREAD

**Issue by NandoKstroNet** [OwlCarousel2/OwlCarousel2#2175]
Hey everybody!

I have a small question, how can I reload the carousel after adding dynamic elements in the div?

For example, after this:

`$(".owl-carousel").html(html);`

Thanks!

**Comment by keefyhub** [comment]
You could try [refresh.owl.carousel](https://owlcarousel2.github.io/OwlCarousel2/docs/api-events.html#refresh-owl-carousel)

Or you could only initialise the plugin after you have added the HTML

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
