### ISSUE TITLE
Pass to next slide after youtube video ends.

### ISSUE THREAD

**Issue by cacacobra** [OwlCarousel2/OwlCarousel2#2177]
Is it possible to skip to next slide after Youtube video ends?

I am going to post below my piece of code, it works just fine, but after the video finishes is get stuck.

`$(document).ready(function(){

  
    var owl = $('.owl-carousel');

    /* */
     owl.on('initialized.owl.carousel', function(e){
                  //alert('translated')
               setTimeout(
                  function() {
                      
                     $(".active .owl-video-play-icon").trigger("click");
                      
                 }, 1500);
           
     })
      
    
      
     /**/
     owl.on('translated.owl.carousel', function(e){
           
                 $(".active .owl-video-play-icon").trigger("click"); 
           
     })
     

  
    owl.owlCarousel({
            autoplay:true,
            autoplayTimeout:300000000,
            items:1,
            //singleItem : true,
            merge:true,
            loop:true,
            margin:0,
            
            navText: ["Ant.","Próx."],
            
            //autoWidth: true,
            //autoHeight:true,
            
            //videoHeight: 600, 
            //videoWidth: 300,
            
            
            video:true,
            //videoHeight: 538,
            //videoWidth:true,
            
            //animateOut:true,
            //animateIn:true,
            
            lazyLoad:false,
            center:true,
            nav:true,
            dots:true,       
            
            //onInitialized: fixOwl,
            //onRefreshed: fixOwl,
            
            //onChanged:alert('changed'),
            
            
            responsive:{
                480:{
                    items:1
                },
                600:{
                    items:1
                }
            }
    })
    
   // var $owl = $('.owl-carousel').owlCarousel({ autoWidth: true }).trigger('refresh.owl.carousel');

});`

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this is not an "issue". Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
