### ISSUE TITLE
Auto Height and Multiple Items

### ISSUE THREAD

**Issue by wesearl91** [OwlCarousel2/OwlCarousel2#2179]
Auto height is only taking into consideration the height of the first item even though there is 3 on show, therefore cutting the bottoms off the other items if they are larger. How would I go about it recognising the height of the tallest of the 3 and using that height every time a new one enters the viewing carousel 
  

    $('.owl-carousel').owlCarousel({
    loop:false,
	navRewind: false,
	autoHeight:true,
	  nav: true,
          navText: ['<span class="previous-step-button step-button"><span class="fa fa-chevron-circle-left"></span> Previous Step</span>','<span class="next-step-button step-button">Next Step <span class="fa fa-chevron-circle-right"></span></span>'],
        margin:30,
	items:3,
        responsiveClass:true,
        responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:3,
            nav:false
          },
        1000:{
            items:3,
            nav:true,
            loop:false
            }
        }
    });

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!
