### ISSUE TITLE
Swiping on Mobile the whole page moving up and down

### ISSUE THREAD

**Issue by krishhnaa** [OwlCarousel2/OwlCarousel2#2181]
I am facing an issue with the Owl carousel. While Swiping the carousel on the mobile (iphone) the entire page is moving. Is there any fix for this issue? Can someone reply on this ?

**Comment by rochabianca** [comment]
+1 on this

**Comment by rochabianca** [comment]
For me what worked was not using flex container

founded here: https://github.com/OwlCarousel2/OwlCarousel2/issues/1903

**Comment by krishhnaa** [comment]
@rochabianca  do you have the same issue while swiping? its frustrating it is working fine on androids

**Comment by rochabianca** [comment]
Yep, for me changing the main div for display: inline-block (or block) solved.
But it seems like this problem only occurs on Chrome, Safari worked fine too.

**Comment by krishhnaa** [comment]
@rochabianca No I am using safari only on iphone. it is happening for me I mean the issue is there in safari ..

**Comment by krishhnaa** [comment]
@rochabianca what is main div means? i will try to add display property

**Comment by rochabianca** [comment]
I'm using a main div with two divs inside it, something like this:
<div>
  <div></div>
  <div></div>
</div>

but I think you're having this problem in a app, so maybe my solution won't work for you

**Comment by rochabianca** [comment]
Oh, so if you are using display: flex, maybe take off this solve it

**Comment by pascalporedda** [comment]
Hey @krishhnaa sorry for the late reply, have you found a solution to your problem?

If not please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by krishhnaa** [comment]
@pascalporedda Its ok. I am still facing that issue only on Iphones. Here is my codepen https://codepen.io/krishnay/pen/Vyjrwj . I attached the bug video for reference.
[bug.mov.zip](https://github.com/OwlCarousel2/OwlCarousel2/files/1718461/bug.mov.zip)

**Comment by krishhnaa** [comment]
@pascalporedda Do you have any solution to solve the issue?

**Comment by pascalporedda** [comment]
As far as I can see it, this is fixed with v2.3.1. If you still encounter any problems, feel free to reply me and I will reopen this issue.
