### ISSUE TITLE
Item Width Issue

### ISSUE THREAD

**Issue by abhi0001ch** [OwlCarousel2/OwlCarousel2#2182]
When I apply owl carousel then the width of item is 421px it didnot show single item it show 3 item in a row . I also used singleItem property but it is not working. Please reply me fast.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
