### ISSUE TITLE
vanilla JS

### ISSUE THREAD

**Issue by kikeestrada** [OwlCarousel2/OwlCarousel2#2183]
Hi 

do you have plans to implement a new version made in vanilla JS?

Best Regards!

**Comment by landsman** [comment]
Really good idea. I don't want use carousel with jQuery more.

**Comment by pascalporedda** [comment]
Hey @kikeestrada and @landsman ,

there are no plans to implement a vanilla JS version, at least not in the next few months. There are a lot of bugs that need to be fixed first.

Once those bugs should be fixed there might be a chance to implement a VueJS version of this carousel, but no vanilla JS.

**Comment by landsman** [comment]
Do you work with ES6? It's really great for clean code, workflow.
VueJS allow import vanilla, es6 code as well.

**Comment by pascalporedda** [comment]
Yeah have been working a lot with it lately, it's definitely awesome but we'll have to look at this for this project at another point.

**Comment by garygreen** [comment]
@pascalporedda why Vue? Your considering switching from jQuery, the most ubiquitous framework on the planet, to far smaller opinionated framework? As much as I love Vue, I would not like to see a Vue version of owl carousel. It makes no sense. I would however like to see a Vanilla implementation of the carousel.

There is one already available called [Glide](https://github.com/glidejs/glide) however it doesn't work as seamlessly as Owl carousel even though it does have a similar feature set.

I really hope to see a vanilla version being made, or at least efforts to less rely on jQuery internally. There is no reason a carousel needs Vue, React, Angular, Ember, or put whatever framework you need here X. Straight up Javascript gives the freedom to incorporate the package into whatever project you like.

**Comment by andyduong1920** [comment]
@garygreen You can check https://github.com/ganlanyuan/tiny-slider

**Comment by Spider149** [comment]
If you want to use a library similar to owl carousel written in vanillaJS, try this: https://spider149.github.io/own-carousel/
