### ISSUE TITLE
1px Height Video Background

### ISSUE THREAD

**Issue by robertrhu** [OwlCarousel2/OwlCarousel2#2185]
I have a slider setup that can hold a Vimeo/Youtube video or images.

The video is the first slide.

On load of the page, the first slide has a background image pulled in from the video service (vimeo/youtube) and appears to play a role in collapsing the .owl-stage-outer .owl-height classes to a 1px height. Once I scroll to the next slide and then back, the video/video background image appears and sets the height for these classes properly.

I've searched through SO MANY proposed solutions in this repository and on the web but haven't found anything that works to fix the issue. It seems many have struggled with a similar issue. 

This is literally the last bug I have to fix on this website. Would be so amazing if anyone had some additional insight.

I've tried using a plugin called imagesLoaded, as was suggested in this repository, but its kicking an error of 'imagesLoaded is not a function'. The javascript is installed properly. I'm not sure why its not recognizing the function.

I've tried both ways of initializing:
$(window).load(function(){
and
$(document).ready(function(){

Would love to have a fix that is native to Owl. Has this issue been successfully addressed? Would be so grateful for some assistance.

Thanks!

Here's an example page: http://desrosiers.robertrhu.com/

This is the code I'm working with:
```
<?php

/* Home Page image Slider */

?>

<script>
    $('.item-video').imagesLoaded({
        background: true
    }, function( imgLoad ) {
        $status.text( imgLoad.images.length + ' images loaded checking backgrounds' );
    }
                          );
</script>

<script>
    $(window).load(function(){
        //Initialize Owl Carousel Javascript
        $("#home-slider").owlCarousel({
            items: 1,
            loop: true,
            nav: true,
            navText: [
                "<img src='<?php echo get_template_directory_uri(); ?>/assets/images/desrosiers-architects-image-slider-arrow.png' />",
                "<img src='<?php echo get_template_directory_uri(); ?>/assets/images/desrosiers-architects-image-slider-arrow.png' />"
            ],
            margin: 0,
            dots: false,
            autoplay: false,
            animateOut: 'fadeOut',
            video: true,
            responsive: true,
            autoHeight:true,


        });
        // var mainCarousel = $("#home-slider");
        // mainCarousel.find('.owl-stage .slide').css('height', mainCarousel.find('.owl-stage-outer').height());

    });
</script>
<!--Begin Home Page Property Hero Slider-->

<ul id="home-slider"
    class="owl-carousel">

    <?php if( have_rows('home_page_slider', 'option') ): ?>
        <?php while( have_rows('home_page_slider', 'option') ): the_row();

        //Variables
        $image = get_sub_field('home_page_photo', 'option');
        $vedio = get_sub_field('homepage_vedio', 'option');
        $alt = get_sub_field('home_page_photo_alt', 'option'); ?>

        <li class="slide item-video">
 <?php  if(!empty( $vedio) ){ ?> <a class="owl-video" href="<?php echo $vedio; ?>"></a> <?php } else { ?>
          <img class="slide-image"
                 src="<?php echo $image; ?>"
                 alt="<?php echo $alt; ?>" />
    <?php  } ?>
        </li>

        <?php endwhile; ?>
    <?php endif; ?>

</ul>
```

**Comment by robertrhu** [comment]
Came up with a solution. 
```
var carTimer = setInterval(function() {
if(owlCar.height() > 1) clearInterval(carTimer);
owlCar.trigger('refresh.owl.carousel', [100]);
}, 300);
```
Here owlCar is the instance of owl carousel
( var owlCar = $(".owl-carousel").owlCarousel({options}) )

We are triggering a refresh event on owl every 300 ms until it gets a height. Once it gets a height the event is no longer triggered. window.load was not working because the site is loading slowly.

Hopefully this can help someone else.

**Comment by pascalporedda** [comment]
Hey,
glad you've found a solution to your problem. I'll be addressing an issue related to the auto height plugin that might solve this bug in a future release.
