### ISSUE TITLE
Can't click on the link while mouseDrag is true

### ISSUE THREAD

**Issue by robizzt** [OwlCarousel2/OwlCarousel2#2186]
I don't know if this is an issue, but if someone could tell me how can I click and open a link inside carousel while mouseDrag is true. Thank you very much.

**Comment by lilisath** [comment]
> while mouseDrag is true
Did you try to disable mousedrag? If yes, hrefs  were working?

**Comment by robizzt** [comment]
Yes. It works while mouseDrag is disabled. But I want it to works while mouseDrag is enabled, too.

**Comment by lilisath** [comment]
For me it didn't work. Could you please upload a snippet of your code ?

**Comment by robizzt** [comment]
`
<div id="main-slider">
  | <div id="introSliderImg" class="owl-carousel">
  | <section class="slider-img bg1">
  | <div class="slider-text container">
  | <div class="rightBottom">
  | <span>Subtitle 1</span>
  | <a href="#"><h1 class="carouselBig">Title 1</h1></a>
  | </div>
  | <div class="next-item d-none d-xl-block block-center"><span class="centered"></span></div>
  | </div>
  | </section>
  |  
  | <section class="slider-img bg2">
  | <div class="slider-text container">
  | <div class="rightBottom">
  | <span>Subtitle 2</span>
  | <a href="#"><h1 class="carouselBig">Title 2</h1></a>
  | </div>
  | <div class="next-item d-none d-xl-block block-center"><span class="centered"></span></div>
  | </div>
  | </section>
  |  
  | <section class="slider-img bg1">
  | <div class="slider-text container">
  | <div class="rightBottom">
  | <span>Subtitle 3</span>
  | <a href="#"><h1 class="carouselBig">Title 3</h1></a>
  | </div>
  | <div class="next-item d-none d-xl-block block-center"><span class="centered"></span></div>
  | </div>
  | </section>
  | </div>
  | <div id="customDots" class="owl-dots"></div>
  | </div>
`

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
