### ISSUE TITLE
Owl autoplay loop, but don't clone

### ISSUE THREAD

**Issue by jackdaniel9** [OwlCarousel2/OwlCarousel2#2187]
Hi,

I make a website with multiple Owl Carousel but in Internet Explorer 11 the website is very slow (work fine with chrome), i discover the website is slow because we have "loop:true" and "autoplay:true" and owl clone multiple item. 

It's possible to have "autoplay" to true but don't clone item... and when autoplay is end, restart to start.

Thank's

**Comment by pascalporedda** [comment]
Hey @jackdaniel9 ,

this is sadly not possible. We aiming to improve the clone mechanism in a next release, but there is no option to disable it completely.

**Comment by omaracrystal** [comment]
@pascalporedda 
Any movement on this?

**Comment by omaracrystal** [comment]
@jackdaniel9 @pascalporedda 
I finally figured out a solution!!

Try this:

loop: false,
rewind: true

**Comment by Nurbek0525** [comment]
@omaracrystal 

it is not working 
do you have other solution

**Comment by owaisshahab123** [comment]
not working :(

**Comment by Brian10257** [comment]
when i set loop to false only one item will be displayed on the web site and not all the items i entered in the admin area

**Comment by BajwaSon** [comment]
Try this.....
autoplay:true
rewind:true

**Comment by web-burn** [comment]
@omaracrystal good solution, suits for me

**Comment by amirehsan1370** [comment]
> @jackdaniel9 @pascalporedda I finally figured out a solution!!
> 
> Try this:
> 
> loop: false, rewind: true

Good Solution thanks

**Comment by rajatcb** [comment]
loop: false
will stop cloning elements
