### ISSUE TITLE
Increasing main center image, reducing side images

### ISSUE THREAD

**Issue by RafaeldelM** [OwlCarousel2/OwlCarousel2#2190]
Hi,

Now the side images are about 50%, is there a way to increase main centered image and reduce the sides?

<img width="1360" alt="captura de pantalla 2018-01-15 a les 15 34 19" src="https://user-images.githubusercontent.com/33693330/34947226-cfca190a-fa09-11e7-8bb0-bb82c5adf6d2.png">

Thanks,

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
