### ISSUE TITLE
hide elemt and rebuild 

### ISSUE THREAD

**Issue by kapara** [OwlCarousel2/OwlCarousel2#2191]
Hi, I have problem: I have list of brands, from the begining all brands in carusel, but after I have dropdown menu to choose specific brand (by value) and whant show only lements with this brand.
<div class="owl-carousel owl-loaded">
  <div class="box" data-brand="23">
    ......
  </div>
</div>
Help please who know how it posible?!
Tnx

**Comment by altafhpatel** [comment]
One possibility is to get the value from the drop down and remove the items which match the class in slider.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
