### ISSUE TITLE
On Mouse scroll Go to Next slide

### ISSUE THREAD

**Issue by altafhpatel** [OwlCarousel2/OwlCarousel2#2192]
i Have a slider with full width and height one item per slide. I have enabled the url-hash as well....

when i enable mousewheel it go to random slide i want one slide per scroll how can i accomplish that

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
