### ISSUE TITLE
Modal owl-hidden incorrect width

### ISSUE THREAD

**Issue by krisstoof** [OwlCarousel2/OwlCarousel2#2193]
Items overlap eachother, but when i resize window, everything goes back to normal. It should display 4 items.
![trouble](https://user-images.githubusercontent.com/17534448/35055362-53eee584-fbaf-11e7-9864-54efd10453f2.PNG)

![should](https://user-images.githubusercontent.com/17534448/35055518-acc2518c-fbaf-11e7-8d2e-8178fa0194cc.PNG)

Wrong owl-stage width and also wrong owl-item width. Slider is inside bootstrap modal. Outside of modal is working as it should be, but inside I'm getting this trouble.

I found that this problem has something with owl-hidden class. It's only applied when modal is hidden and when i resize this class i added to slider.

I have made further progress with this problem and I found that owl-carousel version in project is 2.0.0 and my version in layout was 2.2.1.  In newer version there is method AutoRefresh.

**Comment by krisstoof** [comment]
Was there any solution to work with owl carousel 2.0.0 and bootstrap modal. So it won't break as you see on screenshot. I can't change to newer version, so I must to fix somehow with 2.0.0 version.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!
