### ISSUE TITLE
Some portion of inactive item is also visible. Space after last item.

### ISSUE THREAD

**Issue by abhishek-0** [OwlCarousel2/OwlCarousel2#2200]
Hi, I'm using ngx-owl-carosel. I've got this problem, sometimes I see a little part of the next item at the end which is not active at that time. I get this problem sometimes, not always.
When I inspect to see, I saw that, the container "owl-stage-outer" is having that space at the end. and "owl-stage" is not taking it's full width. May be this space is equal to the given margin to items.

Can anyone please help me out with this. I face it a lot.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!
