### ISSUE TITLE
Different Animation on prev and next slide change (Animation from animate.css)

### ISSUE THREAD

**Issue by lukasz-pawlowicz** [OwlCarousel2/OwlCarousel2#2201]
Hi!
Is there a chance to force on slider different animation when I'm using a custom slide Effects from animate.css ?

Example: 
On default slide to right carousel action I have animation that fade to right, but when I click to get previous slide, animation is the same and it's not looking good.

**Comment by pascalporedda** [comment]
Same as #2214 . 

You can feel free to submit a PR for this feature.
