### ISSUE TITLE
OwlCarousel V1.3.2 - jumping to a specific slide

### ISSUE THREAD

**Issue by videotomNYC** [OwlCarousel2/OwlCarousel2#2202]
We have an About page that contains 5 video reels within the Owl carousel: http://24fpsproductions.com/24fps/about.html (Television, Commercial, Digital, Food, and Corporate)

We want to be able to link people to specific slides both from within the site and externally. For example, we would add a submenu under the "About" menu to include direct links to all 5 reels. So if someone was on our site, and selected About>Reels>Digital, the About page would open, and the Carousel would queue up to the Digital reel. Or, we could send an e-mail with a link that goes directly to the About page, queuing up the Food reel.

This seems to be possible, though I don't see a solution here on the forum. There are related posts, but nothing that tackles this specific challenge.

Lastly, we have other carousels on our site, so I would want the solution to apply only to this carousel.

I'm hoping someone can help.

Thank you!

**Comment by pascalporedda** [comment]
Hey @videotomNYC 

I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community. But as much as I've read through this, you should be able to achieve this via hash navigation.
