### ISSUE TITLE
Stage padding option: only right padding 

### ISSUE THREAD

**Issue by SiberMedya** [OwlCarousel2/OwlCarousel2#2203]
Stage padding option: only right padding is possible?

Stage padding option adds left and right padding style (in pixels) onto stage-wrapper.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

You can always add padding via CSS though.

**Comment by Poozan379** [comment]
.owl-stage{padding-left:0px !important;}

try this :)

**Comment by fajriyan** [comment]
thanks, I did it :)
