### ISSUE TITLE
Size merged item should be (one margin size) bigger

### ISSUE THREAD

**Issue by davidlok** [OwlCarousel2/OwlCarousel2#2204]
I was trying to align my Owl carousel with my bootstrap grid. As soon as I want to use the "merge" option I run into alignment problems. The item that is merged (data-merge="2") is to short. I think this merged item should be one margin size bigger. Is there a way to fix this?

Example: https://jsfiddle.net/9ve7k8dq/22/

**Comment by davidlok** [comment]
Created a version without setting the margin. Now alignment is perfect:
https://jsfiddle.net/9ve7k8dq/24/

Remove the padding on the bootstrap container and set margin 0 15px for the slides.

**Comment by pascalporedda** [comment]
Seems like you've fixed your problem.
