### ISSUE TITLE
TypeError: $(...).owlCarousel is not a function

### ISSUE THREAD

**Issue by GerasimenkoEdward** [OwlCarousel2/OwlCarousel2#2207]
Hello.
Help me anybody! I connected in gulpfile.js : 
'app/libs/owlcarousel/dist/assets/owl.carousel.min.js',
Also I wrote it:
@import "app/libs/owlcarousel/dist/assets/owl.carousel.min"
@import "app/libs/owlcarousel/dist/assets/owl.theme.default.min"
in the sass-file.
I wrote : 
**$('.owl-carousel').owlCarousel({
		loop: true,
	});** 

But I got this error : **_TypeError: $(...).owlCarousel is not a function_**
Why?
For example, this function is working very good: 
**$(function() {
	$("ul .sf-menu").superfish({
		cssArrows: false,
		hoverClass: 'sfHover',
	});**

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
