### ISSUE TITLE
Carousel splits in to multiple rows 

### ISSUE THREAD

**Issue by dulara1994** [OwlCarousel2/OwlCarousel2#2215]
My carousel Splits in to two rows. my carousel initilization script is as folows. 
javascript
```
$('.owl-carousel').owlCarousel({
                loop:true,
                margin:10,
                nav:true,
                responsive:{
                    0:{
                        items:3
                    },
                    600:{
                        items:3
                    },
                    1000:{
                        items:3
                    }
                }
                });
```

![2018-02-10 09_58_38-start](https://user-images.githubusercontent.com/26034746/36058720-22a2b92c-0e4e-11e8-916f-2b84dd489e90.jpg)

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
