### ISSUE TITLE
bug In AutoPlay but i solved it

### ISSUE THREAD

**Issue by saddambhati** [OwlCarousel2/OwlCarousel2#2216]
Hi sir, there are bug in autoplay
![untitled](https://user-images.githubusercontent.com/36396217/36085144-83860482-0fe9-11e8-94bd-dc65e9dc190d.png)

this is screenshot of live url of owlcarousel website..

this is the variable name in this code autoplay:true

 its a typing error defines the variable as "autoPlay"

**Comment by pascalporedda** [comment]
Hey @saddambhati 

thanks for spotting this, I'll be fixing this.

**Comment by shbhati** [comment]
welcome sir
