### ISSUE TITLE
Uncaught TypeError: Cannot owl.carousel.min.js:1

### ISSUE THREAD

**Issue by eladnm** [OwlCarousel2/OwlCarousel2#2221]
Please try to help me with this error:

Uncaught TypeError: Cannot read property 'clone' of undefined
This come from the owl carousel but i dont know how to fix it. check my website in console
[http://159.89.224.110/](url)

thanks

**Comment by pascalporedda** [comment]
@eladnm 

Hey i've been looking in the console but wasn't able to spot any issue.

**Comment by pascalporedda** [comment]
Since you didn't replied I will assume that you found a fix for your issue and will therefore close this.
