### ISSUE TITLE
mouseDrag and touchDrag do not work if you connect elfinder.min.js

### ISSUE THREAD

**Issue by amigoscs** [OwlCarousel2/OwlCarousel2#2222]
The essence of the problem I described in the title. mouseDrag and touchDrag does not work if the page has elfinder.min.js

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Comment by pascalporedda** [comment]
Since you didn't replied I will assume that you found a fix for your issue and will therefore close this.
