### ISSUE TITLE
How to change images based on screen size?

### ISSUE THREAD

**Issue by AF4Q** [OwlCarousel2/OwlCarousel2#2224]
Hello,

I have a bought a Magento theme which is using Owl as a slider on the homepage. However, there is one issue that I seem to be running in to. The slider size is not response i.e. it looks good on big screen (laptops, desktop) but on mobile devices it gets very small as compared to other images on the page. 

The solution I have thought to tackle this issue is to load different images in the owl slider on smaller screens. Can you tell how can I achieve this?

Here is the link to the demo of the theme: http://themes.magesolution.com/claue/m2/

Thanks.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
