### ISSUE TITLE
fix for loading image I mean "height: 0"

### ISSUE THREAD

**Issue by Simon1111** [OwlCarousel2/OwlCarousel2#2225]
Sometimes picture dont load and gallery add "height: 0",
`
$(document).ready(function() {
$(".ishod img").load(function() {
    var height = $(this).height();
    var width = $(this).width();
});
`
maybe you add method load or onload in gallery?!
__

Will be plus:
1) if "owl-item" alone and dont have any picture then add class "owl-stage-outer-alone" {.owl-stage-outer-alone {
    pointer-events: none;
}}
2) owl-next owl-prev --- add class "last" if we don't prev or next picture, and add class "none" if we have only one picture
3) add opportunity destroy gallery for same screen like was in version 1
___

Also, thank you for you gallery!
I use it  always with fancybox3,  when I use JQ :+1:

**Comment by pascalporedda** [comment]
Hello @Simon1111 

I guess you've been using the auto height plugin? I've merged a change addressing this kind of issue.

If you weren't using the auto height plugin you may provide me an example showing me what you actually mean.

**Comment by pascalporedda** [comment]
This issue should be fixed with v2.3.2.
