### ISSUE TITLE
Trying to keep "prev" and "next" visible always on mobile

### ISSUE THREAD

**Issue by boydcc18** [OwlCarousel2/OwlCarousel2#2228]
Hey,

new to programming.  started a wordpress blog: whynottotravel.com.  1st Big custom css success- editing stuck header color and substituting my own background image using css.

Now, I wish to make the owl carousel a little different. I wish to keep the "prev" and "next" buttons always visible, before a user touches the picture. Is this possible with custom css?

I'm playing around with Inspect, where I found this is called owl carousel.  unable to really nail anything down in terms of changes.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
