### ISSUE TITLE
is it support in angular 4

### ISSUE THREAD

**Issue by hemanthsp** [OwlCarousel2/OwlCarousel2#2230]
is this lib support in angular 4

**Comment by pascalporedda** [comment]
Why don't you try it out? I haven't tried so I cannot give you an accurate answer to this. Just try it out.

**Comment by hemanthsp** [comment]
try ha!!!!! , it is very difficult to install in angular 4 project , make
one video like how to install owl lib in angular 4 and upload on YouTube,
then i will try and say the result

**Comment by ayttunc** [comment]
I am speechless
