### ISSUE TITLE
How to cancel a click on a link

### ISSUE THREAD

**Issue by zahar92** [OwlCarousel2/OwlCarousel2#2231]
Hello! I ask for help! I need to cancel the standard browser action when clicking on the link. In JS I'm not strong, but in Google found that it can be done using e.preventDefault ();
When the slider is booted, the event is canceled when clicked. But when you drag on a new slide, the link goes through despite e.preventDefault ();
**Now the function looks like this:**
`$('a[class*="_toggler"]').click(function (e) {
	e.preventDefault();
})`

In the documents found that you can track the slide movement and perform the function. But how to use this design I do not know, not enough knowledge! ((
**The event handler from the documents on the official site looks like this:**
`$('.owl-carousel').owlCarousel({
    onDragged: callback
});
function callback(event) {
    ...
}`

How can I merge them so that after moving the slide and clicking on the link there is no transition? Can eat a method easier?

Thanks for the help!

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
