### ISSUE TITLE
Left and right arrows outside slideshow?

### ISSUE THREAD

**Issue by dmwhipp** [OwlCarousel2/OwlCarousel2#2233]
Finally trying to learn responsive design and needed a slideshow. I was able to easily get Owl Carousel up and running on one page and love it (right above footer on test page): http://cismiami.org/new.html

I'd like to tweak the slideshow to use for staff photos: http://cismiami.org/owlstaff.html

I found instructions here for switching to arrows and getting them on the same line as the images, but for the life of me cannot figure out how to get them to appear outside the image carousel instead of superimposed on them. I'm using a separate folder for the CSS files so I don't mess up the first sample, but here are my CSS files for the Staff page:

- http://cismiami.org/js/owlstaff/assets/owl.carousel.css
- http://cismiami.org/js/owlstaff/assets/owl.theme.default.css

Any help would be greatly appreciated.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

You should get this to work with some custom css.
