### ISSUE TITLE
Page turn transition effect

### ISSUE THREAD

**Issue by pennybuster** [OwlCarousel2/OwlCarousel2#2235]
Hey there! Can somebody please help me implement the following transition effect to the slider?
Demos:
https://codepen.io/maple-leaf/pen/QwvgLQ
https://tympanus.net/Tutorials/FullscreenBookBlock/
http://wowslider.com/css-slider-aqua-flip-demo.html (choose More>Book to see)
Thanks a lot!

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
