### ISSUE TITLE
Text in slider animation

### ISSUE THREAD

**Issue by annert7** [OwlCarousel2/OwlCarousel2#2236]
### A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.>
1. This is the first step
2. This is the second step
3. Further steps, etc.

_____________
### `<url>` - a link to the reduced test case. You can use one of the following services:
- https://codepen.io/anon/pen/prvbMp
- https://jsfiddle.net/h8x8bvn9/2/) 
- https://jsbin.com/bojonaceve/2/edit?html,js,output

_____________
### Any other information you want to share that is relevant to the issue being reported.
This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by annert7** [comment]
Sorry I am new to this....
I need help animating text to slide up. I have got very basic understanding of css & WordPress please help me.
Many thanks

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
