### ISSUE TITLE
CSS error

### ISSUE THREAD

**Issue by EpicKau** [OwlCarousel2/OwlCarousel2#2237]
version 2.2.1
cloudflare cdn
/assets/owl.carousel.min.css

Its not really an error or a bug but you'r src is wrong.

`.owl-carousel .owl-dot, .owl-carousel .owl-nav .owl-next, .owl-carousel .owl-nav .owl-prev {
cursor:hand
}
`

cursor:hand is not supported, please delete.

**Comment by pascalporedda** [comment]
@EpicKau Might you consider to open a PR for this?

**Comment by pascalporedda** [comment]
Will be fixed with #2256.
