### ISSUE TITLE
How do i identify and change the background color of the active dot when using a custom dotsContainer in owl carousel 2

### ISSUE THREAD

**Issue by Chamathfernando** [OwlCarousel2/OwlCarousel2#2238]
I am creating an owl carousel with a custom dotsContainer. I want to change the background color of the dot when it is clicked. Can someone help me with this.

Here is the fiddle URL for the website i am developing. 
https://jsfiddle.net/Chamath_Fernando/n6gsf5tr/

Thank you in advance!

**Comment by pascalporedda** [comment]
Hello this is not a bug related to the OwlCarousel, please ask such questions on a platform like stackoverflow.

**Comment by suriya-a9** [comment]
https://github.com/OwlCarousel2/OwlCarousel2/issues/2238#event-1514706647
