### ISSUE TITLE
Everything broken when showing single image in a slide (bug since 1 year...)

### ISSUE THREAD

**Issue by wateround** [OwlCarousel2/OwlCarousel2#2242]
All in comment.

I saw alot of issues about this, and there is no fix, i can't really understand.

But it pretty weird bug that has not been fixed since like 1 year... ?

**Comment by wateround** [comment]
I mean, there no official OwlCarousel fix.

Not a single line of code. LOL

**Comment by pascalporedda** [comment]
Might you consider trying this in 2.3.1? I don't really know which issue you mean though.

**Comment by dgopress** [comment]
Hello there. Thats my issue too. In the official site https://owlcarousel2.github.io/OwlCarousel2/demos/demos.html doesn't have an option with one slide. I just wanna show one image at a time in my slider. 
Like this example:
![image](https://user-images.githubusercontent.com/15031908/37798993-bc28f960-2df4-11e8-8bdd-0164381b2446.png)

I have multiples images in my site, but it shows 3 at a time. Thats my page: http://clientes.doca21.com.br/modelo_cleber/

Do you know what I mean? Istead of showing 3 at a time, I just wanna show 1 at a time.
Thanks in any advance.

**Comment by pascalporedda** [comment]
Simply set option items to 1, there are many sites used by our clients that are using single image slides that are working fine.

As far as I can see it, there is no problem existing. If you still encounter any problem feel free to reply to me.

**Comment by dgopress** [comment]
@pascalporedda Hi there! Thanks for your answer. Now I'm having some styling trouble. The arrows of sliders appears at the bottom of slider, and the dots doesn't appears. Thats my config.
`		$(document).ready(function(){
		  $(".owl-carousel").owlCarousel({
			items:1,
		  	autoplay:true,
		  	loop:true,
		  	nav:true,
		  	dots:true,
		});
		  });
`
and thats the result (look at bottom left)
![image](https://user-images.githubusercontent.com/15031908/37854430-48dc76ee-2ec1-11e8-8d58-6e8a8b86a25c.png)

Thanks in any advance.

**Comment by wateround** [comment]
Thank for everyone for all great comment.

But there still a bug.

Ex: i have slider with 3 banners. But if i remove 2 or this banner, that all broke.

:(

Thank everyone for help but that not fixed :(

Thank :)

**Comment by dgopress** [comment]
@wateround can you share your link, or paste your code here?

**Comment by dgopress** [comment]
@pascalporedda I'm experiencing some navigation trouble on mobile. My slider shows really big on mobile and the scroll doesn't work when I try to scroll the page. There's any way to fix that?

**Comment by pascalporedda** [comment]
The vertical scroll option, when scrolling on the carousel has been disabled be default. You can change this via css by adding touch-action: pan-y; to the .owl-item class

**Comment by kgrant-rp** [comment]
2021 Owl carousel still does not work in any respect.
None of these issues are fixed.
