### ISSUE TITLE
Foundation Webpack issue

### ISSUE THREAD

**Issue by gabrielbajada** [OwlCarousel2/OwlCarousel2#2244]
Hello,

This isn't really an issue with OwlCarousel but I've scoured the internet and didn't know where else to ask.

I usually use Owl Carousel with Foundation via JointsWP, a theme for WordPress. This time i'm trying to integrate it with Foundation for sites. 

Could someone please guide me as to where the following code should be placed. 

```
//...
plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery'
    }),
],
//...
```

I know this might be a stupid question, but I've never worked with Webpack before.

Thank you,

Gabriel

**Comment by pascalporedda** [comment]
Hello @gabrielbajada ,

is your project using webpack? If so there should be a webpack.config.js or sth. similar, there you should add it. If your project isn't using webpack at all, you might consider simply using sth. like gulp or grunt or any kind of cdn.

**Comment by gabrielbajada** [comment]
Yeah, I ended up adding it to gulpfile.babel.js.

Thanks for your help!
