### ISSUE TITLE
How to correctly associate a select  option with slider?

### ISSUE THREAD

**Issue by DmitriyShvanyk** [OwlCarousel2/OwlCarousel2#2245]
Hello
Code - https://jsfiddle.net/6kh4mr4v/
why the selected option 8 - the fifth slide is selected.
Thanks

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
