### ISSUE TITLE
Dist CSS has a SCSS variable in it

### ISSUE THREAD

**Issue by jordie23** [OwlCarousel2/OwlCarousel2#2247]
{$owl-image-path} is hardcoded into https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/dist/assets/owl.carousel.css

Same with the minified version:

https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/dist/assets/owl.carousel.min.css

It's causing issues as we compile the owl carousel css into our bigger app and now it's got an undefined scss variable error

version 2.3.1

It appears it was added in https://github.com/OwlCarousel2/OwlCarousel2/commit/d4973a7ccca2a941716678ecaca5868bc968332b

**Comment by pascalporedda** [comment]
#2246 Fixed it. Will make a bugfix release for this.

**Comment by jordie23** [comment]
Thanks :)
