### ISSUE TITLE
Unable to disable rewind

### ISSUE THREAD

**Issue by YellowCrocus** [OwlCarousel2/OwlCarousel2#2249]
I want to create an 'infinite' loop and therefore tried to set the rewind-value to false. However, this does not disable the rewind animation at all. I've tried alternatives and searched for a solution but couldn't find anything. Below is the code I'm using. Everything else is working fine so far.

```
<script>
		  $(".owl-carousel").owlCarousel({
		  	loop:true,
		    margin:10,
		    nav:true,
		    rewind:false,
		    center:true,
		    autoplay:true,
		    autoplayTimeout:4000,
			autoplayHoverPause:true,
		    responsive:{
		        0:{
		            items:1
		        },
		        600:{
		            items:1
		        },
		        1000:{
		            items:1
		
```

**Comment by jacktown11** [comment]
I've come across the same question, and I have tested older versions. This bug exist from 2.3.1. And unfortunately another feature I need doesn't function in 2.x, so hoping the problem to be fixed.

**Comment by nunoguerra** [comment]
One more here.

**Comment by YellowCrocus** [comment]
@jacktown11   You're right, I switched to v2.2.1 and the rewind issue, as well as another issue I was having, was resolved.

**Comment by nginex** [comment]
Try the solution described here #2261

**Comment by YellowCrocus** [comment]
Works for me, thank you!
