### ISSUE TITLE
Why Navigation change structure (navclass)???

### ISSUE THREAD

**Issue by MarsDiep9** [OwlCarousel2/OwlCarousel2#2251]
We use owlcarousel for us themes. And now, when we update version 2.3.0 (auto update by nodejs), then it not working. We find out navigation plugin change class? please help me, we have more 100 themes, we can't change css, because It is very time consuming.

**Comment by pascalporedda** [comment]
Hello @MarsDiep9 

could you provide me with a JSFiddle or sth. similar by what you mean? I don't know about any navigation structural changes.

**Comment by nginex** [comment]
In your owl settings you can change all what you need

See a full list of options for navigation plugin.

<img width="450" alt="screenshot 2018-03-21 21 04 22" src="https://user-images.githubusercontent.com/5188136/37731708-87dc6cd6-2d4b-11e8-8ad5-b8bc5a825f48.png">

**Comment by pascalporedda** [comment]
I'll close this issue, you'll probably solved your problem already.
