### ISSUE TITLE
Different animation when slide left

### ISSUE THREAD

**Issue by nickorlov** [OwlCarousel2/OwlCarousel2#2252]
I have such a slider with animate.css vertical animation:
```
      $(".owl-carousel2").owlCarousel({
        items: 1,
        mouseDrag: false,
        loop: true,
        autoplay: true,
        animateOut: 'slideOutUp',
        animateIn: 'slideInUp'
      });
```
All is good when I scroll it up but when I scroll it down, I see 'up' animation because of slideOutUp and slideInUp settings. How to make it scroll back with different order animation?

**Comment by pascalporedda** [comment]
There is a PR for this kind of feature, which will be included in a future release, but no planned date yet.
