### ISSUE TITLE
Page swiping up and down not work on mobile devices v2.3.2

### ISSUE THREAD

**Issue by Siilionu** [OwlCarousel2/OwlCarousel2#2253]
Hi,

Page swiping (up and down) not work on mobile devices v2.3.2. 

Go to your demo page: http://owlcarousel2.github.io/OwlCarousel2/demos/basic.html and try to swipe page up and down on carousel, you see what i mean.

**Comment by Siilionu** [comment]
Hi, @pascalporedda 

I use Samsung 7s (android). The same behavior is also on Chrome devce toolbar. Try to swipe page up and down swiping on a carousel not on page itself: http://owlcarousel2.github.io/OwlCarousel2/demos/basic.html

**Comment by pascalporedda** [comment]
I was able to reproduce this, but I'am not sure if that is intended or not. Need a second look into this.

**Comment by Siilionu** [comment]
The biggest problem is when used with full screen carousel (as many websites use). It is not possible to scroll the page at all.

**Comment by pascalporedda** [comment]
I've thought that this might be an issue. In this case you can override the css property `touch-action` on the .owl-item class with pan-y as a value.

**Comment by Siilionu** [comment]
Thanks, @pascalporedda 

This solved the problem. :)

```
.owl-carousel.owl-drag .owl-item {
	-ms-touch-action: pan-y;
	touch-action: pan-y;
}
```

Best regards

**Comment by pascalporedda** [comment]
I will actually change this in the next upcoming version, yes.
