### ISSUE TITLE
Hidden slider doesn't load images after resizing window

### ISSUE THREAD

**Issue by YellowCrocus** [OwlCarousel2/OwlCarousel2#2254]
I have a website with several images. Each image reveals a div containing text and the Owl Carousel slider when clicked. So there are several owl sliders in total. Here's a rough demo of the site structure: https://codepen.io/t-silver/pen/GxqJwg

The sliders all work fine in different browser sizes, and when a slider is revealed and the browser resized, the slider will resize accordingly and still work fine. However, all the hidden sliders don't seem to load any of the images after opening them after the resize. I _can_ see the navigation arrows, but it will just show me a blank space where the image should be:
<img width="306" alt="screenshot 2018-03-15 16 38 59" src="https://user-images.githubusercontent.com/37377828/37473902-6fd93578-286f-11e8-8ab9-45977fa7d377.png">
The images of the slider load as soon as I resize the browser window or when I click on 'Inspect Element' using Firefox. Is it possible to fix this?

Here's the code I'm using for Owl Carousel:
```

$(".owl-carousel").owlCarousel({
		  	loop:true,
		    margin:10,
		    items:1,
		    nav:true,
		    navText: ["<img src='images/left.png'>","<img src='images/right.png'>"],
		    center:true,
		    autoplay:true,
		    autoplayTimeout:4000,
			autoplayHoverPause:true,
			responsive:{
	        0:{
	            items:1
	        },
	        600:{
	            items:1
	        },
	        1000:{
	            items:1
        }
    }
	  });
```

**Comment by YellowCrocus** [comment]
Update: when adding "autoWidth:true" to one of the responsive sets, the images do show up, but they are all stacked on top of eachother.

**Comment by pascalporedda** [comment]
Hello could you provide a fiddle with a owl carousel to reproduce this behaviour?

**Comment by YellowCrocus** [comment]
@pascalporedda Here's the Fiddle: https://jsfiddle.net/Zigzagshaped/h75ote9o/14/ 

However I've actually managed to solve my issue while trying to recreate the problem in JSFiddle. I was working with Owl v2.3.2., but when using Owl v2.2.1 all my issues dissapear.

I was trying to recreate the problem in jsfiddle based on a fiddle from another user here, but couldn't reproduce the problem all of a sudden. When I copied his files (https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js) and (https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js) and used them in my actual website, the problem disappeared. I found out he uses 2.2.1 instead, while I was using 2.3.2.

**Comment by nginex** [comment]
The latest version 2.3.2 includes a new option _checkVisibility_. Set this option to true and it will work

`checkVisibility: true`

**Comment by YellowCrocus** [comment]
@nginex Thanks, this solves my issue (in the fiddle at least!). Though I don't really understand how this function fixes both my rewind & my loading issue - what exactly does it do?

**Comment by nginex** [comment]
@YellowCrocus no problems

The default value of _checkVisibility_ is not provided and a new method _.isVisible()_ replaces old usage _this.$element.is(':visible')_ that was used in .to() and rewind functionality.

Check this comment too https://github.com/OwlCarousel2/OwlCarousel2/issues/2261#issuecomment-375072465

I create PR to fix such problems

**Comment by YellowCrocus** [comment]
@nginex Great, thank you very much for the explanation! I'll mark it as solved.
