### ISSUE TITLE
Tumbnails does not work correctly, in two synchronous Сarousel

### ISSUE THREAD

**Issue by TotemWide** [OwlCarousel2/OwlCarousel2#2255]
Hello everyone) Two roundabouts, on the first picture 1 item on the second of his miniature and the following images. When you scroll through 1 items of the first carousel, then all the miniatures move behind it.Is this a bug, or is the code not correct? Thank you!
JS
 // sliders control
  $(document).ready(function () {
    // reference for main items
    var slider = $('#slider');
    // reference for thumbnail items
    var thumbnailSlider = $('#thumbnailSlider');
    //transition time in ms
    var duration = 900;

    // carousel function for main slider
    slider.owlCarousel({
      loop: true,
      nav: true,
      navText : ['<i class="fa fa-angle-left"></i>','<i class="fa fa-angle-right"></i>'],
      items: 1,
      dots: false,
      thumbs: true,
      thumbImage: false,
      thumbsPrerendered: true,
      thumbContainerClass: 'owl-thumbs',
      thumbItemClass: 'owl-thumb-item',
      onInitialized: function() {
        $('.gallery-map-wrapper #map').height($('.information-block').height());
      }
    }).on('changed.owl.carousel', function (e) {
      //On change of main item to trigger thumbnail item
      thumbnailSlider.trigger('to.owl.carousel', [e.item.index, duration, true]);
    });

    // carousel function for thumbnail slider
    thumbnailSlider.owlCarousel({
      loop: false,
      nav: false,
      dots: false,
      items: 1,
    }).on('click', '.owl-item', function () {
      // On click of thumbnail items to trigger same main item
      slider.trigger('to.owl.carousel', [$(this).index(), duration, true]);

    }).on('changed.owl.carousel', function (e) {
      // On change of thumbnail item to trigger main item
      slider.trigger('to.owl.carousel', [e.item.index, duration, true]);
    });

  });
PUG/HTML
                       //- main slider
			.slider-container
				#slider.slider.owl-carousel
					- for(var i = 1; i < 5; i++)
						.item
							.content
								img(src='images/hotel-image' + i + '.jpg', alt='Alt ' + i)
			//- Thumbnail slider container
			.thumbnail-slider-container
				#thumbnailSlider.owl-thumbs.thumbnail-slider.owl-carousel
					- for(var i = 1; i < 45; i++)
						.item.owl-thumb-item
							.content
								img(src='images/hotel-slider/' + i + '.png', alt='full slider image')

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
