### ISSUE TITLE
broken infinity loops

### ISSUE THREAD

**Issue by nordbit** [OwlCarousel2/OwlCarousel2#2261]
as title said.
Firefox 59.01
Windows 10 x64
jquery 3.3.1
owl.carousel 2.3.2
I upgrade owl.carousel form old version from 01.2017 to the newest (2.3.2) because new jquery compatibility and infinity loops no longer works.
Is totally broken compared to old version
Carousel is rewinding backward after last item to first position, no matter configuration

https://codepen.io/nordbit/pen/MVbjOL

I digged slightly in my old projects from past few months and last working version for me was 2.3

**Comment by Siilionu** [comment]
I have the same problem.

**Comment by KEMPZOR** [comment]
+1 I also have version 2.3.2. Loop does not work.

**Comment by sten360** [comment]
This is my first time using Owl Carousel and I was wondering what the hell was going on. Actually, my carousel sometimes randomly breaks even with loop turned off. It mostly happens when using nav buttons or dots to navigate, I think the internal counter gets messed up somehow. 

Anyway, since you mentioned 2.3 worked fine, could you please share it? I need to get this project up and running asap and I'd hate to have to look for a new carousel solution at this point.

**Comment by Siilionu** [comment]
Previous version that worked was v2.2.0 (for my needs). You will find it here: https://github.com/OwlCarousel2/OwlCarousel2/releases

I moved back to the v2.2.0 until critical issues are resolved in a new version.

**Comment by nginex** [comment]
I'm not sure if there is a bug
Just set this option to true in your owlCarousel settings and it will work as expected 

`checkVisibility: true`

You can see new changes here in this method Owl.prototype.isVisible

**Comment by Siilionu** [comment]
Yes, "checkVisibility: true" seems to work. But, is this the right way to solve the problem? I can not find a word about "checkVisibility" in documentation: https://owlcarousel2.github.io/OwlCarousel2/docs/api-options.html Also, the demo site does not point to this (the loop does not work there as well): https://owlcarousel2.github.io/OwlCarousel2/demos/basic.html 

Is this some kind of a secret? :)

**Comment by nginex** [comment]
As I understood in the latest version there is new method `this.isVisible()`

Before it was `this.$element.is(':visible')`

So now you see the difference

**Comment by sod** [comment]
Oh no. I thought I defaulted it to true via [docs/assets/owlcarousel/owl.carousel.js](https://github.com/OwlCarousel2/OwlCarousel2/pull/1843/files#diff-c2fb54c2268f23cd5da9807af865e257R218) :(

**Comment by nginex** [comment]
@sod it seems you didn’t provide default value in src script, only in docs

**Comment by pascalporedda** [comment]
I will take care of this on this upcoming weekend to merge your PR.

**Comment by pascalporedda** [comment]
I merged the PR, gonna do some other things and will publish a hotfix for this later.

**Comment by pascalporedda** [comment]
2.3.3 is published and contains this fix.
