### ISSUE TITLE
next / prev buttons under the modified script

### ISSUE THREAD

**Issue by filmets** [OwlCarousel2/OwlCarousel2#2262]
Added here this piece to determine the location of the active element and automatically start from it when the page is loaded

`var poWidth = $(".owl-item").width(); // Find out the width of one element
            var poWidthBlock = $(".owl-wrapper-outer").width(); // Find out the width of the outer block
            var poAll = $(".owl-item").length; // Total items in the carousel
             var poPrev = $("#inside").prevAll().length; // Number of elements before the selected one

             var poResultMax = poWidth * poAll - poWidthBlock + 1; // Maximum distance
             var poResult = poWidth * poPrev; // Distance to the active element

            if (poResult <= poResultMax) {
              var poRes = poResult;
            } else {
               var poRes = poResultMax;
            }

            base.$elem.find(".owl-wrapper").css("display", "block");
            base.$elem.find(".owl-wrapper").css("transform", "translate3d(-" + poRes + "px, 0px, 0px)"); // Result`

with a touch, and mice if you pull everything perfectly works from an active place. But the prev / next buttons do not want to start from the same place, they start with the first element. How to solve such a question? [Example situation on JSFiddle](https://jsfiddle.net/mrStanislav/1yjq0wLy/23/)

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
