### ISSUE TITLE
Add an extra class to the middle element

### ISSUE THREAD

**Issue by marekka** [OwlCarousel2/OwlCarousel2#2264]
Hi, thanks for great plugin! Can we hook to it, so if we have 3 "active" slides, the 2nd one got an extra "superaCtive" class?

This way we could add some extra styling to it...

**Comment by pascalporedda** [comment]
How would this work if you have an even number of active items?

**Comment by marekka** [comment]
OK, bit how to hook?
A checkup has to happen on each transition + onload?

**Comment by pascalporedda** [comment]
Sure there has be to a checkup, but I guess it should be possible to make this work with the custom events provided by owl carousel, as I don't think that this is a needed feature for the OwlCarousel.
