### ISSUE TITLE
console.log accidental released 

### ISSUE THREAD

**Issue by SassNinja** [OwlCarousel2/OwlCarousel2#2268]
Hi,

after having updated my ow.carousel package there appear multiple console.log which are caused by the autoHeight plugin:
https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/src/js/owl.autoheight.js#L36

I think this is not intended and should be removed or is there a particular reason?

**Comment by pascalporedda** [comment]
It shouldn't be you are right. I've merged your PR.
