### ISSUE TITLE
Click Previous from first element to last element causes blank slide to show

### ISSUE THREAD

**Issue by gmandala-akacrm** [OwlCarousel2/OwlCarousel2#2273]
I have a carousel with 9 elements and the following options:

var newCarousel = $(document.getElementById(carouselId)).owlCarousel({
                loop: true,
                nav: true,
               items: 1,
                center: true,
                autoplay: true,
                mouseDrag: true,
                dots:true,
                autoplayTimeout: 5000
            });

Clicking Next through the entire selection shows no issues.  Clicking Prev, however, does.  If I click Prev on the very first element, the slide goes to the very last element but it displays a blank page.  It requires a mouse drag to get the slide to display.  Is there any way that I can get the last slide to display without a mouse drag?

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

**Comment by gmandala-akacrm** [comment]
It is an issue with OwlCarousel.  Can I set up a go to meeting and show you?

**Comment by gmandala-akacrm** [comment]
![lastframerequiresmousedrag](https://user-images.githubusercontent.com/27360847/37987562-7ff5b4a2-31cc-11e8-8fcc-d09ca457d8c0.gif)
Here is a GIF of the problem.  Look at the very end.

**Comment by gmandala-akacrm** [comment]
![lastframerequiresmousedrag](https://user-images.githubusercontent.com/27360847/37987795-327a83dc-31cd-11e8-9dc6-3a345e694000.gif)
Here is a video of the problem.  If you look at the last slide transition, it requires a mouse drag to become visible.
