### ISSUE TITLE
Error in mobile Chrome. Problem

### ISSUE THREAD

**Issue by bugsbunnyua** [OwlCarousel2/OwlCarousel2#2278]
Hello I have a problem with  my site
Owl carousel in mobile on Chrome look like this https://ibb.co/gsR3LS , but it's wrong. She was looking like this https://ibb.co/hBDuS7
This problem only in Chrome

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)

You have not added a link to a working live example. See [CONTRIBUTING.md](https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/CONTRIBUTING.md).

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version!

**Comment by bugsbunnyua** [comment]
sorry I'm not experienced, I do not know how to use the services, here is the link
[http://rhombus-hotel.com/](url)

**Comment by pascalporedda** [comment]
Well then you should learn this first, without a fiddle I won't be able to help you, it's not that hard though. 

Feel free to reply me if once you provided a working fiddle.
