### ISSUE TITLE
Loop/Reaches End & Ignores CSS Transition

### ISSUE THREAD

**Issue by smallminddesign** [OwlCarousel2/OwlCarousel2#2279]
I've noticed that when the carousel reaches the end and slides to the first slide again, it ignores the CSS property "transition". Here is my code:

```
.owl-carousel .owl-item {
    -webkit-backface-visibility:hidden!important;
    -webkit-transform:translateZ(0) scale(1.0,1.0) translate3d(0,0,0)!important;
    -webkit-transition:all 0.5s;
    -moz-transition:all 0.5s;
    -o-transition:all 0.5s;
    transition:all 0.5s;
}

.owl-carousel .owl-item.center {
    -webkit-transform:translateZ(0) scale(1.2,1.2) translate3d(0,0,0)!important;
}

$(".owl-carousel").owlCarousel({
    loop:true,
    margin:0,
    nav:true,
    center:true,
    navText:["<i class='far fa-angle-left'></i>","<i class='far fa-angle-right'></i>"],
    items:2
});
```
I don't see that element scale down with a transition. Just blinks to scale(1.0). You can see this happening on the dev site I'm working on: http://tjcs.wearemindful.io/. Scroll down to the "Featured Guests" section and use the arrows.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
