### ISSUE TITLE
Crashes in create-react-app application

### ISSUE THREAD

**Issue by sapolio** [OwlCarousel2/OwlCarousel2#2280]
I'm trying to apply OwlCarousel to my react component in create-react-app application this way:
```
import $ from 'jquery';
import 'owl.carousel';

class Slider extends React.Component {
  componentDidMount() {
      this.$slider = $(this.sliderContainer);
  }
...
}
```
At import 'owl.carousel' i get this:

> Cannot read property 'fn' of undefined

```  
  1709 |  * @todo Navigation plugin `next` and `prev`
  1710 |  * @public
  1711 |  */
> 1712 | $.fn.owlCarousel = function(option) {
  1713 | 	var args = Array.prototype.slice.call(arguments, 1);
  1714 | 
  1715 | 	return this.each(function() {
```
I'm new to all of this. Does it work somehow differently?

**Comment by pascalporedda** [comment]
Well jQuery is not defined there. I don't know your webpack setup, but it is mostly caused by a wrong webpack config, but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

**Comment by sapolio** [comment]
But I successfully applied $ (). addClass () in the component code. Does this not mean that $ is defined?

**Comment by dsavai** [comment]
How to fix the issue https://stackoverflow.com/questions/60134279/owl-carousel-typeerror-cannot-read-property-fn-of-undefined
