### ISSUE TITLE
Vertical mobile website scroll issue

### ISSUE THREAD

**Issue by cazebo** [OwlCarousel2/OwlCarousel2#2281]
I can't vertically scroll website (on mobile), because my finger starts sliding on carousel block (with horizontal scroll). 

Live example here - https://shiptor.ru/

**Comment by VitaliyBogdanov** [comment]
Fresh bug in css:

````css
.owl-carousel.owl-drag .owl-item {
	touch-action none;
````
This rule is prevent any touch actions. You can redefine it in your own styles. And wait for plugin updates.

**Comment by pascalporedda** [comment]
This is not a bug, this is intended. As vitaliy mentioned, you can fix this with your own custom css by adding pan-y to the touch-action of .owl-item.

**Comment by pascalporedda** [comment]
Hey @daniluski 

As so many people reported that they are having issues with this, I'll remove this part that was added earlier so the vertical scrolling will work again as before.

**Comment by daniluski** [comment]
I understand that is not an issue... I know how to use that... but a lot of people don't understand and think that their websites are broken... I think it would work very nice without this resource... Thanks

**Comment by daniluski** [comment]
Let me know how could I update it please
