### ISSUE TITLE
Multiple Url Hash Navigation

### ISSUE THREAD

**Issue by in-session** [OwlCarousel2/OwlCarousel2#2282]
Hi All,

is there a way to make the Url Hash Navigation mutliple in combination of diffrent sliders?

```

<div class="owl-carousel owl-theme" data-container="name">
       <div class="item" data-hash="zero"></div>
</div>

<div class="owl-carousel owl-theme" data-container="demo">
       <div class="item" data-hash="zero"></div>
</div>

<div class="owl-carousel owl-theme" data-container="name">
       <div class="item" data-hash="zero"></div>
</div>

```

output hash: #name=zero?demo=zero?name=zero

THX and Regards Chris

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
