### ISSUE TITLE
4 items on first slide and 3 on the rest

### ISSUE THREAD

**Issue by greenlightpete** [OwlCarousel2/OwlCarousel2#2283]
How can I set a carousel up so that the first slide has 4 items and then the other slides have 3.

Thanks in advance

**Comment by FeST1VaL** [comment]
maybe use 2 items with flex? Or maybe u help "merge" option
<div class='owl-item'>
 <div class='item'></div>
 <div class='item'></div>
 <div class='item'></div>
 <div class='item'></div>
</div>
<div class='owl-item'>
 <div class='item'></div>
 <div class='item'></div>
 <div class='item'></div>
</div>

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
