### ISSUE TITLE
i only want 2 dots not 3

### ISSUE THREAD

**Issue by Skymaster1337** [OwlCarousel2/OwlCarousel2#2285]
what do  i write to get my owl carousel auto play to, show 2 dots instead of 3 ( currently 6 slides running ) and it must run with 6, but i need 2 dots not 3.

there must be commands for that but cant find the right word for these

**Comment by Skymaster1337** [comment]
![tomuch](https://user-images.githubusercontent.com/32289240/38379667-aeae4070-3901-11e8-84c8-4839e058aaeb.jpg)

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

**Comment by Skymaster1337** [comment]
It is a issue on owlcarousel? Those dots have to come from somewhere? Just want to know where so i can edit how it make 2 or 3

Sendt fra min iPhone

Den 9. apr. 2018 kl. 08.10 skrev Pascal Poredda <notifications@github.com<mailto:notifications@github.com>>:


Closed #2285<https://github.com/OwlCarousel2/OwlCarousel2/issues/2285>.
