### ISSUE TITLE
Owl Carousel 2: Tap / Click and Swipe enabled over entire image area

### ISSUE THREAD

**Issue by pinkp** [OwlCarousel2/OwlCarousel2#2286]
I'm using Owl Carousel 2.2.1. I wish to enable the navigation via tap / click and swipe at the same time so users especially on mobile can do both. I'm finding that that by making the tap zone (nav area) fill half the image area with css that it stops the touch swipe or mouse drag. Is it possible to achieve both? I've seen it done here on an older version of Owl: [http://rg-e.com/physical/index.html](url)

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
