### ISSUE TITLE
Triggering NEXT from link/text in slide caption

### ISSUE THREAD

**Issue by bcontento** [OwlCarousel2/OwlCarousel2#2287]
I have the carousel as part of a template I downloaded. Everything works fine (the regular nav controls), but I'd like to include my own button/link (called MY STORY in the code below) in the slide caption area that will trigger the NEXT slide event. I've tried everything and can't come up with a working model.

I know that the carousel has to be instantiated but I can't track down where that is happening (external JS file somewhere). Is it possible I'm just not attaching the event to the right instance of the carousel?

one of the scripts I tried to attach based on some reading/research:

<script>
  $("#mystory").on('click',function(){        
   owl.trigger('next.owl');
})      
</script>

**in the template:**

<section id="tt-intro" class="slideshow-intro">
    <div class="tt-intro-inner">
      <div class="gl-carousel-wrap gel-carousel no-padding">

        <div class="owl-carousel cc-height-5 dots-right bg-dark" data-items="1" data-loop="true"
             data-nav="true" data-nav-speed="500" data-mouse-drag="false" data-dots-speed="500" data-autoplay="false"
             data-autoplay-timeout="8000"  data-autoplay-speed="500"
             data-autoplay-hover-pause="true">

          <div class="cc-item">

            <span class="cover bg-transparent-3-dark"></span>

            <div class="cc-image bg-image"
                 style="background-image: url(assets/img/intro/intro-10.jpg); background-position: 100%;"></div>			 
             <div class="intro-caption caption-animate intro-caption-xxlg center">
				 				 
				 <div style="text-align: left;margin-top: 180px;">
                **<a href="#" class="btn btn-white-bordered margin-top-5" id="mystory" >My Story</a>**
              </div>
            </div>

          </div>
		
<div class="cc-item">

            <span class="cover bg-transparent-3-dark"></span>

            <div class="cc-image bg-image"
                 style="background-image: url(assets/img/intro/intro-11.jpg); background-position: 100%;"></div>
			  

             <div class="intro-caption caption-animate intro-caption-xxlg center">
              
              <div style="text-align: left;margin-top: 180px;">
                 
                <a href="#"  class="btn btn-white-bordered margin-top-5" id="mystory" >My Story</a>
              </div>
            </div>

          </div>

		  </div></div></div>

  </section>

**Comment by keefyhub** [comment]
Hi @bcontento,

you would need to do something like this

```
$("#mystory").on('click', function () {
  $('.owl-carousel').trigger('next.owl');
});
```

So when you click on `#mystory` you need to let it know the target for triggering `next.owl`

(just be aware if you are using more than 1 carousel it might break, so put a specific class or ID on the carousel)

**Comment by bcontento** [comment]
I fixed the syntax based on what you sent but still not working. More than likely it's that there are multiple carousels on the page. The problem is that the template creates the instances and I don't know how to identify them so that I can target the correct one.

<script>
    function myStory(){
		$("#mystory").on('click', function () {
               $('.owl-carousel').trigger('next.owl');
              });
	}
</script>

In the template JS file, I see where I believe the call to create the carousels comes from. Does this help ID each carousel and how to target the one I want correctly?

$(window).on('load', function() { // fixes Owl Carousel "autoWidth: true" issue (https://github.com/OwlCarousel2/OwlCarousel2/issues/1139).

		$('.owl-carousel').each(function(){
			var $carousel = $(this);

      if ($carousel.attr('data-nav-custom')) {
        $carousel.on("initialized.owl.carousel", function (event) {
          var carousel = $(event.currentTarget),
            customNav = $(carousel.attr("data-nav-custom"));

          // Custom Navigation Events
          customNav.find(".owl-arrow-next").click(function (e) {
            e.preventDefault();
            carousel.trigger('next.owl.carousel', 800);
          });
          customNav.find(".owl-arrow-prev").click(function (e) {
            e.preventDefault();
            carousel.trigger('prev.owl.carousel', 800);
          });
        });
      }

**Comment by keefyhub** [comment]
If you are not able to add a class or ID to the carousel, you could use this

```
$("#mystory").on('click', function () {
  $(this).closest('.owl-carousel').trigger('next.owl')
});
```

**Comment by bcontento** [comment]
THANKS KEEFYHUB! I was able to make that work with some tweaking.

**Comment by pascalporedda** [comment]
Seems to be solved.
