### ISSUE TITLE
Anchor around images causes carousel to break

### ISSUE THREAD

**Issue by vishy93** [OwlCarousel2/OwlCarousel2#2290]
I am currently trying to wrap the images in anchor tags, but doing so causes the carousel to collapse on each transition.

Inspecting the code I can that the height is being set to 1px each time, before correctly resetting the height. 

I have created a codepen [here](https://codepen.io/vishpatel93/pen/zWmKqK), but strangely it also looks to be an issue with the image(s) being used on my local site, as on the codepen the placeholder images does not cause this behaviour.

**Update:**

Investigating further the height reset is caused by the lazyloading, as the second image is not loaded yet it default the slideshow back to 1px. Would there be a way to respect height obtained from first slide. So, won't reset the height back to 1px, or will delay the calculation at least upon till the image has been lazyloaded ?

**Comment by pascalporedda** [comment]
You could achieve such behaviour with custom CSS and JS, but I don't think that it is necessary for the OwlCarousel to be implemented.
