### ISSUE TITLE
Lazyloaded images of carousel below loading before in view and before ready/load event

### ISSUE THREAD

**Issue by vishy93** [OwlCarousel2/OwlCarousel2#2291]
Dear Community,

I am using this caoursel as a product slider below and a hero slider at the top. The hero slider is a full width responsive slider of one image at a time, and duly has no height defined. 

Then below I have a product carousel, which displays multiple items. Now, in the chrome browser, latest version: Version 65.0.3325.181 (Official Build) (64-bit); I can see using the dev tools that the 4 images of the carousel below are loading even though they are not in the  viewport yet. (Not yet scrolled too).

Thus, how can I correct this so the images are correctly "lazyLoaded": loaded when in view?

Also, I have noticed the four images in some instances of load to be loading actually before the ready or load event have even fired. So, before the carousel has been initiated which is strange.

For test case purposes please see [here](https://codepen.io/vishpatel93/full/zWmKqK/).

**Comment by pascalporedda** [comment]
The "lazyLoad" feature does not check if the element is in the viewport, if rather checks if the current slide is an "active" slide. The behaviour you are looking for is not implemented.

**Comment by vishy93** [comment]
Okay, would there it be possible to use something like https://www.andreaverlicchi.eu/lazyload/ ?

**Comment by pascalporedda** [comment]
You can try it out, but I can't guarantee that they are compatible.
