### ISSUE TITLE
How disable inline css for Item

### ISSUE THREAD

**Issue by mohandes** [OwlCarousel2/OwlCarousel2#2293]
In some SEO website checker advise me to remove inline css, But OwlCarousel2 automatic change value of inline width : like style='width226px' .

I want use this css in external file:
@media (min-width: 576px) { .owl-item{width: 181.333px;margin-left:5px;}} 
@media (min-width: 768px) { .owl-item{width: 210.333px;margin-left:5px;}}
@media (min-width: 992px) { .owl-item{width: 235px;margin-left:5px;}}
@media (min-width: 1200px) { .owl-item{width: 226px;margin-left:5px;}}

But i don't know how remove or disable inline css for item?

**Comment by pascalporedda** [comment]
Hi mohandes,

sorry to let you know that this is not possible, but inline css shouldn't make any seo difference though.
