### ISSUE TITLE
Owl carousel is leaking out of container bootstrap

### ISSUE THREAD

**Issue by aloksharma1** [OwlCarousel2/OwlCarousel2#2301]
hi,
for the sake of convenience i have uploaded the problem code on [here](http://nationwidegetaway.com/demo/) , right now i am using body overflow-x:hidden to hide leaking owl out of my page html and even when i try to inspect element it makes images very large or out of bounds (i can confirm this on resize too). so i believe owl not calculating height and width correctly.  

_____________
test url [here](http://nationwidegetaway.com/demo/) 

_____________
bootstrap version is 3.3.7
owl version is 2.3.3
i am using sidebar in bootstrap as given in [here](https://bootstrapious.com/p/bootstrap-sidebar)

**Comment by pascalporedda** [comment]
You are simply missing a column around the carousel, but these issues are not related to the OwlCarousel.

**Comment by aloksharma1** [comment]
what column? i already tried putting it in container - container fluid - row - col-md-12 nothing worked

**Comment by aloksharma1** [comment]
yes i already tried that, i have been using bootstrap since many years and i never had this issue with previous versions of owl that why i created this issue.

**Comment by evgeniedasaev** [comment]
Have the same problem
container fluid > row > col-md-12 > owl-carousel
And i have the width of owl about 5000px!

**Comment by rajatkaplan** [comment]
https://codepen.io/bootstrapped/pen/XKyjpP

Solution: 
.container-fluid {
	max-width: 1230px;
}
