### ISSUE TITLE
Pull(or drag) page not work on mobile over the OwlCarousel2 block

### ISSUE THREAD

**Issue by cakama3a** [OwlCarousel2/OwlCarousel2#2305]
I can not get the page down lower than the carousel on my mobile phone
All because the scrolling option of the page in the block with the carousel does not work.

This is only work when the mouseDrag option is set 
**mouseDrag: false**
But this is not an option, since on the PC then the sliding option does not work.

https://youtu.be/rakXkWyLBNY

**Comment by pascalporedda** [comment]
This was a change introduced lately, but many people are reporting that they are having issues with this. It will be therefore removed, you'll either have to wait for the next release or overwrite the touch-action property on the .owl-item class to "pan-y" or "initial".
