### ISSUE TITLE
How to create perfect vertical slider in owl carousel?

### ISSUE THREAD

**Issue by buyfie** [OwlCarousel2/OwlCarousel2#2308]
### A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.>
1. This is the first step
2. This is the second step
3. Further steps, etc.

_____________
### `<url>` - a link to the reduced test case. You can use one of the following services:
- https://codepen.io/anon/pen/prvbMp
- https://jsfiddle.net/h8x8bvn9/2/) 
- https://jsbin.com/bojonaceve/2/edit?html,js,output

_____________
### Any other information you want to share that is relevant to the issue being reported.
This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

**Comment by pascalporedda** [comment]
There is no option provided from the OwlCarousel to create a vertical slider.

**Comment by buyfie** [comment]
Is there an idea to come up with this update in the coming days?

**Comment by mrov** [comment]
it would be great

**Comment by medvedar** [comment]
+1

**Comment by zwozwo** [comment]
you can make it look like a vertical slider
if you simply use the animate slideInDown and slideInUp for example.
animateIn:'slideInDown',
animateOut: 'slideOutUp',

**Comment by zwozwo** [comment]
Sorry I forgot, of course it works onlay with 1 visible item...

**Comment by diogenesjup** [comment]
https://codepen.io/marcogu00/pen/eLeWMq here a example working well
