### ISSUE TITLE
OWL v1.3.3

### ISSUE THREAD

**Issue by anshul0430** [OwlCarousel2/OwlCarousel2#2311]
<div class="testimonial-area recent-property" style="background-color: #FCFCFC; padding-bottom: 
    15px;">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1 col-sm-12 text-center page-title">
                    
                    <h2>Our Customers Said  </h2> 
                </div>
            </div>

            <div class="row">
                <div class="row testimonial">
                    <div class="row">
                      <div class="col-md-8">
   <div id="testimonial-slider">
   <div class="item">
      <div class="client-text">
     <h5 class="articleText">जैन धर्म में अक्षय तृतीया का क्या है महत्व, जानिए...</h5>
      </div>
     <img class="jainImage" src="assets/img/jainarticle1.jpg" alt="">
      <h6 class="postedText">Posted By :</h6>
      <h6 class="postedby">Brijpal Singh</h6>
    </div>
   <div class="item">
    <div class="client-text">
    <h5 class="articleText">जैन धर्म में अक्षय तृतीया का क्या है महत्व, जानिए...</h5>
         </div>
   <img class="jainImage" src="assets/img/jainarticle1.jpg" alt="">
   <h6 class="postedText">Posted By :</h6>
    <h6 class="postedby">Brijpal Singh</h6>
  </div>
   <div class="item">
    <div class="client-text">
   <h5 class="articleText">जैन धर्म में अक्षय तृतीया का क्या है महत्व, जानिए...</h5>
    </div>
   <img class="jainImage" src="assets/img/jainarticle1.jpg" alt="">
   <h6 class="postedText">Posted By :</h6>
   <h6 class="postedby">Brijpal Singh</h6>
   </div>
   <div class="item">
    <div class="client-text">
           <h5 class="articleText">जैन धर्म में अक्षय तृतीया का क्या है महत्व, जानिए... 
   </h5>
    </div>
    <img class="jainImage" src="assets/img/jainarticle1.jpg" alt="">
    <h6 class="postedText">Posted By :</h6>
    <h6 class="postedby">Brijpal Singh</h6>
     </div>

   </div>

   <button type="button" class=" btn btn-default articlebtn">button</button>

                      </div>

                    I don't know what to do . Please help me

              JS

           jQuery OwlCarousel v1.3.3
            http://www.owlgraphic.com/owlcarousel/
            I want to add an Auto play in this testimonial slider. I had done all fixes by myself.

**Comment by pascalporedda** [comment]
I'am sorry but I don't know what you want, according to your title you are using a OwlCarousel version that is no longer supported.
