### ISSUE TITLE
Slider not working/appearing

### ISSUE THREAD

**Issue by Nic787** [OwlCarousel2/OwlCarousel2#2317]
Hi,

I would like to create a fade-in/out hero slider for my homepage, but I'm not sure to understand how OwlCarousel2 works.

Currently I have:
`<div class="hero-slider">
            <ul class="slider-image">
                <li style="background-image: url(images/background1.jpg)"></li>
                <li style="background-image: url(images/background2.jpg)"></li>
            </ul>
        </div>`

And
`$(document).ready(function(){
    $(".slider-image").owlCarousel({
        number:1,
        loop:true,
        mouseDrag:false,
        touchDrag:false,
        pullDrag:false,
        freeDrag:false,
        dots:false,
        autoplay:true,
        autoplaySpeed:1000,
        autoplayTimeout:1000,
        slideTransition: EaseInOut,
        animateOut: 'fadeOut',
        animateIn: 'fadeIn'
    });
  });`

But it is not working. I maybe forgot something, but I really want some help with that. The first image is showing, but it doesn't change to the second one.

It also show an error at slideTransition: ease-in-out, Syntax error, but I don't know why. I'm trying to achieve a cross-fade effect between images.

How do I chose time it take to go to the other image… I would like to change image each 5 seconds. I'm not sure to understand autoplaySpeed and Timeout.
----
EDIT: Now I changed to 'ease-in-out' with the '' and it completely changed my code by itself.
![image](https://user-images.githubusercontent.com/11185348/39597380-2e746950-4ee3-11e8-96f3-35a7440442a3.png)

What's going on?
----
EDIT 2: I added class owl-carousel to the < ul >, but it still add a lot of divs after and hide my < li > tag very far away.

**Comment by pascalporedda** [comment]
You should probably read the docs on how to use the OwlCarousel. It is stated quite clearly how to use it.
