### ISSUE TITLE
owl-slider display only one slide

### ISSUE THREAD

**Issue by Anderor** [OwlCarousel2/OwlCarousel2#2323]
The theme is used as a slider owl. There are 2 sliders. If I delete 1 slider, the page does not work.
Is it possible to have just one slider without a loop?
any idea?
Thanks
_____________
link:
- http://sipe.novock.sk/

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
