### ISSUE TITLE
Custom progress bar its duration last as the total time of all slides

### ISSUE THREAD

**Issue by MasterJuan** [OwlCarousel2/OwlCarousel2#2325]
Hello,

First of all, it's not a bug rather than a help!

I want to create a progress bar which it will be loaded over the custom pager and its duration will be the duration of all sliders.

Take a look here: https://codepen.io/AntoniosKrinis/pen/VxQKOq/
I am using two approaches (see javascript section). At the moment works only the second.
You can enable or disable each approach by comment in/out  these lines:

          // First Approach (doesn't work)
		// onInitialized: progressBar,
		// onTranslate: moved,
		// onTranslated: progressBar,
		// onDrag : pauseOnDragging,
    
          // Second Aprroach
    	onInitialized: startProgressBar,
    	onTranslate: resetProgressBar,
    	onTranslated: startProgressBar,

At the moment, as you can see the progress bar loaded to each element (because in my html code I have include it to each pager element).

My scope is:
Progress bar start from the first slide and fully loaded at the end of the last slide.
So the total duration will be 20 seconds.
When someone click a tab, then the progress bar must be stopped to that point and if the user click to another tab, to be started again from that point.

Thanks in advance!

Best regards

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
