### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by flexsingit** [OwlCarousel2/OwlCarousel2#2327]
I used following options:
{
    loop:true,
    margin:10,
    navigation:true,
    dots:true,
    items: 3
  }

but when there is 3 or less than 3 items, it hides the navigation event after loop:true

I want to show the navigation always.

**Comment by pascalporedda** [comment]
Yes, this is a already known issue #1462, I tried to find a fix for it, but wasn't really successful. 

As we don't need multiple issues for this, I'll close this one.
