### ISSUE TITLE
OwlCarousel2 in 2 lines

### ISSUE THREAD

**Issue by rrlonghii** [OwlCarousel2/OwlCarousel2#2329]
Hi. Is it possible to use the owl carousel 2 arranged in 2 lines? Something like a sequence of photos in chronological order in two lines!

Something like this:
https://www.wonderplugin.com/wp-content/uploads/2015/05/tworows-600x403.png

https://www.drupal.org/files/issues/Slick%20Grid.png

each image is an external link

**Comment by pascalporedda** [comment]
At least there is not yet an option or any possible way that I know.
