### ISSUE TITLE
REmove inline

### ISSUE THREAD

**Issue by anshul0430** [OwlCarousel2/OwlCarousel2#2332]
<div id="testimonial-slider" class="owl-carousel owl-theme">
                                <div class="item pqr">
                                    <div class="client-text">
                                        <h5 class="articleText">जैन धर्म में अक्षय तृतीया का क्या है महत्व, जानिए...</h5>
                                    </div>
                                    <img class="jainImage" src="assets/img/jainarticle1.jpg" alt="">
                                    <h6 class="postedText">Posted By :</h6>
                                    <h6 class="postedby">Brijpal Singh</h6>
                                </div>
                                <div class="item pqr">
                                    <div class="client-text">
                                        <h5 class="articleText">जैन धर्म में अक्षय तृतीया का क्या है महत्व, जानिए...</h5>
                                    </div>
                                    <img class="jainImage" src="assets/img/jainarticle1.jpg" alt="">
                                    <h6 class="postedText">Posted By :</h6>
                                    <h6 class="postedby">Brijpal Singh</h6>
                                </div>
                                <div class="item pqr">
                                    <div class="client-text">
                                        <h5 class="articleText">जैन धर्म में अक्षय तृतीया का क्या है महत्व, जानिए...</h5>
                                    </div>
                                    <img class="jainImage" src="assets/img/jainarticle1.jpg" alt="">
                                    <h6 class="postedText">Posted By :</h6>
                                    <h6 class="postedby">Brijpal Singh</h6>
                                </div>
                                <div class="item pqr">
                                    <div class="client-text">
                                     <h5 class="articleText">जैन धर्म में अक्षय तृतीया का क्या है महत्व, जानिए...</h5>
                                    </div>
                                    <img class="jainImage" src="assets/img/jainarticle1.jpg" alt="">
                                    <h6 class="postedText">Posted By :</h6>
                                    <h6 class="postedby">Brijpal Singh</h6>
                                </div>
        
                            </div>

![screenshot 2018-05-14 19 12 05](https://user-images.githubusercontent.com/30527706/40000968-d0c9efd4-57aa-11e8-89ec-59d01c95cca4.png)
I want to drove the inline css in owl-item

**Comment by pascalporedda** [comment]
This is not possible as it updates automatically according to the browser width.
