### ISSUE TITLE
How to create response owl carousel with data attribute?

### ISSUE THREAD

**Issue by shivkumarsingh7** [OwlCarousel2/OwlCarousel2#2345]
`<div id="imageslider-8250515471527011033" class="owl-carousel owl-theme owl-featured-brand owl-loaded owl-drag" data-animateout="false" data-animatein="false" data-items="5" data-dot="false" data-nav="false" data-loop="false" data-autoplay="false" data-autoplay-timeout="0" data-autoplay-speed="false" data-navspeed="false" data-dotsspeed="false" data-autoplay-pauonhover="false" data-autoheight="false" data-lazyload="false" data-touchdrag="false" data-mousedrag="false" data-pulldrag="false">
                `

**Comment by keefyhub** [comment]
you could use an array in a data attribute as you have for the other options

`data-responsive='{"0":{"items": "1"}, "1024":{"items": "3"}}'`

```
var responsive = $('.js-carousel').data('responsive');
$(".js-carousel").owlCarousel({
  dots: true,
  loop: false,
  margin: 10,
  nav: false,
  responsive: responsive
});
```

Note the format of the data attribute, I had to use single quotes to surround it and double quotes inside the array.
