### ISSUE TITLE
I want 4 image + half left, half right image in one row

### ISSUE THREAD

**Issue by abhilesh11live** [OwlCarousel2/OwlCarousel2#2364]
I am trying to make crousal with 4 image and 1 half left, 1 half right image (like in image)
![owl](https://user-images.githubusercontent.com/24887167/41496663-caff7e80-7162-11e8-87d3-7153aeb23a34.png)
 but its not working as it show 4 image only and not showing half left and right images.
 I am using jquery code: 

`<script>
jQuery('.loop').owlCarousel({
    center: true,
    items:1,
    loop:true,
    margin:20,
	autoplay:true,
	autoplayTimeout:5000,
	autoplayHoverPause:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
	}
});

    </script>`

**Comment by ordinarycas** [comment]
「center: fales」

But, It is multiple video play, it will the formatting is off
example：
https://codepen.io/ORdinarycas/full/XqmwXW/

**Comment by abhilesh11live** [comment]
As in your example same I get the images view. But is this is possible to make half portion of left and right side image + 4 images in center as I show in my question in OWL Crousal.????

**Comment by mathiasnovas** [comment]
In case you haven't solved it already, I believe what you want is stage padding: https://owlcarousel2.github.io/OwlCarousel2/demos/stagepadding.html

**Comment by abhilesh11live** [comment]
Thanks Mathiasnovas, 
This solution works.
Thanks for reply.
