### ISSUE TITLE
On drag for <30 px  to the right slides for full visible width

### ISSUE THREAD

**Issue by janson-git** [OwlCarousel2/OwlCarousel2#2371]
### A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.

With drag distance for <30px to the right carousel jumps for distance of visible width.
Different behavior for drag less than 30px to the left and to the right.

Steps to reproduce:
1. open page with carousel (http://owlcarousel2.github.io/OwlCarousel2/demos/stagepadding.html)
2. press left mouse button on carousel and drag for <30px to the right
3. release left mouse button
4. carousel will slide to the right for the distance of visible items count
5. same steps for left drag will correctly gets closest item

_____________
### A link to the reduced test case. You can use one of the following services:

It may be reproduced on page http://owlcarousel2.github.io/OwlCarousel2/demos/stagepadding.html

Drag for one item to the left, then drag to the right a little (less than 30 px) and you can see: carousel will jump to the right for 4 items!

Actually, amount of right-drug must be less then value of 'pull' in src/js/owl.carousel.js:897
That is the treshold amount of drug, if dragging less it - carousel must be return to current position. If more then value - carousel must get next position.
_____________
### Any other information you want to share that is relevant to the issue being reported.

Fixed by https://github.com/OwlCarousel2/OwlCarousel2/pull/2370

It will change calc of closest item for drug less than 30 px. With this fix mini drag behavior for the left and right directions will be same.

**Comment by pascalporedda** [comment]
Merged and will be released with the next version.
