### ISSUE TITLE
Issue with bootstrap tabs

### ISSUE THREAD

**Issue by alanpilloud** [OwlCarousel2/OwlCarousel2#239]
First of all, thanks a lot for your great carousel, which is the best by far !

Here is my issue : I made 4 carousels included in 4 bootstrap tabs.
Everything used to work fine with the owl js 2.0.0-beta.2.1.

However, with the owl js 2.0.0-beta.2.4, the first carousel is well displayed, but then, switching between tabs, the width of the items is not ok.

See attached image.
![carousel1](https://cloud.githubusercontent.com/assets/3446547/3466204/654f5974-027c-11e4-87e5-0f087bdcb45e.png)
![carousel2](https://cloud.githubusercontent.com/assets/3446547/3466205/654f89d0-027c-11e4-8231-3c1fae94a98c.png)

Thanks again

**Comment by ktsixit** [comment]
Could somebody explain what's needed to be done to fix this issue? The carousel in the jsfiddle  that's supposed to be the solution, is not working for me. The carousel is hidden.
Should I create a new post for this?

**Comment by amirhsh** [comment]
@alanpilloud Hi 
I have same problem in bootstrap tabs. Did you finally solve that problem?
Thanks in advance

**Comment by amirhsh** [comment]
@witrin @ocvninfo  @dennisreimann 
Hi guys.
I have same problem but I couldn't find out what exactly your solution is.
Can you help me ?

**Comment by amirhsh** [comment]
@witrin @ocvninfo @dennisreimann @alanpilloud 
Good news ! 
I found the solution:

initialize_owl($('#owl1'));


    $('a[href="#book"]').on('shown.bs.tab', function () {
        initialize_owl($('#owl1'));
    }).on('hide.bs.tab', function () {
        destroy_owl($('#owl1'));
    });

    $('a[href="#package"]').on('shown.bs.tab', function () {
        initialize_owl($('#owl2'));
    }).on('hide.bs.tab', function () {
        destroy_owl($('#owl2'));
    });

    $('a[href="#sound"]').on('shown.bs.tab', function () {
        initialize_owl($('#owl3'));
    }).on('hide.bs.tab', function () {
        destroy_owl($('#owl3'));
    });

	function initialize_owl(el) {


	    el.owlCarousel({
	     	loop:true,
		    margin:10,
		    rtl:true,
		    nav:false,
		    dots:false,
		    lazyLoad:true,
		    responsive:{
		        0:{
		            items:2
		        },
		        480:{
		            items:3
		        },
		        767:{
		            items:4,
		            margin:30
		        }
		        
		    }
	    });
	}

	function destroy_owl(el) {
		el.trigger("destroy.owl.carousel");
		el.find('.owl-stage-outer').children(':eq(0)').unwrap();
	}

**Comment by Utang** [comment]
amirhsh thanks! Your solution works

**Comment by arassea17** [comment]
thanks @witrin very much for your work.

**Comment by toir427** [comment]
https://www.youtube.com/watch?v=tKrt9ev4S24
