### ISSUE TITLE
Blank space before and after carousel

### ISSUE THREAD

**Issue by roweenaweb** [OwlCarousel2/OwlCarousel2#24]
Hiya,
I've got this working nicely for what I need and it's great, thank you. There is blank spacing before and after my carousel, how can I can rid of this so that the carousel stops when the last photo is reached? see:

http://www.roweena.co.uk/projects/christina/archive-home.html

I am instantiating with:

$('#owl-demo-1').owlCarousel({
center: true,
  items:3,
  loop:false,
  startPosition:      1,
  margin:10,
  navigation: true,
  navText: ['<','>'],
  naviSpeed:    450
});

Thank you :-)

**Comment by igorissen** [comment]
Hi, I've this issue with v2.0.0-beta.3. How can I solve this issue ?

```javascript
var owlDefaultOpts = {
      center         : true,
      loop           : false,
      lazyLoad       : true,
      margin         : 10,
      responsiveClass: true,
      responsive     : {
        0   : { items: 1 },
        480 : { items: 2 },
        1325: { items: 3 }
      }
    };
```

**Comment by ishigami** [comment]
I've this issue too.

var owlDefaultOpts = {
      center: true,
      loop: true,
      items: 1,
      autoWidth: true
    };

**Comment by sweettimes** [comment]
This issue have not yet fixed :(

**Comment by prynce00** [comment]
Try Minifying your HTML carousel contents before initializing the OwlCarousel

Mine looks like this

`<div class="owl-carousel owl-theme"> <div class="custom-owl-item"> <h4>1</h4> </div><div class="custom-owl-item"> <h4>2</h4> </div><div class="custom-owl-item"> <h4>3</h4> </div><div class="custom-owl-item"> <h4>4</h4> </div><div class="custom-owl-item"> <h4>5</h4> </div><div class="custom-owl-item"> <h4>6</h4> </div><div class="custom-owl-item"> <h4>7</h4> </div><div class="custom-owl-item"> <h4>8</h4> </div><div class="custom-owl-item"> <h4>9</h4> </div><div class="custom-owl-item"> <h4>10</h4> </div><div class="custom-owl-item"> <h4>11</h4> </div><div class="custom-owl-item"> <h4>12</h4> </div></div>`

**Comment by lia-milind** [comment]
How to add space before first and last slide so i can display the space between arrow and sider. I want display nav arrow in middle of carousel like left | slider-1 | slide-2 | slide-3 |slide-4 | right arrow
