### ISSUE TITLE
trigger('refresh.owl.carousel') doesn't work

### ISSUE THREAD

**Issue by sqwk** [OwlCarousel2/OwlCarousel2#241]
Triggering a refresh after resizing the outermost container doesn't work.

```
$(document).on('click', '.owl-magnify', function() {
    var $carousel = $(this).closest('.slides');
    if ($(window).width() > 816 && !$carousel.hasClass('alignfull')) {
        $carousel.addClass('alignfull').trigger('refresh.owl.carousel');
    }
});
```

`.owl-magnify` is a custom button added to `.owl-controls`. The class alignfull is added successfully, however, a refresh is not being triggered. (Only refreshes when resizing the browser window.)

**Comment by hbpratik** [comment]
I simply use below syntax to avoid the problem.

window.dispatchEvent(new Event('resize'))

**Comment by pratik916** [comment]
I simply use below syntax to avoid the problem.

`window.dispatchEvent(new Event('resize'))`
