### ISSUE TITLE
Formatting title tag

### ISSUE THREAD

**Issue by anderlk** [OwlCarousel2/OwlCarousel2#2425]
The Slider title is actual marked as h1.  When I change this to another heading tag, the animation of the title don't work anymore.

Is it possible to change the formattig of title text in Slider, to work with animation?

**Comment by zwozwo** [comment]
I think you made your title animation? with js? do you have an example?
I am not sure what you mean...

**Comment by anderlk** [comment]
Ok, thanks for the note, the title animation was made via CSS:

`.slide__carosel .owl-item.active .slide__inner h1 {
    -webkit-animation-name: flipInX;
    animation-name: flipInX;`

That's it and works fine :).
