### ISSUE TITLE
Wrong directions

### ISSUE THREAD

**Issue by takeifuku** [OwlCarousel2/OwlCarousel2#2450]
I have problem with slide direction in case: 
+ total items: 5
+ show items: 4
+ slide by: 3
When I clicked on nav button, the slide direction was moving by opposite way as it has to.

See problem here: https://codepen.io/takeifuku/pen/YOmGjN

**Comment by jesspritchard** [comment]
What was the fix for this? I'm experiencing the same issue even though the EXACT same code is working properly on another site?
