### ISSUE TITLE
Carousel Swiping

### ISSUE THREAD

**Issue by skuzmina** [OwlCarousel2/OwlCarousel2#2454]
1. Go to the http://vargo2018.sohotest.com/ on your phone
2. Swipe the Slideshow Foward
3. Try to Swipe Carousel Backward

**Issue**: Can the swiping backward will be the same as swiping forward?

Please advise, 
Sandra

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
