### ISSUE TITLE
After install - The website encountered an unexpected error. Please try again later.

### ISSUE THREAD

**Issue by srhcpa** [OwlCarousel2/OwlCarousel2#2460]
Hi,

I just installed OwlCarousel2 by following the Video Tutorial on the page.

`https://www.drupal.org/project/owlcarousel2`

I installed OwlCarousel via Composer.  This is the entry in my composer.json: "drupal/owlcarousel2": "^1.0@RC"

Next, I copied the "dist" folder into my libraries/OwlCarousel2/dist.

Then, I flushed my cache.

Then, I went to content and tried adding a new OwlCarousel2. That's when I get the error" The website encountered an unexpected error. Please try again later.

What might be causing this?

Thanks,

Stephen

**Comment by pascalporedda** [comment]
This has nothing to do with this project, rather look into the composer project.
