### ISSUE TITLE
Carousel auto play's when in mobile mode and autoplay false

### ISSUE THREAD

**Issue by AcidRaZor** [OwlCarousel2/OwlCarousel2#2462]
As per description. auto play is set to false, browser on PC doesn't auto play, but the moment it's in mobile view it starts automatically cycling through items.

$(".slider").owlCarousel({
        loop: false,
        margin: 0,
        nav: true,
        autoplay: false,
        animateOut: 'fadeOut',
        animateIn: 'fadeIn',
        items: 1,
        navText: ["<i class='fa fa-angle-left'></i>", "<i class='fa fa-angle-right'></i>"],
        dots: true,
        autoHeight: true,
        lazyLoad: true,
    });

**Comment by AcidRaZor** [comment]
Apologies. PEBCAK

**Comment by ncorre** [comment]
@AcidRaZor why you apologies ? I have the same issue and can't find the way to solve it. :)

**Comment by wpexplorer** [comment]
Anyone figure out a good fix?
