### ISSUE TITLE
Detect responsive height, fullPage.js with OwlCarousel

### ISSUE THREAD

**Issue by grodriguezbv** [OwlCarousel2/OwlCarousel2#2463]
Hello,

I'm using [fullPage.js](https://github.com/alvarotrigo/fullPage.js#fullpagejs) with OwlCarousel and I need to calculate the height for change the number of items. Is there any method to calculate it?

Thanks in advance for your attention.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
