### ISSUE TITLE
Owl Stage width bug

### ISSUE THREAD

**Issue by akoievroman** [OwlCarousel2/OwlCarousel2#2467]
### When I setup owl slider with more than 700 photos, I got wrong stage width calculation.

This bug is critical if you use owl slider for a Full-width slideshow.
Also if set loop: true, then you need fewer photos to see this bug [700/2].
Due to this owl, does not work in IE (32bit).

Some calculation:
$(".owl-item").length
778
$(".owl-item").width()
1694
1694*778

Stage width should be ~ 1317932px, but as you can see it is 1.32571e+06px

**Anybody knows how to avoid this?**

_____________
This is what i mean: http://nimb.ws/Sx759R
example:
http://jsfiddle.net/RomanRebus/moaLgyu0

**Comment by pascalporedda** [comment]
Well it works for me, so it does not really seem like a bug to me. Who is using a 32bit IE anyways?

**Comment by akoievroman** [comment]
> Well it works for me, so it does not really seem like a bug to me. Who is using a 32bit IE anyways?

So, you are saying that **width: 1.32571e+06px**  for slider wrapper is not a bug? http://nimb.ws/uySRvQ
I do not think that this is ok and the fact that 64x browsers work with this does not mean that this is the norm.

https://owlcarousel2.github.io/OwlCarousel2/docs/started-welcome.html
**Owl Carousel has been tested in following browsers/devices: IE7/8/10/11**
Great...


Also, will be great to add mode without "full width" wrapper. 
For example:
If you are using fade effects, you do not need a wrapper with such width, because you see only one photo and do not see the second slide before showing.
I think it will increase browsers compatibility and added more variants for customization.
