### ISSUE TITLE
[Question] - Touch drag on iframes

### ISSUE THREAD

**Issue by sadikyalcin** [OwlCarousel2/OwlCarousel2#2471]
This is more of a JavaScript / HTML question and maybe should be posted on Stack but here it is.

My carousel consists iframes. I would like to be able to use the drag/swipe gestures provided by Owl but it is impossible as the iframes are 100% in width and height. So all the events are captured by the iframe rather than the owl container.

```
<div class="owl-item">
  <iframe></iframe>
</div>
```

Disabling pointer-events is not a solution as I do have all sorts of events needed on the iframes.

Has anyone found a way around this? Maybe even passing events on from the iframe to the parent might work.

**Comment by pascalporedda** [comment]
You could try putting an overlay over the iframes that captures all actions (clicks, touches etc.) and only passes clicks and direct touch.clicks through to the iframe and don't pass the swipe / drag events to the carousel.

But anyway, this is for Stackoverflow though.
