### ISSUE TITLE
Carousel inside Carousel [clones not initialized]

### ISSUE THREAD

**Issue by seltix5** [OwlCarousel2/OwlCarousel2#2472]
Hello,
When using carousel inside carousel, clones are not initialized.

example : https://jsfiddle.net/seltix/5dyju03L/17/

How can I solve this problem?

Thank you.

**Comment by seltix5** [comment]
So,
After some testings, I build this solution :
I start using the 'initialized.owl.carousel' event to call owlcarousel builder again but because this event default handler does not stop propagation it will create infinite loop between the child and the parent carousel.
Adding "e.stopPropagation();" here https://github.com/OwlCarousel2/OwlCarousel2/blob/develop/dist/owl.carousel.js#L2198 (after the IF) solved the problem. 
Any better solution? should I create PR?

**Comment by pascalporedda** [comment]
I don't really see any use case for this. Sorry.

**Comment by seltix5** [comment]
The use case is to build one fullwidth carousel of products with each one showing one slider with the product photos thus the sliders inside a slider.
Thank you anyway :+1:
