### ISSUE TITLE
Static DIV on the right

### ISSUE THREAD

**Issue by berberon** [OwlCarousel2/OwlCarousel2#2475]
Hi

Is it possible to have a single DIV static and fixed on the right most position while the other rotate?

I'd like to have 10 images (1,2,3,4,5,6,7,8,9,10) where image 10 is static on the right while 1,2,3 | 4,5,6 | 7,8,9 rotate.

Thanks

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.

**Comment by berberon** [comment]
That's ok,

I managed to get what i wanted done.
Thought it may be useful as a feature for other people.

For example, when you are offering a replacement product, you want to show the original "out of stock" product static and then allow the other replacement offers to scroll.

Thanks
berber
