### ISSUE TITLE
Slide via mousemove (with autoplay)

### ISSUE THREAD

**Issue by yanyagunov** [OwlCarousel2/OwlCarousel2#2483]
I want the Owl carousel to behave like this example with additional autoplay. So initially it slides continuously in an endless loop and when hovering it slides depending on the x-position of the cursor:

(https://jsbin.com/uninug/3/edit?html,css,output)

Is that possible with Owl?

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
