### ISSUE TITLE
Having issue when modify width of carousel container

### ISSUE THREAD

**Issue by hassandad** [OwlCarousel2/OwlCarousel2#2484]
I have owl carousel inside a container div with id "recently-viewed-products-grid". At certain cases i have to decrease width of this container to 60% and then again at certain case i increase the width of this parent container again to 100%. 
```
<div class="products-grid row owl-carousel" id="recently-viewed-products-grid">
<!-- All my grid items here -->
</div>
```

Whats happening is that slider miscalculate the amount of slide it will require to show all products and show less products.

Lets say slider has 10 products and all these 10 can be viewed by dragging the slider. But when i decrease its width of parent container to 60% then it show 7 or 8 products by dragging the slider to last. And never show last two or three products. I have also tried refreshing it using

`$('#recently-viewed-products-grid').trigger('refresh.owl.carousel')`

it some how breaks the slider and all images get merged into each other and event listener

`onRefresh: onRecentOwlRefresh,`

never get called by this.

Can you please help me in this scenario. Here is my configuration

```
var recentViewOwl = jQuery("#recently-viewed-products-grid").owlCarousel({
            nav: true,
            items : 5,
            loop: false,
            //autoWidth:true,
            //navText: [&#x27;next&#x27;,&#x27;prev&#x27;]
            responsive:{
                360:{
                    items:2,
                },
                721:{
                    items:2,
                },
                767:{
                    items:3,
                },
                1200:{
                    items:5,
                }
            },            
            responsive: true,
            responsiveRefreshRate : 200,
            responsiveBaseElement: "#recently-viewed-products-grid",
            onRefresh: onRecentOwlRefresh,
          });

          function onRecentOwlRefresh(event){
            console.log('REFRESSHED',event);
          }
```

One more thing when i resize my browser window with this parent container 100% width, instead of showing 3 items it show all 5 items with small item boxes but actually it should show 3 items or less.

**Comment by pascalporedda** [comment]
(Sorry about the canned reply.)
I'm sorry but this seems not be an "issue" related to the OwlCarousel project. Please go to a site like [http://stackoverflow.com/](url) and get help by the community.
