### ISSUE TITLE
OwlCaroussel2 Error when run on Flask web server

### ISSUE THREAD

**Issue by loicquirion** [OwlCarousel2/OwlCarousel2#2517]
My owl carroussel was working perfectly when run on file:///C:/Users/loicp/Desktop/coding/home.html
but I just decided to run my code on a Flask web server (http://localhost/) and I get this error in my console:

GET http://localhost/owlcarousel/owl.carousel.min.css net::ERR_ABORTED 404 (NOT FOUND)
localhost/:13 GET http://localhost/owlcarousel/owl.theme.default.min.css net::ERR_ABORTED 404 (NOT FOUND)
2localhost/:700 GET http://localhost/owlcarousel/owl.carousel.min.js net::ERR_ABORTED 404 (NOT FOUND)
jquery-3.3.1.js:3818 jQuery.Deferred exception: $(...).owlCarousel is not a function TypeError: $(...).owlCarousel is not a function
    at HTMLDocument.<anonymous> (http://localhost/:705:23)
    at mightThrow (https://code.jquery.com/jquery-3.3.1.js:3534:29)
    at process (https://code.jquery.com/jquery-3.3.1.js:3602:12) undefined
jQuery.Deferred.exceptionHook @ jquery-3.3.1.js:3818
process @ jquery-3.3.1.js:3606
setTimeout (async)
(anonymous) @ jquery-3.3.1.js:3640
fire @ jquery-3.3.1.js:3268
fireWith @ jquery-3.3.1.js:3398
fire @ jquery-3.3.1.js:3406
fire @ jquery-3.3.1.js:3268
fireWith @ jquery-3.3.1.js:3398
ready @ jquery-3.3.1.js:3878
completed @ jquery-3.3.1.js:3888
jquery-3.3.1.js:3827 Uncaught TypeError: $(...).owlCarousel is not a function
    at HTMLDocument.<anonymous> ((index):705)
    at mightThrow (jquery-3.3.1.js:3534)
    at process (jquery-3.3.1.js:3602)

Can someone help me out?

Thanks!!

**Comment by loicquirion** [comment]
Solved!! I put all my carousel files into the static folder.

**Comment by Abubakarharuna10** [comment]
I'm facing the same issues
