### ISSUE TITLE
IOS Safary Weird scroll bahaviour

### ISSUE THREAD

**Issue by Rob-Nengerman** [OwlCarousel2/OwlCarousel2#2535]
### A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.>
When you touch slide on IOS devices you also move vertically.  
Only on Safary Browser

_____________
### `<url>` - a link to the reduced test case. You can use one of the following services:
[Our site](https://volkoren.tv)

_____________
### Any other information you want to share that is relevant to the issue being reported.
Some solution that didn't work for me are.

#Solution 1
`window.blockMenuHeaderScroll = false;
$(window).on('touchstart', function(e) {
    if ($(e.target).closest('.owl-grab').length == 1) {
        blockMenuHeaderScroll = true;
    }
});
$(window).on('touchend', function() {
    blockMenuHeaderScroll = false;
});
$(window).on('touchmove', function(e) {
     if (blockMenuHeaderScroll) {
        e.preventDefault();
     }
});`

#Solution 2
`.owl-carousel
{
    -ms-touch-action: pan-y;
    touch-action: pan-y;
}`

#Solution 3
`function stopMobileScroll() {
    document.ontouchmove = function (e) {
        e.preventDefault();
    };
};

function enableMobileScroll() {
    document.ontouchmove = function () {
        return true;
    };
};

$('.owl-carousel').owlCarousel({
    loop: false,
    slideBy: 1,
    onDrag: stopMobileScroll,
    onDragged: enableMobileScroll
});`

**Comment by Rob-Nengerman** [comment]
Look like the same issue.
#2459

**Comment by WebDigDev** [comment]
var tapArea, startX ;

   tapArea = document.querySelectorAll('.owl-carousel');
   startX = 0;
   for (var item of tapArea) {
     item.ontouchstart = function(e) {
       startX = e.touches[0].clientX;
     };
     item.ontouchmove = function(e) {
       if (Math.abs(e.touches[0].clientX - startX) > 5 && e.cancelable ) {
         e.preventDefault();
       }
     };
   }

**Comment by Rob-Nengerman** [comment]
This issue is fixed for me. 

Thanks to @WebDigDev
