### ISSUE TITLE
wrong variable name

### ISSUE THREAD

**Issue by iannacone** [OwlCarousel2/OwlCarousel2#2536]
https://github.com/OwlCarousel2/OwlCarousel2/blob/b76f3cff8147338091978f16c548978abac0d14e/src/scss/_theme.scss#L53

`$dot-rounded` should be `$owl-dot-rounded`

**Comment by simongoricar** [comment]
This was discussed in #2318, and #2321 fixes it (though it has not been merged yet).

**Comment by iannacone** [comment]
the issue list is a jungle. sorry anyway.
