### ISSUE TITLE
Controls missing!

### ISSUE THREAD

**Issue by AlenDesigns** [OwlCarousel2/OwlCarousel2#2577]
I just implemented owlcarousel into my project and got it working without a problem except controls are not showing.

I know some people fixed it by utilising css but the problem here is that I do not have controls rendered in my html. 

I also updated owlcarousel js file for the one which you are using on your website but I did not manage to get it to work.

Can someone please help? 
Thanks

**Comment by keefyhub** [comment]
Can you paste or link to the code you are using? I believe the controls should always be rendered just hidden with CSS if not required (or set to false)
