### ISSUE TITLE
Not working on IE9 click on prev and next button

### ISSUE THREAD

**Issue by bharatdangar** [OwlCarousel2/OwlCarousel2#258]
HI Owl,

Owl carousel is not working when i click on prev or next button. its working fine on owlcarousel2 first beta vesrion but not working on 2.4 version.

Please help me how can i fix this.

Here id JSfiddle URL
http://jsfiddle.net/zGde3/13/

there is slide changing but that slide is not animating.when click on pagination and next prev but slide is not animating

**Comment by niraj-ui** [comment]
Please suggest me how to solve

**Comment by bharatdangar** [comment]
Here you can find updated version of owl carousel working with ie9 

https://owlcarousel2.github.io/OwlCarousel2/

Please use this version
