### ISSUE TITLE
owl carousel is not working with *ngFor in angular 7

### ISSUE THREAD

**Issue by azaddeveloper** [OwlCarousel2/OwlCarousel2#2608]
```   
<div class="item" *ngFor='let document of documentArray;let i = index '>
            <div class="lab-grid-cell w-third--d w-half--t w-full--m">
                <div class="img-hover-zoom img-hover-zoom--brightness">
                    <img src="../../../assets/images/food-4.png">
                </div>
                <h3>test</h3>
            </div>
   </div>


 jQuery('.documentation').owlCarousel({
          loop: false,
          margin: 10,
        rewind: true,
          nav: false,
          responsive: {
            0: {
              items: 1
            },
            600: {
              items: 2
            },
            1000: {
              items: 4
            }
          }
 
    });```

**Comment by azaddeveloper** [comment]
Working fine without *ngfor
`<div class="item">
                                            <div class="lab-grid-cell w-third--d w-half--t w-full--m">
                                                <div class="img-hover-zoom img-hover-zoom--brightness">
                                                    <img src="../../../assets/images/food-4.png">
                                                </div>
                                                <h3>Foodie-Grade Recipes </h3>
                                            </div>
                                        </div>`
with *ngfor displayed static and not sliding
`   <div class="item" *ngFor='let document of documentArray;let i = index '>
                                                <div class="lab-grid-cell w-third--d w-half--t w-full--m">
                                                    <div class="img-hover-zoom img-hover-zoom--brightness">
                                                        <img src="../../../assets/images/food-4.png">
                                                    </div>
                                                    <h3>safsadf</h3>
                                                </div>
                                            </div>`




` jQuery('.documentation').owlCarousel({
          loop: false,
           margin: 10,
           rewind: true,
           nav: false,
          responsive: {
            0: {
              items: 1
            },
            600: {
              items: 2
            },
            1000: {
              items: 4
            }
          }
 
    });`

**Comment by azaddeveloper** [comment]
I have fixed this problem by [Jugaad](https://en.wikipedia.org/wiki/Jugaad)

**Step 1 :** In the HTML page, I added the documentation class.
```
<div class="owl-carousel documentation">
  </div>
```
**Step 2 :** I create items usgin for loop in the Ts file and append it under the documentation class.
```
this.documentservice.get_documentation().subscribe(
      data => {
        let result: any = data;
        this.documentArray = result.data;
        let string:string
        for(let i=0;i<=this.documentArray.length -1;i++){
          string += '<div  class="item"><div style="display: inline-block; position: relative; text-align: center;" class="lab-grid-cell w-third--d w-half--t w-full--m"> <div style="    background: #222f3e; height: 200px; overflow: hidden; margin: 2px;    " class="img-hover-zoom img-hover-zoom--brightness"> <img style="cursor:pointer;filter: brightness(80%); width: 100%; height: 100%;" src=" '+this.backend_url+'/assets/pdf/images/'+this.documentArray[i].thumbnail+' "> </div> <a href="javascript:void(0);" > <h3 class="doc-category" id="'+this.documentArray[i].id+'"  style="position: absolute; bottom: 0; color: #fff; text-align: center; width: 100%;">'+this.documentArray[i].name+'</h3></a> </div> </div>';
        }
       string = string.replace('undefined','');
       jQuery('.documentation').append(string);
      },
      error => {
        console.log(error);
      });
```
**Step 3 :** And initialized owlCarousel after viewInit
```
ngAfterViewInit() {
    setTimeout(function () {
      jQuery('.documentation').owlCarousel({
        loop: true,
        margin: 10,
         nav: false,
        responsive: {
          0: {
            items: 1
          },
          600: {
            items: 2
          },
          1000: {
            items: 4
          }
        }

      });
    }, 300);
}
```

**Comment by resuta566** [comment]
bro I have object I cant loop inside

**Comment by priyesh-shukla** [comment]
@azaddeveloper i have applied your solution but same problem.Can you suggest how i can resolve this issue.Here is my code:
service file:
      this.data.getCourse(params).subscribe(
        (res: any) => {
          if (!res) return;
          let aa = JSON.stringify(res.body.data);//console.log(aa);
          let getCourses = JSON.parse(aa);
          //console.log(getCourses);
          this.courses = getCourses;
          let string:string
          for(let i=0;i<=this.courses.length -1;i++){
            string += '<div class="item"><div style="display: inline-block; position: relative; text-align: center;" class="lab-grid-cell w-third--d w-half--t w-full--m"><div style="background: #222f3e; height: 200px; overflow: hidden; margin: 2px;" class="img-hover-zoom img-hover-zoom--brightness"> <img style="cursor:pointer;filter: brightness(80%); width: 100%; height: 100%;" src="'+this.courses[i].thumbnail_link+' "></div> <a href="javascript:void(0);" ><h3 class="doc-category" id="'+this.courses[i].post_id+'"style="position: absolute; bottom: 0; color: #fff; text-align: center; width: 100%;">'+this.courses[i].title+'</h3></a></div></div>';
          }
          //console.log(string);
          string = string.replace('undefined','');
          jQuery('.documentation').append(string);
        },
        error => {
          console.log("Error in API", error)
        }
      )
html file:
<div class="owl-carousel documentation"></div>

**Comment by resuta566** [comment]
> @azaddeveloper i have applied your solution but same problem.Can you suggest how i can resolve this issue.Here is my code:
> service file:
> this.data.getCourse(params).subscribe(
> (res: any) => {
> if (!res) return;
> let aa = JSON.stringify(res.body.data);//console.log(aa);
> let getCourses = JSON.parse(aa);
> //console.log(getCourses);
> this.courses = getCourses;
> let string:string
> for(let i=0;i<=this.courses.length -1;i++){
> string += '
> 
> ![]('+this.courses[i].thumbnail_link+' )
> <h3 class="doc-category" id="'+this.courses[i].post_id+'"style="position: absolute; bottom: 0; color: #fff; text-align: center; width: 100%;">'+this.courses[i].title+'
> ';
> }
> //console.log(string);
> string = string.replace('undefined','');
> jQuery('.documentation').append(string);
> },
> error => {
> console.log("Error in API", error)
> }
> )
> html file:

Dude I just use another carousel, try ngx-gallery

**Comment by ShevchukOleg** [comment]
Guys, I have a similar problem. The solution was to apply **_ngx-owl-carousel-o_** (Compatibility Angular 8). The transfer of asynchronous data to the carousel is performed through the template directive:

`<owl-carousel-o [options]="customOptions">
    <ng-container *ngFor="let slide of slidesStore">
      <ng-template carouselSlide [id]="slide.id">
        <img [src]="slide.src" [alt]="slide.alt" [title]="slide.title">
      </ng-template>
   </ng-container>
 </owl-carousel-o>`

**For usege you shold:**
1 npm install ngx-owl-carousel-o
2 Add styles to angular.json
3 Import RoutingModule and Routes into AppModule unless they are imported.
4 Import BrowserAnimationsModule into AppModule unless it is imported.
5 Import CarouselModule into a module which declares a component intended to have a carousel.
6 Add to needed component customOptions
7 Add html-markup to the template of the component

[Details](https://www.npmjs.com/package/ngx-owl-carousel-o)

All the best!!!

**Comment by krishnawaterland** [comment]
We have a working solution for this (personally it is a bad fix )
here we go

if you using angular then you can add it in your main.js file
-------------------------------------------------------------------------------------
    setTimeout(function(){ 
        $('.blog-slides').owlCarousel({
            loop: true,
            nav: true,
            dots: true,
            autoplayHoverPause: true,
            autoplay: true,
            margin: 30,
            navText: [
                "<i class='bx bx-chevron-left'></i>",
                "<i class='bx bx-chevron-right'></i>"
            ],
            responsive: {
                0: {
                    items: 1,
                },
                576: {
                    items: 1,
                },
                768: {
                    items: 2,
                },
                992: {
                    items: 3,
                }
            }
        });

    }, 2000);
