### ISSUE TITLE
How can I start owl carousel with an inactive dot?

### ISSUE THREAD

**Issue by YBernardo1975** [OwlCarousel2/OwlCarousel2#2616]
Hi everybody,
I'm successfully running a 3 slides owl carousel as a front element in my website. It works like a charm, but I need to load the first dot to appear inactive.
As a default, the 3 dots load as follows:
active-inactive-inactive
Is there a way to load them like this:
inactive-active-inactive?

Thanks!!

**Comment by keefyhub** [comment]
It sounds like you want to start at the 2nd item (if you are on a loop with 3 items).

You could try using start position - https://owlcarousel2.github.io/OwlCarousel2/docs/api-options.html#startposition

**Comment by YBernardo1975** [comment]
That is absolutely right,  thanks a lot!
