### ISSUE TITLE
infinite loop not working with 5 items ?

### ISSUE THREAD

**Issue by pierkidesign** [OwlCarousel2/OwlCarousel2#27]
Hello
I'm not able to make carousel work in infinite loop with 5 items visibles (on total of 5 items).

This is my code : 
$('#round').owlCarousel({
        items:5,
        loop:true,
        merge:true,
        center:true,
        responsiveClass:true,  
        mouseDrag:true,
        touchDrag:true,
        pullDrag:true,
        freeDrag:false,
        //margin:5,
        callbacks:true,
        navigation:true,
        URLhashListener:true,
        dots:false,
        //autoplayHoverPause:true,
        startPosition: 'URLHash'
    });
I use owl2 beta 1.5
I precise that one previous version of this plugin (beta 1.0) worked great with 5 items but did a fast rewind when last item + 1 is active.

An other pb is : next / previous buttons not working under IE11
Thanks =)

PS : great job ! owl carousel is one of my favorite jaquery plugin !

**Comment by priyaemphasize** [comment]
hi owl,
im facing issue in url hasing concept, when items is set as three and on clicking on the link it does not redirects to correct item.here is my code for your reference. Please help me to fix this problem.

My code:
$('.loop').owlCarousel({
  
  items:5,
  navText: false,
  nav:true,
  center: true,
  loop:true,
  dots: false,
  margin:0,
  merge:true,
  URLhashListener:true,
  startPosition: 'URLHash',
   navigationText: false,
 
  responsive:{
	0:{
      items:1
    },
	
	800:{
      items:5
    },
	
    600:{
      items:3
    },
	1366:{
      items:5
	  
	  
    }
		}
});
Fyi....
![error](https://cloud.githubusercontent.com/assets/11974071/8253806/e527d790-16b0-11e5-88b2-1d3a1d8b6f70.png)

**Comment by anuragjainsagar** [comment]
i wants to setup items:1.5 in the viewport and disable next button in last slide. so in this prev and next button is not working.


owl.owlCarousel({
        itemsCustom : [
          [0, 1.5],
          [1200, 2]
        ],
        navigation : true,
        nav: true,
        pagination : false,
        rewindNav : false
        
      });

Can anyone help me for solve the issue of prev. and next button of slider in 1.5 slides.


Thanks
