### ISSUE TITLE
create and update owl carousel with adding elements dynamically from javascript

### ISSUE THREAD

**Issue by SoniKarsh** [OwlCarousel2/OwlCarousel2#2725]
Using AJAX call i'm getting data from Server to my JS code and now i want to show that data into slider as the data i'm getting is images and now i need to update my slider.

My functionality is like based on the selection from a list of buttons i'm getting data from server and then server in return sending me the list of images based on the selection.

Now, i'm removing all the current child elements present inside owl-carousel class element and then creating and adding new elements based on the data ive got from the server and then adding that to my owl-carousel class.

But then its updating data but slider is not working its getting added as normal element and not as an carousel.

`var owl = $('.c-carousel').owlCarousel({
            loop: false,
            margin: 10,
            nav: true,
            navText: [
                "<i class='fa fa-caret-left'></i>",
                "<i class='fa fa-caret-right'></i>"
            ],
            autoplay: true,
            autoplayHoverPause: true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 3
                },
                1000: {
                    items: 5
                }
            }
        });`

Above is code for carousel

After creating an element im appending it to the main class having class owl-carousel
element.appendChild(newElementDiv);

element is an element that has a class as owl-carousel.
newElementDIv is an element that is used as an item inside owl-carousel.

Now, to update or reinitiate or make it run i don't know what to do. 

I looking forward to a solution. Thanks in advance.

i've tried some solution like

owl.owlCarousel();

Didnt work.

Also tried, owl.trigger('add.owl.carousel',
                            [newElementDIv]).trigger('refresh.owl.carousel');

**Comment by Cortexelus** [comment]
You could try destroying the `.c-carousel` element, creating and initializing a new one from scratch.

**Comment by SoniKarsh** [comment]
> You could try destroying the `.c-carousel` element, creating and initializing a new one from scratch.

Yeah. Thanks for the answer. I've actually implemented this and it worked.
