### ISSUE TITLE
OwlCarousel2  border action

### ISSUE THREAD

**Issue by whiteme1210** [OwlCarousel2/OwlCarousel2#2736]
When I click on the navigation dot below, a black frame will appear around it, how can I write it off?### 

[https://owlcarousel2.github.io/OwlCarousel2/demos/responsive.html](url)

![image](https://user-images.githubusercontent.com/51694409/83510035-eb076400-a4fe-11ea-8f00-de12974d6e87.png)
![擷取1](https://user-images.githubusercontent.com/51694409/83510250-446f9300-a4ff-11ea-91ef-c720e388c863.png)

**Comment by UnluckySerivelha** [comment]
Hi!
Just 
```
.owl-theme .owl-dots .owl-dot:focus {
    outline: none;
}
```

**Comment by whiteme1210** [comment]
> 嗨！
> 只是
> 
> ```
> .owl-theme .owl-dots .owl-dot:focus {
>     outline: none;
> }
> ```

Hi 

> Hi!
> Just
> 
> ```
> .owl-theme .owl-dots .owl-dot:focus {
>     outline: none;
> }
> ```

Hi 
so many Thx , You solved my problem
