### ISSUE TITLE
Destroy then re-enable?

### ISSUE THREAD

**Issue by jasonujmaalvis** [OwlCarousel2/OwlCarousel2#274]
Hello,

Has anyone got an example of destroying a carousel and then re-enabling it later on?

I'm basically destroying a carousel on small devices and then trying to re-enable the carousel when its resized back to large devices.

When I destroy the carousel and resize i get errors in the console:

Uncaught TypeError: Cannot read property '_checkVisibile' of null
Uncaught TypeError: Cannot read property '_onResize' of null

Not sure if its a bug or something I'm doing wrong.

Thanks

**Comment by alexiscm72** [comment]
I solved with this code:
$(".carousel-mini").each(function () {
    $(this).owlCarousel('destroy');      
  });
instead this:
$(".carousel-mini").owlCarousel('destroy');

**Comment by Humairah-Mujawar** [comment]
> Sorry but you have to re-create the carousel:
> 
> ```js
> $('.owl-carousel')
>   .owlCarousel({...})
>   .owlCarousel('destroy')
>   .owlCarousel({...})
> ```
> 
> A re-enabling will be not possible in the near feature.

thanks @witrin , this works!
