### ISSUE TITLE
Sync carousels

### ISSUE THREAD

**Issue by gabrielhsp** [OwlCarousel2/OwlCarousel2#278]
I am creating a slideshow with thumbnails, but I can not make the owl who gets the thumbs has a link that makes the main owl connect one item to another. Is there a way to do this? I can not use the first version of the owl because my main slideshow need to centralize the items, as there are different sizes. 

I put the code in CodePen: http://codepen.io/anon/pen/xgDhz

Sorry about my english :|

**Comment by odahcam** [comment]
#1378
