### ISSUE TITLE
Last item not fully reachable

### ISSUE THREAD

**Issue by coder20938** [OwlCarousel2/OwlCarousel2#293]
When there are too many pictures, the couple last pictures of the carousel are not displaying.
The last one displayed seems cut.

However, if we the browser is a lot wider, the pictures actually appear.

Here is an example:
http://codepen.io/anon/pen/sxrje

**Comment by baldwicc** [comment]
+1

**Comment by aaroncshearer** [comment]
+1

**Comment by smilledge** [comment]
+1, Anyone have a solution for this yet?

**Comment by theskillwithin** [comment]
+1

**Comment by theskillwithin** [comment]
using freedrag or loop is not a solution to this if the client does not want it to loop.    freedrag doesn't work either it just lets you kinda while holding it down see that there is more but when u let go it will bounce back.

**Comment by dingo-d** [comment]
Same thing happens to me. Any news on a workaround?

**Comment by catalinciupitu** [comment]
The issue seems to be the "items" setting, aka "active" images. The carousel container must be wider enough to display the last active images. I manage to dynamically change this setting and seems to work for me. This is the code I used in my project:

```
var carousel = $(".carousel");

carousel.owlCarousel({
                items : 3,
                autoWidth: true,
                lazyLoad: true,
                nav : true,
                dots: false,
                margin: 1,
                navContainerClass: 'owl-buttons',
                navText:	["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"]
            });

carousel.on('initialized.owl.carousel resized.owl.carousel', function() {
                var carouselWidth = $(this).width();
                var owlInstance = $(this).data('owlCarousel');
                var imgsWidth = 0;
                $($(this).find('img').get().reverse()).each(function(i) {
                    imgsWidth += $(this).width();
                    if (imgsWidth > carouselWidth) {
                        owlInstance.settings.items = i ? i : 1;
                        $(this).trigger('refresh.owl.carousel');
                        return false;
                    }
                });                
            });
```

**Comment by YellowSmiley** [comment]
I found adding fixed it for me:

```
.owl-item {
        padding-left:10px;
        padding-right:10px;
    }
```

**Comment by gyx8899** [comment]
Fixed in #1419
And get the latest version will be ok!

**Comment by sweettimes** [comment]
+1

**Comment by pinolo1** [comment]
@sawyerh set the max width at carousel container for example 1280px or 960 and margin auto. It work for me.

**Comment by murph133** [comment]
@pinolo1 Your solution seems to work! Brilliant! Thank you.

**Comment by pascalporedda** [comment]
The related PR for this has been merged a while ago. I will close this issue.

**Comment by maruf1020** [comment]
> @sawyerh set the max width at carousel container for example 1280px or 960 and margin auto. It work for me.

Is this just a CSS change??

**Comment by matteolcd** [comment]
@maruf1020 

> Is this just a CSS change??

Yes, but this tread it's very old, i don't knew if it's work jet..
