### ISSUE TITLE
Smooth autoplay

### ISSUE THREAD

**Issue by Globegitter** [OwlCarousel2/OwlCarousel2#296]
Just started using this plugin and really loving it so far but one thing that would make the autoplay function look that much more beautiful in my use-case, is if it would support 'smooth' autoplay. Meaning that it doesn't stop at every new image but just smoothly carries on looping forever.

**Comment by jason-engage** [comment]
Good hack thanks sth.

I added a custom setting called slideTransition: 'linear' to turn it on and off.

**Comment by cortopy** [comment]
@sth84 that sounds like a good solution. But I can't find where to make the second change. I can't find either line 2496 or the function you mention. 

The current dev version has 1654 lines only? What am I missing?

**Comment by jason-engage** [comment]
@cortopy you're probably not looking at the fully compiled js including all the subscripts.

**Comment by cortopy** [comment]
It's either getting late or I'm going blind, but where is the fully compiled js? I'm looking at the src folder but I can't find js files anywhere else

**Comment by jason-engage** [comment]
@cortopy you have to make it with the gruntfile

**Comment by cortopy** [comment]
Ah! I only know gulp so not familiar with grunt really. 

Apart from getting the exact line, I've searched in all files for "Autoplay.prototype.autoplay" but that's nowhere to be seen for me. I've also searched within the repository in Github but nothing

**Comment by jason-engage** [comment]
@cortopy i added the instructions above - the autoplay stuff in the the video js

**Comment by cortopy** [comment]
Thanks a lot for that. At least now I know how grunt works. Ok, so I've set it all up and now I'm getting the BIG file but I'm still unable to find "Autoplay.prototype.autoplay"

The closest is "Autoplay.prototype.play" but it doesn't run `clearInterval` & `setInterval`, so I'm still unable to find where to change these. For example, `clearInterval` only appears in the stop function

**Comment by jason-engage** [comment]
Hmm, they must have changed it. Its still in my code, which is about a month old. You should probably be able to download an older revision from git... 

if there's no other setinterval in there then maybe your best bet is to grab an older version and mod that. I'm not sure what they've updated in the meantime tho...

**Comment by jason-engage** [comment]
I don't see any changes to that. What's at that line number 2496?

**Comment by cortopy** [comment]
Thanks so much @jason-engage !!! That's my big mystery solved. I was pretty sure it had something to do with the autoplay plugin https://github.com/smashingboxes/OwlCarousel2/blob/develop/src/js/owl.autoplay.js but just couldn't find what exactly

https://github.com/smashingboxes/OwlCarousel2/commit/c9fbddf74ed2291b0313d4e5d8add9d50de4b07c
This commit in July removed that particular function. I can see in your code you already applied the hack and your carousel looks awesome! Thanks for that

@witrin I'm just copying you here in case this helps. I can see smooth scrolling is in the roadmap. I hope it's not been dropped but just in case
Thanks so much @jason-engage !!! That's my big mystery solved. I was pretty sure it had something to do with the autoplay plugin https://github.com/smashingboxes/OwlCarousel2/blob/develop/src/js/owl.autoplay.js but just couldn't find what exactly

https://github.com/smashingboxes/OwlCarousel2/commit/c9fbddf74ed2291b0313d4e5d8add9d50de4b07c
This commit in July removed that particular function. I can see in your code you already applied the hack and your carousel looks awesome!  I'll try to see how to apply this with the new version but otherwise yours works just fine. Thanks for that.

**Comment by 0x1ad2** [comment]
@jason-engage I've found your script (http://awesome-media-gallery.en.gg/js/vendor/owl.carousel.custom.min.js) and it's working like a charm. I was wondering if you have an unminified version available?

**Comment by andyexeter** [comment]
@0x1ad2 Try removing the `.min` from the URL ;)

**Comment by jason-engage** [comment]
@0x1ad2 @andyexeter Yep!

**Comment by 0x1ad2** [comment]
Ah thanks didn't knew that one was available :)

**Comment by YuraChumak** [comment]
thanks, it helped me

**Comment by Jaibles** [comment]
@jason-engage any chance you could share that file again please? :)

**Comment by daviddeutsch** [comment]
@jason-engage would you mind creating a PR from this? I'd love to include fixes like this one! (Would prefer to have the original author of the fix on the commit timeline rather than claiming credit for it myself.)

**Comment by jason-engage** [comment]
@Jaibles @daviddeutsch 

Good idea David, I created a repo with the files.

https://github.com/jason-engage/awesome-media-carousel

Enjoy!

**Comment by daviddeutsch** [comment]
Hey, thanks @jason-engage! Still - last chance to make a Pull Request for your changes, otherwise I will make one and it ends up being my name in the commit history 😉

**Comment by jason-engage** [comment]
@daviddeutsch Thanks for the kind thinking, but I'm really not sure if this fix would integrate well with your latest OC version. I'll let you go ahead and make the magic happen. Hopefully this thread will stand in honor of my great contribution! lol

**Comment by daviddeutsch** [comment]
Alright, I will try to do it justice 😉

**Comment by dragosmocrii** [comment]
Any news on this? Is this implemented?

**Comment by bamboorocket** [comment]
Hi, I just implemented this on my site, big thanks.
BUT noted an issue with the settings of:

      slideTransition: 'linear',
      autoplayTimeout: 0,
      autoplaySpeed: 5000

The autoplayHoverPause is not working.
Any ideas how I can get the pause on hover to work again?

**Comment by KevinTaron** [comment]
thanks. love it!

**Comment by robbporto** [comment]
+1

Any news? I tested on version 2.2.1 and it's not available.

**Comment by zdarovka** [comment]
+1 Looking for a solution.

**Comment by robbporto** [comment]
Any news on this? I really wanna continue to use this plugin but I need this functionality...

**Comment by iMezied** [comment]
+1

**Comment by emanuelrosa** [comment]
+1 Yep. Looking for a solution! 🙏

**Comment by amaurycatelan** [comment]
#1490

**Comment by de-b** [comment]
+1 Worked like a charm. Thank you @jason-engage

**Comment by cameronepstein** [comment]
This works but be aware on mobile there are huge scrolling issues

**Comment by vojto** [comment]
I don't know if @daviddeutsch ever created PR based on @jason-engage's changes.

This worked for me: https://github.com/OwlCarousel2/OwlCarousel2/pull/2138

**Comment by svanskivar** [comment]
How can do this with current version of OwlCarousel?

**Comment by chrisschwartze** [comment]
Also looking for this +!

**Comment by pascalporedda** [comment]
I've looked into the PR of vojito and tweaked the changes a bit. The `slideTransition` option will be available in the next release.

**Comment by janbabiak** [comment]
working settings for v2.3.4
autoplay : true,
slideTransition: 'linear',
autoplayTimeout : 4000, 
autoplayHoverPause : false,
autoplaySpeed : 4000,

the point is, autoplayTimeout is not timeout (does not start at end of autoplay slide), but it's ticking interval, ... so autoplaySpeed (duration of slide) should not be higher than autoplayTimeout (some increasing speed logic is aplied and it works strange)

**Comment by piotrchabros** [comment]
does not fucking work

**Comment by marcohanke** [comment]
@janbabiak works great event toady. Thanks. But is there a solution to skip the "first" 4000ms?
Id like to start the scrolling instant after pageload.
Thanks

**Comment by esadeghi942** [comment]
hi
i have this problem but this library is very good.just this code reslove your problem

$(".element").trigger('play.owl.autoplay',[delay,speed])

just set speed=5000

good luck
