### ISSUE TITLE
attaching a callback to `initialize.owl.carousel` does not fire

### ISSUE THREAD

**Issue by richcouzzi** [OwlCarousel2/OwlCarousel2#305]
Pretty much all of attachable events are working—apart from `initialize.owl.carousel` and `initialized.owl.carousel`. I can't seem to bind to these events.

This does _not_ work:

``` javascript
var $videos = $('.coaches__videos');

$videos.owlCarousel({loop: true});
$videos.on('initialize.owl.carousel', function( event ){
    console.log( event );
});

$videos.on('initialized.owl.carousel', function( event ){
    console.log( event );
});     
```

This _does_ work:

``` javascript
var $videos = $('.coaches__videos');

$videos.owlCarousel({loop: true});
$videos.on('drag.owl.carousel', function( event ){
    console.log( event );
});
```

Any ideas? Thanks.

**Comment by zhaodadi** [comment]
Thanks!! @witrin

**Comment by rajemahendra21** [comment]
thanks @witrin

**Comment by theStreets93** [comment]
Short info: http://www.owlcarousel.owlgraphic.com/demos/events.html

Notice that **initialize.owl.carousel** and **initialized.owl.carousel** events must be attached before Owl Carousel initialization.

**Comment by niravpatel9898** [comment]
Nothing worked for me. I tried writing a callback function in the options. In the documentation the event name was `onInitialized` and still it was not working. Somehow I landed up on [this codepen link](https://codepen.io/OwlFonk/pen/fJump) where the event name was `afterInit`. afterInit worked for me.

**Comment by manchumahara** [comment]
@niravpatel9898  afterInit worked for you because you are using old version of owl carousel if I am not wrong. Can you please check and update here ?

**Comment by aline-matos** [comment]
Update of @witrin answer:
[https://owlcarousel2.github.io/OwlCarousel2/demos/events.html](url)
