### ISSUE TITLE
Resize Manipulation

### ISSUE THREAD

**Issue by grafixes** [OwlCarousel2/OwlCarousel2#32]
Hi Bartosz,

First off, you've created an amazing product, thank you!

Is there a manipulation event I can use to manually fire the resize function that OwlCarousel uses for its responsiveness? I'm developing a site on which the carousels width dynamically changes without the browser-window being resized. So the browser stays the same size while the carousel itself is enlarged or reduced by clicking on a trigger. I've tried using the jQuery .resize(); function but doesn't seem to do the trick.

I've found that you've developed plugin manipulation functionality like owl.data('owlCarousel').updatePosition(); . Is there also an event for triggering the resize function?

Best Regards,
Max

**Comment by denone** [comment]
We've just used code snippet from that fiddle http://jsfiddle.net/GN22j/2/ :+1: in one our project. Thanks!
