### ISSUE TITLE
autoWidth + lazyLoad

### ISSUE THREAD

**Issue by eiszfuchs** [OwlCarousel2/OwlCarousel2#33]
OwlCarousel seems to have to load all images before being able to calculate widths while `autoWidth` is set to `true`. Maybe I'm just doing it wrong.
My setup basically looks like this:

``` html
<div class="owl-carousel">
    <div style="width: 500px;">
        <span class="caption">Caption A</span>
        <img class="owl-lazy" width="500" height="200" data-src="large-image.a.jpg" alt="">
    </div>

    <div style="width: 700px;">
        <span class="caption">Caption B</span>
        <img class="owl-lazy" width="700" height="200" data-src="large-image.b.jpg" alt="">
    </div>

    <div style="width: 1200px;">
        <span class="caption">Caption C</span>
        <img class="owl-lazy" width="1200" height="200" data-src="large-image.c.jpg" alt="">
    </div>

    <div style="width: 300px;">
        <span class="caption">Caption D</span>
        <img class="owl-lazy" width="300" height="200" data-src="large-image.d.jpg" alt="">
    </div>
</div>
```

The thing is that I already know how big my images are and don't have to wait for images to load. Also, I'm resizing images as the browser's window is resized, but _that_ is working like it's supposed to do once the slider is initialised.
Is there a way to tell it to rely on widths I already provide?

**Comment by Whiplash5057** [comment]
Hey guys, the if statement is not present in v1.3.3. Is there a fix to this that I can use
