### ISSUE TITLE
Horizontal Center Items When Less Than 'Full'

### ISSUE THREAD

**Issue by AJB99** [OwlCarousel2/OwlCarousel2#35]
Hi there, amazing plugin.

I'm trying to figure out how to center all the items within a carousel if there's not enough items to fill it up. I'm using Owl Carousel to house the thumbnails for a video playlist.

For example, if my carousel has enough width to contain 8 thumbnails, but there's only 4 items in any given playlist, is there a way to have those 4 thumbnails center within the carousel?

**Comment by mohnstrudel** [comment]
Hi Owl,

first of all - amazing plugin! Is the centering available via an option as of 2015? I've got two carousels, one for "hot" products and one for latest. I'd like to display the big picture (hot product) centered - http://take.ms/BhgHn
