### ISSUE TITLE
More control over video players

### ISSUE THREAD

**Issue by zabinetta** [OwlCarousel2/OwlCarousel2#355]
I would like to use youtube players parameters. sometimes I dont want the related videos and stuff
e.g. like
near line 2111:
/**
	 * Default options.
	 * @public
	 */
	Video.Defaults = {
		video: false,
		videoHeight: false,
		videoWidth: false,
		videoParamsYoutube: '&rel=0',
		videoParamsVimeo: ''
	};

and near line 2251:
if (video.type === 'youtube') {
			html = '<iframe width="' + width + '" height="' + height + '" src="http://www.youtube.com/embed/'
				+ video.id + '?autoplay=1' + this._core.settings.videoParamsYoutube + '&v=' + video.id + '" frameborder="0" allowfullscreen></iframe>';
		} else if (video.type === 'vimeo') {
			html = '<iframe src="http://player.vimeo.com/video/' + video.id + '?autoplay=1' + this._core.settings.videoParamsVimeo + '" width="' + width
				+ '" height="' + height
				+ '" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';
		}

I'm not so sure if there are vimeo-params and how they work.......

**Comment by eparisio** [comment]
i've created a pull request for this, i added only a base support for youtube parameters
