### ISSUE TITLE
Optionally replace pagination dots with numbers

### ISSUE THREAD

**Issue by Dobby89** [OwlCarousel2/OwlCarousel2#356]
In the old owl carousel, there was an option to use numbers for the pagination, using the ```paginationNumbers``` parameter.

Can this option be added?

**Comment by nathansh** [comment]
You could also use a CSS counter:

```
.owl-dots {
	counter-reset: dots;
}
.owl-dot:before {
	counter-increment:dots;
	content: counter(dots);
}
```

**Comment by tuanbtre** [comment]
using jquery add number of page to span
$('.owl-dot').each(function(){
		$(this).children('span').text($(this).index()+1);
	});

**Comment by tuanbtre** [comment]
using jquery add number of page to span
$('.owl-dot').each(function(){
		$(this).children('span').text($(this).index()+1);
	});
