### ISSUE TITLE
to.owl.carousel throws an error

### ISSUE THREAD

**Issue by hanspagel** [OwlCarousel2/OwlCarousel2#376]
hey, I'm trying to sync two carousels. I'm using the to.owl.carousel and it throws an error:

``` javascript
$slider.on('changed.owl.carousel', function(event) {
    var page = event.page.index;
    $otherslider.trigger('to.owl.carousel', [page]);
});
```

as parameters I used different things: [0], [0, 300], [1], 2...

all versions throw this error:

```
Uncaught TypeError: Cannot read property 'start' of undefined (owl.carousel.js:2961)
```

owl.carousel.js:2961 says

``` javascript
$.proxy(this._overrides.to, this._core)(this._pages[((position % length) + length) % length].start, speed);
```

this._pages is undefined

I don't know how to get deeper into this, has anyone an idea? Using 'next.owl.carousel' works in the first example but I would have a lot of checks to get both in sync. Using 'to.owl.carousel' would be great.

**Comment by richbradshaw** [comment]
I also get this, but only when setting dots: false.

**Comment by overly-engineered** [comment]
im with @richbradshaw on this. problem went away as soon as i removed dots: false

**Comment by drtobal** [comment]
Same problem here, fixed on `dots: true`

**Comment by shtalinberg** [comment]
dots: false 
TypeError: Cannot read property 'start' of undefined
