### ISSUE TITLE
Auto height for multiple items

### ISSUE THREAD

**Issue by shur** [OwlCarousel2/OwlCarousel2#378]
There are some difficulties with autoHeight option to work with multiple visible items.
My questions a slightly different. How to make all items (not only visible) have the same height which equals the tallest of them.

I plan to use the script in a responsive template for RAXO module (http://www.raxo.org/)
so how to make the height to recalculate accordingly.
![owl-carousel-same-height](https://cloud.githubusercontent.com/assets/1245155/3776725/39eec532-1959-11e4-8e4d-6e5c86b76122.png)

Do you plan to add this option, e.g. autoHeigh:all ?

**Comment by daviddeutsch** [comment]
This needs to be fixed either with a custom theme or with a flexbox solution down the road (v2.5 or later).

**Comment by marcing** [comment]
This can be achieved with CSS by applying flexbox to stage:

`
.own-carousel.owl-carousel .owl-stage
{
	display: flex;
	flex-direction: row;
}

.own-carousel.owl-carousel .owl-stage::after
{
	display: none;
}

.own-carousel.owl-carousel .owl-item 
{
	float: none;
}`

**Comment by behnamazimi** [comment]
I used flex to solve this issue:

```
 .owl-stage {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;

    -webkit-flex-wrap: wrap;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
}
```
above code for `owl-stage` and below for `owl-item` class:

```
.owl-item{
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    height: auto !important;
}

```
I hope this reply help every body that have this issue.

**Comment by isalew** [comment]
@behnamazimi, thank you. That was simple and just what I needed!

**Comment by polodev** [comment]
Keep .owl-stage display flex. and all child will take all space by `flex: 1`

~~~css
  .owl-stage {
   display: flex;
  }
  .owl-item {
   display: flex;
   flex: 1;
  }
~~~

**Comment by lerouxm** [comment]
```css
.owl-stage {
   display: flex;
}
.owl-item {
   display: flex;
   flex: 1 0 auto;
}
```
Worked better for me as using `flex: 1` leaded to 1px cropped first element.

**Comment by avtneyney** [comment]
@lerouxm, thank you for the flex: 1 **0** auto; tip because it also fixes underflow (if this is the right word here) on the rightmost owl-item when owl-stage is displayed as flex container, this is something that's been bothering me for quite some time now.

**Comment by engineerdevi** [comment]
Set the autoHeight option of the owl-carousel to false. It stretches all small owl-items to the height of the tallest owl-item.
 `autoHeight: false`

**Comment by abidiel** [comment]
@behnamazimi

Working in Owl Carousel v2.3.4, thanks

**Comment by patricechaula** [comment]
@behnamazimi thank you.
