### ISSUE TITLE
Specify containers for next/prev buttons and dot navigation

### ISSUE THREAD

**Issue by gnettles** [OwlCarousel2/OwlCarousel2#41]
First off - this is a great plugin!

Some page layouts may require the carousel controls to be outside the container for the carousel itself. It would be great if you added this as an option, something like:

```
{
navContainer: 'some-class' // or even $('some-class'),
dotsContainer: 'another-class' // or $('another-class')
}
```

I recognize this may be an edge-case for most - but thought I'd put it out there anyway. I have a version working locally if you're interested (though it's rough for now)

**Comment by technbuzz** [comment]
Is there a way to move the dotContainer in specific situation. For example I want the dotContainer to be placed somewhere else but on smaller I want its default position.

**Comment by Primajin** [comment]
@technbuzz apart from css positioning, you can use flexbox' order to switch positions, and then back on larger screen.
