### ISSUE TITLE
Error in destroy()

### ISSUE THREAD

**Issue by uudens** [OwlCarousel2/OwlCarousel2#423]
When calling or triggering `destroy` I run into this error:

```
Uncaught TypeError: Cannot read property 'dom' of undefined
```

Here is a CodePen, hotlinked to newest dist in master. Press one of the buttons to see the error (I use Chrome). http://codepen.io/anon/pen/BwKAq

Error doesn't happen when using owl.carousel.js hotlinked from http://www.owlcarousel.owlgraphic.com/

**Comment by allantatter** [comment]
When will this be merged into master branch? Approximate time maybe?
