### ISSUE TITLE
v1 jumpTo event in OwlCarousel2

### ISSUE THREAD

**Issue by JosHuybrighs** [OwlCarousel2/OwlCarousel2#441]
If you want to have in v2 beta a similar functionality as the v1 jumpTo method; you must trigger a carousel.trigger('to.owl.carousel', [position, speed]) call. OwlCarousel2 will then popup the requested slide.
I did not extensively checked the code but I think that when you set 'speed' to, let's say 200, then, before the requested slide is shown, each slide between the currently active one and the intended, will come up for 200ms. So, if you have 10 slides to skip it takes 2 seconds before the wanted one appears.
Now, contrary to what one would expect when setting 'speed' to 0, a default 'timout', defined by settings.smartSpeed, is used for every slide.

You can overcome this, by specifying a very short 'speed' value, like '1' or by changing the implementation of Owl.prototype.duration as shown next.

Owl.prototype.duration = function(from, to, factor) {
//return Math.min(Math.max(Math.abs(to - from), 1), 6) \* Math.abs((factor || this.settings.smartSpeed));
return Math.min(Math.max(Math.abs(to - from), 1), 6) \* Math.abs((factor == undefined) ? this.settings.smartSpeed : factor);
};

This solved my problem, but it still doesn't seem to be the best solution, because I have the impression that 'jumping' to a slide in this way (by setting speed to 0) internally in the code will still bringup all the neighbour slides one after each other albeit you won't see it on the screen.

**Comment by dbalabka** [comment]
@JosHuybrighs it was useful for me. It isn't clear from the documentation how to programmatically switch slide.
