### ISSUE TITLE
Navigation not working?

### ISSUE THREAD

**Issue by fritx** [OwlCarousel2/OwlCarousel2#480]
``` js
$carousel.owlCarousel({
  loop: true,
  items: 1
})
```

However, the navigation doesn't show automatically.

I use Zepto.
Any ideas? Thanks very much!

**Comment by marcustisater** [comment]
Why isn't this implemented into owl2? It's broken, you can't see the dots unless you have styled them.

**Comment by damon7304** [comment]
yep @rustemgareev  it work perfecty fine

**Comment by jakeoblivion** [comment]
As mentioned, author forgot to add them to the zip...
Original theme is found here:
http://www.owlcarousel.owlgraphic.com/assets/owlcarousel/assets/owl.theme.default.min.css

**Comment by mike-source** [comment]
Still an issue

**Comment by codyme** [comment]
still an issue

**Comment by guykatz** [comment]
I have noticed that the problem is that the code does not add the 'owl-theme' class to the wrapper div.
if you add it (by code or via your html) the dots and nav will appear
this applies to 2.1.6 which is the only version I use.
thanks

**Comment by mikeyaworski** [comment]
Wow. this is still an issue...

Edit: changing `<div class="owl-carousel" ...` to `<div class="owl-carousel owl-theme"...` made it work.

**Comment by guykatz** [comment]
I think once I added the 'owl-theme' class to the div it started working.

**Comment by jpekeene** [comment]
Still an issue @jakeoblivion is right, pasted those into empty css file and all was well again.

**Comment by d88pak** [comment]
Same issue here
I have `class="owl-carousel owl-theme"` and have included the `owl.theme.css` from version 1. Still no dots visible.

**Comment by jpekeene** [comment]
@d88pak Make sure the css file is not empty, that was my issue.

**Comment by jonabaptistella** [comment]
It is still a issue in the last version...  @daviddeutsch

**Comment by rusticblonde** [comment]
Hi, this has been closed but is STILL not working. Any news of a resultion?!?!

**Comment by MomentumDigitalCreative** [comment]
Be careful not to load or initialise any of the OwlCarousel2 scripts twice, I did by accident and it caused this exact issue.

**Comment by MarkGrenville** [comment]
This is more than 2 years old.. its very weird that someone didn't add the styles for the dots to the style sheet. Anyway the answer from 6nqymrpaydon worked for me. Thanks.

**Comment by lukasz-formela** [comment]
> As mentioned, author forgot to add them to the zip...
> Original theme is found here:
> http://www.owlcarousel.owlgraphic.com/assets/owlcarousel/assets/owl.theme.default.min.css

It's a dead link for me.
Also ++ to the thread.
