### ISSUE TITLE
calling remove.owl.carousel removes entire carousel

### ISSUE THREAD

**Issue by petty** [OwlCarousel2/OwlCarousel2#481]
... so when I call:

```
var $carousel = $(".owl-carousel");

$carousel.trigger('remove.owl.carousel', 0 );
```

... instead of that slide (the first) getting removed the entire carousel is getting removed.

Here's my carousel instantiation:

```
$carousel.owlCarousel({
                loop: false,
                autoWidth: true,
                dots: true,
                nav: false,
                mouseDrag : true,
                responsive:{
                    0:{
                        items:1
                    },
                    480:{
                        items:2
                    },
                    768:{
                        items:3
                    },
                    1024:{
                        items:4
                    }
                }
            });
```

Also, what my real goal is, is to be able to iterate & delete, e.g.

```
for (i=50;i<=100;i++) {
    $carousel.trigger('remove.owl.carousel', i );
}
```

**Comment by alessandroweb** [comment]
Any solutions?!

**Comment by jhongstore** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dcjae@naver.com 님께 보내신 메일 <Re: [OwlCarousel2] calling remove.owl.carousel removes entire carousel (#481)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by cjames** [comment]
I caught the same bug. I'm going to go with renaming the event. Beware of the change.owl.carousel event as well as it can be triggered by change events within the item.

**Comment by joeyjoejoejr** [comment]
Looks like this is a live one.

**Comment by richgcook** [comment]
I am getting issues, too, even when using this. Essentially, removing the first slide when the screen size is below 767...

```
$(window).resize(function() {
	if ($(window).width() < 767) {
		$('.wide-slider').each(function() {
			var $this = $(this);
			$this.trigger('remove.owl.carousel', 0);
		});
	}
});
```

**Comment by sanderkruger** [comment]
I'm having the same issue. I tried stepping through the code, but I'm not enough of a jQuery expert to see the bug. Renaming the event looks like a bad option because plugins depend on it, such as navigation, which needs the event to remove the item too.

Looking at the handler in the Navigation plugin, it seems that the bug is not in how the Event object is passed on, although it seems odd to me that the remove target is the Owl object and not the item.

**Comment by aleroy** [comment]
sujitkumardora has the gist of it ... but you don't need rename the event. 

The `Owl.prototype.remove` needs to fully-qualify the `methodName` parameter in its call to `this.trigger()`. (this should be done in several other places as well...might be a good idea to make it a requirement).

Anyways, here's a diff to fix the remove issue (against the current master branch as the time of this post):

    1330c1330
    < 		this.trigger('remove', { content: this._items[position], position: position });
    ---
    > 		this.trigger('remove.owl.carousel', { content: this._items[position], position: position });

**Comment by matthieu-interaktiv** [comment]
Any updates on this bug?

**Comment by ses** [comment]
@OwlFonk please fix this bug. Thanks

**Comment by aleroy** [comment]
It's fixed in the dev branch. A lot of things are fixed in the dev branch.

If you migrate to the dev branch, note that it deprecates the need for `$('.owl-carousel').trigger()`, opting for the more stable `('.owl-carousel').owlCarousel(`*method*, **args*`)`

    // remove the first item (dev version)
    $('.owl-carousel').owlCarousel( 'remove', 0 );

**Comment by oneChifu** [comment]
Hey. Thanx to sujitkumardora for idea. I just renamed "remove" event name in owlCarousel code to "del" (for example) and it's work fine. Remove item from carousel dynamicly:

$(document).on('click', 'delete_item', function(e) {
	e.preventDefault();
	$(this).closest('.owl-item').trigger('del.owl.carousel', $(this).index());
});

**Comment by jin-cheng** [comment]
Line 1424
	this.trigger('remove', { content: this._items[position], position: position });
	-->
	this.trigger('del', { content: this._items[position], position: position });
	
Line 1431
	this.trigger('removed', { content: null, position: position });
	-->
	this.trigger('deled', { content: null, position: position });

Line 1457
	'remove': this.remove
	-->
	'del': this.remove

**Comment by digz6666** [comment]
Is it included in the master branch?

**Comment by samir-kamble** [comment]
not working for me at-least. Cant remove intermediate elements on click of delete of each item.

**Comment by buingthai** [comment]
my ideal for older version (<2.2) carousel:
$(".owl-item").remove()
then, you can add item with event "add.owl.carousel"
hope to help you!

**Comment by foxartbox** [comment]
Working solution:

*** HTML
<div class="header_links">
	<div class="owl-carousel">
		<a href="" target="_blank"><img class="svg" src="/images/1.jpg" alt="" /></a>
		<a href="" target="_blank"><img class="svg" src="/images/1.jpg" alt="" /></a>
		<a href="" target="_blank"><img class="svg" src="/images/1.jpg" alt="" /></a>
		<a href="" target="_blank"><img class="svg" src="/images/1.jpg" alt="" /></a>
	</div>
</div>


*** JS
$(window).bind("load", function() {
	// copy default code before carousel loaded
	var header_links__html = $('.header_links').html();

	window_resize();

	$(window).resize(function() {
		window_resize();
	});

	function window_resize() {
		// mobile
		if ( $(window).width() < 900 ) {
			if ( !$('.header_links').find('.owl-carousel').hasClass('owl-loaded') ) {
				$('.header_links').find('.owl-carousel').owlCarousel({
					autoplay: true,
					autoplayHoverPause: true,
					autoplayTimeout: 2500,
					dots: true,
					items: 2,
					loop: true,
					nav: false,
					responsive: {
						0: {
							items: 1
						},
						320: {
							items: 2
						},
						600: {
							items: 3
						},
						800: {
							items: 5
						}
					},
					smartSpeed: 350
				});
			}
		}
		//desktop
		else {
			if ( $('.header_links').find('.owl-carousel').hasClass('owl-loaded') ) {
				$('.header_links').find('.owl-carousel').remove();

				$('.header_links').append( header_links__html );
			}

			if ( !$('.header_links').find('.owl-carousel').length ) {
				$('.header_links').append( header_links__html );
			}
		}
	}
});

**Comment by faderriko** [comment]
Thanks foxartbox . Its working

**Comment by pascalporedda** [comment]
Seems like this one is solved.
