### ISSUE TITLE
Use of cursor: grab; and cursor: grabbing;

### ISSUE THREAD

**Issue by TomOne** [OwlCarousel2/OwlCarousel2#499]
Currently Owl Carousel only uses `cursor: grab;` as soon as the carousel is grabbed/dragged.

But the grab and grabbing cursors have the following semantics:
- The `grab` cursor is intended to indicate something that can be grabbed/dragged, so I would use it on `:hover` of the carousel.
- The `grabbing` cursor indicates that something is currently grabbed/dragged.

How about implementing it like this?

**Comment by joszua** [comment]
You may want to modify the style of owl-carousel, specifically the `.owl-drag` and `.owl-grab` classes. Just make sure to add the parent `<div>` class⁠—e.g. `parent-div`  before it to apply only the modification inside that parent `<div>`. It works for me.
```
.parent-div .owl-carousel.owl-theme.tour-packages-slider.owl-loaded.owl-drag {
    cursor: grab;
}

.parent-div .owl-carousel.owl-theme.tour-packages-slider.owl-loaded.owl-grab {
    cursor: grabbing;
}
```
