### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by bloccxx** [OwlCarousel2/OwlCarousel2#51]
Any thoughts on addind a "full screen mode"?  Kind of like http://nicinabox.com/superslides/ and http://buildinternet.com/project/supersized/

Thank alot for your hard work on this, Owl!!

**Comment by Rombecchi** [comment]
Wating for version 3.0... 
In mobile version I need a zoom feature such this: the page shows carousel with multiple photos (autowidth). When user clicks the carousel, it zoom to a responsive fullscreen with a single photo (so, if the user rotate the screen the content will adapt accordingly).
Thanks in advance
