### ISSUE TITLE
Download missing files

### ISSUE THREAD

**Issue by n2fole00** [OwlCarousel2/OwlCarousel2#518]
Hi, When downloading the distributed version of OC from the site, you are supposed to get a structure like this...

owlcarousel/
├── assets/
│   ├── owl.carousel.css
│   ├── owl.carousel.min.css
│   ├── owl.theme.default.css
│   ├── owl.theme.default.min.css
│   ├── owl.theme.green.css
│   ├── owl.theme.green.min.css
│   └── owl.video.play.png
│
├── owl.carousel.js
├── owl.carousel.min.js
├── LICENSE-MIT
└── README.md

...instead the download has only...

owlcarousel/
├── assets/
│   ├── owl.carousel.css
│
├── owl.carousel.js
├── owl.carousel.min.js

**Comment by micahlisonbee** [comment]
Same issue here.

**Comment by jhongstore** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dcjae@naver.com 님께 보내신 메일 <Re: [OwlCarousel2] Download missing files (#518)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by joeyjoejoejr** [comment]
Can someone verify that this is still an issue?

**Comment by sidneygijzen** [comment]
Yes, still an issue. The downloaded zip file (v.2.0.0-beta.2.4) contains the structure described in the OP, so without the theme css files.

**Comment by rob-m-andrews** [comment]
I'm correcting this issue.

**Comment by funkdified** [comment]
Um.. Yeah.. Same issue. Just downloaded it.. also sent a tweet to https://twitter.com/OwlFonk ..

**Comment by gshulegaard** [comment]
Theme files are still missing which causes various issues.  For me, I cannot get "dots" pagination to work.

**Comment by anti-destin** [comment]
Same issue here. But v2.0.0-beta3 (see Quick Start: https://github.com/smashingboxes/OwlCarousel2#quick-start) has the missing files. I just grabbed them from that package.

**Comment by daviddeutsch** [comment]
This will be fixed with the switch to gulp #1330

**Comment by Job19delque** [comment]
"Can someone verify that this is still an issue?"
