### ISSUE TITLE
Synced Owls?

### ISSUE THREAD

**Issue by evanart** [OwlCarousel2/OwlCarousel2#580]
Hey! Big fan of Owl Carousel, currently using it on my company's home page.

We use a version of "Synced Owls" which is documented here:

http://owlgraphic.com/owlcarousel/demos/sync.html

I've been wanting to update to the Owl Carousel 2 beta to add some new animations and infinite looping, but doing so seems to have broken our synced carousels.

My guess is it has something to do with the goTo event. Does OC2 not support custom events yet? I can't find anything about events in the documentation. Am I missing something, or do I need to just wait until those are added in a newer version?

Any help would be greatly appreciated. Thanks!
E

**Comment by lmartins** [comment]
@pafnuty Thank you very much for taking the same to setup that sample. It helped me immensely today.
Cheers!

**Comment by jhongstore** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

dcjae@naver.com 님께 보내신 메일 <Re: [OwlCarousel2] Synced Owls? (#580)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by pafnuty** [comment]
@5tormTrooper Unfortunately I didn't get to implement looping carousel, not enough skills
@lmartins I am glad that my efforts were not in vain

**Comment by lmartins** [comment]
@5tormTrooper have you found a solution for the looping problem. Just bumped into this problem too.

**Comment by 5tormTrooper** [comment]
@lmartins No. Not enough skills either I'm afraid.

**Comment by laimisf** [comment]
I've reproduced the same effect as on http://owlgraphic.com/owlcarousel/demos/sync.html. 
<br>The code might not be the nicest, but it works. One difference is that instead of class '.synced' I used class '.current'. <br>
```javascript
//SYNCED OWL CAROUSEL (version 2.0.0-beta.2.4)
        var
                $sync1 = $("#sync1"), //big photo
                $sync2 = $("#sync2"), //thumbs
                duration = 300;

        //big photo
        $sync1
                .owlCarousel({
                    items: 1
                })
                .on('changed.owl.carousel', function (e) {
                    var syncedPosition = syncPosition(e.item.index);
                    alert(syncPosition(e.item.index));

                    if ( syncedPosition != "stayStill" ) {
                        $sync2.trigger('to.owl.carousel', [syncedPosition, duration, true]);
                    }
                });

        //thumbs
        $sync2
                .on('initialized.owl.carousel', function() { //must go before owl carousel initialization
                    addClassCurrent( 0 );
                })
                .owlCarousel({ //owl carousel init
                    items: 4
                })
                .on('click', '.owl-item', function () {
                    $sync1.trigger('to.owl.carousel', [$(this).index(), duration, true]);
                });


        //adds 'current' class to the thumbnail
        function addClassCurrent( index ) {
            $sync2
                    .find(".owl-item")
                    .removeClass("current")
                    .eq( index ).addClass("current");
        }

        //syncs positions. argument 'index' represents absolute position of the element
        function syncPosition( index ) {

            //PART 1 (adds 'current' class to thumbnail)
            addClassCurrent( index );


            //PART 2 (counts position)

            var itemsNo = $sync2.find(".owl-item").length; //total items
            var visibleItemsNo = $sync2.find(".owl-item.active").length; //visible items

            //if all items are visible
            if (itemsNo === visibleItemsNo) {
                return "stayStill";
            }

            //relative index (if 4 elements are visible and the 2nd of them has class 'current', returns index = 1)
            var visibleCurrentIndex = $sync2.find(".owl-item.active").index( $sync2.find(".owl-item.current") );

            //if it's first visible element and if there is hidden element before it
            if (visibleCurrentIndex == 0 && index != 0) {
                    return index - 1;
            }

            //if it's last visible element and if there is hidden element after it
            if (visibleCurrentIndex == (visibleItemsNo - 1) && index != (itemsNo - 1)) {
                    return index - visibleItemsNo + 2;
            }

            return "stayStill";
        }
        // ./SYNCED OWL CAROUSEL
```

**Comment by sibinx7** [comment]
It is not working... I have 2 slider with same images but these slider have different event.item.value...
For first slider it is 0-3 and for second slider 5-8

**Comment by daviddeutsch** [comment]
Check out this issue: [issues/1378 - Linked OwlCarousel instances](https://github.com/OwlCarousel2/OwlCarousel2/issues/1378)
