### ISSUE TITLE
Undefined e.property.name

### ISSUE THREAD

**Issue by beytarovski** [OwlCarousel2/OwlCarousel2#581]
Hi, 

When I put a form element in one of slide items like `input` field, after adding some characters and clicking tab button (blurred from input), owl.carousel.js returns:

```
TypeError: undefined is not an object (evaluating 'e.property.name') in owl.carousel.js:2346
```

So how can we solve this?

Thanks

**Comment by siyamak45** [comment]
I'm having the same problem. how can I solve this?
Thanks.

**Comment by florentbarriol** [comment]
Hello,
I have the same issue. Anyone know how to fix it ?
Thanks.

**Comment by adriandrozdz** [comment]
I believe there is a problem with animation function, but if anyone knows how to solve I would really appreciate.

**Comment by vinh014** [comment]
$( '#carousel_id *' ).on( 'click change', function(event) {
      event.stopPropagation();
});

Don't receive events which is bubbled from child elements such as input.

**Comment by courtneynguyen** [comment]
I am having the same issue.

**Comment by d10** [comment]
Ping? Any updates?

**Comment by aviddv1** [comment]
Same issue here using version 2.0.0 on line 2346:

if (e.property.name == 'position')

**Comment by shankarshananpk** [comment]
I also have same issue.

**Comment by sujeongy** [comment]
same issue 2
