### ISSUE TITLE
"d[c[(c.length - 1)]] is undefined" error

### ISSUE THREAD

**Issue by ugurbulut** [OwlCarousel2/OwlCarousel2#628]
If you set "items" parameter to "1" and "loop" is true, owlCarousel stops working and gives "d[c[(c.length - 1)]] is undefined" error.

<strong>File:</strong> owl.carousel.js
<strong>Line:</strong> 299.
<strong>Code:</strong>
<code>
for (i = 0, n = Math.abs(delta / 2) ; i < n; i++) {
                if (delta > 0) {
                    this.$stage.children().eq(items.length + clones.length - 1).remove();
                    clones.pop();
                    this.$stage.children().eq(0).remove();
                    clones.pop();
                } else {
                    clones.push(clones.length / 2);
                   <strong> this.$stage.append(items[clones[clones.length - 1]].clone().addClass('cloned'));</strong>
                    clones.push(items.length - 1 - (clones.length - 1) / 2);
                    this.$stage.prepend(items[clones[clones.length - 1]].clone().addClass('cloned'));
                }
            }
</code>

I think we need to check (items.length > 1), if loop is true.

**Comment by pareshsojitra** [comment]
This code will fix issue... 

Find "loop: true",
&
Replace it with following
loop: $(".blog-carousel > .type-post").length <= 1 ? false : true,

**Comment by pascalporedda** [comment]
This is an really old issue, I guess this one has been fixed a while ago? I will close this one, as it is over 3 years old.

**Comment by Balram-Aim** [comment]
Thanks guys! You saved my day!

**Comment by joni182** [comment]
great!! thank you very much
