### ISSUE TITLE
loop: true when one slide crash initialization

### ISSUE THREAD

**Issue by bezenson** [OwlCarousel2/OwlCarousel2#655]
Set loop: true and create in HTML one slide only. It will return error in console:

```
 Uncaught TypeError: Cannot read property 'clone' of undefined
```

on this line:

```
this.$stage.append(items[clones[clones.length - 1]].clone().addClass('cloned'));
```

**Comment by joeyjoejoejr** [comment]
Can you create a jsfiddle demonstrating this bug and using the most recent download from develop?
