### ISSUE TITLE
how to make synced carousels (clickable thumb-navigation) with OwlCarousel2?

### ISSUE THREAD

**Issue by Franz-Kafka** [OwlCarousel2/OwlCarousel2#691]
There are already some issues from the last year (#80, #278) dealing with the same topic but I think there is now real solution. So – what I want to achieve is just the same as in this demo in Owl version 1: http://owlgraphic.com/owlcarousel/demos/sync.html

I have done it so far:
http://jsfiddle.net/19v6ybug/

You can click in the navigation in a thumb to navigate to the correct slide (but when you go back to slide number one… something is wrong). 
But what I also want to have included is that when I click on the last navigation-thumb the navigation-carousel should move one forward to show the next nav-thumb (like in the demo of owl carousel 1). 

And for now the slide-carousel is not really synced with the navigation-carousel. 
I found this snippet but it does not work: 

```javascript
sync1 = $("#slider");
sync2 = $("#navigation");
sync1.on('changed.owl.carousel', function(event) {
sync2.trigger('to.owl.carousel', [event.item.index,300,true]);
```

Would be awsome if you can help to make a working snippet everyone can use.

**Comment by benwo** [comment]
+1

**Comment by robmar19** [comment]
I used this script seen below, which seems to work fine ... but now I'm having trouble adding a single 'active' class to a thumbnail to highlight which bigger image is being shown above. My search continues ...


jQuery(document).ready(function ($) {

	var $sync1 = $(".big-images"),
		$sync2 = $(".thumbs"),
		flag = false,
		duration = 300;

	$sync1
		.owlCarousel({
			items: 1,
			margin: 10,
			nav: true,
			dots: true,
      		animateOut: 'fadeOut'
		})
		.on('changed.owl.carousel', function (e) {
			if (!flag) {
				flag = true;
				$sync2.trigger('to.owl.carousel', [e.item.index, duration, true]);
				flag = false;
			}
		});

	$sync2
		.owlCarousel({
			margin: 20,
			items: 3,
			nav: true,
			center: false,
			dots: false,
      		navRewind: false
		})
		.on('click', '.owl-item', function () {
			$sync1.trigger('to.owl.carousel', [$(this).index(), duration, true]);

		})
		.on('changed.owl.carousel', function (e) {
			if (!flag) {
				flag = true;		
				$sync1.trigger('to.owl.carousel', [e.item.index, duration, true]);
				flag = false;
			}
      
      
		});
 
  
});

**Comment by szagol** [comment]
JS
<code>
sync2.on('click', '.owl-item', function(e) {
        e.preventDefault();
        $('.some-class').removeClass('active');
        console.log($(this));
        $(this).find('.some-class:first').addClass('active');
     })
</code>
css:

<code>
.acttive {
position: absolute;
width: 94.5%;
height: 83%;
top: 5px;
left: -1px;
background: rgba(104,171,29,0.4);
font-size: 16px;
/* padding: 0px; */
border-top: 11px solid #68ab1d;
border-bottom: 9px solid #68ab1d;
border-left: 5px solid #68ab1d;
border-right: 5px solid #68ab1d; 
}
</code>

Try something like above. There is empty div with "some-class" inside carousel item, and when you click on this element class "active" is added ;)
Works fine for me ;)

**Comment by robmar19** [comment]
This works, thanks. But when I click the navigation buttons ('next' and 'prev') the top carousel moves to the next picture but won't update the bottom thumbnails as they weren't actually clicked at any point ...

So you end up with an active class on a thumbnail that isn't the top photograph ... Not sure how to remedy that.

**Comment by szagol** [comment]
What can I say? Yeah, it won't.
Maybe:

<code>
sync1.on(changed.owl.carousel', function(e) { 
e.preventDefault(); 
sync2.find('.some-class').removeClass('active'); 
sync2.find('.some-class:first').addClass('active'); }) 
</code>

But it's just a "blind guess"

**Comment by robmar19** [comment]
Yeah, that doesn't seem to work. Many thanks though!

I had the idea of disabling the navigation and disabling the drag feature, so basically it works by clicking just the thumbnails. But unfortunately when you get to the end of the thumbnail area you can't then drag it back or use the navigation to go back to the first image, so not very useable.

I somehow need to disable the next/prev buttons so that they don't effect the first carousel and only effect the thumbnail area where it scrolls along (also the case for dragging with the mouse).

Oh well, I will keep looking for a remedy ...

**Comment by szagol** [comment]
About highlighting active class. 
I think you should try something with changed.owl.carousel event. 
When you'll figure it out, please post it here, because it would be nice to have this feature in my slider ;P

**Comment by robmar19** [comment]
Will do ...

I can see it functioning in Owl 1 on the Synced Owls page - http://owlgraphic.com/owlcarousel/demos/sync.html

So I assume it should work on Owl 2 as well ...

**Comment by szagol** [comment]
I figured out some trick, but i dont know how to do it.
You can add to slider options: "center: true". Then the active element will get "center" class. My problem is to add class active to div with "some-class" when it is inside "center" element.
Any solution?

**Comment by szagol** [comment]
Ok. As I said, in thumbnails options I used "center: true". Below are my two css classes for my project. Basicaly it gives the effect that we were talking about, so the change of big slide changes also active element in thumbnails.

<code>
.center {
    background: rgba(104,171,29,1);
    height: 160px;
    outline: 10px solid rgba(104,171,29,1);
    z-index: 100;

}

.center img {
    opacity: 0.4;
}

</code>

active element is centered but it is fine for me.

**Comment by robmar19** [comment]
Yeah, I tried this as well and it adds a center class. But unfortunately my gallery can't be centered (I need it left aligned) and there doesn't look like there's an option to override the center styling.

**Comment by szagol** [comment]
:( 
Maybe try to persuade your boss/client to make it centered ;)
Worked for me :p

**Comment by robmar19** [comment]
Ha yeah, I wish that was an option for me :-1: 

I tried to use the center: true, then override the translate3d using !important in the css, but it won't work as each time the thumbnails need to be moved along to view more the pictures the translate3d is set to '0' so the carousel won't function at all.

Oh well, back to square one ...

**Comment by szagol** [comment]
@robmar19 
Can you add responsive option for your slider, and chceck one thing for me?
I have infinite loop turned on, and my thumbnails contains 6 elements, but when I add responsive option, (for example 500{items: 3}) all my synchronization goes somwhere (i don't know where ;)) and my slider performs like dumb f...k. 
Can you chceck how your slider will perform?

**Comment by robmar19** [comment]
yeah, it does the same thing as soon as I add loop:true on mine ...

**Comment by szagol** [comment]
Hmm, Im thinking about another sync method. 
Firsto of all in my slider title for a big slide and correspondent thumbnail is received from the same database. So I figured out, that when I know these strings I can take index of elements containing these strings, and and by that way synchronize them.

But..

I don't know how to receive item index from element with specific content inside :)
Can you help?
Yes, Im new to jquery (also js) ;)

**Comment by dcafc** [comment]
I was looking for an answer to this too. I don't know if anyone solved this yet, so thought I would post my solution if it helps anyone.

Add the following to the $sync1 changed.owl.carousel event like this:

$sync2.find('.item').removeClass('synced');
$sync2.find(".owl-item").eq(current).find('div.item').addClass('synced');

where .item is a div inside an .owl-item div and the 'highlight' class is called .synced.

Hope that helps someone.

**Comment by robmar19** [comment]
Hey dcafc,

I'm still looking for a solution to this, so good to hear from someone saying they found an answer to the highlight issue I replied to on this thread. Would it be possible to show the whole code you're using for this?

Would really appreciate it as I'm a bit stuck ...

Many thanks

**Comment by Albhaku** [comment]
I found a CodePen and it solves almost everything. Except for some setts I cannot use, so I made some adjust and after a few minutes, was done, so:

`$(document).ready(function() {

    var sync1 = $("#slider");
    var sync2 = $("#navigation");
    var syncedSecondary = true;

    sync1.owlCarousel({
        items:1,
        loop:true,
        margin:10,
        autoplay:true,
        autoplayTimeout:6000,
        autoplayHoverPause:false,
        nav: false,
        dots: true
    }).on('changed.owl.carousel', syncPosition);

    sync2
    .on('initialized.owl.carousel', function () {
        sync2.find(".owl-item .projectitem").eq(0).addClass("active");
    })
    .owlCarousel({
        items:6,
        margin:10,
        autoplay:false,
        nav: false,
        dots: false
    }).on('changed.owl.carousel', syncPosition2);

    function syncPosition(el) {
        //if you set loop to false, you have to restore this next line
        //var current = el.item.index;

        //if you disable loop you have to comment this block
        var count = el.item.count-1;
        var current = Math.round(el.item.index - (el.item.count/2) - .5);
        if(current < 0) {
            current = count;
        }
        if(current > count) {
            current = 0;
        }
        //end block

        sync2
        .find(".projectitem")
        .removeClass("active")
        .eq(current)
        .addClass("active");
    }

    function syncPosition2(el) {
        if(syncedSecondary) {
            var number = el.item.index;
            sync1.data('owl.carousel').to(number, 100, true);
        }
    }

    sync2.on("click", ".projectitem", function(e){
        e.preventDefault();
        sync1.trigger('to.owl.carousel', [$(e.target).parents('.owl-item').index(), 300, true]);
    });
});`

"projectitem" is the name I gave to original "item" div in carousel demo. And "active" is my class. As you can see, I made mi "projectitem" active, and not my "owl-item" cause "loop:true" was giving me so many issues. Hope to be not too late.

**Comment by daviddeutsch** [comment]
Check out this issue: [issues/1378 - Linked OwlCarousel instances](https://github.com/OwlCarousel2/OwlCarousel2/issues/1378)

**Comment by silicondigit** [comment]
You can play with events 
check this link http://silicon.ma/owlcarousel2/demos/sync.html

**Comment by tonyhhisc** [comment]
> You can play with events 
> check this link http://silicon.ma/owlcarousel2/demos/sync.html

Thank you! This is what I was looking for... the ability to auto-move thumbnail pagination when the last slide (or next to last) is clicked so that you don't have to use the "next/prev" buttons. But there's only one problem with it for me, once it gets to the end shouldn't it go in reverse? IE, click the first image and it will paginate backwards for you? 

Anyone have a solution for this? Sorry I am a total JS newbie.

Much appreciated, 

Tony

**Comment by siddharthundare** [comment]
> I found a CodePen and it solves almost everything. Except for some setts I cannot use, so I made some adjust and after a few minutes, was done, so:
> 
> `$(document).ready(function() {
> 
> ```
> var sync1 = $("#slider");
> var sync2 = $("#navigation");
> var syncedSecondary = true;
> 
> sync1.owlCarousel({
>     items:1,
>     loop:true,
>     margin:10,
>     autoplay:true,
>     autoplayTimeout:6000,
>     autoplayHoverPause:false,
>     nav: false,
>     dots: true
> }).on('changed.owl.carousel', syncPosition);
> 
> sync2
> .on('initialized.owl.carousel', function () {
>     sync2.find(".owl-item .projectitem").eq(0).addClass("active");
> })
> .owlCarousel({
>     items:6,
>     margin:10,
>     autoplay:false,
>     nav: false,
>     dots: false
> }).on('changed.owl.carousel', syncPosition2);
> 
> function syncPosition(el) {
>     //if you set loop to false, you have to restore this next line
>     //var current = el.item.index;
> 
>     //if you disable loop you have to comment this block
>     var count = el.item.count-1;
>     var current = Math.round(el.item.index - (el.item.count/2) - .5);
>     if(current < 0) {
>         current = count;
>     }
>     if(current > count) {
>         current = 0;
>     }
>     //end block
> 
>     sync2
>     .find(".projectitem")
>     .removeClass("active")
>     .eq(current)
>     .addClass("active");
> }
> 
> function syncPosition2(el) {
>     if(syncedSecondary) {
>         var number = el.item.index;
>         sync1.data('owl.carousel').to(number, 100, true);
>     }
> }
> 
> sync2.on("click", ".projectitem", function(e){
>     e.preventDefault();
>     sync1.trigger('to.owl.carousel', [$(e.target).parents('.owl-item').index(), 300, true]);
> });
> ```
> 
> });`
> 
> "projectitem" is the name I gave to original "item" div in carousel demo. And "active" is my class. As you can see, I made mi "projectitem" active, and not my "owl-item" cause "loop:true" was giving me so many issues. Hope to be not too late.
> 
> Original CodePen and all thanks to "Washaweb": http://codepen.io/washaweb/pen/KVRxRW

What If I have 5 images or item only it will not working on that condition.
