### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by aguilera51284** [OwlCarousel2/OwlCarousel2#709]
There are plans for this project to move Vanilla JS?.....

**Comment by robcolburn** [comment]
This plugin relies pretty heavily on jQuery for:
* Array/Object/Function stuff (could be replaced by underscore/lodash)
* DOM events (could be replaced by manual event registration polyfill)
* DOM creation/manipulation.  This gets un-fun without a DOM framework.

**Comment by joeyjoejoejr** [comment]
Thanks @robcolburn 

Yeah, it's unlikely that this change will be made anytime soon, if at all.  I do see us trying to ensure compatibility with jquerylite(angular) and zepto being a possibility.

**Comment by robcolburn** [comment]
I'd love it to be more Bring-Your-Own-jQuery (jQuery-like), and me more straight-up includable with Browserify/WebPack.

Now:
```js
var $ = window.jQuery = require("jquery")
require("./lib/owl-carousel")

var myOwl = $
  .owlCarousel(…)
  .data("owlCarousel")
```
Ideally:
```js
var $ = require("jquery")
var owl = require("owl-carousel")($)

var myOwl = owl(…)
```

Then I can swap for a jQuery-like or maybe a slim jQuery.

**Comment by jonathantneal** [comment]
It might take some time, but I’ll dabble with this one:

https://github.com/jonathantneal/OwlCarousel2/commits/feature/vanilla-js

**Comment by robcolburn** [comment]
@jonathantneal,
Yeah, ES5 will JS take care of JS-lang deficiencies.  We'd then only support IE>=9, or tell users to use an [es5-shim](https://github.com/es-shims/es5-shim) if they want to support IE<9.

Updated my comment to include more detailed steps.

**Comment by jonathantneal** [comment]
Closed due to inactivity, @daviddeutsch ?

**Comment by daviddeutsch** [comment]
Nah, just out of scope for now. I'm not a big fan of these kind of semi-rewrites. I'd rather tackle it in the bigger refactoring we have planned down the road (#1538)
