### ISSUE TITLE
There should be a way to get "active items"

### ISSUE THREAD

**Issue by ivandotv** [OwlCarousel2/OwlCarousel2#730]
In case of responsive functionality there is no way for me to know how many `items` are active.
I have to listen for `resize` event and then query the DOM for `.owl-item.active` 
This is very bad for performance.

**Comment by PabloDeGrote** [comment]
You can get the internal functions with `$('#carousel').data("owlCarousel")`

Then I have overwritten the refresh function with a reference saved to the original refresh function. This so I could use the built-in responsiveRefreshRate:

````
this.instance = $('#carousel').data("owlCarousel");
this.instance.__refresh = this.instance.refresh;
this.instance.refresh = function() {
    self.utils.getMediaQueries.call(self);

    this.__refresh();
};
````

To get all items use the object DOM like so:
````
console.log(this.instance.dom.$oItems); 
//$oItems = original items
//$cItems = cloned items
//$items = all items (cloned & original)
````

**Comment by ikixxx** [comment]
That's my point , I also have code that waits for refresh to query the
items. This should be built int.
