### ISSUE TITLE
Autoplay is not working properly

### ISSUE THREAD

**Issue by carlotrimarchi** [OwlCarousel2/OwlCarousel2#737]
I'm trying to use the play and stop events on a carousel but I can't get them to work as they should.

I configured the carousel like this:
```javascript
function init() {
    var owl = $("#s01e13-slideshow");
    owl.owlCarousel({
        autoplay: true,
        autoplayTimeout: 500,
        autoplayHoverPause:false,
        center: true,
        items: 1,
        responsive:{
            0:{
                items:1,
            },
        600:{
            items:1,
        },
        1000:{
            items:1,
        }
        },
        animateIn: 'fade',
        animateOut: 'fade'
    });

    $('.prevBtn').click(function() {
        owl.trigger('prev.owl.carousel', [0]);
    });
    $('.nextBtn').click(function() {
        owl.trigger('next.owl.carousel', [0]);
    });

    $('.playBtn').on('click', function() {
        owl.trigger('play.owl.autoplay', [1000]);
    });
    $('.pauseBtn').on('click', function() {
        owl.trigger('stop.owl.autoplay');
    });
}
```

And when it's loaded it starts autoplaying and I can stop it, so the stop event works. But then when I click on the "play" button it doesn't autoplay.

Also, in this demo page: http://www.owlcarousel.owlgraphic.com/demos/autoplay.html
In the example you use the events "autoplay.play.owl" and "autoplay.stop.owl", while according to the documentation they should be "play.owl.autoplay" and "stop.owl.autoplay".

Thanks for your help

**Comment by ayoub-bousetta** [comment]
You can just use :

$('.play').on('click',function(){
     owl.trigger('owl.play',5000);
})

$('.stop').on('click',function(){
   owl.trigger('owl.stop');
})
