### ISSUE TITLE
infiniteloop with slideBy: 'page' rewinds.... 

### ISSUE THREAD

**Issue by n3rdatwork** [OwlCarousel2/OwlCarousel2#746]
The infiniteloop works fine with sliding one item - but when I use it with slideBy: 'page' it slides back to the left. Not nice. :-/

My options:
        loop:true,
        autoplay: true,
        margin:10,
        nav:true,
        slideBy:'page',
        responsive:{
            0:{
                items:3
            },
            992:{
                items:4
            },
            1200:{
                items:5
            }
        }

**Comment by PrestonStahley** [comment]
I ran into this as well. loop:true and slideBy:'page' don't seem to work together.

http://codepen.io/anon/pen/RPdwdr
