### ISSUE TITLE
When "autoWidth" is true,  is group pagination (owl-dots) possible?

### ISSUE THREAD

**Issue by vincentjareno** [OwlCarousel2/OwlCarousel2#751]
Hi,

Is there a way for the carousel to have a group pagination (owl-dots) instead of individual dots when "autoWidth" option is true? I've attached a screenshot of the output.
![carousel-update](https://cloud.githubusercontent.com/assets/5987645/6710233/1c0e1278-cdba-11e4-8715-1353a0795bb9.png)

Thanks, and I would like to say that this is a superb plugin.

Thanks again.

**Comment by ivande** [comment]
Hi, I would like to know this too.

**Comment by shrpne** [comment]
`dotsEach: false` options don't works with `autoWdith`, `center` and `dotsData`
