### ISSUE TITLE
Ghost images on stage after resize

### ISSUE THREAD

**Issue by sanderkruger** [OwlCarousel2/OwlCarousel2#762]
I have a carousel with items that consist of a <figure> with 2 children, an <img> and a <figcaption>. The carousel is configured to loop and to show different numbers of items going from 6 down to 2 as the viewport size gets smaller.

In Chrome, if the number of items is reduced, I get funny artefacts: copies of the images showing behind the items. The images have no counterpart in DOM, so it seems to be a repaint issue. If I change one of the CSS styles of the stage in Developer Tools, a repaint happens and the image disappears.

This doesn't happen in IE or Firefox.

Below you see my carousel after resizing. The image of 'Kavi Koyote' is copied on the stage between the 2 items on the right.

![capture](https://cloud.githubusercontent.com/assets/1422536/6811467/6da82954-d268-11e4-83fe-e3a07847ed6a.JPG)

While this might be classified as a Webkit bug, I think it's serious enough to consider a workaround in Owl Carousel. Perhaps something after a resize that will force a repaint of the stage.

**Comment by leandroruel** [comment]
seems the clones effect appearing behind the original items.

**Comment by Kaz-** [comment]
I'm having the same issue, has someone found a workaround ?

**Comment by sanderkruger** [comment]
I have a rather unelegant workaround for this:

    $('#my-carousel').on('resized.owl.carousel', function() {
        var $stage = $(this).find('.owl-stage');
        var c = $stage.css('background-color');
        c = (c == '#fffffe' || c == 'rgb(255, 255, 254)') ? '#ffffff' : '#fffffe';
        $stage.css('background-color', c);
    });

Basically, by swapping the background color between 2 indiscernable shades of white, the browser is forced to repaint. I tried other things, like inspecting the inner or outer height, changing the display CSS property to none and back, but they all got optimized away.

**Comment by jonw100** [comment]
I'm also having an identical issue, though it's not just images - the item borders and sometimes text too, often just parts of an item.  SanderKruger's workaround above does not fully fix my problem unfortunately.  Been trying to get somewhere with this for hours but not feeling optimistic now.  This is practically the only place I have found mention of this problem so I'm guessing it does not affect a lot of people.  Wish I knew why

**Comment by dhenry-adpear** [comment]
I have run into a similar problem. The only way I got around it was removing [-webkit-backface-visibility: hidden;] under .owl-carousel .owl-item.

**Comment by jonw100** [comment]
Ooh you superstar!  Thanks so much for posting that solution - looking good so far

**Comment by Galch24** [comment]
I have the same problem with artifacts on Chrome. Solution from dhenry-adpear is worked for me. Thank you bro.

**Comment by neysimoes** [comment]
```
.owl-carousel .owl-item {
  backface-visibility: hidden;
  transform: translate3d(0,0,0);
}
```
(add prefix if you want, I'm using autoprefixer)

**Comment by floydh** [comment]
Use this to redraw the images on the carousel's onResized event https://coderwall.com/p/ahazha/force-redraw-on-an-element-jquery

`onResized: function(){
          $(this).find('img').redraw();
 }`
