### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dom' of undefined

### ISSUE THREAD

**Issue by AndrewEastwood** [OwlCarousel2/OwlCarousel2#768]
This is what I get when I'm trying to invoke the destroy function. And it seems that the lib is not working so good with dynamic elements. When my Backbone collection adds more items then I get vertical list with those elements and the's all

**Comment by AndrewEastwood** [comment]
it's inside this block:
```
	Hash.prototype.destroy = function() {
		var handler, property;

		$(window).off('hashchange.owl.navigation');

		for (handler in this.handlers) {
			this.owl.dom.$el.off(handler, this.handlers[handler]);
		}
		for (property in Object.getOwnPropertyNames(this)) {
			typeof this[property] != 'function' && (this[property] = null);
		}
```

here ```this.owl``` is undefined somehow

**Comment by mhintz** [comment]
I'm seeing this too. Initializing the carousel and then destorying it immediately after fails right out of the box

**Comment by AndrewEastwood** [comment]
It seems that this project is no longer supported, I guess

**Comment by gregbenner** [comment]
Annoying to fix but.. checkout the develop branch, 'npm install && bower install' then 'grunt dist' and copy over and use the new .js and .css
had the same issue when using this with React but the newer version seems to work.

**Comment by flyinbryan125** [comment]
function Hash.prototype.destroy
change 
this.owl.dom.$el.off(handler, this.handlers[handler]);
to
this.core.dom.$el.off(handler, this.handlers[handler]);

Hope this helps someone.
