### ISSUE TITLE
Loop with one item breaks everything

### ISSUE THREAD

**Issue by TcPhilBushnell** [OwlCarousel2/OwlCarousel2#771]
Setting `loop: true` as an option with only one `<div class="owl-item">...</div>` breaks the plugin and it doesn't show anything. I've added a check in my code but really it shouldn't break.

Regards,

**Phil Bushnell**

**Comment by jpigor** [comment]
Same thing here, Phil.

What did you do to make this work? We need the loop-functionality, but sometimes only 1 image is needed and like you mentioned... It shouldn't break... 

Regards,
Igor J.

**Comment by TcPhilBushnell** [comment]
Here is a condensed and simplified version of my code:

```javascript
var carousel = $('.owl-carousel');

var numberOfSlides = $('.owl-item', carousel).length;

var options = {
    ...
    loop: false,
    ....
};

if (numberOfSlides > 1) {
    options.loop = true;
}

carousel.owlCarousel(options);
```

Regards,

**Phil Bushnell**

**Comment by jpigor** [comment]
Awesome! Appreciate it! Thanks Phil! :)
