### ISSUE TITLE
Images flickering when infinity loop reaches edge in Chrome

### ISSUE THREAD

**Issue by TcPhilBushnell** [OwlCarousel2/OwlCarousel2#772]
I've noticed that images flicker/flash and appear to 'load' or 'refresh' in Chrome when changing between slides near the edges of the infinity loop. This appears to be fine in IE11, Firefox and iOS (as a random selection of other checks I've done).

I've solved this issue by adding `z-index: 1` to the `.owl-item` class.

Regards,

**Phil Bushnell**

**Comment by OPM87** [comment]
Thanks for this info.
I noticed that the CSS3 transform-style Property of the images causes this behaviour.
Seems Chrome has problems with `transform-style: preserve-3d;`
If you force `transform-style: flat;` to the img the problem is also gone. But I don't know what sideeffects this can cause. So I think `z-index:1` is better.

**Comment by ses** [comment]
perfect! thanks

**Comment by prod1992** [comment]
thanks!

**Comment by dudewad** [comment]
Thank you!!

**Comment by dudewad** [comment]
Given that this is a "bug" in chrome, shouldn't this "fix" get rolled into the next update?

**Comment by gideonheilbron** [comment]
I forced hardware acceleration using transform: translate3d(0, 0, 0); on the owl-item and that also fixed it.

**Comment by gideonheilbron** [comment]
My solution also fixed this issue: https://github.com/smashingboxes/OwlCarousel2/issues/806 and probably all the other flickering issues too!

**Comment by dudewad** [comment]
I can confirm this fix, it works. And, I agree- this is the better solution, and I've swapped it out for the z-index one. There's no way to confirm that somebody doesn't want to z-index differently, which could cause usability issues, and one would assume modifying the translade3d value will likely be both less common and still solve the same problem.

**Comment by gideonheilbron** [comment]
I agree! Z-index can be risky to modify in a plugin like this. translate3d is a known fix for improving animations in Chrome, so I guess this won't be a problem to most users.

**Comment by michaelwoodruff** [comment]
The ```z-index: 1``` on ```.owl-item``` class fixed it for me. Thanks.

**Comment by nidhi333-9** [comment]
Where is the owl-item class??
