### ISSUE TITLE
Carousel resizing ignores browser scrollbar

### ISSUE THREAD

**Issue by shorstki** [OwlCarousel2/OwlCarousel2#792]
Hi,

I've found an issue with OwlCarousel2 - with full page width carousel, when content on page is added or expanded and the scrollbar appears. Before this, items in carousel fits perfectly into page. **With scrollbar, content of the last visible item on the right side is partly below scrollbar**. Even resizing the window don't change this behaviour.

Any other content is automatically scaled to new page width (old width - scroll width), but **OwlCarousel just ignores appearance of the browser scrollbar**. It's weird because the *responsiveBaseElement* (like `<body></body>`) is changing its width according to scrollbar visibility.

Edit: further investigation shows that problem is caused by invisible owl-stage content while refreshing - it has no height, so witdh of items is calculated like there were no scrollbar. After refresh stage is displayed and then scrollbar appears... Afther that width of items no longer fits new window/body width.

**Comment by yongtw123** [comment]
After tracing the callbacks, I found the culprit to be one line in the core JS file `this.$element.addClass(this.options.refreshClass);` in `Owl.prototype.refresh`. The `refreshClass`, or `.owl-refresh`, points to a CSS style that makes the entire carousel DOM `display: none`, thus any subsequent calls to `width()` will not include the vertical scrollbar. I believe this is identical to what you have discovered @shorstki . 
Although removing the offending line does solve the problem, I do not know if it applies to all cases.

**Comment by Naphier** [comment]
:+1: Thank you! I'm not sure what that line is doing but commenting it out seems to have fixed all of my  ails! Hopefully it doesn't break anything else down the line.
