### ISSUE TITLE
How to sync two owlCarousel  using version 2?

### ISSUE THREAD

**Issue by freeduc** [OwlCarousel2/OwlCarousel2#80]
$(document).ready(function() {

```
        sync1 = $("#sync1");
        sync2 = $("#sync2");

        sync1.on('changed.owl.carousel', function(event) {
            sync2.trigger('next.owl.carousel');
        });

        sync1.owlCarousel({
            center : true,
            loop : true,
            items : 1,
            margin:0,
            nav : true
        });

        sync2.owlCarousel({
            center : true,
            loop : true,
            items : 3,
            margin:10,
            nav : true
        });

    });
```

Is it possible to know drag forward or backward?

I made sync two owlCarousel using version 1 with website demo.

**Comment by davidspiess** [comment]
I think a demo application on the website would be very helpful for a lot of users.

**Comment by kaikubasta** [comment]
I found a [demo](http://poligon.pro/owl/) on Google, but would really love to see one on the official website, too.

**Comment by smknstd** [comment]
@kaikubasta thanks 4 sharing !

**Comment by sibinx7** [comment]
Thanks @kaikubasta 

But this is not working on sliders with loop option true. It work well without loop.

**Comment by francescocortese** [comment]
@freeduc your solution work so good!

**Comment by francescocortese** [comment]
This is my solution for the oprions loop:true and center: true

	var sync2 = $('#sync1'),
		sync1 = $('#sync2');
		
		// Sync nav
		sync1.on('click', '.owl-next', function () {
			sync2.trigger('next.owl.carousel')
		});
		sync1.on('click', '.owl-prev', function () {
			sync2.trigger('prev.owl.carousel')
		});

        // Start Carousel
        sync1.owlCarousel({
            center : true,
            loop : true,
            items : 1,
            margin:0,
            nav : true
        });

        sync2.owlCarousel({
            center : true,
            loop : true,
            items : 3,
            margin:10,
            nav : false
        });

**Comment by alaahd** [comment]
I have managed to sync two carousels with the following options: 
- loop
- center 
- RTL 

```javascript

var sync1 = $('#sync1'),
    sync2 = $('#sync2'),
    duration = 300,
    thumbs = 4;

// Sync nav
sync1.on('click', '.owl-next', function () {
    sync2.trigger('next.owl.carousel')
});
sync1.on('click', '.owl-prev', function () {
    sync2.trigger('prev.owl.carousel')
});

// Start Carousel
sync1.owlCarousel({
    rtl: true,
    center : true,
    loop: true,
    items : 1,
    margin:0,
    nav : true
})

sync2.owlCarousel({
    rtl: true,
    center: true,
    loop: true,
    items : thumbs,
    margin:10,
    nav : false
})
.on('click', '.owl-item', function() {
    var i = $(this).index()-(thumbs+1);
    sync2.trigger('to.owl.carousel', [i, duration, true]);
    sync1.trigger('to.owl.carousel', [i, duration, true]);
});
 
```

**Comment by daviddeutsch** [comment]
Check out this issue: [issues/1378 - Linked OwlCarousel instances](https://github.com/OwlCarousel2/OwlCarousel2/issues/1378)

**Comment by tigertooth01** [comment]
I modified it to get dragging event in both carousels. But `center : false`, and `rtl : fals`e was my required case.

`// Sync nav
sync1.on('click', '.owl-next', function () {
    sync2.trigger('next.owl.carousel')
});
sync1.on('click', '.owl-prev', function () {
    sync2.trigger('prev.owl.carousel')
});

// Start Carousel
sync1.owlCarousel({
    // center : true,
    loop: true,
    items : 1,
    margin:0,
    nav : true,
    navText : ["&lsaquo;","&rsaquo;"]
})
.on('dragged.owl.carousel', function (e) {
        if (e.relatedTarget.state.direction == 'left') {
            sync2.trigger('next.owl.carousel')
        } else {
            sync2.trigger('prev.owl.carousel')
        }
});


sync2.owlCarousel({
    // center: true,
    loop: true,
    items : thumbs,
    margin:10,
    nav : true,
    navText : ["&lsaquo;","&rsaquo;"]
})
.on('click', '.owl-item', function() {
    var i = $(this).index()-(thumbs);
    sync2.trigger('to.owl.carousel', [i, duration, true]);
    sync1.trigger('to.owl.carousel', [i, duration, true]);
})
.on('changed.owl.carousel', function (e) {
	console.log(e.item.index-thumbs);
	if (!flag) {
		flag = true;		
		sync1.trigger('to.owl.carousel', [e.item.index-thumbs, duration, true]);
		flag = false;
	}
});`
