### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by pavelthq** [OwlCarousel2/OwlCarousel2#800]
Does project will have release? What status of current development?

Thanks.

**Comment by macx** [comment]
@AngeIII The last commit is from February. Seems to be dead, if see the counts on Pull-Requests and issues.

**Comment by josephws** [comment]
It needs a lot of updates, it doesn't seems to be working on mobile devices ??

**Comment by AngeIII** [comment]
We uses them on Visual Composer for WordPress plugin and seems work fine also in mobile.

**Comment by josephws** [comment]
@AngeIII Can you please check my issue https://github.com/smashingboxes/OwlCarousel2/issues/801
I don't know why it's not worki on any phone/tablet ?

**Comment by andrewcourtney** [comment]
I was wondering also. I'd like to use it for a commercial project but don't want to run the risk of using the beta version since there are so many bugs. Infinity scroll was one of my biggest needs too :( I guess I'll have to find another solution....

**Comment by macx** [comment]
In Februrary they announced “big updates” (see #703). Not a good sign.

**Comment by josephws** [comment]
So far the old version is working great for me.

**Comment by Marc-pi** [comment]
the question is when a new version will be made/packaged, because several critical bugs were discovered (see the tracker issue) and some fixes provided. @joeyjoejoejr @OwlFonk , any clue?

**Comment by miniMAC** [comment]
OWL dead

**Comment by Flowgram** [comment]
It's apparently not dead: https://github.com/smashingboxes/OwlCarousel2/issues/756 . Looks hopeful.

**Comment by leandroruel** [comment]
please close the issue, this project still in development.

**Comment by shikkaba** [comment]
NOW is it dead?

**Comment by zandiarash** [comment]
> 
> 
> NOW is it dead?

seems yes

**Comment by macx** [comment]
It's official: 4eedcca

**Comment by shikkaba** [comment]
This makes me sad. RIP OwlCarousel.
