### ISSUE TITLE
Doesn't appear on mobile devices (Phones/Tablets)

### ISSUE THREAD

**Issue by josephws** [OwlCarousel2/OwlCarousel2#801]
I created a test page with this version () it works perfectly on PC but doesn't appear at all on any mobile device.

Test page: http://feat.youmobile.org/test/md-cardstest.html

Any help ?

**Comment by Hamlj** [comment]
You have some undefined variable and get 404 for some reason

GET http://feat.youmobile.org/test/undefined 404 (Not Found)

**Comment by josephws** [comment]
this error is only mobile devices, but in PC it doesn't show any errors !

WTH is undefined ??

**Comment by AngeIII** [comment]
You probably using incorrect ```<!DOCTYPE html>``` and also your owl.carousel.js is empty

**Comment by josephws** [comment]
I updated the page http://feat.youmobile.org/tests/mdtest.html

I can't find what is calling the "http://feat.youmobile.org/test/undefined", do you have a working code that you can send to me ?

I really need it and I don't know what's wrong !

thank you for your help

**Comment by AngeIII** [comment]
add ```<!DOCTYPE html>``` on top of output and recheck

**Comment by josephws** [comment]
still the same thing, Why this error only on mobile phones ?
does it work on your PC ?

**Comment by AngeIII** [comment]
Remove everything else - cloudflare and google and etc. - you should remove everything that is not relative to owlcarousel if it will work so you need to dig deeper.

**Comment by josephws** [comment]
I just did, same issue ?
What jquery version you are using ? it seems like the owl.carousel.js is triggering this issue

**Comment by josephws** [comment]
I just found this, still no answer http://stackoverflow.com/questions/27761724/owl-carousel-disappears-when-you-view-in-mobile?

**Comment by hauareyou** [comment]
This could be the same problem I am having. At window size 767px or less the owl-stage width increase to huge px. For me its like 23000px. Not sure why, but I am looking into it. Let me know if you have the same problem.

**Comment by imarkdesigns** [comment]
I can't able to determine what's the problem since it is 404 already...

**Comment by KennethAshley** [comment]
@josephws is this still an issue?

**Comment by lucasvel** [comment]
Hi, I don't know if it's related since the original link is broken.
I had a similar issue while using owl carousel with Bootstrap v4. I only had this issue with the new "small" width (>= 544px and < 768 px). Within that widths the carousel completely disappeared.
In my case I fixed it by setting a CSS media query like this:
```css
@media (max-width: 767px) and (min-width: 544px) {
  .owl-stage-outer {
    width: 547px;
  }
  .owl-prev, .owl-next {
    top: 65%;
  }
}
```

YMMV and HTH

**Comment by emacaste** [comment]
> Hi, I don't know if it's related since the original link is broken.
> I had a similar issue while using owl carousel with Bootstrap v4. I only had this issue with the new "small" width (>= 544px and < 768 px). Within that widths the carousel completely disappeared.
> In my case I fixed it by setting a CSS media query like this:
> 
> ```css
> @media (max-width: 767px) and (min-width: 544px) {
>   .owl-stage-outer {
>     width: 547px;
>   }
>   .owl-prev, .owl-next {
>     top: 65%;
>   }
> }
> ```
> 
> YMMV and HTH

Same problem here, fixed with that

`@media (max-width: 991px) and (min-width: 0px) {
            .owl-stage-outer {
                width: 100%;
            }
        }`

Very very weird....
