### ISSUE TITLE
Auto height not working

### ISSUE THREAD

**Issue by vdecree** [OwlCarousel2/OwlCarousel2#835]
Hi there,

I've never needed it before, but I'm trying to get that autoHeight working and it's not playing ball. I'm using version 2.0.0. 

The stage is just keeping a fixed height, despite having 5 slides with different heights of content. 

```
<div style="height: 130px;" class="owl-stage-outer owl-height">
```

My script is simply:

```
var testimonial_slider = $('.testimonial-slider');

    testimonial_slider.owlCarousel({
      items: 1,
      loop: true,
      autoHeight: true
    });
```

**Comment by betagoo** [comment]
I have similar problem with autoHeight=true.
When slides are images, after page load slider height is set to 20px. I have to refresh page, then works fine.
But if browser cache is empty, autoHeight works wrong.
When I set autoHeight: false, everything works fine, but slider height is constant.

**Comment by mikehdt** [comment]
From http://www.owlcarousel.owlgraphic.com/demos/autoheight.html
"The plan is to calculate all visible items and change height according to heighest item."

From what I understand, this functionality is not yet currently implemented...

**Comment by bgonz** [comment]
So is that the case - "autoHeight" is not quite ready yet?

**Comment by austinhinderer** [comment]
According to the changelog, autoHeight has been fixed. Is this issue resolved?
http://owlcarousel.owlgraphic.com/docs/support-changelog.html

**Comment by mikehdt** [comment]
That's the docs for beta 2.4, which are outdated. The owner of the project has changed from OwlFonk to Smashing Boxes. As far as I'm aware does not have this functionality for multiple slides, only for single slides. There is a pre-beta-3 floating around however I've not had a chance to test it to see if this has works yet or not.

**Comment by rezelute** [comment]
The autoHeight is buggy even when using single slides.
The autoHeight function seems to work with changed events but not with resized events. To overcome this i am having to change the stage height every time the browser is resized but then also on the changed events (When you resize the window and then navigate slides, bugs start to show).

 owl.on('resized.owl.carousel', function (event) {
          setOwlHeight();
     })

owl.on('translated.owl.carousel', function (event) {
 //....
 setOwlHeight();
})

**Comment by kashburn** [comment]
To fix the AutoHeight issue of not resizing on mobile orientation change I changed the  /** All event handlers **/ section of the AutoHeight plugin to read:
/**
		 * All event handlers.
		 * @protected
		 * @type {Object}
		 */
		this._handlers = {
			'initialized.owl.carousel': $.proxy(function() {
				if (this._core.settings.autoHeight) {
					this.update();
				}
			}, this),
			'resized.owl.carousel': $.proxy(function() {
				if (this._core.settings.autoHeight) {
					this.update();
				}
			}, this),
			'changed.owl.carousel': $.proxy(function(e) {
				if (this._core.settings.autoHeight && e.property.name == 'position'){
					this.update();
				}
			}, this),
			'loaded.owl.lazy': $.proxy(function(e) {
				if (this._core.settings.autoHeight && e.element.closest('.' + this._core.settings.itemClass)
					=== this._core.$stage.children().eq(this._core.current())) {
					this.update();
				}
			}, this)
		};


Which really only added the resized function, but it fixed the issue for me for AutoHeight on a single slide on mobile.

**Comment by pascalwacker** [comment]
I also still have the issue.

**Comment by Vadiazu** [comment]
using owl carousel as widget for magento 2. 0 there for version 2 beta 3.0 css was also changed:
 /* Vertically center items smaller than the stage */
    .owl-carousel .owl-stage {
        display: table;
        .lib-inline-block-space-container();
        .owl-item {
            .lib-inline-block-space-item();
            display: table-cell;
            vertical-align: top;
            float: none;
	
            /* Fixes blank/flashing slides when loop is set to true */
            .lib-css(backface-visibility, hidden);
            .lib-transform(translateZ(0) scale(1.0, 1.0));
        }
    }
so as now they used display table all carousel elements have the same height, i simply commented this block of code, after that all works fine.

**Comment by pascalporedda** [comment]
I've addressed this issue in the latest commit, this will be fixed in the next release.
