### ISSUE TITLE
Lazyload: true and loop: true cause uncaught TypeError

### ISSUE THREAD

**Issue by timkirtley** [OwlCarousel2/OwlCarousel2#85]
Hey.

Using the LazyLoad and Loop options together I get the following js error:

Uncaught TypeError: Cannot set property 'loaded' of undefined

triggered at this line of code:
$item.data('owl-item').loaded = true;

Both features still work correctly having said that...

**Comment by spacedawwwg** [comment]
This is still an issue using this set up:

```js
$carousel.owlCarousel({
      margin: 20,
      loop: true,
      autoWidth: true,
      lazyLoad: true,
      center: true,
      autoplay: true,
      autoplayTimeout: 5000,
      autoplayHoverPause: true,
      nav: true,
      dots: false,
      mouseDrag: false
});
```

![screen shot 2015-05-09 at 20 14 29](https://cloud.githubusercontent.com/assets/1691867/7551622/1f0328d2-f688-11e4-9a51-e75b55df7b49.png)
