### ISSUE TITLE
currentItem

### ISSUE THREAD

**Issue by t3premium** [OwlCarousel2/OwlCarousel2#856]
Can you please release the event.item.currentItem like in owl carousel 1 http://owlgraphic.com/owlcarousel/demos/owlStatus.html

It is very useful for the following example http://codepen.io/OwlFonk/pen/dpjhB
Also it would be nice to switch active class on/off

**Comment by iandonovan** [comment]
We'll consider adding this, but feel free to fire up your own pull request!
