### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by greg5green** [OwlCarousel2/OwlCarousel2#897]
The current website is controlled by the old developers of this project and cannot be updated. It needs to get some sort of CNAME record set up to redirect to the GitHub Pages site?

The GitHub Pages sites has a lot of bad links since the site was originally developed to be hosted at the root level. These should be changed to be relative.

**Comment by djam90** [comment]
Do you have access to the domain DNS settings?

**Comment by daviddeutsch** [comment]
Noooooope. :confused:
