### ISSUE TITLE
Windows Phone autoplay

### ISSUE THREAD

**Issue by Emnalyeriar** [OwlCarousel2/OwlCarousel2#916]
The autoplay feature stops working on windows phone after one slide. While debugging I found that this._core.is('busy') returns true and the interval function just omits the function to move slides. Anyone knows why this happens?
Tested on Lumia 520 WP 8.1 Internet Explorer browser.

**Comment by JanaKemmer** [comment]
I also tested it on my site on a windows phone, and my slider worked perfectly there (also autoplay).
I tested it on Lumia 530 on WP 8.1 Internet Explorer

Do you maybe have some conflicting plugin that causes this error?

**Comment by greg5green** [comment]
Finally got my hands on a Windows Phone for a couple hours and noticed this issue (it is exhibited in our [demos](http://smashingboxes.github.io/OwlCarousel2/demos/autoplay.html)).

Lumia 435
Windows 8.10.14234.375

I don't really know how to debug any issues on Windows Phone -- any chance anyone has a moment to look at this?

**Comment by ssarnecki** [comment]
I've got this issue not only on windows phone (lumia 720), but also on samsung galaxy s3

**Comment by daviddeutsch** [comment]
See #1942
