### ISSUE TITLE
Several Lazy Load Carousel on same page don't work with ios / safari ?

### ISSUE THREAD

**Issue by Moldjuice** [OwlCarousel2/OwlCarousel2#938]
Hi,
About this bug 
https://www.drupal.org/node/2328369

Is the 2.0.0 version fixed this bug ?
is it functional for the Safari browser with ios (on iphone)?

Thanks, 
Best,

**Comment by vodniciarv** [comment]
+1

**Comment by pascalporedda** [comment]
As far as I know this bug isn’t existing anymore, therefore I’ll close this issue.
