### ISSUE TITLE
Over-sensitive rightward swipe on mobile

### ISSUE THREAD

**Issue by e2tha-e** [OwlCarousel2/OwlCarousel2#947]
Hi. May I open a pull request to adjust the sensitivity of the rightward swipe feature on mobile devices? (Rightward swipe means the swipe goes from left to right bringing the hidden slide on the left into view.) I think that the sensitivity of the leftward swipe is fine (it requires a 30 px pull.) However, the equivalent sensitivity doesn't apply for the rightward swipe.

**Comment by e2tha-e** [comment]
After looking at the code, I see that direction === 'right' for the description above. Corrected.

**Comment by daviddeutsch** [comment]
PR accepted and merged, thanks!
