### ISSUE TITLE
Wish to bring onResize into Owl.prototype.refresh

### ISSUE THREAD

**Issue by e2tha-e** [OwlCarousel2/OwlCarousel2#948]
I've found it necessary to have Owl.prototype.refresh call Owl.prototype.onResize in order to have Owl carousels properly resize when the carousel had been loaded via AJAX and the viewport had been resized. May I submit a pull request to add this method to that function?

**Comment by Apollo127** [comment]
I would like to see this added as well!

**Comment by sidati** [comment]
Me 2

**Comment by pascalporedda** [comment]
The according PR has been merged and the changes will be available in the next release.
