### ISSUE TITLE
Loop issue

### ISSUE THREAD

**Issue by igorissen** [OwlCarousel2/OwlCarousel2#954]
Hi,

I have an issue with the `loop` feature. Check the YouTube link below to see what is my issue.

[https://youtu.be/QKkjEob4vVg](https://youtu.be/QKkjEob4vVg)

This my configuration

``` javascript
var owlDefaultOpts = {
  center: true,
  loop: true,
  lazyLoad: true,
  margin: 10,
  responsiveClass: true,
  responsive: {
    0: { items: 1 },
    480: { items: 2 },
    1325: { items: 3 }
  }
};
```

I create 2 directives because the `ng-repeat` doesn't work well with OwlCarousel.

``` javascript
(function () {
  angular.module("MyApp")
    .directive("owlCarousel", owlCarouselDirective);

  function owlCarouselDirective() {
    return {
      restrict  : "A",
      transclude: false,
      link      : function ($scope, element, attributes) {
        $scope.initCarousel = function () {
          $(element).owlCarousel($scope.HomeVM.owlDefaultOpts);
        };
      }
    };
  }
})();

(function () {
  angular.module("MyApp")
    .directive("owlCarouselItem", owlCarouselItemDirective);

  function owlCarouselItemDirective() {
    return {
      restrict  : "A",
      transclude: false,
      link      : function ($scope, element, attributes) {
        if ( $scope.$last )
          $scope.initCarousel();
      }
    };
  }
})();
```

And this is the HTML

``` html
<div owl-carousel class="owl-carousel">
    <div owl-carousel-item ng-repeat="item in HomeVM.featuredLists">
        <a ng-href="{{item.list_url}}">
            <img ng-src="{{item.images.medium}}">
        </a>
    </div>
</div>
```

Any idea how to solve this ?

Thanks.

**Comment by greg5green** [comment]
Hey, @rob-m-andrews I seem to remember you having a similar problem and coming up with a solution -- any ideas?

**Comment by igorissen** [comment]
I have set `center: false` and I get this

[https://youtu.be/YGi6HtmuqQo](https://youtu.be/YGi6HtmuqQo)

```
{
    center: false,
    loop: true,
    lazyLoad: true,
    margin: 10,
    responsiveClass: true,
    responsive: {
        0: { items: 1 },
        480: { items: 2 },
        1325: { items: 3 }
    }
}
```

**Comment by igorissen** [comment]
We found something strange. When we resize the window we can see the carousel looping very well. You can see an example in this [video](https://youtu.be/kQuSs-RJN50) and go to the page [here](https://get.movistapp.com).

**Comment by leandroruel** [comment]
why your website don't have a scrollbar? O.o

**Comment by igorissen** [comment]
Irrelevant for the issue but I'll answer it.

I'm just a developer and this is a client request.

**Comment by leandroruel** [comment]
Ah yes, sorry for asking, but I already suspected that. = D

well about the issue, when i try inspect your carousel on dev tools the entire carousel stop of load. but when i close the dev tools he load again.

**Comment by kevincador** [comment]
Do you have a workaround or do you need more info about this issue?

We'll launch our web site https://get.movistapp.com/ this end of week and we would like to know if we need to be patient or if we need to look at another solution.

Thanks for your support.

**Comment by leandroruel** [comment]
@kevincador if you need somithing now! try this: http://www.idangero.us/swiper/get-started/#.VfwnedsVhBc

**Comment by igorissen** [comment]
@leandroruel Thanks. I'll try this one.

**Comment by Biffyn** [comment]
@igorissen I know it's been a while, but did you manage to find a workaround for problem. I'm running into the exact same issue. Thanks!

**Comment by igorissen** [comment]
@Biffyn We finally used [Swiper](http://www.idangero.us/swiper/get-started/#.VfwnedsVhBc) as a workaround

**Comment by Biffyn** [comment]
Thank for the replay, will look into this
