### ISSUE TITLE
Cannot read property 'replace' of undefined Line 513

### ISSUE THREAD

**Issue by escobar022** [OwlCarousel2/OwlCarousel2#978]
Getting an error when running all inits.
'Cannot read property 'replace' of undefined Line 513' 
Reverted back to previous version and it works.

Using: 

```
 $("#slider").owlCarousel({
                    loop: true,
                    autoplay: true,
                    autoplayHoverPause: false,
                    autoplaySpeed: 3000,
                    animateOut: 'fadeOut',
                    animateIn: 'fadeIn',
                    items: 1,
                    dots: false
                });
```

but also fails:

```
 $("#slider").owlCarousel();
```

```
<div id="slider">
   <div class="slide" style="background-image:url(<?php echo $image1[0]; ?>);"></div>
   <div class="slide" style="background-image:url(<?php echo $image2[0]; ?>);"></div>
   <div class="slide" style="background-image:url(<?php echo $image3[0]; ?>);"></div>
   <div class="slide" style="background-image:url(<?php echo $image4[0]; ?>);"></div>
</div>
```

Any ideas? 

``` javascript
if (settings.responsiveClass) {
    this.$element.attr('class',
    this.$element.attr('class').replace(new RegExp('(' + this.options.responsiveClass + '-)\\S+\\s', 'g'), '$1' + match)
    );
}
```

**Comment by greg5green** [comment]
What does your markup look like? And the JS used to invoke the plugin?

**Comment by escobar022** [comment]
updated the question, sorry about that

**Comment by greg5green** [comment]
This was with beta-3, right?

**Comment by escobar022** [comment]
Yes, on master

**Comment by greg5green** [comment]
The problem here is that there is no `class` attribute on on your `<div id="slider">`. To fix this problem immediately, add a class attribute and you won't get the error anymore. On another note, have you added the CSS from `owl.carousel.css` to your own CSS files and substituted `#slider` for `.owl-carousel`? You will need that CSS or some similar CSS for the carousel to behave properly.

I'm going to mark this issue as a bug because not having the class attribute shouldn't cause an error. Test case: http://codepen.io/anon/pen/LVKEqw

**Comment by leecollings** [comment]
Hey, this is happening with 2.1.0 too, but on line 523. Issue is that I am using a class with the carousel, so why is this breaking?

FYI, on the old 2.0.0 beta, it works fine.

**Comment by janxalot** [comment]
I'm having the same issue.. When I declare two carousels with seperate ID's they combine into one. :S

**Comment by livacengiz** [comment]
You can do this

```
<div id="slider"  class="owl-carousel owl-theme">
   <div class="slide" style="background-image:url(<?php echo $image1[0]; ?>);"></div>
   <div class="slide" style="background-image:url(<?php echo $image2[0]; ?>);"></div>
   <div class="slide" style="background-image:url(<?php echo $image3[0]; ?>);"></div>
   <div class="slide" style="background-image:url(<?php echo $image4[0]; ?>);"></div>
</div>
```

**Comment by lucasrafaelleite** [comment]
Add the class: "class="owl-carousel"
